### ISSUE TITLE
tns debug ios --chrome --emulator | chrome fails to connect 

### ISSUE THREAD

**Issue by wpfeiffe** [NativeScript/nativescript-cli#2997] opened 2017-07-21 17:11 UTC
### Which platform(s) does your issue occur on?
iOS, MacOS Sierra, 10.12.6

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.1.1
- Cross-platform modules: 3.1.1
- Runtime(s): "tns-ios":3.1.0
- Plugin(s): (look for the version number in the `package.json` file of your
project)
    "nativescript-bottombar": "^3.0.4",
    "nativescript-geolocation": "^3.0.0",
    "nativescript-google-maps-sdk": "^2.3.2",
    "nativescript-ngx-fonticon": "^2.2.1",
    "nativescript-oauth": "^2.0.1",
    "nativescript-telerik-ui": "^3.0.1",

### Please tell us how to recreate the issue in as much detail as possible.
1. Run: tns debug ios --chrome --emulator
2. Attempt to attach chrome debugger with resultant chrome-devtools url

### Is there code involved? Not really.  I think I can reproduce this with hello world.  

When I issue the 'tns debug ios --chrome --emulator' command, everything starts up fine.  When I attach the chrome debugger using the 'chrome-devtools' url that the command prints to console, chrome immediately shows a message saying it is disconnected and the console where I issued the command shows:
.
Frontend client connected.
Backend socket created.
Error: connect ECONNREFUSED 127.0.0.1:18181
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

Chrome shows message popup:

"Debugging connection was closed. Reason: websocket_closed
Reconnect when ready by reopening DevTools"

**Comment by dtopuzov** [comment] 2017-07-25 08:58
Hi @wpfeiffe 

Is it only applicable when you debug with chrome, or you can also reproduce with iOS Inspector?
Do you reproduce it each time when you run the command or only sometimes?

**Comment by wpfeiffe** [comment] 2017-07-25 10:47
I can reproduce the issue every time with "tns debug ios --chrome".  If I
just issue "tns debug ios", the nativescript debugger starts and all is
good for the length of the debug session.

I am not sure what the "IOS Inspector" is.  Is this another debugging
tool?  I'm somewhat new to mobile/nativescript so I haven't encountered
that yet..

**Comment by dtopuzov** [comment] 2017-07-25 14:28
Hi @wpfeiffe 

Thanks for the information.
"iOS Inspector" is what you get when you run `tns debug ios`.
I can not reproduce the issue at the moment, so I suppose it is environment related.

What are versions of `node` and `npm` on your machines?
Can you also check that port 18181 is not used by some other program or it is not blocked by something.

I have no idea if it will help or not, but I can also suggest reinstalling your Chrome browser.

**Comment by wpfeiffe** [comment] 2017-07-26 00:28
It looks like port 18181 is open on my machine.  I could try reinstalling chrome,  but I actually see the same issue when I run from Intellij Idea nativescript plugin.  I actually started attempting debugging in Intellij Idea, got/reported the same error to the plugin author. He asked if it worked in chrome.  When I saw the result, I reported it here.  So it appears the issue shows itself on 2 different debuggers.  I agree its likely something in my environment, but having a hard time pinning it down.  Thanks for assistance.

**Comment by wpfeiffe** [comment] 2017-07-26 00:31
Node and npm versions
$ node --version
v7.10.0
$ npm --version
4.2.0

**Comment by dtopuzov** [comment] 2017-07-26 06:41
I've tested with both `node8` and `node6`, but never tried `node7`.

**Comment by dtopuzov** [comment] 2017-11-08 13:28
Hi @wpfeiffe do you still experience the issue with latest releases of {N}?

**Comment by wpfeiffe** [comment] 2017-11-08 23:57
Not yet but I will update and retry...

**Comment by govi2010** [comment] 2017-11-27 07:40
@dtopuzov  I am facing same issue. 

![image](https://user-images.githubusercontent.com/8776031/33255560-4496c5ba-d374-11e7-84f0-9ba7d01ff48a.png)

When i past url into chrome. It doesn't show anything in source tab

**Comment by mkarthik415** [comment] 2017-12-10 06:03
I have deleted below folder and restarted the debug, then I got it to work
platform
hook

**Comment by jeremypele** [comment] 2018-01-09 18:40
Got the same issue since a long time as well. Running on node 6.0.0

**Comment by jujupec** [comment] 2018-02-08 10:13
on your terminal
`cache clean --force`

And delete your cache in chrome

**Comment by dtopuzov** [comment] 2018-06-08 13:13
@govi2010 @jeremypele If you still reproduce the issue can you please post version of nativescript and package.json of your apps.

**Comment by jeremypele** [comment] 2018-06-08 13:15
@dtopuzov Working fine on my side with the upgrade to {N} 4.1 :)

**Comment by dtopuzov** [comment] 2018-06-08 15:31
Closing the issue since it looks resolved.

**Closed by dtopuzov** 2018-06-08 15:31 UTC
Labels: debug, needs more info, os: ios
