### ISSUE TITLE
Support for TypeScript-based NativeScript projects

### ISSUE THREAD

**Issue by tailsu** [NativeScript/nativescript-cli#1117] opened 2015-10-28 15:12 UTC
As a NativeScript used, I want to develop my project in TypeScript, but I don't want to muck around with TypeScript compilers, Grunt, Gulp or whatever.

How to Use
--------------
Execute:
```
$ tns install typescript
```
From now on, commands like `tns prepare`, `tns build`, etc. will compile all `*.ts` files under `app/` and output the respective `*.js` files and the compiled files will be the ones that go into the built package.

**Comment by tailsu** [comment] 2015-10-28 15:13
Implemented in #1116

**Comment by vchimev** [comment] 2015-11-11 16:16
The transpilation does not work when outside the project the `prepare` command is executed through the `--path` option. For example: `tns prepare android/io --path <absolute/relative path>`.

**Comment by rosen-vladimirov** [comment] 2015-11-13 10:45
@vchimev  the issue is fixed in version 0.2.1 of `nativescript-dev-typescript` module. Can you test again :)

**Comment by vchimev** [comment] 2015-11-16 12:58
It's fine, thanks.

@tailsu, @rosen-vladimirov - Is there any way to preserve my own *.tsconfig* as currently it is overwritten every time when `tns install typescript` is called?

**Comment by rosen-vladimirov** [comment] 2015-11-16 12:59
Hm, what's the use-case to call it more than once?

**Comment by vchimev** [comment] 2015-11-17 10:07
I'm concerned about the scenario when I have already my `.ts` project along with `.tsconfig` file, than executing `tns install typescript` will overwrite my `.tsconfig`.

**Comment by vchimev** [comment] 2015-11-17 11:03
How you could get started:
=====================
- install NativeScript CLI version 1.5 when it is released
```
npm install -g nativescript
```
- clone NativeScript Hello World project template for TypeScript:
```
git clone git@github.com:NativeScript/template-hello-world-ts.git template-hello-world-ts
```
- create a new app using the template:
```
tns create myApp --copy-from template-hello-world-ts
```
- change the current working directory to your new app
```
cd myApp
```
- install the TypeScript module
```
tns install typescript
```
Than executing any of the commands: `tns prepare`, `tns build`, `tns run` will compile all `*.ts` files under `app/` directory and output the respective `*.js` files; the compiled files will be the ones that go into the built package.

**Closed** 2015-11-17 11:04 UTC
Labels: 3 - Done, changelog, feature
