### ISSUE TITLE
LiveSync does not reload the changed page on iOS simulator

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#1215] opened 2015-11-18 17:41 UTC
Tested with 1.5 RC.

Steps to reproduce:
- tns livesync ios --emulator --watch
- make a change to the active .xml/.css

The change does not take effect until you manually navigate to any other page of the app.
/CC: @hshristov 

Output:
```
BeforeHookName for command prepare is before-prepare
Images from Xcode project
[ 'Default-568h@2x.png',
  'Default-Landscape.png',
  'Default-Landscape@2x.png',
  'Default-Portrait.png',
  'Default-Portrait@2x.png',
  'Default.png',
  'Default@2x.png',
  'Icon-40@3x.png',
  'Icon-60@3x.png',
  'Icon-Small-50.png',
  'Icon-Small-50@2x.png',
  'Icon-Small.png',
  'Icon-Small@2x.png',
  'Icon-Small@3x.png',
  'add_to_groceries.png',
  'add_to_groceries@2x.png',
  'add_to_groceries@3x.png',
  'checked.png',
  'checked@2x.png',
  'checked@3x.png',
  'delete.png',
  'delete@2x.png',
  'delete@3x.png',
  'done.png',
  'done@2x.png',
  'done@3x.png',
  'history.png',
  'history@2x.png',
  'history@3x.png',
  'icon-40.png',
  'icon-40@2x.png',
  'icon-60.png',
  'icon-60@2x.png',
  'icon-72.png',
  'icon-72@2x.png',
  'icon-76.png',
  'icon-76@2x.png',
  'icon.png',
  'icon@2x.png',
  'logo copy.png',
  'selected.png',
  'selected@2x.png',
  'selected@3x.png',
  'share.png',
  'share@2x.png',
  'share@3x.png',
  'unchecked.png',
  'unchecked@2x.png',
  'unchecked@3x.png',
  'logo.png' ]
Current images from App_Resources
[ 'Default-568h@2x.png',
  'Default-Landscape.png',
  'Default-Landscape@2x.png',
  'Default-Portrait.png',
  'Default-Portrait@2x.png',
  'Default.png',
  'Default@2x.png',
  'Icon-40@3x.png',
  'Icon-60@3x.png',
  'Icon-Small-50.png',
  'Icon-Small-50@2x.png',
  'Icon-Small.png',
  'Icon-Small@2x.png',
  'Icon-Small@3x.png',
  'add_to_groceries.png',
  'add_to_groceries@2x.png',
  'add_to_groceries@3x.png',
  'checked.png',
  'checked@2x.png',
  'checked@3x.png',
  'delete.png',
  'delete@2x.png',
  'delete@3x.png',
  'done.png',
  'done@2x.png',
  'done@3x.png',
  'history.png',
  'history@2x.png',
  'history@3x.png',
  'icon-40.png',
  'icon-40@2x.png',
  'icon-60.png',
  'icon-60@2x.png',
  'icon-72.png',
  'icon-72@2x.png',
  'icon-76.png',
  'icon-76@2x.png',
  'icon.png',
  'icon@2x.png',
  'logo copy.png',
  'logo.png',
  'selected.png',
  'selected@2x.png',
  'selected@3x.png',
  'share.png',
  'share@2x.png',
  'share@3x.png',
  'unchecked.png',
  'unchecked@2x.png',
  'unchecked@3x.png' ]
New images to add into xcode project: 
Images to remove from xcode project: 
Project successfully prepared
AfterHookName for command prepare is after-prepare
Transfering /Work/GitHub/nativescript-cli-tests/appGroceries/app/app.css to /Users/vchimev/Library/Developer/CoreSimulator/Devices/4DF4BF74-B903-4072-95A8-C4F1A9B373D0/data/Containers/Bundle/Application/815BF613-8308-42F2-AE17-EAFA537332DA/appGroceries.app/app
Exec /usr/local/Cellar/node/4.2.1/bin/node /Work/GitHub/nativescript-cli-tests/node_modules/ios-sim-portable/lib/ios-sim.js notify-post org.nativescript.appGroceries:NativeScript.Debug.AttachRequest 
 stdout:  
 stderr: 
Successfully synced application org.nativescript.appGroceries.
```

**Comment by vchimev** [comment] 2015-11-18 17:48
Note: if I run a TypeScript app and make a change in a .css file - the app restarts and the change takes effect.

**Comment by Fatme** [comment] 2015-11-19 15:19
I'm closing this issue because it cannot be reproduced.

**Closed by Fatme** 2015-11-19 15:19 UTC
Labels: bug
