### ISSUE TITLE
Project with plugin variables does not build

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#1508] opened 2016-02-18 14:18 UTC
_From @victorhugom on February 18, 2016 14:16_

Error:
```
malformed document. First element should be <plist>
# build ios
```

I did:

npm install -g nativescript
tns platform remove ios
tns platform add ios
npm install tns-core-modules@latest --save
tns build ios

And also tried:

remove folder: node_modules
remove folder: platform 

npm install -g nativescript
tns platform remove ios
tns platform add ios
npm install tns-core-modules@latest --save
tns build ios

_Copied from original issue: NativeScript/NativeScript#1581_

**Comment by victorhugom** [comment] 2016-02-18 17:21
You can close this issue, after remove and add the plugins is building again

**Comment by rosen-vladimirov** [comment] 2016-02-18 20:32
Ok, that's weird. Can you send me the list of plugins you are using?

**Comment by victorhugom** [comment] 2016-02-18 22:22
Plugins:
```
 "nativescript-facebook-plugin": "git+https://github.com/NativeScript/nativescript-facebook-plugin.git",
"nativescript-google-maps-sdk": "^1.2.2",
"nativescript-iqkeyboardmanager": "^1.0.0",
"nativescript-loading-indicator": "^1.0.0",
"nativescript-videoplayer": "git+https://github.com/bradmartin/nativescript-videoplayer.git",
```

After some investigation I discovered where exactly were the errors:

First: the **videoplayer** plugin didn't have the <plist> tag in the file.
Second: The build process wasn't reading the plugin variables used in the **Facebook** plugin to build the .plist file correctly

**Comment by Plamen5kov** [comment] 2016-02-25 14:11
same problem with the plugin variables on android

**Comment by rosen-vladimirov** [comment] 2016-02-25 21:22
Is this only in the facebook plugin or can be reproduced with any kind of plugin with variables?

**Comment by Plamen5kov** [comment] 2016-02-26 08:28
I just tried it out, it looks like it still doesn't work. Here's what id did:

1. `tns plugin add nativescript-barcodescanner`
2. went to `node_modules/nativescript-barcodescanner/platforms/android/AndroidManifest.xml` and added this line to manifest:
```
<tag>{APP_ID}</tag>
```
3. went to `node_modules/nativescript-barcodescanner/package.json` and added 
```
    "variables": {
        "APP_ID": {
             "defaultValue": "myAppId"
        }
    }
```
to the `"nativescript"` key as described here: https://github.com/NativeScript/nativescript-cli/issues/882

4. run `tns prepare android`

Error: 
```
tns prepare android
Copying template files...
Project successfully created.
Processing node_modules failed. Exception: Unable to find the value for APP_ID plugin variable into project package.json file. Verify that your package.json file is correct and try again.
Sending exception report (press Ctrl+C to stop).....
```

Cli version: 1.6.1.
same happens with 1.6.0

**Comment by dtopuzov** [comment] 2016-06-06 13:40
Still valid in {N} 2.0.1 with steps Plamen5kov described.

**Comment by Plamen5kov** [comment] 2016-08-02 09:13
Still able to reproduce with cli 2.1.1. 
Build doesn't crash but APP_ID is still not replaced with the value from package.json

**Closed** 2016-08-02 10:40 UTC
Labels: bug, Plugins
