### ISSUE TITLE
Install type script source, with 'tns create'

### ISSUE THREAD

**Issue by ralphmason** [NativeScript/nativescript-cli#522] opened 2015-06-04 15:25 UTC
Sorry if this has been asked before.

It would be really nice to install the typescript source along side the compiles javascript when an application is created.

The compiled javascript is much harder to read & change than the typescript.

**Comment by AlexandreRoba** [comment] 2015-06-14 13:28
+1 tns create should support an option parameter to include the typescript source

**Comment by ErjanGavalji** [comment] 2015-07-01 10:31
Yep, these are already in the works, commented in the [Choose template functionality](https://github.com/NativeScript/nativescript-cli/issues/374) and [Enable transpilers support in NativeScript projects](https://github.com/NativeScript/nativescript-cli/issues/493) issues.

Once both the features available, we will publish the templates in TypeScript as well.

For the time being, you can view the TypeScript source of the templates in the [NativeScript apps folder](https://github.com/NativeScript/NativeScript/tree/master/apps). Template are located in folders, named by the "template-{templateName}" scheme.

By the way, [building](http://docs.nativescript.org/running-latest) the [NativeScript/NativeScript](https://github.com/NativeScript/NativeScript) repo, you'll get the tns-template-x.x.x-ts.tgz archives, which are actually the templates packed as npm.

**Comment by ErjanGavalji** [comment] 2015-07-01 10:32
Closing the issue now, for it gets a duplicate of the two, listed above.

**Closed by ErjanGavalji** 2015-07-01 10:32 UTC
