### ISSUE TITLE
tns run ios issue with 2.5.0 - unable to sync files on iOS Simulator

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#2476] opened 2017-02-02 09:02 UTC
Output:
```
Unable to sync files. Error is: cp: copyFileSync: could not write to dest file (code=ENOENT):/Users/toddanglin/Library/Developer/CoreSimulator/Devices/50DFBA8C-A077-4EB4-B49F-93D2FAE13810/data/Containers/Bundle/Application/6878EDAF-504B-4366-9CE4-B5A97870EA3C/ns-demo.app/Resources/en.lproj/Localizable.strings
```

Seems to fail with the same error on different files in “/Resources/en.lproj”. Here it’s “Localizable.strings.” Sometimes it’s “InfoPlist.strings”.

**Comment by Plamen5kov** [comment] 2017-02-02 11:34
How to reproduce: 
Add folder to `<project_name>/app` folder once an application is created with any template.

**Comment by JuanDelgadillo** [comment] 2017-02-03 03:29
I got the same problem over here. I'm using the plugin `nativescript-i18n` and when I make a first change after run `tns run ios` it refresh the app but with next changes it throws that error and not reload the app anymore. I'm using tns 2.5.0

**Comment by toddanglin** [comment] 2017-02-03 03:32
+1 I've go the same situation as @JuanDelgadillo. Building on Mac for iOS, targeting the simulator.

`tns run ios --emualtor` will work the first time and do one LiveSync. After that, it errors-out with the `copyFileSync` errors. Current workaround is to simply kill the running command and restart `tns run`.

**Comment by ludwiktrammer** [comment] 2017-02-08 13:26
I'm experiencing the problem while using `nativescript-dev-sass`. I'm able to run the app using "tns run android", but as soon as I touch a single .scss file NativeScript tries to sync and everything blow ups. Here is the relevant issue in `nativescript-dev-sass` bugtracker: https://github.com/toddanglin/nativescript-dev-sass/issues/18

**Comment by vance** [comment] 2017-04-28 16:07
I still get this in `tns --version 2.5.4`. The first time is fine, but on 2nd run, my assets directory fails every time since I added images to it. 

```
[1] Transferring project files...
[1] Unable to sync files. Error is: EEXIST: file already exists, mkdir '... /assets '
```

**Comment by lukeramsden** [comment] 2017-05-11 10:30
I still get this aswell.

**Comment by pkoleva** [comment] 2017-05-12 07:11
Hey, @vance @lukeramsden,
We've released 2.5.5 and 3.0.1 with another fix that references this problem. Would you like to give it a try and write back with the results. Meanwhile I'll reopen the issue.

**Comment by dtopuzov** [comment] 2017-05-12 14:04
@vance @lukeramsden Can you reproduce the problem with hello-world app?

I believe it is an issue caused by `nativescript-dev-sass`, `nativescript-i18n` or some other plugin.
If the issue is caused by some 3rd party plugin we should log it in plugin's repo.

**Comment by lukeramsden** [comment] 2017-05-12 14:07
@dtopuzov I will try tomorrow, and I use both of those plugins :P

**Comment by toddanglin** [comment] 2017-05-12 21:15
FWIW, the `nativescript-dev-sass` plugin _should_ be updated and working as expected in NativeScript 2.5.x and 3.x. Let me know if you encounter an issue and we'll try to troubleshoot.

**Comment by dtopuzov** [comment] 2017-05-13 07:37
@lukeramsden pelase also post versions of those pluging, it might hapen that it is plugin problem that is fixed in newer versions of the plugin.

**Comment by dtopuzov** [comment] 2017-05-22 06:59
@lukeramsden Any update on this?

**Comment by lukeramsden** [comment] 2017-05-22 14:15
@dtopuzov Sorry I didn't get a chance to test it, been very busy releasing the app.

**Comment by shakes90** [comment] 2017-05-30 10:28
I'm getting a similar problem with the latest version of nativescript 3.0.1 - Very basic setup on Ubuntu 16.04 although my colleagues who work in a windows environment tell my live-sync is OK for them - error as follows when edit a basic ts file from the Hello world app and save:

Executing before-prepare hook from /home/simon/projects/nativescript/HelloWorld/hooks/before-prepare/nativescript-dev-android-snapshot.js
Executing before-prepare hook from /home/simon/projects/nativescript/HelloWorld/hooks/before-prepare/nativescript-dev-typescript.js
Preparing project...
Project successfully prepared (android)
Executing after-prepare hook from /home/simon/projects/nativescript/HelloWorld/hooks/after-prepare/nativescript-dev-android-snapshot.js
Transferring project files...
Unable to sync files. Error is: Multiple errors were thrown:
ENOENT: no such file or directory, stat '/home/simon/projects/nativescript/HelloWorld/platforms/android/src/main/assets/app/app.component.ts___jb_tmp___'

**Comment by shakes90** [comment] 2017-05-30 10:51
OK - found the answer to the above problem - Intellij saves temp files as a "safe write" option which was causing the issue. So if turn off evrything is OK. System Settings => "Use safe write" in intellij

**Comment by dtopuzov** [comment] 2017-05-30 11:38
Hi @shakes90 It looks you are hitting https://github.com/NativeScript/nativescript-cli/issues/2720 which is already fix and available at `nativescript@next`.

**Comment by Nikoms** [comment] 2017-06-08 00:56
@shakes90 is right

On linux I didn't have this issue on NS 2.5, and I have it now on 3.0

**Comment by dtopuzov** [comment] 2017-06-08 06:40
Hi @Nikoms, 

The issue @shakes90 is different from the original issue in this thread.
It is already fixed in code base, available in @next builds and will be released in 3.1.0.

How to test with @next builds:
```
npm un -g nativescript
npm cache clean
npm i -g nativescript@next
```

**Comment by dtopuzov** [comment] 2017-06-08 06:45
Closing this issue since `tns run ios` works property in general.

Reported issues are either problem with specific plugin (should be addressed by plugin itself) or not related with the original issue (the problem with temp files on linux).

**Closed by dtopuzov** 2017-06-08 06:45 UTC
Labels: bug, livesync, Need More Info

**Comment by RoyiNamir** [comment] 2018-05-29 07:14
No. This problem returned on TNS 4.

Look at this screen where my app is On : 

![image](https://user-images.githubusercontent.com/2842123/40643340-7db05e6c-6328-11e8-8a81-4788240b190a.png)



Now let's change something in the code

![image](https://user-images.githubusercontent.com/2842123/40643367-95513064-6328-11e8-91a6-17b4df9bf312.png)

See error : 

![image](https://user-images.githubusercontent.com/2842123/40643443-ddc11224-6328-11e8-8e1a-887e65a49176.png)

It didn't happen before in v 3
Files are read only due to TFS. But it did work before v4.

complete package.json : 

https://gist.github.com/RoyiNamir/c7adb7454b075369b0d325b88575f374

**Comment by dtopuzov** [comment] 2018-06-08 13:50
Hi @RoyiNamir 

Thanks for logging it at separate issue, we will investigate and post updates there.
