### ISSUE TITLE
New project's package.json all on one line

### ISSUE THREAD

**Issue by cfjedimaster** [NativeScript/nativescript-cli#1756] opened 2016-05-12 20:33 UTC
I just made a new project and my package.json is all on one line. Obviously I can fix this myself, but that should be easy to fix in the CLI.

**Comment by enchev** [comment] 2016-05-30 06:20
Are you shareing and opening by chance this package.json created on Mac with some Windows editor?

**Comment by cfjedimaster** [comment] 2016-05-30 18:05
Nope, all on a Mac.

**Comment by rosen-vladimirov** [comment] 2016-06-02 09:26
Hi @cfjedimaster ,
The issue is caused by npm itself, you can reproduce it by doing the following:
```
$ npm cache clean
$ npm install lodash
$ npm config get cache
```
The last command will give you the path to your cache. Navigate to this directory and you'll find lodash package there. Open the directory, there you'll find directory with version and inside it there's package dir and package.tgz. Now if you check the package directory, there's package.json file, which is written on one line.
This package.json is created and updated by npm itself. However if you check the package.tgz, you'll see that the package.json there is correct. 

In some cases nativescript-cli will extract the package.tgz over the package directory and this will generate correct package.json file there, but I'm not sure when and how npm replaces it with the incorrect one (on a single line) after that.

However as this is not an issue of CLI, I'm gonna close this issue. Thanks for reporting it.

**Closed by rosen-vladimirov** 2016-06-02 09:26 UTC
