### ISSUE TITLE
Error when creating project

### ISSUE THREAD

**Issue by benradock** [NativeScript/nativescript-cli#3391] opened 2018-02-23 20:00 UTC
I've just been starting to get NativeScript to work on my computer. I've gone through all of the installation instructions, and everything seems to be installed correctly.

Whenever I try to make the tutorial application, I type "tns create HelloWorld --template nativescript-template-tutorial" into the command line. I get this error:

Installing  nativescript-template-tutorial
+ nativescript-template-tutorial@3.4.0
added 2 packages and updated 1 package in 2.398s
cp: no such file or directory: C\Users\Ben Radock\HelloWorld\node_modules\native-script-template-tutorial

I am running the command in C:\Users\Ben Radock if that is pertinent.

Any help would be appreciated.

**Comment by Fatme** [comment] 2018-02-25 21:23
Hey @benradock,

Can you execute `tns create HelloWorld --template nativescript-template-tutorial --log trace` and send us the produced log.

**Comment by benradock** [comment] 2018-02-25 22:54
C:\Users\Ben Radock>tns create HelloWorld --template nativescript-template-tutorial --log trace
Loading extensions.
execFile: C:\Android\android-sdk\platform-tools\adb "help"
Exec npm -v
 stdout: 5.6.0

 stderr:
Exec node-gyp -v
 stdout:
 stderr: 'node-gyp' is not recognized as an internal or external command,
operable program or batch file.

Error while executing node-gyp -v: Command failed: node-gyp -v
'node-gyp' is not recognized as an internal or external command,
operable program or batch file.

Exec "C:\Android\android-sdk\platform-tools\adb" version
 stdout: Android Debug Bridge version 1.0.39
Version 0.0.1-4500957
Installed as C:\Android\android-sdk\platform-tools\adb.exe

 stderr:
spawn: C:\Android\android-sdk\tools\emulator "-help"
Result when throw error is false:
{ stdout: 'Android Emulator usage: emulator [options] [-qemu args]\r\n  options:\r\n    -list-avds                     list available AVDs\r\n    -sysdir <dir>                  search for system disk images in <dir>\r\n    -system <file>                 read initial system image from <file>\r\n    -writable-system               make system image writable after \'adb remount\'\r\n    -datadir <dir>                 write user data into <dir>\r\n    -kernel <file>                 use specific emulated kernel\r\n    -ramdisk <file>                ramdisk image (default <system>/ramdisk.img\r\n    -image <file>                  obsolete, use -system <file> instead\r\n    -initdata <file>               same as \'-init-data <file>\'\r\n    -data <file>                   data image (default <datadir>/userdata-qemu.img\r\n    -partition-size <size>         system/data partition size in MBs\r\n    -cache <file>                  cache partition image (default is temporary file)\r\n    -cache-size <size>             cache partition size in MBs\r\n    -no-cache                      disable the cache partition\r\n    -nocache                       same as -no-cache\r\n    -sdcard <file>                 SD card image (default <datadir>/sdcard.img\r\n    -snapstorage <file>            file that contains all state snapshots (default <datadir>/snapshots.img)\r\n    -no-snapstorage                do not mount a snapshot storage file (this disables all snapshot functionality)\r\n    -snapshot <name>               name of snapshot within storage file for auto-start and auto-save (default \'default-boot\')\r\n    -no-snapshot                   perform a full boot and do not do not auto-save, but qemu vmload and vmsave operate on snapstorage\r\n    -no-snapshot-save              do not auto-save to snapshot on exit: abandon changed state\r\n    -no-snapshot-load              do not auto-start from snapshot: perform a full boot\r\n    -snapshot-list                 show a list of available snapshots\r\n    -no-snapshot-update-time       do not do try to correct snapshot time on restore\r\n    -wipe-data                     reset the user data image (copy it from initdata)\r\n    -avd <name>                    use a specific android virtual device\r\n    -skindir <dir>                 search skins in <dir> (default <system>/skins)\r\n    -skin <name>                   select a given skin\r\n    -no-skin                       deprecated: create an AVD with no skin instead\r\n    -noskin                        same as -no-skin\r\n    -memory <size>                 physical RAM size in MBs\r\n    -accel <mode>                  Configure emulation acceleration\r\n    -no-accel                      Same as \'-accel off\'\r\n    -ranchu                        Use new emulator backend instead of the classic one\r\n    -engine <engine>               Select engine. auto|classic|qemu2\r\n    -netspeed <speed>              maximum network download/upload speeds\r\n    -netdelay <delay>              network latency emulation\r\n    -netfast                       disable network shaping\r\n    -code-profile <name>           enable code profiling\r\n    -show-kernel                   display kernel messages\r\n    -shell                         enable root shell on current terminal\r\n    -no-jni                        disable JNI checks in the Dalvik runtime\r\n    -nojni                         same as -no-jni\r\n    -logcat <tags>                 enable logcat output with given tags\r\n    -no-audio                      disable audio support\r\n    -noaudio                       same as -no-audio\r\n    -audio <backend>               use specific audio backend\r\n    -raw-keys                      disable Unicode keyboard reverse-mapping (deprecated)\r\n    -radio <device>                redirect radio modem interface to character device\r\n    -port <port>                   TCP port that will be used for the console\r\n    -ports <consoleport>,<adbport> TCP ports used for the console and adb bridge\r\n    -onion <image>                 use overlay PNG image over screen\r\n    -onion-alpha <%age>            specify onion-skin translucency\r\n    -onion-rotation 0|1|2|3        specify onion-skin rotation\r\n    -dpi-device <dpi>              specify device\'s resolution in dpi (default 165)\r\n    -scale <scale>                 scale emulator window (deprecated)\r\n    -http-proxy <proxy>            make TCP connections through a HTTP/HTTPS proxy\r\n    -timezone <timezone>           use this timezone instead of the host\'s default\r\n    -dns-server <servers>          use this DNS server(s) in the emulated system\r\n    -cpu-delay <cpudelay>          throttle CPU emulation\r\n    -no-boot-anim                  disable animation for faster boot\r\n    -no-window                     disable graphical window display\r\n    -version                       display emulator version number\r\n    -report-console <socket>       report console port to remote socket\r\n    -gps <device>                  redirect NMEA GPS to character device\r\n    -keyset <name>                 specify keyset file name\r\n    -shell-serial <device>         specific character device for root shell\r\n    -tcpdump <file>                capture network packets to file\r\n    -bootchart <timeout>           enable bootcharting\r\n    -charmap <file>                use specific key character map\r\n    -prop <name>=<value>           set system property on boot\r\n    -shared-net-id <number>        join the shared network, using IP address 10.1.2.<number>\r\n    -gpu <mode>                    set hardware OpenGLES emulation mode\r\n    -camera-back <mode>            set emulation mode for a camera facing back\r\n    -camera-front <mode>           set emulation mode for a camera facing front\r\n    -webcam-list                   lists web cameras available for emulation\r\n    -screen <mode>                 set emulated screen mode\r\n    -force-32bit                   always use 32-bit emulator\r\n    -selinux <disabled|permissive> Set SELinux to either disabled or permissive mode\r\n    -unix-pipe <path>              Add <path> to the list of allowed Unix pipes\r\n    -fixed-scale                   Use fixed 1:1 scale for the initial emulator window.\r\n\r\n     -qemu args...                 pass arguments to qemu\r\n     -qemu -h                      display qemu help\r\n\r\n     -verbose                      same as \'-debug-init\'\r\n     -debug <tags>                 enable/disable debug messages\r\n     -debug-<tag>                  enable specific debug messages\r\n     -debug-no-<tag>               disable specific debug messages\r\n\r\n     -help                         print this help\r\n     -help-<option>                print option-specific help\r\n\r\n     -help-disk-images             about disk images\r\n     -help-keys                    supported key bindings\r\n     -help-debug-tags              debug tags for -debug <tags>\r\n     -help-char-devices            character <device> specification\r\n     -help-environment             environment variables\r\n     -help-keyset-file             key bindings configuration file\r\n     -help-virtual-device          virtual device management\r\n     -help-sdk-images              about disk images when using the SDK\r\n     -help-build-images            about disk images when building Android\r\n     -help-all                     prints all help content\r\n\r\n',
  stderr: '',
  exitCode: 1 }
The result of checking is Android Emulator installed is:
- stdout: Android Emulator usage: emulator [options] [-qemu args]
  options:
    -list-avds                     list available AVDs
    -sysdir <dir>                  search for system disk images in <dir>
    -system <file>                 read initial system image from <file>
    -writable-system               make system image writable after 'adb remount'
    -datadir <dir>                 write user data into <dir>
    -kernel <file>                 use specific emulated kernel
    -ramdisk <file>                ramdisk image (default <system>/ramdisk.img
    -image <file>                  obsolete, use -system <file> instead
    -initdata <file>               same as '-init-data <file>'
    -data <file>                   data image (default <datadir>/userdata-qemu.img
    -partition-size <size>         system/data partition size in MBs
    -cache <file>                  cache partition image (default is temporary file)
    -cache-size <size>             cache partition size in MBs
    -no-cache                      disable the cache partition
    -nocache                       same as -no-cache
    -sdcard <file>                 SD card image (default <datadir>/sdcard.img
    -snapstorage <file>            file that contains all state snapshots (default <datadir>/snapshots.img)
    -no-snapstorage                do not mount a snapshot storage file (this disables all snapshot functionality)
    -snapshot <name>               name of snapshot within storage file for auto-start and auto-save (default 'default-boot')
    -no-snapshot                   perform a full boot and do not do not auto-save, but qemu vmload and vmsave operate on snapstorage
    -no-snapshot-save              do not auto-save to snapshot on exit: abandon changed state
    -no-snapshot-load              do not auto-start from snapshot: perform a full boot
    -snapshot-list                 show a list of available snapshots
    -no-snapshot-update-time       do not do try to correct snapshot time on restore
    -wipe-data                     reset the user data image (copy it from initdata)
    -avd <name>                    use a specific android virtual device
    -skindir <dir>                 search skins in <dir> (default <system>/skins)
    -skin <name>                   select a given skin
    -no-skin                       deprecated: create an AVD with no skin instead
    -noskin                        same as -no-skin
    -memory <size>                 physical RAM size in MBs
    -accel <mode>                  Configure emulation acceleration
    -no-accel                      Same as '-accel off'
    -ranchu                        Use new emulator backend instead of the classic one
    -engine <engine>               Select engine. auto|classic|qemu2
    -netspeed <speed>              maximum network download/upload speeds
    -netdelay <delay>              network latency emulation
    -netfast                       disable network shaping
    -code-profile <name>           enable code profiling
    -show-kernel                   display kernel messages
    -shell                         enable root shell on current terminal
    -no-jni                        disable JNI checks in the Dalvik runtime
    -nojni                         same as -no-jni
    -logcat <tags>                 enable logcat output with given tags
    -no-audio                      disable audio support
    -noaudio                       same as -no-audio
    -audio <backend>               use specific audio backend
    -raw-keys                      disable Unicode keyboard reverse-mapping (deprecated)
    -radio <device>                redirect radio modem interface to character device
    -port <port>                   TCP port that will be used for the console
    -ports <consoleport>,<adbport> TCP ports used for the console and adb bridge
    -onion <image>                 use overlay PNG image over screen
    -onion-alpha <%age>            specify onion-skin translucency
    -onion-rotation 0|1|2|3        specify onion-skin rotation
    -dpi-device <dpi>              specify device's resolution in dpi (default 165)
    -scale <scale>                 scale emulator window (deprecated)
    -http-proxy <proxy>            make TCP connections through a HTTP/HTTPS proxy
    -timezone <timezone>           use this timezone instead of the host's default
    -dns-server <servers>          use this DNS server(s) in the emulated system
    -cpu-delay <cpudelay>          throttle CPU emulation
    -no-boot-anim                  disable animation for faster boot
    -no-window                     disable graphical window display
    -version                       display emulator version number
    -report-console <socket>       report console port to remote socket
    -gps <device>                  redirect NMEA GPS to character device
    -keyset <name>                 specify keyset file name
    -shell-serial <device>         specific character device for root shell
    -tcpdump <file>                capture network packets to file
    -bootchart <timeout>           enable bootcharting
    -charmap <file>                use specific key character map
    -prop <name>=<value>           set system property on boot
    -shared-net-id <number>        join the shared network, using IP address 10.1.2.<number>
    -gpu <mode>                    set hardware OpenGLES emulation mode
    -camera-back <mode>            set emulation mode for a camera facing back
    -camera-front <mode>           set emulation mode for a camera facing front
    -webcam-list                   lists web cameras available for emulation
    -screen <mode>                 set emulated screen mode
    -force-32bit                   always use 32-bit emulator
    -selinux <disabled|permissive> Set SELinux to either disabled or permissive mode
    -unix-pipe <path>              Add <path> to the list of allowed Unix pipes
    -fixed-scale                   Use fixed 1:1 scale for the initial emulator window.

     -qemu args...                 pass arguments to qemu
     -qemu -h                      display qemu help

     -verbose                      same as '-debug-init'
     -debug <tags>                 enable/disable debug messages
     -debug-<tag>                  enable specific debug messages
     -debug-no-<tag>               disable specific debug messages

     -help                         print this help
     -help-<option>                print option-specific help

     -help-disk-images             about disk images
     -help-keys                    supported key bindings
     -help-debug-tags              debug tags for -debug <tags>
     -help-char-devices            character <device> specification
     -help-environment             environment variables
     -help-keyset-file             key bindings configuration file
     -help-virtual-device          virtual device management
     -help-sdk-images              about disk images when using the SDK
     -help-build-images            about disk images when building Android
     -help-all                     prints all help content


- stderr:
Exec mono --version
 stdout:
 stderr: 'mono' is not recognized as an internal or external command,
operable program or batch file.

Error while executing mono --version: Command failed: mono --version
'mono' is not recognized as an internal or external command,
operable program or batch file.

Exec git --version
 stdout: git version 2.16.1.windows.2

 stderr:
Exec gradle -v
 stdout:
------------------------------------------------------------
Gradle 3.0
------------------------------------------------------------

Build time:   2016-08-15 13:15:01 UTC
Revision:     ad76ba00f59ecb287bd3c037bd25fc3df13ca558

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Windows 10 10.0 amd64


 stderr:
Exec "C:\Program Files\Java\jdk1.8.0_162\bin\javac" -version
 stdout:
 stderr: javac 1.8.0_162

System information:
{ procInfo: 'nativescript/3.4.2',
  platform: 'win32',
  os: 'Windows 10 Pro 6.3.16299',
  shell: 'C:\\WINDOWS\\system32\\cmd.exe',
  dotNetVer: '4.7.02556',
  procArch: 'x64',
  nodeVer: 'v8.9.4',
  npmVer: '5.6.0',
  nodeGypVer: null,
  xcodeVer: null,
  xcodeprojGemLocation: null,
  itunesInstalled: false,
  cocoapodVer: null,
  adbVer: 'Android Debug Bridge version 1.0.39',
  emulatorInstalled: true,
  monoVer: null,
  gitVer: '2.16.1.windows.2',
  gradleVer: '3.0',
  javacVersion: '1.8.0_162' }
Starting watch on killswitch C:\Users\BENRAD~1\AppData\Local\Temp\Ben Radock\KillSwitches\cli
Initializing analytics statuses.
Analytics statuses:  { TrackFeatureUsage: 'disabled', TrackExceptions: 'disabled' }
Path already exists and is not empty %s
Error: Path already exists and is not empty C:\Users\Ben Radock\HelloWorld
    at Errors.fail (C:\Users\Ben Radock\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:125:28)
    at ProjectService.<anonymous> (C:\Users\Ben Radock\AppData\Roaming\npm\node_modules\nativescript\lib\services\project-service.js:47:30)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Ben Radock\AppData\Roaming\npm\node_modules\nativescript\lib\services\project-service.js:10:58)
    at <anonymous>
List of registered commands: /?, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, clean-app, clean-app|android, clean-app|ios, create, debug, debug|android, debug|ios, deploy, dev-generate-help, dev-generate-messages, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, devices, devices|android, devices|ios, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, error-reporting, extension, extension|install, extension|uninstall, help, info, init, install, platform, platform|add, platform|clean, platform|remove, platform|update, plugin, plugin|add, plugin|install, plugin|remove, plugin|update, post-install-cli, prepare, proxy, proxy|clear, proxy|set, publish, publish|ios, run, run|android, run|ios, test, test|android, test|init, test|ios, update, usage-reporting
Reading help for command 'create'. FileName is 'create.md'.
# create

┌────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Usage                  │ Synopsis                                                                                                                                     │
│ Create from default    │ $ tns create <App Name> [--path <Directory>] [--appid <App ID>]                                                                              │
│ JavaScript template    │                                                                                                                                              │
│ Create from default    │ $ tns create <App Name> --template typescript [--path <Directory>] [--appid <App ID>] OR $ tns create <App Name> --tsc [--path <Directory>]  │
│ TypeScript template    │ [--appid <App ID>] OR $ tns create <App Name> --template tsc [--path <Directory>] [--appid <App ID>]                                         │
│ Create from default    │ $ tns create <App Name> --template angular [--path <Directory>] [--appid <App ID>] OR $ tns create <App Name> --template ng [--path          │
│ Angular template       │ <Directory>] [--appid <App ID>] OR $ tns create <App Name> --ng [--path <Directory>] [--appid <App ID>]                                      │
│ Copy from existing     │ $ tns create <App Name> [--path <Directory>] [--appid <App ID>]                                                                              │
│ project                │                                                                                                                                              │
│ Create from custom     │ $ tns create <App Name> [--path <Directory>] [--appid <App ID>] --template <Template>                                                        │
│ template               │                                                                                                                                              │
└────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

Creates a new project for native development with NativeScript.

### Options

    * --path - Specifies the directory where you want to create the project, if different from the current directory. The directory must be empty.
    * --appid - Sets the application identifier for your project.
    * --template - Specifies a valid npm package which you want to use to create your project. If --template is not set, the NativeScript CLI creates the project from the default JavaScript hello-world template.
    * --ng - Sets the template for your project to the Angular template.
    * --tsc - Sets the template for your project to the TypeScript template.

### Attributes

    * <App Name> is the name of project. The specified name must meet the requirements of all platforms that you want to target. For more information about the <App Name> requirements, run $ tns help create
    * <App ID> is the application identifier for your project. It must be a domain name in reverse and must meet the requirements of all platforms that you want to target. If not specified, the application identifier is set to org.nativescript.<App name> For more information about the <App ID> requirements, run $ tns help create


C:\Users\Ben Radock>

**Comment by benradock** [comment] 2018-02-25 22:55
[log.txt](https://github.com/NativeScript/nativescript-cli/files/1756819/log.txt)

**Comment by Fatme** [comment] 2018-02-26 08:03
Hey @benradock,

Thank you for sending us the log.

I missed to tell you to delete the `HelloWorld` folder before executing `create` command. 
So please execute the followings:

1. Delete `C\Users\Ben Radock\HelloWorld` folder
2. Execute `tns create HelloWorld --template nativescript-template-tutorial --log trace` command and send us the log.

**Comment by benradock** [comment] 2018-02-26 15:37
[log2.txt](https://github.com/NativeScript/nativescript-cli/files/1759218/log2.txt)

**Comment by rosen-vladimirov** [comment] 2018-02-27 09:19
Hi @benradock ,
Thank you for providing the logs. We've investigated them and we've tried to reproduce the issue, but without success. Basically, when CLI creates new project, it executes several `npm install` commands and tries to parse their output. However, it looks like the template is not installed correctly on your machine or at least it is not on the place where CLI expects it.
In order to determine the cause of the issue, we'll need more information about this case:
1. Can you reproduce the issue by using `$ tns create myApp`.
2. Can you reproduce the issue when executing the command in another location, for example in your D: drive  (in case you have such)?

This issue seems similar to [this one](https://github.com/NativeScript/nativescript-cli/issues/2921). Can you try running [this script](https://gist.github.com/rosen-vladimirov/40c258de1a366555ac36ceab66377f4d) in your terminal - just download the file and execute `node testNpm.js` in your `C:\Users\Ben Radock` dir. It should create two directories in the dir where you are executing it and should install lodash as dependency in both of them. Can you send us the output of the script?

**Comment by benradock** [comment] 2018-03-06 22:57
[log3.txt](https://github.com/NativeScript/nativescript-cli/files/1787056/log3.txt)

Here is what is output when I run node testNpm.js and tns create myApp. I'm not sure if I should be running the "tns create" command in a different directory, depending on where things are located.

**Comment by Plamen5kov** [comment] 2018-03-12 07:31
Hi @benradock,
Because I saw you had an empty space in your path `C\Users\Ben Radock\HelloWorld\node_modules\native-script-template-tutorial`
Could you please try running the `tns create command in `C:\`.

**Comment by rover-rock** [comment] 2018-03-22 01:59
I have an err when executing `tns create ....`  too.  npm ERR! code ECONNRESET!

**Comment by Fatme** [comment] 2018-04-05 06:11
Hi @rover-rock,
Can you please check this thread https://github.com/NativeScript/nativescript-cli/issues/3465 and try the suggestion on your side?

**Comment by rover-rock** [comment] 2018-04-05 06:19
@Fatme  Thank you very much.I have resolve this already.

**Comment by Fatme** [comment] 2018-04-05 07:03
Hi @benradock,

Thank you for providing the log. Based on your output we guess it is node's bug. You can check this thread https://github.com/NativeScript/nativescript-cli/issues/2921 and this one https://github.com/nodejs/node/issues/6807#issuecomment-219992306 and use the provided solution.

I'm closing this one, but feel free to reopen it or/and open an another in case you have some problems.

**Closed by Fatme** 2018-04-05 07:03 UTC
