### ISSUE TITLE
console.log sometimes dispay date, username, app & processId at the beginning

### ISSUE THREAD

**Issue by hshristov** [NativeScript/nativescript-cli#3162] opened 2017-10-17 05:54 UTC
```
Layout: Page(5)@file:///app/page.1.xml:1:1; :measureChild: ActionBar(6)@file:///app/page.1.xml:3:5; MeasureSpec: EXACTLY 750, MeasureSpec: AT_MOST 1206} 
(/Users/hhristov/tmp/actionbar/node_modules/tns-core-modules/trace/trace.js:156:28)

Oct 17 08:47:08 mcsofhhristov actionbar[3446]: CONSOLE LOG file:///app/tns_modules/tns-core-modules/trace/trace.js:156:28: Layout: Frame(1) :measureChild: Page(5)@file:///app/page.1.xml:1:1; MeasureSpec: EXACTLY 750, MeasureSpec: EXACTLY 1206}
```

**Comment by KristianDD** [comment] 2017-11-02 12:26
@hshristov Thanks you for the report. Could you please verify if its still reproducible with CLI version 3.3.0. I think it might been fixed with the Xcode9 simulator logs issue.

**Comment by Natalia-Hristova** [comment] 2018-02-15 15:36
Rerun an app several times and "consolelogging" multiple times and I couldn't reproduce this issue using `Xcode 9.2` and `CLI 3.4.2`.

**Comment by Natalia-Hristova** [comment] 2018-03-12 08:03
Closing due to inactivity.

**Closed by Natalia-Hristova** 2018-03-12 08:03 UTC
