### ISSUE TITLE
Debug Port being ignored...

### ISSUE THREAD

**Issue by eutobias** [NativeScript/nativescript-cli#317] opened 2015-03-13 16:47 UTC
Hello, sorry my bad english :)..

I'm testing NativeScript since yesterday and i fight a lot against debug parameters and found something that could be a problem. (i'm not sure if the problem is really a bug or me fault), let me explain.

My hardware:
MacBook Pro - Mavericks, Asus a501 - Android 4.4.2

I'm trying to debug on my android device and running the default project create when you add a platform, it's run fine, install fine, works fine...

But when i run:
*tns debug android --debug-brk*

the app open but paused on a black screen, ok it's the expected behavior, i saw in some place that the node inspector is not launched correctly on mac... ok.. fine, no problem i can open it.

Then i try
*tns debug android --debuggerPort 7788 --debug-brk*

i wait the installer on device and then open my browser (http://127.0.0.1:8080/debug?port=7788) and got nothing.

Then i've tryed --debugger-port, --debug-port, --debugPort as here (https://github.com/telerik/mobile-cli-lib/blob/master/options.ts) and nothing.

Then i try:
*tns debug android --debuggerPort 7788 --debug-brk --log trace*

Now i got it (last line of trace)
*spawn: node /usr/local/lib/node_modules/nativescript/node_modules/node-inspector/bin/inspector --debug-port 54865*

i don't know if port the parameter is wrong but always i try to set it, i'm ignored and get a random port number.

Just to be clear, debug is working great when i open http://127.0.0.1:8080/debug?port=54865 or whatever random port, the problem is, i can't set a debug port and always have to open manually the node inspector. if i could set the port would be wonderfull.

Thank you for this amazing development platform!
:)

**Comment by blocka** [comment] 2015-03-17 06:42
Likewise on my ubuntu machine, chrome does not open with the debugger as advertised. I need to grab the random port as shown above.

**Comment by alex-rokabilis** [comment] 2015-03-17 22:42
thanks for noticing this I was struggling for the same thing, I am new to nativescript too. Also how can you see the console.log messages?

**Comment by eutobias** [comment] 2015-03-18 01:37
Well everyone is new to nativescript =p...
Open your browser with the url i've said replacing the port

**Comment by rosen-vladimirov** [comment] 2015-03-24 15:11
Hi @eutobias 
Please excuse us for the late reply. You are correct ```--debug-port``` option is ignored when ti is combine with ```--debug-brk```. You have found the easiest workaround - to execute debug command with log trace and check the port from there.

**Comment by eutobias** [comment] 2015-03-24 15:26
How could i debug without --debug-brk parameter? Is it possible?

**Comment by rosen-vladimirov** [comment] 2015-03-24 15:38
Hi @eutobias 
You can start your app on the device/emulator and try
```
tns debug android --start --debug-port 7878
```

**Comment by blocka** [comment] 2015-03-24 15:40
The problem with this is that you have to put in `debugger;` statements in
your code, because they're no way to set breakpoints in the debugger. Why
does `--debug-brk` ignore `--debug-port`?

On Tue, Mar 24, 2015 at 11:38 AM, Rosen Vladimirov <notifications@github.com

**Comment by rosen-vladimirov** [comment] 2015-03-26 13:27
Hi @blocka ,
This is a bug, that we'll fix for one of our next releases. If the issue is urgent, you can fork the repo on your side and fix the problem. After that you can send us a Pull Request with the fix. More information can be found [here](https://github.com/NativeScript/nativescript-cli/blob/master/CONTRIBUTING.md#contribute-to-the-code-base)

**Comment by dtopuzov** [comment] 2016-02-26 09:07
Should be resolved with latest version.

**Closed by dtopuzov** 2016-02-26 09:07 UTC
Labels: bug, debug
