### ISSUE TITLE
I get an Error: The current version of nativescript-dev-webpack (1.0.0) is not compatible with the used CLI: 5.4.2.  when i run tns run android --bundle

### ISSUE THREAD

**Issue by Mudaib** [NativeScript/nativescript-cli#4845] opened 2019-07-12 16:58 UTC
when I run tns run android build --bundle I get this error: [. Error: The current version of nativescript-dev-webpack (1.0.0) is not compatible with the used CLI: 5.4.2. Please upgrade your NativeScript CLI version (npm i -g nativescript).
I have tried installing the nativescript cli again but it seems not to work

**Comment by ILikePizza555** [comment] 2019-07-12 18:46
I am also getting this error, with `nativescript-dev-webpack (1.0.0-next-2019-07-04-112332-01)`

**Comment by rezaee** [comment] 2019-07-13 16:28
I get the same massega:
```
Your application will be deployed only on the device specified by the provided index or identifier.
Unable to apply changes on device: emulator-5554. Error is: The current version of nativescript-dev-webpack (1.0.0) is not compatible with the used CLI: 5.4.2. Please upgrade your NativeScript CLI version (npm i -g nativescript)..
```

When I want to run `tns run android --device Pixel_2_API_29`

**Comment by rezaee** [comment] 2019-07-14 15:35
Anyone could solve his/her problem?

**Comment by vmutafov** [comment] 2019-07-14 15:42
Hi! Could you try using NativeScript CLI from the RC tag? (`npm i -g nativescript@rc`)

**Comment by rezaee** [comment] 2019-07-14 15:52
Hi,
What is the RC tag? If we install it, how can we come back to CLI 6 when released?

**Comment by rezaee** [comment] 2019-07-14 16:42
@vmutafov : I tried your code but I got:

```
ERROR in ../node_modules/nativescript-dev-webpack/load-application-css-angular.js
Module not found: Error: Can't resolve '~/app' in 'C:\Users\m\Desktop\JS\NativeScript\conFusion\node_modules\nativescript-dev-webpack'
 @ ../node_modules/nativescript-dev-webpack/load-application-css-angular.js 5:49-65
```

**Comment by vmutafov** [comment] 2019-07-14 18:33
Hi @rezaee :) The RC stands for Release Candidate. The RC tags of the NativeScript packages are the almost final version before the official release. You can take a look at the NPM page for the CLI for example: https://www.npmjs.com/package/nativescript When NativeScript 6.0 is released, the `latest` tag will point to 6.0.0 and not 5.4.2 like now. There are some other tags like `next` which is build on every merged pull request in github and contains the newest features before they are released officially. 

If you install the NativeScript CLI globally with the RC tag like you did, when 6.0 is released you can just update the CLI again with `npm i -g nativescript` and you'll have the released version of the CLI.

About your problem, could you share your app or at least the `package.json`. I'm concerned specifically about the `nativescript` packages' versions. And also, does the application start or it fails build time?

**Comment by rezaee** [comment] 2019-07-15 04:47
@vmutafov , Hi and thanks for help. My project is uploaded here: https://github.com/rezaee/confusion-last

**Comment by rezaee** [comment] 2019-07-15 05:07
This is the result I do get:

```

C:\Users\m\Desktop\JS\NativeScript\conFusion>tns run android --device Pixel_2_API_29
Searching for devices...
Starting Android emulator with image Pixel_2_API_29
Waiting for emulator device initialization...
Your application will be deployed only on the device specified by the provided index or identifier.
Preparing project...
clean-webpack-plugin: C:\Users\m\Desktop\JS\NativeScript\conFusion\platforms\android\app\src\main\assets\app\**\* has been removed.
File change detected. Starting incremental webpack compilation...

webpack is watching the files…

Hash: 2b1d4d4176ff99ccb573
Version: webpack 4.35.3
Time: 11339ms
Built at: 07/15/2019 9:36:13 AM
                                                              Asset       Size   Chunks             Chunk Names
                                   App_Resources/Android/app.gradle  556 bytes           [emitted]
                 App_Resources/Android/src/main/AndroidManifest.xml   1.37 KiB           [emitted]
    App_Resources/Android/src/main/res/drawable-hdpi/background.png   3.42 KiB           [emitted]
          App_Resources/Android/src/main/res/drawable-hdpi/icon.png    6.8 KiB           [emitted]
          App_Resources/Android/src/main/res/drawable-hdpi/logo.png   32.4 KiB           [emitted]
    App_Resources/Android/src/main/res/drawable-ldpi/background.png   1.31 KiB           [emitted]
          App_Resources/Android/src/main/res/drawable-ldpi/icon.png   3.23 KiB           [emitted]
          App_Resources/Android/src/main/res/drawable-ldpi/logo.png   9.95 KiB           [emitted]
    App_Resources/Android/src/main/res/drawable-mdpi/background.png   1.89 KiB           [emitted]
          App_Resources/Android/src/main/res/drawable-mdpi/icon.png   3.42 KiB           [emitted]
          App_Resources/Android/src/main/res/drawable-mdpi/logo.png   15.8 KiB           [emitted]
App_Resources/Android/src/main/res/drawable-nodpi/splash_screen.xml  304 bytes           [emitted]
   App_Resources/Android/src/main/res/drawable-xhdpi/background.png   5.26 KiB           [emitted]
         App_Resources/Android/src/main/res/drawable-xhdpi/icon.png   10.4 KiB           [emitted]
         App_Resources/Android/src/main/res/drawable-xhdpi/logo.png     54 KiB           [emitted]
  App_Resources/Android/src/main/res/drawable-xxhdpi/background.png   10.3 KiB           [emitted]
        App_Resources/Android/src/main/res/drawable-xxhdpi/icon.png   20.3 KiB           [emitted]
        App_Resources/Android/src/main/res/drawable-xxhdpi/logo.png    116 KiB           [emitted]
 App_Resources/Android/src/main/res/drawable-xxxhdpi/background.png   3.87 KiB           [emitted]
       App_Resources/Android/src/main/res/drawable-xxxhdpi/icon.png   73.8 KiB           [emitted]
       App_Resources/Android/src/main/res/drawable-xxxhdpi/logo.png    193 KiB           [emitted]
           App_Resources/Android/src/main/res/values-v21/colors.xml  104 bytes           [emitted]
           App_Resources/Android/src/main/res/values-v21/styles.xml  902 bytes           [emitted]
               App_Resources/Android/src/main/res/values/colors.xml  237 bytes           [emitted]
               App_Resources/Android/src/main/res/values/styles.xml   1.68 KiB           [emitted]
                                                app/images/logo.png     21 KiB           [emitted]
                                                          bundle.js    310 KiB   bundle  [emitted]  bundle
                                                       package.json   81 bytes           [emitted]
                                                         runtime.js   71.7 KiB  runtime  [emitted]  runtime
                                                tns-java-classes.js    0 bytes           [emitted]
                                                          vendor.js     16 MiB   vendor  [emitted]  vendor
Entrypoint bundle = runtime.js vendor.js bundle.js
[./app/about/about.component.ts] 1.26 KiB {bundle} [built]
[./app/app.component.ts] 910 bytes {bundle} [built]
[./app/app.module.ts] 4.03 KiB {bundle} [built]
[./app/app.routing.ts] 1.47 KiB {bundle} [built]
[./app/comment/comment.component.ts] 1.75 KiB {bundle} [built]
[./app/contact/contact.component.ts] 1.74 KiB {bundle} [built]
[./app/dishdetail/dishdetail.component.ts] 7.75 KiB {bundle} [built]
[./app/favorites/favorites.component.ts] 4.31 KiB {bundle} [built]
[./app/home/home.component.ts] 8.48 KiB {bundle} [built]
[./app/menu/menu.component.ts] 1.23 KiB {bundle} [built]
[./app/reservation/reservation.component.ts] 4.83 KiB {bundle} [built]
[./app/reservationmodal/reservationmodal.component.ts] 2.3 KiB {bundle} [built]
[./app/services/couchbase.service.ts] 1.03 KiB {bundle} [built]
[./app/services/dish.service.ts] 1.6 KiB {bundle} [built]
[./main.ts] 2.36 KiB {bundle} [built]
    + 528 hidden modules

WARNING in ../node_modules/app-settings/lib/settings.js 41:15-32
Critical dependency: the request of a dependency is an expression
 @ ./app/userauth/userauth.component.ts
 @ ./app/app.module.ts
 @ ./main.ts

ERROR in ../node_modules/nativescript-dev-webpack/load-application-css-angular.js
Module not found: Error: Can't resolve '~/app' in 'C:\Users\m\Desktop\JS\NativeScript\conFusion\node_modules\nativescript-dev-webpack'
 @ ../node_modules/nativescript-dev-webpack/load-application-css-angular.js 5:49-65
 @ ./main.ts
Webpack compilation complete. Watching for file changes.
Webpack build done!

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':packageReleaseResources'.
> Could not resolve all files for configuration ':_internal_aapt2_binary'.
   > Could not find com.android.tools.build:aapt2:3.4.0-5326820.
     Searched in the following locations:
       - file:/C:/Users/m/.m2/repository/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820.pom
       - file:/C:/Users/m/.m2/repository/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820-windows.jar
       - https://repo.maven.apache.org/maven2/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820.pom
       - https://repo.maven.apache.org/maven2/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820-windows.jar
       - https://maven.google.com/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820.pom
       - https://maven.google.com/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820-windows.jar
       - https://jcenter.bintray.com/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820.pom
       - https://jcenter.bintray.com/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820-windows.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Failed to build plugin nativescript-phone :
Error: Command gradlew.bat failed with exit code 1
```

**Comment by sis0k0** [comment] 2019-07-15 10:04
Hi @rezaee,

The build is failing because of the following error (based on the log you posted):
```
ERROR in ../node_modules/nativescript-dev-webpack/load-application-css-angular.js
Module not found: Error: Can't resolve '~/app' in 'C:\Users\m\Desktop\JS\NativeScript\conFusion\node_modules\nativescript-dev-webpack'
 @ ../node_modules/nativescript-dev-webpack/load-application-css-angular.js 5:49-65
 @ ./main.ts
```

The problem is that webpack cannot load the global styles file - `app.css`. By default, this file should be in the `src/` directory. In the project that you shared it's located in `src/app/`. If you experience other problems while migrating to NativeScript 6.0 and the bundle workflow, please check the `migration-to-bundle` issues - https://github.com//issues?q=is%3Aissue+label%3Amigration-to-bundle+user%3ANativeScript.

**Comment by rezaee** [comment] 2019-07-15 11:46
@sis0k0 :  I did some corrections in my app and also updated git repository, but I still get this result:

```

C:\Users\m\Desktop\JS\NativeScript\conFusion>tns run android --device Pixel_2_API_29
Searching for devices...
Starting Android emulator with image Pixel_2_API_29
Waiting for emulator device initialization...
Your application will be deployed only on the device specified by the provided index or identifier.
Preparing project...
clean-webpack-plugin: C:\Users\m\Desktop\JS\NativeScript\conFusion\platforms\android\app\src\main\assets\app\**\* has been removed.
File change detected. Starting incremental webpack compilation...

webpack is watching the files…

Hash: faa894b7bacbbac9d1cf
Version: webpack 4.35.3
Time: 12988ms
Built at: 07/15/2019 4:14:37 PM
                                                              Asset       Size   Chunks             Chunk Names
                                   App_Resources/Android/app.gradle  556 bytes           [emitted]
                 App_Resources/Android/src/main/AndroidManifest.xml   1.37 KiB           [emitted]
    App_Resources/Android/src/main/res/drawable-hdpi/background.png   3.42 KiB           [emitted]
          App_Resources/Android/src/main/res/drawable-hdpi/icon.png    6.8 KiB           [emitted]
          App_Resources/Android/src/main/res/drawable-hdpi/logo.png   32.4 KiB           [emitted]
    App_Resources/Android/src/main/res/drawable-ldpi/background.png   1.31 KiB           [emitted]
          App_Resources/Android/src/main/res/drawable-ldpi/icon.png   3.23 KiB           [emitted]
          App_Resources/Android/src/main/res/drawable-ldpi/logo.png   9.95 KiB           [emitted]
    App_Resources/Android/src/main/res/drawable-mdpi/background.png   1.89 KiB           [emitted]
          App_Resources/Android/src/main/res/drawable-mdpi/icon.png   3.42 KiB           [emitted]
          App_Resources/Android/src/main/res/drawable-mdpi/logo.png   15.8 KiB           [emitted]
App_Resources/Android/src/main/res/drawable-nodpi/splash_screen.xml  304 bytes           [emitted]
   App_Resources/Android/src/main/res/drawable-xhdpi/background.png   5.26 KiB           [emitted]
         App_Resources/Android/src/main/res/drawable-xhdpi/icon.png   10.4 KiB           [emitted]
         App_Resources/Android/src/main/res/drawable-xhdpi/logo.png     54 KiB           [emitted]
  App_Resources/Android/src/main/res/drawable-xxhdpi/background.png   10.3 KiB           [emitted]
        App_Resources/Android/src/main/res/drawable-xxhdpi/icon.png   20.3 KiB           [emitted]
        App_Resources/Android/src/main/res/drawable-xxhdpi/logo.png    116 KiB           [emitted]
 App_Resources/Android/src/main/res/drawable-xxxhdpi/background.png   3.87 KiB           [emitted]
       App_Resources/Android/src/main/res/drawable-xxxhdpi/icon.png   73.8 KiB           [emitted]
       App_Resources/Android/src/main/res/drawable-xxxhdpi/logo.png    193 KiB           [emitted]
           App_Resources/Android/src/main/res/values-v21/colors.xml  104 bytes           [emitted]
           App_Resources/Android/src/main/res/values-v21/styles.xml  902 bytes           [emitted]
               App_Resources/Android/src/main/res/values/colors.xml  237 bytes           [emitted]
               App_Resources/Android/src/main/res/values/styles.xml   1.68 KiB           [emitted]
                                                app/images/logo.png     21 KiB           [emitted]
                                                          bundle.js    315 KiB   bundle  [emitted]  bundle
                                                       package.json   81 bytes           [emitted]
                                                         runtime.js   71.7 KiB  runtime  [emitted]  runtime
                                                tns-java-classes.js    0 bytes           [emitted]
                                                          vendor.js     16 MiB   vendor  [emitted]  vendor
Entrypoint bundle = runtime.js vendor.js bundle.js
[./app.css] 1.7 KiB {bundle} [built]
[./app/about/about.component.ts] 1.26 KiB {bundle} [built]
[./app/app.component.ts] 910 bytes {bundle} [built]
[./app/app.module.ts] 4.03 KiB {bundle} [built]
[./app/app.routing.ts] 1.47 KiB {bundle} [built]
[./app/comment/comment.component.ts] 1.75 KiB {bundle} [built]
[./app/contact/contact.component.ts] 1.74 KiB {bundle} [built]
[./app/dishdetail/dishdetail.component.ts] 7.75 KiB {bundle} [built]
[./app/favorites/favorites.component.ts] 4.31 KiB {bundle} [built]
[./app/home/home.component.ts] 8.48 KiB {bundle} [built]
[./app/menu/menu.component.ts] 1.23 KiB {bundle} [built]
[./app/reservation/reservation.component.ts] 4.83 KiB {bundle} [built]
[./app/reservationmodal/reservationmodal.component.ts] 2.3 KiB {bundle} [built]
[./app/services/couchbase.service.ts] 1.03 KiB {bundle} [built]
[./main.ts] 2.36 KiB {bundle} [built]
    + 531 hidden modules

WARNING in ../node_modules/app-settings/lib/settings.js 41:15-32
Critical dependency: the request of a dependency is an expression
 @ ./app/userauth/userauth.component.ts
 @ ./app/app.module.ts
 @ ./main.ts
Webpack compilation complete. Watching for file changes.
Webpack build done!

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':packageReleaseResources'.
> Could not resolve all files for configuration ':_internal_aapt2_binary'.
   > Could not find com.android.tools.build:aapt2:3.4.0-5326820.
     Searched in the following locations:
       - file:/C:/Users/m/.m2/repository/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820.pom
       - file:/C:/Users/m/.m2/repository/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820-windows.jar
       - https://repo.maven.apache.org/maven2/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820.pom
       - https://repo.maven.apache.org/maven2/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820-windows.jar
       - https://maven.google.com/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820.pom
       - https://maven.google.com/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820-windows.jar
       - https://jcenter.bintray.com/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820.pom
       - https://jcenter.bintray.com/com/android/tools/build/aapt2/3.4.0-5326820/aapt2-3.4.0-5326820-windows.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Failed to build plugin nativescript-phone :
Error: Command gradlew.bat failed with exit code 1
```

**Comment by KristianDD** [comment] 2019-07-16 10:18
Hi @rezaee,
After extracting the `app.css` to the `src` folder and changing the `@import 'nativescript-theme-core/css/purple.css';` to `@import '~nativescript-theme-core/css/purple.css';` the project was build successfully.

I would suggest clearing the build artifacts and configuration folders of your project and try building the project again.
`rm -rf platforms C:\Users\{UserName}\.gradle`

The second location is the Gradle cache, which might resolve the `Could not find com.android.tools.build:aapt2:3.4.0-5326820.` error.

**Comment by KristianDD** [comment] 2019-08-05 07:25
Closing due to inactivity.

**Closed by KristianDD** 2019-08-05 07:25 UTC
Labels: needs more info, question
