### ISSUE TITLE
Livesync process takes high cpu

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#4199] opened 2018-12-04 10:43 UTC
@agnoam commented on [Tue Dec 04 2018](https://github.com/NativeScript/NativeScript/issues/6657)

Hello, 
I run the `tns run android` on my Windows 10 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz machine.

Why NativeScript livesync is very cpu wasteful. There is any way to decrease its  process, Because for comparison Flutter livesync work batter and not stuck my pc.

**Comment by rosen-vladimirov** [comment] 2018-12-06 21:03
Hey @agnoam ,
We are not experiencing the same behavior on our side. 
During LiveSync CLI starts several subprocesses, but we have not observed such high CPU load.
Can you identify which are the processes that are causing the high CPU load, for example using [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) - with this tool you can monitor the processes, order them by CPU load and once you identify the ones which are causing the load, you can double-click them and check all of the arguments of the process. Can you send us this information, so we can check what is the process used for and can we do something to reproduce the issue on our side and suggest a solution?

I'm looking forward to hearing from you.

**Comment by dtopuzov** [comment] 2019-01-19 19:04
Closing since we have not enough info and steps to reproduce.

**Closed by dtopuzov** 2019-01-19 19:04 UTC
Labels: needs more info
