### ISSUE TITLE
console.log on device not working consistently if at all

### ISSUE THREAD

**Issue by dottodot** [NativeScript/nativescript-cli#4570] opened 2019-04-26 16:42 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.3.4
 - Cross-platform modules: 5.3.1
 - Android Runtime: N/A
 - iOS Runtime: 5.3.1
 - Plugin(s): 
    "nativescript-angular": "^7.2.3",
    "nativescript-background-http": "^3.4.0",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-drawingpad": "^3.0.4",
    "nativescript-geolocation": "^4.5.0",
    "nativescript-iqkeyboardmanager": "^1.4.0",
    "nativescript-sentry": "^1.9.1",
    "nativescript-sqlite": "^2.3.3",
    "nativescript-status-bar": "^1.1.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "^6.2.0",

**Describe the bug**

Firstly when using the ios simulator I have no problems whatsoever can work all day and `console.log` will work all the time. The problem only occurs when running on a device which is making debugging anything that you can't use on the simulator hugely frustrating.

On the first load logging generally works at least to start with, however more often than not logging will just stop as you do more things within the app. If I need make a change and it live reloads it pretty much always stops logging.

**To Reproduce**

`tns run ios --bundle`

**Expected behavior**
logging should continue to work just as it does on the simulator.

**Comment by Fatme** [comment] 2019-04-29 14:39
@dottodot,

> however more often than not logging will just stop as you do more things within the app.

Can you please share the exact steps so we can reproduce the issue on our side?

It'll be great appreciated if you send us a sample project demonstrating the described behavior.

**Comment by jasonstcyr** [comment] 2019-07-25 19:48
I'm having something somewhat related.

I'm running my unit tests. They we're working reliably for a long time but then something happening. It started maybe after updating to the newest NativeScript? 

If I run my unit tests using tns test android it will always output the console.log statements reliably on the first run. When I got back to save something it'll re run (I also have to manually relaunch the NS app) and the console.log statement do not display.

They work reliably all the time in the iOS emulator.

**Comment by miroslavaivanova** [comment] 2019-07-30 08:10
@jasonstcyr I logged it as [separate issue](https://github.com/NativeScript/nativescript-cli/issues/4914) because it is not related to the issue from this thread. 
@dottodot The issue seems resolved now. I'm closing it.

**Closed by miroslavaivanova** 2019-07-30 08:10 UTC
Labels: needs more info
