### ISSUE TITLE
broken documentation

### ISSUE THREAD

**Issue by frudman** [NativeScript/nativescript-cli#3211] opened 2017-11-10 15:51 UTC
The documentation of this page is poorly written and reporting a problem on it is broken:

Page url: **https://docs.nativescript.org/runtimes/android/metadata/accessing-packages**

Problem 1) poor documentation: there is NO WAY to know HOW to use/declare **java.lang** or **java.views** (for example) from reading this documentation. A very simple setup instruction is critical as it's very hard to find how to do it in a very disorganized site. I did through these 2 stackoverflow links (which were frustratingly hard to find for such a basic issue): 
a) https://stackoverflow.com/questions/37145983/missing-android-package-in-nativescript-using-typescript
b) https://www.npmjs.com/package/tns-platform-declarations

That information should be combined and made easily available on that very page (above).

Problem 2: when I tried to comment on this (from your "Improve This Page" link at the bottom of your page), it goes to a 404-Page-Not-Found (at least right now, Nov 10, 2017)

We've just discovered NativeScript and it shows **great promise** (really) but little stumbling blocks like this can become a high barrier to adoption for any serious dev effort, especially those coming from Xamarin/C# where the code base (and docs) is [so far] more mature.

**Comment by etabakov** [comment] 2017-11-10 16:50
Hey @frudman. I will try to address your problems one by one:

 - Regarding the not working "Improve This Article" button - A fix was just deployed on live and the button should work as expected now. Thanks for letting us know about this problem!
 - About the poor quality of the article you stumbled upon - This will be discussed with the team and we will try to provide all the required context for the article to be useful. Meanwhile, if you have any suggestions - feel free to open an Issue or Pull Request. We will be very happy to consider it.
 - Regarding the fact that our documentation is disorganised - We have identified this to be a serious problem and part of our roadmap for the next several months is to revise the whole website and build a well-organised and holistic documentation for our product. I hope you will see the improvement in the months to come.
 - Meanwhile, if you still have issues with accessing packages - please, provide us with some details so we can address it.

Finally, many thanks for your honest feedback. I hope you don't stumbled upon such little block, but if you do - be sure to let us know and we will be happy to help.

**Comment by NickIliev** [comment] 2017-11-13 11:33
@frudman Thank you for pointing out the need to update the article about accessing Android packages.
Keep in mind that when using plain JavaScript you do not need to explicitly install `tns-platform-declarations`.  This is needed only when using Angular or TypeScript and is described in [this article section](https://docs.nativescript.org/core-concepts/accessing-native-apis-with-javascript#intellisense-and-access-to-native-apis-via-typescript) about accessing native APIs via TypeScript.

Of course, we have added a note that explains the additional step for TypeScript projects.
The issue is resolved via [this PR](https://github.com/NativeScript/docs/pull/961)

**Comment by etabakov** [comment] 2017-12-05 12:49
I'm closing the issue due to inactivity. If you still have problems with the described scenario - feel free to write back.

**Closed by etabakov** 2017-12-05 12:49 UTC
Labels: docs
