### ISSUE TITLE
TNS version 4 is so verbose. How to disable it 

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-cli#3577] opened 2018-05-12 17:18 UTC
After upgrading to version 4 , on each error there is an error message and and ERror context object
```
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
Successfully synced application org.nativescript.game2 on device 192.168.47.101:5555.
ActivityManager: Start proc 1842:org.nativescript.game2/u0a81 for activity org.nativescript.game2/com.tns.NativeScriptActivity
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ERROR TypeError: Cannot read property 'push' of undefined
JS: ERROR CONTEXT {
JS:   "view": {
JS:     "def": {
```

This ^ is so long that it is **impossible** to work with . 
We have to scroll each time to the top to search what was the error.

Is there a way to disable this behaviour ?
Also it seems that non-related logcat messages are also embedded in this window ( from other services)

So  **Question** 👍 
1) Is it possible to disable the error context object verbosity ?
2) How not to include non-related-logcat ( from other services) when `tns run` ?

A full example for such verbose log : https://pastebin.com/3tpdJiSV

**Comment by NickIliev** [comment] 2018-05-15 13:35
@RoyiNamir the issue is a known problem caused by the verbose loggin of the Angular context. This is related to [https://github.com/NativeScript/android-runtime/issues/1026](https://github.com/NativeScript/android-runtime/issues/1026) and in [this comment](https://github.com/NativeScript/android-runtime/issues/1026#issuecomment-386982278), you will find the actual fix that will be released with version 4.1 of Android runtime.

Closing as duplicate to [https://github.com/NativeScript/android-runtime/issues/1026](https://github.com/NativeScript/android-runtime/issues/1026)

**Closed by NickIliev** 2018-05-15 13:35 UTC
