### ISSUE TITLE
Allow plugins to be prepared, not just added

### ISSUE THREAD

**Issue by maknz** [NativeScript/nativescript-cli#764] opened 2015-08-10 02:54 UTC
We want to use the new `nativescript-telerik-ui`, but have come across a problem. We don't want to commit lib/Android and lib/iOS to version control, as they're automatically generated. But, we do want to include `nativescript-telerik-ui` in our package.json so we can `npm install` it.

Say I clone the project fresh. I've got the entry in my package.json file, but nothing in node_modules because of course it's ignored from version control. I can't do `tns plugin add nativescript-telerik-ui` since it will see it already in package.json and assume it's installed -- but it's not, there's nothing in `lib/`. I see there is a `prepare` function that `add` uses after the npm install, is this what needs to be exposed? We can use npm to get the package added to node_modules, but we need a command to copy the native stuff out to `lib/`, which is then used in the `tns prepare` to pass it down to the native projects, AFAIK.

**Comment by ligaz** [comment] 2015-08-10 09:52
Hi @maknz,
We have a dedicated command for your scenario: [`tns install`](https://github.com/NativeScript/nativescript-cli/blob/master/docs/man_pages/project/configuration/install.md). Please give it a try.

**Comment by maknz** [comment] 2015-08-10 09:53
Argh, how did I miss that? Thanks, will try this soon.

**Comment by maknz** [comment] 2015-08-10 22:33
I get the following:

```
$ tns install
Exception: Platform ios already addedException: Platform android already added
```

We need to keep the iOS platform committed because of Cocoapods.

**Comment by Fatme** [comment] 2015-08-11 09:20
Hi @maknz,

I think you can do the following:

* rm -rf `node_modules`, rm -rf `platforms/ios/<your project name>/app`
* npm i
* `tns prepare ios` 

Let me know if this works for you.

**Comment by valentinstoychev** [comment] 2015-08-11 10:43
@Fatme is this the expected behaviour or do you think there is an issue with the setup on the maknz machine?

**Comment by ligaz** [comment] 2015-08-11 10:49
With the upcoming support for Cocoapods the podfile shouldn't be necessary to be under version control, because it will be an artifact. Regarding the launch screens those should be placed in `app/App_Resources/iOS` and everything should work.

I don't think we currently support partially versioned platforms directory but I guess this should be a scenario that we will want to support (for example the `podfile.lock` should be versioned).

**Comment by maknz** [comment] 2015-08-12 22:53
Thanks, we'll look into reworking the launch screens. At this stage, the only thing preventing us from gitignoring the iOS platform is pods, so that should be sorted in 1.3.

Having a podfile.lock is definitely important, we'll want to be able to commit the exact set of pod dependencies we have, as is common with Gemfile/Gemfile.lock in Ruby and composer.json/composer.lock in PHP.

**Comment by ligaz** [comment] 2015-08-14 03:37
I'm going to close this one for now. We can continue our conversation in the pods support issue #769

**Closed by ligaz** 2015-08-14 03:37 UTC
