### ISSUE TITLE
On adding test frameworks their peerDependencies are not installed

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/nativescript-cli#2283] opened 2016-11-30 11:44 UTC
**Steps to reproduce:**
1. Create app and add platform
2. tns test init --framework jasmine/mocha
3. tns test android/ios

**Expected result:** Tests are executes and results are shown
**Actual result:** Exception `Error: Cannot find module 'jasmine-core'...`

**Comment by Plamen5kov** [comment] 2016-11-30 12:04
_Problem_

Only occurs when the user has installed globally npm version 3.x. The difference between npm 2.x and 3.x is that, npm 2.x installs all peer-dependencies of a package and npm 3.x does not.
Example: lets install the following package with `package.json` like:
```javascript
{
  "name": "some-dependency",
  "version": "1.0.0",
  "peer-dependencies": {
    "peer-dep-1": "0.0.1"
  }
}
```
So if we do:
`npm install some-dependency --save` with npm 2.x, `peer-dep-1` will be installed, but if we do the same with npm 3.x `peer-dep-1` will not be installed. This happens, because npm 3.x does not install the peer-dependencies.

_Possible solutions_
* Forcefully install the peer dependencies of all packages when using `tns init` command. When doing it with npm 2.x, nothing will happen.
* Add missing peer dependency to `tns init` command (harder to maintain)

**Comment by Pip3r4o** [comment] 2016-11-30 13:26
@Plamen5kov how about leaving the responsibility of installing dev peer dependencies to the developer? Messages output by npm are verbose enough where peer dependencies are concerned.

**Comment by NickIliev** [comment] 2016-11-30 13:53
related to [https://github.com/NativeScript/nativescript-cli/issues/2212#issuecomment-263877510](https://github.com/NativeScript/nativescript-cli/issues/2212#issuecomment-263877510)

**Comment by vakrilov** [comment] 2017-03-08 12:10
I think that after seeing the message about the unmet peer dependency -its clear what you have to do. However, it would be great to update the [docs](https://docs.nativescript.org/tooling/testing#configure-your-project) with a note that you will have to manually add a dependency based on the testing framework you choose. It would help people who just follow the guide.

@Pip3r4o moving `peer-dependecy` to `dependency` is out of our reach as it is the `karma-jamine` package that has the peer-dep.

**Comment by dtopuzov** [comment] 2017-04-25 14:21
https://github.com/NativeScript/nativescript-cli/pull/2693 fix `jasmin` and `qunit` successfully, but you still need to manually install `mocha`.

**Comment by dtopuzov** [comment] 2017-04-25 14:35
CLI is now adding peer dependencies, but the problem is that `mocha` is not longer peer dependency.
May be we should close the issue add some notes here: 
https://docs.nativescript.org/tooling/testing#configure-your-project

**Comment by rosen-vladimirov** [comment] 2017-04-26 07:07
I believe the `$ tns test init` command should provide a project that's ready for writing tests, without the need to install any dependencies additionally. We can improve our logic here:
https://github.com/NativeScript/nativescript-cli/blob/master/lib/commands/test-init.ts#L7-L9
https://github.com/NativeScript/nativescript-cli/blob/master/lib/commands/test-init.ts#L32-L33

To add the required depdendencies (as `mocha`).

**Comment by NickIliev** [comment] 2018-05-15 07:53
The issue is still reproducible .. running 
```
tns test init --framework mocha
tns test ios
```

is failing with 
```
Error: Cannot find module 'mocha'
```

**Closed** 2018-06-25 10:19 UTC
Labels: bug, unit testing
