### ISSUE TITLE
Push-Plugin 0.0.13 & Telerik-UI-Plugin 0.2.3

### ISSUE THREAD

**Issue by seppel1992** [NativeScript/nativescript-cli#1434] opened 2016-01-28 09:21 UTC
The build for android fails when both plugins (Push and Telerik-UI) are installed at the same time since the latest upgrade to NativeScript 1.5.2. When one of them are uninstalled, the project build works fine.

Can anybody reproduce? You just have to create an empty project.

![errorpushtelerikui](https://cloud.githubusercontent.com/assets/6443021/12640128/a0ac1624-c5a8-11e5-95f9-25b221abde41.PNG)

**Comment by rosen-vladimirov** [comment] 2016-01-28 09:26
Hi @seppel1992 , 
Can you paste the full error? In fact can you run
`tns build android --log trace`
and send us the output?

**Comment by seppel1992** [comment] 2016-01-28 09:40
Hi @rosen-vladimirov ,
The full output is:

execFile: C:\Users\felix\AppData\Local\Android\Sdk\platform-tools\adb "help"
spawn: C:\Users\felix\AppData\Local\Android\Sdk\tools\android.bat "--help"

       Usage:
       android [global options] action [action options]
       Global options:
  -s --silent     : Silent mode, shows errors only.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -h --help       : Help on a specific command.

                                                                    Valid
                                                                    actions
                                                                    are
                                                                    composed
                                                                    of a verb
                                                                    and an
                                                                    optional
                                                                    direct
                                                                    object:
-    sdk              : Displays the SDK Manager window.
-    avd              : Displays the AVD Manager window.
-   list              : Lists existing targets or virtual devices.
-   list avd          : Lists existing Android Virtual Devices.
-   list target       : Lists existing targets.
-   list device       : Lists existing devices.
-   list sdk          : Lists remote SDK repository.
- create avd          : Creates a new Android Virtual Device.
-   move avd          : Moves or renames an Android Virtual Device.
- delete avd          : Deletes an Android Virtual Device.
- update avd          : Updates an Android Virtual Device to match the folders
                        of a new SDK.
- create project      : Creates a new Android project.
- update project      : Updates an Android project (must already have an
                        AndroidManifest.xml).
- create test-project : Creates a new Android project for a test package.
- update test-project : Updates the Android project for a test package (must
                        already have an AndroidManifest.xml).
- create lib-project  : Creates a new Android library project.
- update lib-project  : Updates an Android library project (must already have
                        an AndroidManifest.xml).
- create uitest-project: Creates a new UI test project.
- update adb          : Updates adb to support the USB devices declared in the
                        SDK add-ons.
- update sdk          : Updates the SDK by suggesting new platforms to install
                        if available.

Exec npm -v 
 stdout: 2.11.3
 
 stderr: 
spawn: java "-version"
Exec node-gyp -v 
 stdout:  
 stderr: Der Befehl "node-gyp" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

Exec "C:\Users\felix\AppData\Local\Android\Sdk\platform-tools\adb" version 
 stdout: Android Debug Bridge version 1.0.32
Revision 09a0d98bebce-android
 
 stderr: 
spawn: C:\Users\felix\AppData\Local\Android\Sdk\tools\android.bat "-h"
Exec mono --version 
 stdout:  
 stderr: Der Befehl "mono" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

Exec git --version 
 stdout: git version 2.7.0.windows.1
 
 stderr: 
Exec gradle -v 
 stdout:  
 stderr: Der Befehl "gradle" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

Exec "C:\Program Files\Java\jdk1.8.0_71\bin\javac" -version 
 stdout:  
 stderr: javac 1.8.0_71

System information:
{ procInfo: 'nativescript/1.5.2',
  platform: 'win32',
  os: 'Windows 10 Pro 6.3.10586',
  shell: 'C:\\WINDOWS\\system32\\cmd.exe',
  dotNetVer: '4.6.01038',
  procArch: 'ia32',
  nodeVer: 'v0.12.7',
  npmVer: '2.11.3',
  javaVer: '1.8.0',
  nodeGypVer: null,
  xcodeVer: null,
  itunesInstalled: true,
  cocoapodVer: null,
  adbVer: 'Android Debug Bridge version 1.0.32',
  androidInstalled: true,
  monoVer: null,
  gitVer: '2.7.0.windows.1',
  gradleVer: null,
  javacVersion: '1.8.0_71' }
Starting watch on killswitch C:\Users\felix\AppData\Local\Temp\felix\KillSwitches\cli
Initializing analytics statuses.
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 0 }
Trying to track feature 'Non-interactive' with value 'build'.
execFile: C:\Users\felix\AppData\Local\Android\Sdk\platform-tools\adb "help"
Looking for project in 'C:\Users\felix\Desktop\Test152'
Project directory is 'C:\Users\felix\Desktop\Test152'.
spawn: C:\Users\felix\AppData\Local\Android\Sdk\platform-tools\adb "start-server"
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 0 }
Trying to track feature 'Non-interactive' with value 'build|android'.
Hooks directories: [ 'C:\\Users\\felix\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\hooks',
  'C:\\Users\\felix\\AppData\\Roaming\\npm\\node_modules\\nativescript\\lib\\common\\hooks',
  'C:\\Users\\felix\\Desktop\\Test152\\hooks' ]
BeforeHookName for command prepare is before-prepare
Project successfully prepared
AfterHookName for command prepare is after-prepare
spawn: C:\Users\felix\AppData\Local\Android\Sdk\tools\android.bat "list" "targets"
Available Android targets:
----------
id: 1 or "android-22"
     Name: Android 5.1.1
     Type: Platform
     API level: 22
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320
 Tag/ABIs : android-tv/armeabi-v7a, android-tv/x86, android-wear/armeabi-v7a, android-wear/x86, default/armeabi-v7a, default/x86, default/x86_64
----------
id: 2 or "android-23"
     Name: Android 6.0
     Type: Platform
     API level: 23
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound360x360, AndroidWearRound400x400, AndroidWearRound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320, AndroidWearRound, AndroidWearRound360x360, AndroidWearRound400x400, AndroidWearRound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320
 Tag/ABIs : android-tv/armeabi-v7a, android-tv/x86, android-wear/armeabi-v7a, android-wear/x86, default/armeabi-v7a, default/x86, default/x86_64
----------
id: 3 or "Google Inc.:Google APIs:22"
     Name: Google APIs
     Type: Add-On
     Vendor: Google Inc.
     Revision: 1
     Description: Android + Google APIs
     Based on Android 5.1.1 (API level 22)
     Libraries:
      * com.android.future.usb.accessory (usb.jar)
          API for USB Accessories
      * com.google.android.media.effects (effects.jar)
          Collection of video effects
      * com.google.android.maps (maps.jar)
          API for Google Maps
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320, AndroidWearRound, AndroidWearRound400x400, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320
 Tag/ABIs : no ABIs.
----------
id: 4 or "Google Inc.:Google APIs:23"
     Name: Google APIs
     Type: Add-On
     Vendor: Google Inc.
     Revision: 1
     Description: Android + Google APIs
     Based on Android 6.0 (API level 23)
     Libraries:
      * com.android.future.usb.accessory (usb.jar)
          API for USB Accessories
      * com.google.android.media.effects (effects.jar)
          Collection of video effects
      * com.google.android.maps (maps.jar)
          API for Google Maps
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in, AndroidWearRound, AndroidWearRound360x360, AndroidWearRound400x400, AndroidWearRound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320, AndroidWearRound, AndroidWearRound360x360, AndroidWearRound400x400, AndroidWearRound480x480, AndroidWearRoundChin320x290, AndroidWearRoundChin360x325, AndroidWearRoundChin360x330, AndroidWearSquare, AndroidWearSquare320x320
 Tag/ABIs : no ABIs.

Directories found in C:\Users\felix\AppData\Local\Android\Sdk\build-tools are 19.1.0, 23.0.2
Versions found in C:\Users\felix\AppData\Local\Android\Sdk\build-tools are 19.1.0, 23.0.2
Selected targetSdk is: 23
Directories found in C:\Users\felix\AppData\Local\Android\Sdk\extras\android\m2repository\com\android\support\appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0, 23.1.1, maven-metadata.xml, maven-metadata.xml.md5, maven-metadata.xml.sha1
Versions found in C:\Users\felix\AppData\Local\Android\Sdk\extras\android\m2repository\com\android\support\appcompat-v7 are 18.0.0, 19.0.0, 19.0.1, 19.1.0, 20.0.0, 21.0.0, 21.0.2, 21.0.3, 22.0.0, 22.1.0, 22.1.1, 22.2.0, 22.2.1, 23.0.0, 23.0.1, 23.1.0, 23.1.1
Selected AppCompat version is: 23.1.1
spawn: C:\Users\felix\Desktop\Test152\platforms\android\gradlew.bat "buildapk" "-PcompileSdk=android-23" "-PtargetSdk=23" "-PbuildToolsVersion=23.0.2" "-PsupportVersion=23.1.1"

:config phase:  createDefaultIncludeFiles
	+found plugins: nativescript-push-notifications
	+found plugins: nativescript-telerik-ui

:config phase:  createPluginsConfigFile
	+creating product flavors include.gradle file in configurations folder...

:config phase:  pluginExtend
	+applying configuration from: C:\Users\felix\Desktop\Test152\platforms\android\configurations\include.gradle
	+applying configuration from: C:\Users\felix\Desktop\Test152\platforms\android\configurations\nativescript-push-notifications\include.gradle
	+applying configuration from: C:\Users\felix\Desktop\Test152\platforms\android\configurations\nativescript-telerik-ui\include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
	+adding dependency: C:\Users\felix\Desktop\Test152\platforms\android\libs\aar\Chart-2015.3.1307-trial-release.aar
	+adding dependency: C:\Users\felix\Desktop\Test152\platforms\android\libs\aar\Common-2015.3.1307-trial-release.aar
	+adding dependency: C:\Users\felix\Desktop\Test152\platforms\android\libs\aar\Data-2015.3.1307-trial-release.aar
	+adding dependency: C:\Users\felix\Desktop\Test152\platforms\android\libs\aar\Input-2015.3.1307-trial-release.aar
	+adding dependency: C:\Users\felix\Desktop\Test152\platforms\android\libs\aar\List-2015.3.1307-trial-release.aar
	+adding dependency: C:\Users\felix\Desktop\Test152\platforms\android\libs\aar\Primitives-2015.3.1307-trial-release.aar
:preBuild UP-TO-DATE
:prePush-pluginNativescript-telerik-uiDebugBuild UP-TO-DATE
:checkPush-pluginNativescript-telerik-uiDebugManifest
:prePush-pluginNativescript-telerik-uiReleaseBuild UP-TO-DATE
:prepareChart201531307TrialReleaseLibrary UP-TO-DATE
:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:prepareComAndroidSupportMediarouterV72300Library UP-TO-DATE
:prepareComAndroidSupportRecyclerviewV72310Library UP-TO-DATE
:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServices840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAds840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAnalytics840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAppindexing840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAppinvite840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAppstate840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesAuth840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesCast840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesDrive840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesFitness840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesGames840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesGcm840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesIdentity840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesLocation840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMaps840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMeasurement840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesNearby840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesPanorama840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesPlus840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesSafetynet840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesVision840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesWallet840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesWearable840Library UP-TO-DATE
:prepareCommon201531307TrialReleaseLibrary UP-TO-DATE
:prepareData201531307TrialReleaseLibrary UP-TO-DATE
:prepareInput201531307TrialReleaseLibrary UP-TO-DATE
:prepareList201531307TrialReleaseLibrary UP-TO-DATE
:preparePrimitives201531307TrialReleaseLibrary UP-TO-DATE
:preparePush-pluginNativescript-telerik-uiDebugDependencies
:compilePush-pluginNativescript-telerik-uiDebugAidl UP-TO-DATE
:compilePush-pluginNativescript-telerik-uiDebugRenderscript UP-TO-DATE
:generatePush-pluginNativescript-telerik-uiDebugBuildConfig UP-TO-DATE
:cleanLocalAarFiles
:deleteJavaDir UP-TO-DATE
:ensureMetadataOutDir UP-TO-DATE
:collectAllJars
:isMetadataGenerationNecessary UP-TO-DATE
:buildMetadata UP-TO-DATE
:copyMetadata UP-TO-DATE
:generatePush-pluginNativescript-telerik-uiDebugAssets UP-TO-DATE
:mergePush-pluginNativescript-telerik-uiDebugAssets UP-TO-DATE
:generatePush-pluginNativescript-telerik-uiDebugResValues UP-TO-DATE
:generatePush-pluginNativescript-telerik-uiDebugResources UP-TO-DATE
:mergePush-pluginNativescript-telerik-uiDebugResources UP-TO-DATE
:processPush-pluginNativescript-telerik-uiDebugManifest UP-TO-DATE
:processPush-pluginNativescript-telerik-uiDebugResources UP-TO-DATE
:generatePush-pluginNativescript-telerik-uiDebugSources UP-TO-DATE
:processPush-pluginNativescript-telerik-uiDebugJavaRes UP-TO-DATE
:compilePush-pluginNativescript-telerik-uiDebugJavaWithJavac UP-TO-DATE
:compilePush-pluginNativescript-telerik-uiDebugNdk UP-TO-DATE
:compilePush-pluginNativescript-telerik-uiDebugSources UP-TO-DATE
:preDexPush-pluginNativescript-telerik-uiDebug UP-TO-DATE
:dexPush-pluginNativescript-telerik-uiDebug FAILED

BUILD FAILED

Total time: 7.989 secs
Analytics statuses: 
{ TrackFeatureUsage: 1, TrackExceptions: 0 }
Trying to track feature 'Non-interactive' with value 'help'.
List of registered commands: /?, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, create, debug, debug|android, debug|ios, deploy, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, emulate, emulate|android, emulate|ios, error-reporting, help, init, install, library, library|add, livesync, platform, platform|add, platform|remove, platform|update, plugin, plugin|add, plugin|remove, prepare, run, run|android, run|ios, test, test|android, test|init, test|ios, usage-reporting
Reading help for command 'build|android'. FileName is 'build-android.md'.
# build android


Thanks for your help!

**Comment by seppel1992** [comment] 2016-01-28 15:53
The build for iOS works under Mac OS X, when both plugins are installed. After I installed the Android SDK in this Mac OS system, the build for Android fails with the same error like using Windows.

**Comment by rosen-vladimirov** [comment] 2016-02-02 06:52
@seppel1992 is the issue resolved (as you have closed it)?

**Comment by seppel1992** [comment] 2016-02-02 07:05
Actually not... No idea why it has been closed, sorry

**Comment by rosen-vladimirov** [comment] 2016-02-02 10:14
Ok, I've reproduced the issue. In fact it's caused by Java limitation of methods. You can find more information in this issue - https://github.com/NativeScript/android-runtime/issues/344 
I'm closing this one as the real issue is described in the related one in the runtime :) 
Thanks for reporting the repro steps.

**Closed by rosen-vladimirov** 2016-02-02 10:14 UTC
