### ISSUE TITLE
Set Button color style is no working

### ISSUE THREAD

**Issue by xuezier** [NativeScript/nativescript-cli#1668] opened 2016-04-06 08:41 UTC
Here is the main.xml code:
```
<Page loaded="loaded" actionBarHidden="true" backgroundSpanUnderStatusBar="true" xmlns:x="nativescript-statusbar">
    <x:StatusBar ios:barStyle="light" android:barStyle="#f05b72" />
    <StackLayout>
        <Image src="~/views/imageSource/login.png" />
        <Button tap="jump" text="Click Me Open" class="mainButton" id="mainButton">
        </Button>
    </StackLayout>
</Page>
```
And Here is the main.css
```
Button { margin-top: 50pt; 
    height: 70px; 
    background-color: #d71345;
    width: 85%; 
    border-radius: 35;
    border-width: 0.1; 
    color:#ffffff; 
}
```
but the Button text is not showing white.

no one can help me? it's seems to the theme causes the problem.
`android:theme="@style/AppTheme"`
Are there any other themes to choose from?

**Comment by NickIliev** [comment] 2016-04-06 10:29
Duplicate of [#1891](https://github.com/NativeScript/NativeScript/issues/1891)

**Closed by NickIliev** 2016-04-06 10:29 UTC
Labels: duplicate
