### ISSUE TITLE
NPM tns-android Cache being corrupted

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#2524] opened 2017-02-11 19:11 UTC
This is more an informational post; since I don't have a way to duplicate it yet.   

I ran into a case where TNS 2.5 was throwing an warning while installing the tns-android #2475 

The issue was caused by somehow a early 2.5.0 @ next ended up in my npm-cache as "2.5.0" so then when tns installing 2.5.0 as normal it was bringing in the early @next version.

**Comment by rosen-vladimirov** [comment] 2017-02-12 14:00
Hey @NathanaelA , I've read the other thread and I have an idea how this might have happened. Are you using `--frameworkPath` parameter? In case you've modified any `tns-android` package and in its package.json the version has been 2.5.0 (after 2.5.0 release or before it), npm has the disturbing behavior to adds your local package to the npm cache. For example with clean cache:
```
$ npm i tns-android // installs npm 2.5.0
$ npm install <local path to modified 2.5.0 version of tns-android> - will add my local copy to the npm cache
$ npm install tns-android // gets the version from cache... which is the modified version
```

Do you think this might be the reason for your issue?

**Comment by NathanaelA** [comment] 2017-02-12 18:55
@rosen-vladimirov - You know I thought about that parameter as a possibility; but I don't recall doing any 2.5's with it.   I used to use it ALL the time; but since I haven't updated my LiveEdit plugin since 2.3, I don't know when I would have used it on a 2.5.0 release.   In addition part of the LiveEdit patch is to add a -MT to the version label so that it is easily determined to be my modified version of the engine, and this didn't have a -MT in the version label.   So at this moment I'm not sure where this v2.5.0 came from...

However it (testing --frameworkPath) was a test I was planning on testing, as I thought it could be a path that could cause it.  Thanks for confirming that is valid route to bad data in the cache.  ;-)

**Comment by rosen-vladimirov** [comment] 2017-05-10 09:43
Hey @NathanaelA , as this issue seems caused by npm's work with cache, I'm closing it. Ping me in case you reproduce it and we'll reopen it.

**Closed by rosen-vladimirov** 2017-05-10 09:43 UTC
Labels: bug, external
