### ISSUE TITLE
tns run can get stuck in a loop since 2.5

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#2469] opened 2017-02-01 15:04 UTC
Since upgrading to NativeScript 2.5 I’ve occasionally hit this odd problem where `tns run ios` gets stuck in a loop.

That is, after I make a change to my app I keep seeing these four lines outputted continuously:

```
Transferring project files...
Unable to sync files. Error is: ENOENT: no such file or directory, stat '/Users/tj/Desktop/HelloWorld/platforms/ios/HelloWorld/app/tns_modules/adm-zip/adm-zip.js'
Skipping prepare.
```

The specific file is sometimes different, but it’s always something in `tns_modules`. I’m going to try to get better recreation steps for you because I know this is a bit vague, but I thought I’d let you know that I’m hitting this.

**Comment by tjvantoll** [comment] 2017-02-01 15:06
I’m actually getting this on Android now too. In this case I’m doing:

```
tns create Groceries --template nativescript-template-ng-groceries
cd Groceries
tns run android
```

After that I wait a few seconds and then I start seeing these lines repeating.

```
Transferring project files...
Unable to sync files. Error is: ENOENT: no such file or directory, stat '/Users/tj/Desktop/Groceries/platforms/android/src/main/assets/app/tns_modules/babel-types/.npmignore'
Skipping prepare.
```

**Comment by naderio** [comment] 2017-02-01 15:44
same here with vanilla NS and scss files .. on android
```
Transferring project files...
Unable to sync files. Error is: Multiple exceptions were thrown:
ENOENT: no such file or directory, stat '<...>/platforms/android/src/main/assets/app/styles/_common.scss'
```

**Comment by Plamen5kov** [comment] 2017-02-03 08:27
@tjvantoll I managed to reproduce the problem. It happens when you try to change a dev-dependency in the node_modules.
We are watching the whole node_modules folder, but we don't push dev-dependencies on the device.
So when you change a dev-dependency, livesync fails to find the file, because the prepare step ignores all files that are a dev-dependency.

**Comment by rosen-vladimirov** [comment] 2017-02-08 21:33
Hey @naderio ,
Your issue will be resolved with this PR: https://github.com/NativeScript/nativescript-cli/pull/2508

**Comment by Plamen5kov** [comment] 2017-02-09 12:14
read more: https://github.com/NativeScript/nativescript-cli/issues/2482

**Closed** 2017-02-09 14:30 UTC
Labels: bug
