### ISSUE TITLE
LiveSync CLI Version 5.0.0 Rebuilds Every File Change

### ISSUE THREAD

**Issue by shortcircuit21** [NativeScript/nativescript-cli#4112] opened 2018-11-08 16:18 UTC
**Environment**
 - CLI: 5.0.0
  "tns-ios": {
            "version": "5.0.0"
        },
        "tns-android": {
            "version": "5.0.0"
        }
 - Plugin(s):
    "dependencies": {
        "@angular/animations": "~6.1.0",
        "@angular/common": "~6.1.0",
        "@angular/compiler": "~6.1.0",
        "@angular/core": "~6.1.0",
        "@angular/forms": "~6.1.0",
        "@angular/http": "~6.1.0",
        "@angular/platform-browser": "~6.1.0",
        "@angular/platform-browser-dynamic": "~6.1.0",
        "@angular/router": "~6.1.0",
        "nativescript-angular": "~6.1.0",
        "nativescript-drop-down": "^4.0.1",
        "nativescript-email": "^1.5.3",
        "nativescript-handle-file": "^4.0.0",
        "nativescript-phone": "^1.4.0",
        "nativescript-share-file": "^1.0.4",
        "nativescript-theme-core": "~1.0.4",
        "nativescript-ui-autocomplete": "^3.9.0",
        "nativescript-ui-calendar": "^3.8.1",
        "nativescript-ui-chart": "^3.9.0",
        "nativescript-ui-dataform": "^3.7.3",
        "nativescript-ui-gauge": "^3.7.1",
        "nativescript-ui-listview": "^3.7.0",
        "nativescript-ui-sidedrawer": "^4.3.0",
        "reflect-metadata": "~0.1.8",
        "rxjs": "^6.0.0",
        "tns-core-modules": "~4.2.0",
        "zone.js": "^0.8.26"
    }
**Describe the bug**
In both Android and IOS livesyncs. Every file change causes the app to do a full rebuild. 

**To Reproduce**
Only thing that I know that might have caused this was I changed the IOS app icons. Which I changed back to defaults, but didn't fix the issue. (Reading from others reporting this issue.)

**Expected behavior**
File change should do a livesync reload not a full application rebuild.

**Comment by dtopuzov** [comment] 2018-11-12 11:10
Hi @shortcircuit21 

Can you please post your full package.json (includign devDependencies)?

**Comment by dtopuzov** [comment] 2018-11-12 11:14
Can you reproduce the same issue with some of {N} official templates?

**Comment by dtopuzov** [comment] 2019-01-19 19:32
Closing since we can not reproduce the issue.

**Closed by dtopuzov** 2019-01-19 19:32 UTC
Labels: needs more info
