### ISSUE TITLE
Add support for Xcode 8.3

### ISSUE THREAD

**Issue by jamessharp** [NativeScript/nativescript-cli#2668] opened 2017-03-28 15:57 UTC
*iOS only* (tns 2.5.3)

Xcode 8.3 has fully removed the ability to do an `xcrun PackageApplication` as is performed when building/running a nativescript app on a development device (see [this line of code here](https://github.com/NativeScript/nativescript-cli/blob/v2.5.3/lib/services/ios-project-service.ts#L431)). This means that `tns run ios` and friends don't work under Xcode 8.3, failing with the following error:

```
xcrun: error: unable to find utility "PackageApplication", not a developer tool or in PATH
Command xcrun failed with exit code 72
```

Some googling around has suggested moving to using `xcodebuild`, and the cordova guys have done the update in this PR: https://github.com/apache/cordova-ios/pull/257

Let me know if you need any further info

**Comment by NickIliev** [comment] 2017-03-29 07:19
Also reported via t.1100681

**Comment by svzi** [comment] 2017-03-30 19:05
Any feedback on this? Specially on how to fix would be really much appreciated!

It happens on my machine as well and now I'm unable to run apps on my iOS device... This is really a deal-breaker!

**Comment by dtopuzov** [comment] 2017-03-31 06:28
We work on fixing the issue and we will provide fix for for {N} CLI 3.0.0 and hot fix for {N} 2.5.*

**Comment by mn-martin** [comment] 2017-03-31 08:03
> and we will also release hot fix for {N} 2.5.*

Really glad to hear that because we're close to release of an app and we wont have the time for an update to 3.0.0. I'm sure we're not alone with this scenario.

**Comment by dxshindeo** [comment] 2017-03-31 08:04
> Really glad to hear that because we're close to release of an app and we wont have the time for an update to 3.0.0. I'm sure we're not alone with this scenario.
Same...

**Comment by teerasej** [comment] 2017-03-31 08:28
> Really glad to hear that because we're close to release of an app and we wont have the time for an update to 3.0.0. I'm sure we're not alone with this scenario.

Same here...

**Comment by dunqan** [comment] 2017-03-31 08:45
As a temporary workaround, you can still build and run your app by opening workspace directly in XCode. Especially for the release purposes.

**Comment by mn-martin** [comment] 2017-03-31 08:59
@dunqan Thank you for that hint. By the way: The run command seems to work just fine with the iOS emulator. (Which helps shorten the dev-times compared to the Xcode workspace route if features can be tested within the emulator)

**Comment by dxshindeo** [comment] 2017-03-31 10:18
> As a temporary workaround, you can still build and run your app by opening workspace in XCode directly. Especially for the release purposes.

Doesn't work for me. 
1. I need to upload my app for testflight to itunes connect. In order to do so, I open .xcworkspace file, select *either* Generic iOS Device or my real connected device, then I click Product->Archive, it is building something which fails with error:

```
Shell Script Invocation Error:
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

2. I tried running the app on my real connected device. It builds successfully, bet when it starts up on my device, console.log says:

```
1   @file:///app/main.js:3:25
JavaScript error:
2017-03-31 13:10:25.599446 TEST[277:27708] file:///app/main.js:3:25: JS ERROR Error: Could not find module 'nativescript-angular/platform'. Computed path '/var/mobile/Containers/Data/Application/1E557C7E-1CE2-4A3D-BE4F-B6D5B8EE8CA6/Library/Application Support/LiveSync/app/tns_modules/nativescript-angular/platform'.
```

**Comment by dxshindeo** [comment] 2017-03-31 10:27
Is it possible to downgrade XCode back to 8.2 and would that solve current problems?

**Comment by CitySim** [comment] 2017-03-31 10:36
Yes, you downloaded XCode 8.2 from https://developer.apple.com/download/more/
`tns build` now works again for me

**Comment by dtopuzov** [comment] 2017-03-31 11:58
You can have both Xcodes installed and switch them with `xcode-select`, example:
 `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer`

Please also run  `xcodebuild -version` after that to verify switch is successful.

**Comment by beas9402** [comment] 2017-03-31 13:39
+1 
Just updated to Xcode 8.3 now can't build iOS.  I love to hear feedback on this.
Thanks

**Comment by dxshindeo** [comment] 2017-03-31 14:42
Downgraded to XCode 8.2.1 - empty project builds and runs and archives without a hitch, so it is probably how my project is setup. Also, an empty project does not have any extra ios plugins (from Podfiles), mine does.

I fixed point 1 in the issue I described above - I followed the solution from here (http://stackoverflow.com/questions/21366549/errorthe-sandbox-is-not-in-sync-with-the-podfile-lock-after-installing-res) by replacing this line:
`diff "${PODS_ROOT}/../Podfile.lock" "${PODS_ROOT}/Manifest.lock" > /dev/null`

Now the errors in point 1 are gone, but archiving fails at new error:

```
Run custom shell script '[CP] Copy Pods Reources'
/Users/ios_developer/Documents/test/platforms/ios/Pods/Target Support Files/Pods-test/Pods-test-resources.sh: line 7: /resources-to-copy-test.txt: Permission denied
```

**Comment by Yamilquery** [comment] 2017-04-02 18:12
Do you know if there is a solution for version 8.3 of Xcode? I do not have space to download the previous version and downgrade... 😞

**Comment by dtopuzov** [comment] 2017-04-02 21:02
We will provide hot fix in several days.

**Comment by fsartori** [comment] 2017-04-03 19:18
Hi all, we have the same error, any update about the hotfix?
Regards,

**Comment by dtopuzov** [comment] 2017-04-03 20:10
Fix landed in master branches.
You can test try with following steps:
```
npm i -g nativescript@next
tns create MyApp --template tns-template-hello-world@rc
tns platform add ios@next --path MyApp
tns run ios --path MyApp
```
Notes: 
Fix is in CLI and `tns-ios` platform, so you need to update both.
@next is current state of our master branches.
We have breaking changes in master branches since (we work on next major version - 3.0.0)
We do not recommend master branches for production developments since sometimes they might be unstable.

We will merge fixes in release branches and release hot fix for latest official version of {N} later this week.

**Comment by fsartori** [comment] 2017-04-03 22:45
Our app is native not hybrid, we need create the build through a jenkins job against the build server.
I'm not sure is this apply in our case

**Comment by GrEg00z** [comment] 2017-04-06 07:58
I did a nativescript update (to last rev in master branches), but I get another error now (at the end of 'tns run ios').
The build is in success, but I get this error when it try to deploy on my real iphone device :   

```
PhaseScriptExecution ??\ Check\ Pods\ Manifest.lock /Users/hackeru/Library/Developer/Xcode/DerivedData/<my app name>-fzwvlpxrggyrqpegcufqkjvwbmdb/Build/Intermediates/ArchiveIntermediates/<my app name>/IntermediateBuildFilesPath/<my app name>.build/Release-iphoneos/<my app name>.build/Script-4220C9F8A61610F98ED1157D.sh
    cd /<my app folder>/platforms/ios
    /bin/sh -c /Users/hackeru/Library/Developer/Xcode/DerivedData/<my app name>-fzwvlpxrggyrqpegcufqkjvwbmdb/Build/Intermediates/ArchiveIntermediates/<my app name>/IntermediateBuildFilesPath/Nowgua.build/Release-iphoneos/<my app name>.build/Script-4220C9F8A61610F98ED1157D.sh
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution ??\ Check\ Pods\ Manifest.lock /Users/hackeru/Library/Developer/Xcode/DerivedData/<my app name>-fzwvlpxrggyrqpegcufqkjvwbmdb/Build/Intermediates/ArchiveIntermediates/<my app name>/IntermediateBuildFilesPath/<my app name>.build/Release-iphoneos/<my app name>.build/Script-4220C9F8A61610F98ED1157D.sh
(1 failure)
Multiple errors were thrown:
Command xcodebuild failed with exit code 65
# run ios
```

Whereas Xcode still works to launch the app on my iphone.


Here my current nativescript version : 

**│ Component             │ Current version              │ Latest version │ Information │**
│ nativescript             │ 3.0.0-2017-04-05-8539  │ 2.5.3                │ Up to date  │
│ tns-core-modules   │ 2.5.2                               │ 2.5.2                │ Up to date  │
│ tns-android             │ 2.5.0                               │ 2.5.0                │ Up to date  │
│ tns-ios                     │ 3.0.0-rc.1-2017-3-28-2  │ 2.5.0                 │ Up to date  │

**Comment by dxshindeo** [comment] 2017-04-06 09:35
Weird, I had that error the other way around - I was able to run from my phone, but not from Xcode. Alas, that was in Xcode 8.2 and I was making an archive. Xcode gave me that error and it was because it did not have Build options->PODS_ROOT->Release variable set. I set it to the same value as Debug variable, and then the error was gone. Perhaps thats relevant to your experience.

**Comment by dtopuzov** [comment] 2017-04-06 10:14
{N} 2.5.4 is now available on npm and it should solve the issues with Xcode 8.3

**Comment by dtopuzov** [comment] 2017-04-06 10:20
@dxshindeo @GrEg00z Can you give us exact steps to reproduce, for example:
```
tns create TestApp
tns plugin add <some plugin>
tns run ios
```

**Comment by GrEg00z** [comment] 2017-04-06 10:33
Thanks to you @dxshindeo ! After this modification in Xcode, I can make a full 'tns run ios' and launch my app direct from it.

Problem is when I perform a : 
```
tns platform remove ios
tns platform add ios
tns run ios
```

Then I have to modify manualy the 'pods_root' variables in Xcode for each 'platform remove/add'
Is there a solution for this ?

@dtopuzov :  This is all commands I type (after upgrading ns to 3.0.0)

I also use Xcode 8.3

**Comment by dxshindeo** [comment] 2017-04-06 10:34
I don't know if this works for `run` command, but I know it works for `build`:
`tns build ios --release`

When passing the release flag, it will create the appropriate PODS_ROOT variable in Xcode.

**Comment by dtopuzov** [comment] 2017-04-06 11:19
Can you please try with `nativescript@2.5.4` and if you still encounter the issue, please provide very detailed steps to reproduce (and context), ideally:
- small project that isolates the problem (or at least package.json of the project)
- CLI commands you run
- What exactly you modify in Xcode

**Comment by GrEg00z** [comment] 2017-04-06 13:06
Now it's ok with nativescript 2.5.4, I can make a full 'tns run ios' without modify 'pods_root' in Xcode.

But now I get this error on starting my app : 

```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x1013c9e20 -[TNSRuntime executeModule:referredBy:]
2   0x1000c6990
3   0x1925e15b8 <redacted>
JavaScript stack trace:
1   @file:///app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:73:28
JavaScript error:
file:///app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:73:28: JS ERROR Error: Property showOverNavigation already registered for type RadSideDrawer
```

It's look to a recent existing problem in telerik plugin :
#https://github.com/telerik/nativescript-ui-feedback/issues/137

Any ideas of this ?

**Comment by odubuc** [comment] 2017-04-06 15:54
After the Update to 2.5.4, with xcode 8.3 I'm getting this error with an empty project

`tns create testApp`
change package.json for a valid provisioning profile
`tns run ios`

```
** ARCHIVE SUCCEEDED **

2017-04-06 11:44:53.515 xcodebuild[5139:64979] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/v6/676b__jj5zn14nsd8jsdd7wm0000gn/T/testApp_2017-04-06_11-44-53.514.xcdistributionlogs'.
1.2.840.113635.100.1.61
1.2.840.113635.100.1.61
2017-04-06 11:44:53.876 xcodebuild[5139:64979] [MT] IDEDistribution: Step failed: <IDEDistributionThinningStep: 0x7fa59f952ee0>: Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
error: exportArchive: No applicable devices found.

Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}

** EXPORT FAILED **

Command xcodebuild failed with exit code 70
```

`tns device` displays my device correctly with status connected

I'm only getting this error with a physical device

**Comment by GrEg00z** [comment] 2017-04-06 21:28
After removing all code of telerik sidedrawer module (in typescript code), the error disapears.

I will try to re-add sidedrawer module to be sure if it's the problem

**Closed** 2017-04-07 07:47 UTC
Labels: bug, critical, iOS

**Comment by dtopuzov** [comment] 2017-04-07 07:48
Closing this issue since we support Xcode 8.3 now.
If you encounter other specific problems please open separate issues.

**Comment by dxshindeo** [comment] 2017-04-07 09:54
Erm, no, it's not fine.
First, why is `tns run ios --device xxxx` command now archiving my project?
`** ARCHIVE SUCCEEDED **`
It takes twice as long for the command to pop the app on my device!

Second, after calling `tns run ios --device xxxx` OR `tns build ios --release` AND then opening .xcworkspace file AND then trying to run the app on the real device (it does work when emulator is selected) from Xcode, I get the following in Xcode console:

```
2017-04-07 12:45:21.049890+0300 TEST[2549:423103] [DYMTLInitPlatform] platform initialization successful
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
2017-04-07 12:45:21.868741+0300 TEST[2549:423001] 1   0x1042adb -[TNSRuntime executeModule:referredBy:]
1   0x1042adb -[TNSRuntime executeModule:referredBy:]
2017-04-07 12:45:21.877689+0300 TEST[2549:423001] 2   0x9dc0b main
2   0x9dc0b main
2017-04-07 12:45:21.877892+0300 TEST[2549:423001] 3   0x1d46a4eb <redacted>
3   0x1d46a4eb <redacted>
JavaScript stack trace:
1   @file:///app/main.js:3:25
JavaScript error:
2017-04-07 12:45:21.878666+0300 TEST[2549:423001] file:///app/main.js:3:25: JS ERROR Error: Could not find module 'nativescript-angular/platform'. Computed path '/var/mobile/Containers/Data/Application/891BD688-73A2-46B6-9A5C-541A46EE86D2/Library/Application Support/LiveSync/app/tns_modules/nativescript-angular/platform'.

file:///app/main.js:3:25: JS ERROR Error: Could not find module 'nativescript-angular/platform'. Computed path '/var/mobile/Containers/Data/Application/891BD688-73A2-46B6-9A5C-541A46EE86D2/Library/Application Support/LiveSync/app/tns_modules/nativescript-angular/platform'.
(lldb) 
```

NS CLI: 2.5.4
Xcode: 8.3
Device: iPhone 5

package.json:

```
{
  "description": "Test Mobile Application",
  "license": "",
  "readme": "",
  "repository": "",
  "nativescript": {
    "id": "org.test.app",
    "tns-ios": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/common": "4.0.1",
    "@angular/compiler": "4.0.1",
    "@angular/core": "4.0.1",
    "@angular/forms": "4.0.1",
    "@angular/http": "4.0.1",
    "@angular/platform-browser": "4.0.1",
    "@angular/platform-browser-dynamic": "4.0.1",
    "@angular/router": "4.0.1",
    "PhoenixClient": "file:resources/PhoenixClient",
    "base-64": "^0.1.0",
    "nativescript-angular": "1.5.1",
    "nativescript-angular-snapshot": "1.5.1-5.5.372.32",
    "nativescript-camera": "0.0.8",
    "nativescript-fresco": "^1.0.16",
    "nativescript-geolocation": "0.0.19",
    "nativescript-gif": "1.0.9",
    "nativescript-google-maps-sdk": "1.4.3",
    "nativescript-imagepicker": "^2.5.1",
    "nativescript-phone": "1.3.0",
    "nativescript-vibrate": "1.1.2",
    "nativescript-webview-interface": "^1.4.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.3.0",
    "tns-core-modules": "2.5.2",
    "tns-platform-declarations": "2.5.2",
    "zone.js": "0.8.5"
  },
  "devDependencies": {
    "@angular/compiler-cli": "4.0.1",
    "@ngtools/webpack": "1.2.13",
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.16.1",
    "copy-webpack-plugin": "4.0.1",
    "extract-text-webpack-plugin": "2.1.0",
    "htmlparser2": "3.9.2",
    "lazy": "1.0.11",
    "nativescript-css-loader": "0.26.1",
    "nativescript-dev-android-snapshot": "0.*.*",
    "nativescript-dev-typescript": "0.4.2",
    "nativescript-dev-webpack": "0.3.7",
    "raw-loader": "0.5.1",
    "resolve-url-loader": "2.0.2",
    "typescript": "2.1.6",
    "webpack": "2.3.3",
    "webpack-sources": "0.2.3"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}

```

**Comment by ekambarrao** [comment] 2017-05-05 04:45
Hi, I am using Visual Studio 2017 Apache Cordova 6.3.1 and trying to build for iOS. I have been facing this issue.
I am getting this error
** BUILD SUCCEEDED ** xcrun: error: unable to find utility "PackageApplication", not a developer tool or in PATH Error: Error code 72
How to fix this!!!!
Everywhere written as 8.3 is problem and xcodebuild should be there. But where, when using Visual studio, which is complete automated one remotebuild, where to do this?
thx
