### ISSUE TITLE
Nativescript  Nodeify plugin not compatible with webpack  

### ISSUE THREAD

**Issue by Falu-G** [NativeScript/nativescript-cli#4764] opened 2019-06-25 11:52 UTC
Cannot Find Module platforms/ios/SymAmMobile/app/tns_modules/nativescript-nodeify/patch-npm-packages.js'.

**Comment by DimitarTachev** [comment] 2019-07-03 07:26
duplicate of https://github.com/EddyVerbruggen/nativescript-nodeify/issues/35

**Closed by DimitarTachev** 2019-07-03 07:26 UTC
