### ISSUE TITLE
iOS apps will not start with Xcode 10

### ISSUE THREAD

**Issue by mrdavidrees** [NativeScript/nativescript-cli#3920] opened 2018-09-21 01:26 UTC
### Tell us about the problem

A few errors included in the log are:
"Failed to load Info.plist from bundle at path"
"Command xcrun with arguments simctl install"
The compiler seems to fail at copying the app files onto the device or simulator.

I have included the entire build log.
I am running a clean build with entire ios platform folder removed.

Why I think this is specific to Xcode 10:
Builds were running successfully until i updated yesterday, looking at my repo i cannot see any noticeable changes to configuration files, with an exception of this in the package-lock.json file:
<img width="327" alt="package-lock" src="https://user-images.githubusercontent.com/811705/45854847-93f44680-bd90-11e8-9348-418b9b02067c.png">

The app will build and run when building directly from Xcode 10, after running "tns prepare ios"

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.4

[typeout-build-log-xcode10.txt](removed)

**Comment by vultix** [comment] 2018-09-24 18:04
I can confirm that I am seeing the same issue.  This is (temporarily) fixed by removing the platforms folder every time you run.

**Comment by datanotion** [comment] 2018-09-26 14:33
I believe you can also fix this by telling xcode 10 to use the legacy build system.  I have since rolled back to xcode 9.x but I think you can find it in the `File > Project/Workspace Settings` sheet.  10 has a new build system and there are still some issues to resolve, so going back to the old way of doing builds fixed most things like this for me.

**Comment by rosen-vladimirov** [comment] 2018-10-02 06:34
Related to: https://github.com/NativeScript/nativescript-cli/issues/3957

**Comment by rosen-vladimirov** [comment] 2018-10-02 11:44
Hey guys, the fix is available in CLI's `next` version, you can install it by executing:
```
npm install -g nativescript@next
```

**Closed** 2018-10-03 08:43 UTC
Labels: bug

**Comment by andreaCremisini** [comment] 2018-10-10 14:22
@NickIliev  i tried, but not working.
