### ISSUE TITLE
Fibers installation problems caused failed.

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#2036] opened 2016-09-07 06:19 UTC
_From @hantsy on September 4, 2016 16:56_

Windows 10(v1607) 64 bit, Node JS 6.5 

I have installed VS 2015 community and install build tools for C++.

When I tried to install Nativescript via command `npm i -g nativescript` and got the following errors.

```
> fibers@1.0.13 install E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers
> node build.js || nodejs build.js


E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "" rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  fibers.cc
  coroutine.cc
..\src\fibers.cc(727): warning C4244: 'argument': conversion from 'std::size_t'
 to 'double', possible loss of data [E:\Users\hantsy\AppData\Roaming\npm\node_m
odules\nativescript\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(731): warning C4244: '=': conversion from 'double' to 'std::si
ze_t', possible loss of data [E:\Users\hantsy\AppData\Roaming\npm\node_modules\
nativescript\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(738): warning C4244: 'argument': conversion from 'std::size_t'
 to 'double', possible loss of data [E:\Users\hantsy\AppData\Roaming\npm\node_m
odules\nativescript\node_modules\fibers\build\fibers.vcxproj]
..\src\coroutine.cc(137): warning C4552: '!': operator has no effect; expected
operator with side-effect [E:\Users\hantsy\AppData\Roaming\npm\node_modules\nat
ivescript\node_modules\fibers\build\fibers.vcxproj]
..\src\coroutine.cc(214): warning C4267: 'argument': conversion from 'size_t' t
o 'unsigned int', possible loss of data [E:\Users\hantsy\AppData\Roaming\npm\no
de_modules\nativescript\node_modules\fibers\build\fibers.vcxproj]
  coro.c
  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_lo
ad_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type
 modifiers [E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_
modules\fibers\build\fibers.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134
  ): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd E:\Users\hantsy\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++`
Alpine users please run: `sudo apk add python make g++`
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
E:\Users\hantsy\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "nativescript"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log
npm ERR! code 1
```

I have tried to uninstall the previous nativescript and node-gyp etc via `npm uninstall -g xxxx` before installing it or run as Administrator, but no help to overcome this error.

_Copied from original issue: NativeScript/NativeScript#2677_

**Comment by rosen-vladimirov** [comment] 2016-09-07 12:09
This is a duplicate of this issue: https://github.com/NativeScript/nativescript-cli/issues/2025
The fix will be included in 2.3.0 
At the moment you can use another version of Node.js (for example LTS version - 4.x.x)

**Closed by rosen-vladimirov** 2016-09-07 12:09 UTC

**Comment by born2net** [comment] 2016-09-14 16:03
yes same issue here...

**Comment by solancer** [comment] 2016-11-04 12:30
Same issue.

linuxsavvy-mbp:app-mobile srinivas$ npm i -g nativescript
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN excluding symbolic link docs/assets/ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Versions/Current -> A
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN excluding symbolic link docs/assets/ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Versions/Current -> A
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
/Users/srinivas/.nvm/versions/node/v7.0.0/bin/tns -> /Users/srinivas/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/bin/nativescript.js
/Users/srinivas/.nvm/versions/node/v7.0.0/bin/nativescript -> /Users/srinivas/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/bin/nativescript.js

> fibers@1.0.13 install /Users/srinivas/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/node_modules/fibers
> node build.js || nodejs build.js

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:49:34: error: no template named 'WeakCallbackData' in namespace 'v8'; did you mean 'WeakCallbackInfo'?
        void WeakCallbackShim(const v8::WeakCallbackData<T, P>& data) {
                                    ~~~~^~~~~~~~~~~~~~~~
                                        WeakCallbackInfo
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:6874:16: note: 'WeakCallbackInfo' declared here
  friend class WeakCallbackInfo;
               ^
../src/fibers.cc:49:34: error: too many template arguments for class template 'WeakCallbackInfo'
        void WeakCallbackShim(const v8::WeakCallbackData<T, P>& data) {
                                        ^                   ~~
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:6874:16: note: template is declared here
  friend class WeakCallbackInfo;
               ^
../src/fibers.cc:102:18: warning: 'NewFromOneByte' is deprecated [-Wdeprecated-declarations]
                return String::NewFromOneByte(isolate, (const uint8_t*)string);
                               ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:2317:21: note: 'NewFromOneByte' has been explicitly marked deprecated here
      Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                    ^
../src/fibers.cc:106:18: warning: 'NewFromOneByte' is deprecated [-Wdeprecated-declarations]
                return String::NewFromOneByte(isolate, (const uint8_t*)string);
                               ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:2317:21: note: 'NewFromOneByte' has been explicitly marked deprecated here
      Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                    ^
../src/fibers.cc:423:80: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
                                return uni::Return(uni::Deref(Isolate::GetCurrent(), tmpl)->GetFunction()->NewInstance(1, argv), args);
                                                                                                           ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:3288:31: note: 'NewInstance' has been explicitly marked deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
../src/fibers.cc:611:14: warning: 'TryCatch' is deprecated [-Wdeprecated-declarations]
                                TryCatch try_catch;
                                         ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:7015:40: note: 'TryCatch' has been explicitly marked deprecated here
  V8_DEPRECATED("Use isolate version", TryCatch());
                                       ^
../src/fibers.cc:731:34: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
                        Coroutine::pool_size = value->ToNumber()->Value();
                                                      ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:8406:22: note: 'ToNumber' has been explicitly marked deprecated here
Local<Number> Value::ToNumber() const {
                     ^
../src/fibers.cc:785:8: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "current"), GetCurrent);
                            ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:2754:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<String> name,
                     ^
../src/fibers.cc:786:8: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "poolSize"), GetPoolSize, SetPoolSize);
                            ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:2754:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<String> name,
                     ^
../src/fibers.cc:787:8: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "fibersCreated"), GetFibersCreated);
                            ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:2754:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<String> name,
                     ^
../src/fibers.cc:55:10: error: no matching member function for call to 'SetWeak'
                handle.SetWeak(val, WeakCallbackShim<F>);
                ~~~~~~~^~~~~~~
../src/fibers.cc:341:9: note: in instantiation of function template specialization 'uni::MakeWeak<&Fiber::WeakCallback, v8::Object, void>' requested here
                        uni::MakeWeak<WeakCallback>(isolate, handle, (void*)this);
                             ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:545:18: note: candidate function template not viable: requires 3 arguments, but 2 were provided
  V8_INLINE void SetWeak(P* parameter,
                 ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:556:18: note: candidate function not viable: requires 0 arguments, but 2 were provided
  V8_INLINE void SetWeak();
                 ^
8 warnings and 3 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/srinivas/.nvm/versions/node/v7.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Users/srinivas/.nvm/versions/node/v7.0.0/bin/node" "/Users/srinivas/.nvm/versions/node/v7.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/srinivas/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/node_modules/fibers
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
/Users/srinivas/.nvm/versions/node/v7.0.0/lib
└── (empty)

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/srinivas/.nvm/versions/node/v7.0.0/bin/node" "/Users/srinivas/.nvm/versions/node/v7.0.0/bin/npm" "i" "-g" "nativescript"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/srinivas/workspace/app-mobile/npm-debug.log
npm ERR! code 1

**Comment by solancer** [comment] 2016-11-04 12:30
same issue

Same issue.

linuxsavvy-mbp:app-mobile srinivas$ npm i -g nativescript
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN excluding symbolic link docs/assets/ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Versions/Current -> A
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN excluding symbolic link docs/assets/ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Versions/Current -> A
npm WARN excluding symbolic link docs/stylesheets/hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
/Users/srinivas/.nvm/versions/node/v7.0.0/bin/tns -> /Users/srinivas/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/bin/nativescript.js
/Users/srinivas/.nvm/versions/node/v7.0.0/bin/nativescript -> /Users/srinivas/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/bin/nativescript.js

> fibers@1.0.13 install /Users/srinivas/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/node_modules/fibers
> node build.js || nodejs build.js

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:49:34: error: no template named 'WeakCallbackData' in namespace 'v8'; did you mean 'WeakCallbackInfo'?
        void WeakCallbackShim(const v8::WeakCallbackData<T, P>& data) {
                                    ~~~~^~~~~~~~~~~~~~~~
                                        WeakCallbackInfo
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:6874:16: note: 'WeakCallbackInfo' declared here
  friend class WeakCallbackInfo;
               ^
../src/fibers.cc:49:34: error: too many template arguments for class template 'WeakCallbackInfo'
        void WeakCallbackShim(const v8::WeakCallbackData<T, P>& data) {
                                        ^                   ~~
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:6874:16: note: template is declared here
  friend class WeakCallbackInfo;
               ^
../src/fibers.cc:102:18: warning: 'NewFromOneByte' is deprecated [-Wdeprecated-declarations]
                return String::NewFromOneByte(isolate, (const uint8_t*)string);
                               ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:2317:21: note: 'NewFromOneByte' has been explicitly marked deprecated here
      Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                    ^
../src/fibers.cc:106:18: warning: 'NewFromOneByte' is deprecated [-Wdeprecated-declarations]
                return String::NewFromOneByte(isolate, (const uint8_t*)string);
                               ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:2317:21: note: 'NewFromOneByte' has been explicitly marked deprecated here
      Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                    ^
../src/fibers.cc:423:80: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
                                return uni::Return(uni::Deref(Isolate::GetCurrent(), tmpl)->GetFunction()->NewInstance(1, argv), args);
                                                                                                           ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:3288:31: note: 'NewInstance' has been explicitly marked deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
../src/fibers.cc:611:14: warning: 'TryCatch' is deprecated [-Wdeprecated-declarations]
                                TryCatch try_catch;
                                         ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:7015:40: note: 'TryCatch' has been explicitly marked deprecated here
  V8_DEPRECATED("Use isolate version", TryCatch());
                                       ^
../src/fibers.cc:731:34: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
                        Coroutine::pool_size = value->ToNumber()->Value();
                                                      ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:8406:22: note: 'ToNumber' has been explicitly marked deprecated here
Local<Number> Value::ToNumber() const {
                     ^
../src/fibers.cc:785:8: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "current"), GetCurrent);
                            ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:2754:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<String> name,
                     ^
../src/fibers.cc:786:8: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "poolSize"), GetPoolSize, SetPoolSize);
                            ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:2754:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<String> name,
                     ^
../src/fibers.cc:787:8: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
                        fn->SetAccessor(uni::NewLatin1Symbol(isolate, "fibersCreated"), GetFibersCreated);
                            ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:2754:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<String> name,
                     ^
../src/fibers.cc:55:10: error: no matching member function for call to 'SetWeak'
                handle.SetWeak(val, WeakCallbackShim<F>);
                ~~~~~~~^~~~~~~
../src/fibers.cc:341:9: note: in instantiation of function template specialization 'uni::MakeWeak<&Fiber::WeakCallback, v8::Object, void>' requested here
                        uni::MakeWeak<WeakCallback>(isolate, handle, (void*)this);
                             ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:545:18: note: candidate function template not viable: requires 3 arguments, but 2 were provided
  V8_INLINE void SetWeak(P* parameter,
                 ^
/Users/srinivas/.node-gyp/7.0.0/include/node/v8.h:556:18: note: candidate function not viable: requires 0 arguments, but 2 were provided
  V8_INLINE void SetWeak();
                 ^
8 warnings and 3 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/srinivas/.nvm/versions/node/v7.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Users/srinivas/.nvm/versions/node/v7.0.0/bin/node" "/Users/srinivas/.nvm/versions/node/v7.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/srinivas/.nvm/versions/node/v7.0.0/lib/node_modules/nativescript/node_modules/fibers
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
/Users/srinivas/.nvm/versions/node/v7.0.0/lib
└── (empty)

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/srinivas/.nvm/versions/node/v7.0.0/bin/node" "/Users/srinivas/.nvm/versions/node/v7.0.0/bin/npm" "i" "-g" "nativescript"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/srinivas/workspace/app-mobile/npm-debug.log
npm ERR! code 1

**Comment by tskweres** [comment] 2016-11-05 21:43
I am getting this error as well

**Comment by megamindbrian** [comment] 2017-05-25 20:36
I am getting this error now.

**Comment by rosen-vladimirov** [comment] 2017-05-25 20:39
@megamindbrian , NativeScript 3.0.x do not use fibers. May I ask you for more information - which version of `nativescript` are you trying to install?
I suggest trying:
```
$ npm uninstall -g nativescript
$ npm cache clean
$ npm install -g nativescript@latest
```

If the above does not help, please send us the following information:
1. The exact output of `npm install -g nativescript@latest`
1. Your npm version (output of `npm -v`)
1. Your Node.js version (output of `node -v`).

**Comment by megamindbrian** [comment] 2017-05-25 20:46
Why doesn't it resolve the correct dependency for nativescript?
