### ISSUE TITLE
"ERROR Error: Could not find module" after 2.5 upgrade

### ISSUE THREAD

**Issue by alexziskind1** [NativeScript/nativescript-cli#2491] opened 2017-02-06 02:16 UTC
The following project throws a seg fault 11 after an upgrade to nativescript 2.5:
https://github.com/alexziskind1/courses-rps-conference-app-ng/tree/master/rps-conf-ng

Here's the full error message:
```ERROR Error: Could not find module './locales/nb_NO'. Computed path '/Users/alex/Library/Developer/CoreSimulator/Devices/7EF5EC7B-FB52-49AF-B710-2077B6F98F98/data/Containers/Bundle/Application/2315EEB1-3603-4678-B6F6-F1834C7437D2/rpsconfng.app/app/tns_modules/faker/lib/locales/nb_NO'.
Feb  5 21:05:55 AlexMBP com.apple.CoreSimulator.SimDevice.7EF5EC7B-FB52-49AF-B710-2077B6F98F98.launchd_sim[15029] (UIKitApplication:org.nativescript.rpsconfng[0xbb3f][16195]): Service exited due to Segmentation fault: 11
```

This was working well before the upgrade to 2.5 while on 2.4.2.

**Comment by Plamen5kov** [comment] 2017-02-08 12:57
Can't reproduce. Ran:
```
git clone https://github.com/alexziskind1/courses-rps-conference-app-ng.git problem
cd problem && rps-conf-ng
tns run ios
```

**Comment by alexziskind1** [comment] 2017-02-08 13:35
I was just able to reproduce with nativescript 2.5 installed. I recorded a video (about 1.5 minutes) of the process:
https://youtu.be/reeDLOIiSB8

Alex

**Comment by Plamen5kov** [comment] 2017-02-08 14:45
@alexziskind1 Thank you, I managed to reproduce your problem, and I will investigate.

**Comment by Plamen5kov** [comment] 2017-02-09 07:33
@alexziskind1 the missing file is not being copied. This is a [problem](https://github.com/shelljs/shelljs/issues/547) with a module we're using called shelljs. It's fixed in the next version of the module so we'll try to update and all should be OK.

**Comment by alexziskind1** [comment] 2017-02-09 12:17
OK Thanks! Is there something I can do in the meantime so I can move past this. Do you suggest a temporary workaround?

**Comment by Plamen5kov** [comment] 2017-02-09 13:29
You can use cli from @next, because i'll fix it shortly in master branch.
`npm install -g nativescript@next`

**Closed** 2017-02-15 12:46 UTC
Labels: bug

**Comment by alexziskind1** [comment] 2017-02-15 13:16
Just to give some feedback - using the @next version (3.0.0-2017-02-09-7977) did work.

Thanks for the suggestion @Plamen5kov
