### ISSUE TITLE
tns create "app" won

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/nativescript-cli#1438] opened 2016-02-01 15:46 UTC

**Comment by rosen-vladimirov** [comment] 2016-02-01 20:55
I believe this is a duplicate of https://github.com/NativeScript/nativescript-cli/issues/1439 so I'm closing it.

**Comment by sitefinitysteve** [comment] 2016-02-01 20:56
Oh yeah...wtf happened here

**Closed by rosen-vladimirov** 2016-02-01 20:55 UTC
