### ISSUE TITLE
Stuck on starting emulator on Android

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-cli#2210] opened 2016-11-09 11:35 UTC
## Issue
I have noticed that from time to time when trying to "run" an {N} application on Android via `tns emulate android` the terminal gets stuck after:

> Starting Android emulator with image Nexus_5X_API_24

and after a flew minutes this error is shown:

> Cannot run your app in the native emulator. Increase the timeout of the operation with the --timeout option or try to restart your adb server with 'adb kill-server' command. Alternatively, run the Android Virtual Device manager and increase the allocated RAM for the virtual device.

Doing the mentioned `adb kill-server` or timeout increasing does not resolve the issue.

## Workaround

Manually start the Android emulator via Android Studio and use `tns run android`

**Comment by dtopuzov** [comment] 2016-11-09 11:41
Another work around:
`tns run android --timeout 300`

**Comment by VladimirAmiorkov** [comment] 2016-11-29 14:27
@dtopuzov None of those workarounds work for me on my end. The same message is written to the terminal:

> $ tns run android --timeout 300
> Starting Android emulator with image Nexus_5X_API_24

or

> $ tns run android --avd Nexus_5X_API_24
> Starting Android emulator with image Nexus_5X_API_24

**Comment by dtopuzov** [comment] 2016-11-29 14:38
CLI defaults to latest installed and booting of Api24 is significantly slower compared to Api23.

**Comment by VladimirAmiorkov** [comment] 2016-11-29 15:34
Maybe we can improve upon this by giving access to changing what CLI uses as default emulator.

**Comment by rosen-vladimirov** [comment] 2016-11-29 15:52
@VladimirAmiorkov you can pass `--avd <name of emulator>` - this way CLI will use it instead :)

**Comment by VladimirAmiorkov** [comment] 2016-11-29 16:12
@rosen-vladimirov Yes this is a good option to have but I do not think it should be considered a "goto" solution for this issue as it is not a visible option that many users will not know that exists or know how to search for such option (maybe add it somewhere in the docs). What I am talking about is as CLI currently will use the latest emulator available which may cause all kinds of issues (like this one), it would be great if the users can change what CLI will use when executing `tns emulate android` (without additional options).

**Comment by Plamen5kov** [comment] 2016-12-08 13:35
I'm with @rosen-vladimirov, the default should use the newest emulator installed. We have a way for the user to use a different emulator using `--device` flag, and this flag is described in the help of the `tns emulate` command.

**Comment by VladimirAmiorkov** [comment] 2016-12-08 13:50
@Plamen5kov Hmm, well that is absolutely true but the fact is that the goto and simplest command `tns emulate android` does not work on my end at all making it useless. Having to write and remember the full name of the device when simply wanting to start an {N} app is lets say inconvenient at the very least. I am hoping we can do better for our default command.

**Comment by Plamen5kov** [comment] 2016-12-08 16:56
@VladimirAmiorkov I could understand the logic behind the user choosing what emulator to be started as a default behavior, but if all of the given options get stuck we still won't have an answer to the real problem. That's why i believe, it's best to focus on the problem of why it's stuck and fix it. After we've fixed the major problem,  we can have a discussion of what will the best user experience be.

**Comment by VladimirAmiorkov** [comment] 2016-12-09 07:46
@Plamen5kov Yes of course, finding the source and possibly fixing it so that the execution is not getting stuck is the first concern that should be taken into account. Adding a way to change the default device was as mentioned earlier nothing more than a improvement suggestion rather than a fix for this issue.

**Comment by Plamen5kov** [comment] 2016-12-21 07:09
@VladimirAmiorkov  is there a way to reproduce this problem or does it happen for random emulators on random API levels?

**Comment by dtopuzov** [comment] 2017-01-05 11:10
It happen always when emulator is not started before `tns run android` and emulator startup time is slower than 2 minutes (which happens with arm emulators or latest api levels or slow desktop machines).

Steps to reproduce:
```
tns run android --avd Name-of-some-very-slow-arm-emulator
```

Note: Currently `tns run android -avd <emulator name>` is broken, but you get my point.

**Comment by Plamen5kov** [comment] 2017-03-10 10:07
Closing this, since the original issue has a solution we've provided which is `--timeout`. Furthermore, we plan on deprecating and removing the emulate command.

**Closed by Plamen5kov** 2017-03-10 10:07 UTC
Labels: bug, minor

**Comment by kamlekar** [comment] 2018-01-10 09:46
@Plamen5kov This issue occurs to me even for `tns run android` and `tns debug android`. I am using `3.4.0` nativescript version.

**Comment by Plamen5kov** [comment] 2018-01-10 09:48
Hi @kamlekar, could you open a new issue, following the issue template so we can help you resolve your issue faster.

**Comment by kamlekar** [comment] 2018-01-10 09:51
Ok will do. Thanks for quick reply.
