### ISSUE TITLE
Download hello-world template from github url

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#372] opened 2015-03-24 15:29 UTC
CLI should be able to download hello world template from github url. Currently it works only with local path.

**Comment by bfattori** [comment] 2015-07-31 00:33
This looks like the problem I'm talking about here. Do I have some sort of npm release the that contains this build, possibly? Or is this feature partially implemented?

**Comment by rosen-vladimirov** [comment] 2015-12-16 21:58
Closing as duplicate of https://github.com/NativeScript/nativescript-cli/issues/374
Check the other issue for more details.

**Closed by rosen-vladimirov** 2015-12-16 21:58 UTC
Labels: feature
