### ISSUE TITLE
Hardcoded paths getting into project.pbxproj

### ISSUE THREAD

**Issue by karaahmed** [NativeScript/nativescript-cli#759] opened 2015-08-07 08:40 UTC
For more information refer to the issue form nativescript-ui-samples repo: https://github.com/telerik/nativescript-ui-samples/issues/8

**Comment by maknz** [comment] 2015-08-10 03:03
:+1:, please please please.

**Comment by Fatme** [comment] 2015-08-10 09:20
Hi guys,

We've already fixed this issue - https://github.com/NativeScript/nativescript-cli/issues/679. The fix will be included in 1.2.2 version of {N}. We've planned to release today. You can give a try to a new version and let us know if the fix works for you.

**Comment by teobugslayer** [comment] 2015-08-10 10:14
Duplicate of https://github.com/NativeScript/nativescript-cli/issues/679

**Closed by teobugslayer** 2015-08-10 10:14 UTC
