### ISSUE TITLE
tns run ios not working properly

### ISSUE THREAD

**Issue by chauhan-saurabh** [NativeScript/nativescript-cli#3234] opened 2017-11-28 13:15 UTC
```
Successfully installed on device with identifier '23938CBC-2E07-4381-B95A-5E3FD1B729C1'.
Successfully transferred all files.
Refreshing application...
Successfully synced application org.nativescript.shyft on device 23938CBC-2E07-4381-B95A-5E3FD1B729C1.
Executing before-watch hook from /Users/saurabh.chauhan/Desktop/clone/futuredms-shyft-auto-mobile/shyft/hooks/before-watch/nativescript-dev-sass.js
Found peer node-sass
Executing before-watch hook from /Users/saurabh.chauhan/Desktop/clone/futuredms-shyft-auto-mobile/shyft/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.4.2
6:39:48 PM - Compilation complete. Watching for file changes.
```

**Comment by dtopuzov** [comment] 2017-11-28 14:27
Hi @chauhan-saurabh 

Can you please elaborate more on "tns run ios not working properly"?
Please also provide:
- Steps to reproduce the issue
- Version of nativescript, xcode, npm, nodejs
- package.json of your project

**Comment by dtopuzov** [comment] 2017-11-29 08:51
Closing as duplicate of https://github.com/NativeScript/nativescript-cli/issues/3235

**Closed by dtopuzov** 2017-11-29 08:51 UTC
Labels: question
