### ISSUE TITLE
Fibers problems in npm install and running tns 

### ISSUE THREAD

**Issue by matt4446** [NativeScript/nativescript-cli#1348] opened 2015-12-14 23:10 UTC
Hello any clever people.

Specs Windows 10 x64 (AMD) 

A couple of weeks ago I had this all working (1.4, 1.5 preview *from the demos*)... Now ive stumbled down a hill and got lost.  

I cant seem to get node.js to play nice particularly nativescript-cli. 
So first my issues pointed to here (fibers could not compile -  fatal error LNK1104: cannot open file 'libcpmt.lib'): https://github.com/nodejs/node-gyp/issues/629

To get fibers building was a enjoyable journey. 
and now if I reinstall any version of node i need to run this: 
npm config set msvs_version 2015 --global

back on topic: 
Installing Nativescript: 

... 
 fibers@1.0.6 install C:\Users\barmy\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers
> node build.js || nodejs build.js

`win32-x64-v8-4.5` exists; testing *(see image below)*
...
continues a bit bringing up a few more errors *like the c++ errors but a few different lines*
... 
FATAL ERROR: v8::Context::Exit() Cannot exit non-entered context

The problem continues even if i copy the successfully compiling 1.0.8 into the project. 

![fibers-error](https://cloud.githubusercontent.com/assets/1550939/11796241/309c84b2-a2b3-11e5-9610-a17049302d76.png)

the ignore button doesn't help as when you run tns afterwards it brings up the same image again. 

Anyone else experienced similar problems? 
Its hard to find anything based on the c++ error description. 

I've tried various versions of node (0.10.x, 0.12.x, 4.2.x) and npm (various). 
redistributes of VC 2010, 2012, 2013 (x86 + x64) 
windows 7 sdk 
VC for Pyton 2.7
Cleared npm cache several times. 
Cleared it all out and started again. 

I'm getting close to a clean reinstall of windows. <-- avoiding -- tiring ;-) 
But its beginning to feel like a fresh install is the only way of fixing what ever happened some point a few weeks ago. 

Any ideas: good, crazy or otherwise... ? 

Thanks, Matt

**Comment by rosen-vladimirov** [comment] 2015-12-15 07:03
Hi Matt,
It looks like you have faced [this issue](https://github.com/laverdet/node-fibers/issues/262)
I've tried to reproduce it on my side, but without success. If I can reproduce it, we can work with @laverdet in order to fix it.
Can you try one of the suggested solutions in the thread and write there, so we could investigate it further. I'll keep trying to reproduce it, so we could provide permanent fix for this :) 
Thanks in advance for your cooperation.

**Comment by matt4446** [comment] 2015-12-15 11:49
5 days ago. Possibly. It was longer than that that ive had the problem (so i stopped looking in that direction). Similar things popped up but for a long time ago but was more directed at a npm version issue. I'll try the patch when i get some free time at home. (probably thursday evening ... possibly this evening but i wont be back to quite late).  

Is fibers a recent addition or has that been there for a while. Im just a little perplexed how It all broke between nov 14-21st ish time. 
The only weird thing I recall doing is installing the beta amd crimson drivers around that time.

**Comment by rosen-vladimirov** [comment] 2015-12-15 13:10
Well, `fibers` is our dependency from day 0. As you can see, this error is not reproducible on every machine, the "fix" that's been proposed is from August, but there's no one to confirm that it is correct.

I'll test the code on Windows 10 later today and see if I'm able to reproduce it after latest updates, maybe some of them caused the unexpected behavior.

**Comment by laverdet** [comment] 2015-12-15 17:12
Yeah I would like to get a confirmation on the behavior of this bug on a user's system, and then I will land one of those fixes upstream. It seems this only happens on certain Windows boxes, and I'm not really sure what the pattern is.

@matt4446 if you want to help out you could pick up where the other user left off, apply this fix:
https://github.com/meteor/node-fibers/commit/d519f0c5971c33d99c902dad346b817e84bab001

And then this patch with some debug statements:
https://github.com/laverdet/node-fibers/issues/262#issuecomment-163483884

Then run `node build -f` in your fibers directory and tell me what it outputs when you require the newly built binary.

**Comment by rosen-vladimirov** [comment] 2015-12-15 21:31
Ok, I've tried on Windows 7, Windows 8.1 and two Windows 10 machines and I cannot reproduce the issue using Node 4.2.1, 4.2.3 or 5.2.0
Looks like there's something really specific here.
By the way, @matt4446 , installation of nativescript-cli does not require any Visual Studio - we have prebuilt all C++ modules (including fibers), so the only thing that you should see in the output is:
```
`win32-x64-v8-4.5` exists; testing
Binary is fine; exiting
```
So we'll be waiting for any possible information that you can give us, if you can try @laverdet 's steps , it will be great help for us. Thanks in advance!!!

**Comment by matt4446** [comment] 2015-12-15 22:42
Thanks for putting the time in to explore. It is a curious one. Not too long ago it was all working and now no ... 
I dont have time to test much out over the next couple of day but I should be able to get a good look before the weekend.

**Comment by matt4446** [comment] 2015-12-15 22:50
Actually ... this was perfect:
https://github.com/meteor/node-fibers/commit/d519f0c5971c33d99c902dad346b817e84bab001

**Comment by matt4446** [comment] 2015-12-15 22:57
I'll test a bit later in the week to validate that it is still working.

**Comment by rosen-vladimirov** [comment] 2015-12-16 00:30
Great @matt4446 , 
Thank you very, very much for your cooperation. When you have time later this week, could you apply this patch as well:
```
And then this patch with some debug statements:
laverdet/node-fibers#262 (comment)

Then run node build -f in your fibers directory and tell me what it outputs when you require the newly built binary.
```
In order to "require" the binary, just copy it from `<fibers dir>/build/Release/fibers.node` to `bin/win32-x64-v8-4.5/fibers.node` and execute `npm i` in the `<fibers dir>`. This will check the binary by requiring it and you should see the output that @laverdet  needs.

Your help is really appreciated.

**Closed** 2016-06-02 12:46 UTC
Labels: external

**Comment by enchev** [comment] 2016-06-09 12:22
Cannot reproduce with latest
