### ISSUE TITLE
Issues since update 1.5: tns doctor not working. ANDROID_HOME not recognised. Cannot add android platform

### ISSUE THREAD

**Issue by FabioThe1** [NativeScript/nativescript-cli#1275] opened 2015-11-28 16:47 UTC
After the update to 1.5 following issues occured:

- In the 1.5 installation log shows this error message: 
The ANDROID_HOME environment variable is not set or it points to a non-existent directory. You will not be able to perform any build-related operations for Android.
To be able to perform Android build-related operations, set the ANDROID_HOME variable to point to the root of your Android SDK installation directory.

ANDROID_HOME environment variable is not set correctly.

- tns doctor and tns platform add android showing this error:
Cannot read property 'match' of null

**Comment by barryhippo** [comment] 2015-11-29 07:36
so do I. Wait how to resolve.

**Comment by rosen-vladimirov** [comment] 2015-11-30 06:44
Hi @FabioThe1 and @barryhippo 
The issue you have faced is related to missing cocoapods on your machine. The issue is already logged [here](https://github.com/NativeScript/nativescript-cli/issues/1245) and we'll fix it for our next release. As a workaround I recommend you to execute `sudo gem install cocoapods`.
I'm closing this thread as it is duplicate of the mentioned one :) Feel free to contact us in case you have any other problems or concerns.

**Closed by rosen-vladimirov** 2015-11-30 06:44 UTC
