### ISSUE TITLE
[3.0.0] Can't remove or update plugins

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/nativescript-cli#2792] opened 2017-05-09 14:25 UTC
I have just updated to N 3.0.0 following the instructions [here](https://docs.nativescript.org/releases/upgrade-instructions) and I'm now unable to remove or update any plugins.

```
tns plugin update nativescript-background-http
SyntaxError: Expected "/*", "//" or "{" but "<" found.
```

```
tns plugin remove nativescript-background-http
Plugin "nativescript-background-http" is not installed.

tns plugin remove tns plugin remove nativescript-geolocation
SyntaxError: Expected "/*", "//" or "{" but "<" found.
```

This syntax error looks very similar to another issue I reported a few days ago: https://github.com/NativeScript/nativescript-cli/issues/2782#issuecomment-299484642

```
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.0.0           │ 3.0.0          │ Up to date    │
│ tns-core-modules │ 3.0.0           │ 3.0.0          │ Up to date    │
│ tns-android      │                 │ 3.0.0          │ Not installed │
│ tns-ios          │ 3.0.0           │ 3.0.0          │ Up to date    │
└──────────────────┴─────────────────┴────────────────┴───────────────┘

Dependencies:
┌────────────────────────────────┬─────────┐
│ Plugin                         │ Version │
│ nativescript-background-http   │ ^2.5.1  │
│ nativescript-carousel          │ ^2.3.1  │
│ nativescript-geolocation       │ 0.0.19  │
│ nativescript-google-maps-sdk   │ ^2.0.3  │
│ nativescript-imagepicker       │ ^2.5.1  │
│ nativescript-iqkeyboardmanager │ ^1.0.1  │
│ nativescript-permissions       │ ^1.2.3  │
│ nativescript-theme-core        │ ~1.0.2  │
│ tns-core-modules               │ ^3.0.0  │
└────────────────────────────────┴─────────┘
Dev Dependencies:
┌───────────────────────────────────┬─────────┐
│ Plugin                            │ Version │
│ babel-traverse                    │ 6.23.1  │
│ babel-types                       │ 6.23.0  │
│ babylon                           │ 6.16.1  │
│ lazy                              │ 1.0.11  │
│ nativescript-dev-android-snapshot │ ^0.*.*  │
└───────────────────────────────────┴─────────┘
```

**Comment by 3rror404** [comment] 2017-05-09 14:29
It seems that the plugin is actually removed when running `tns plugin remove <plugin_name>` even though there is an error displayed in terminal.

**Comment by dtopuzov** [comment] 2017-05-09 19:38
Hi @3rror404 can you run `tns plugin update <some-plugin> --log trace` and paste the output.
Can you also post full package.json of your app, since I'm not able to reproduce the issue with single plugin.

Can you also try to remove following from your package.json:
```
babel-traverse
babel-types
babylon
lazy  
```
and try plugin update again?

Workaround:
Use `npm i <plugin-name> --save` for regular plugins and `npm i <plugin-name> --save-dev` for dev plugins like `nativescript-dev-android-snapshot`

**Comment by 3rror404** [comment] 2017-05-10 09:49
Hi @dtopuzov,

I had to downgrade to N 2.5.4 to continue my project so I'm unable to provide any more information currently.

If I get the time I will try to update again and do as you have requested.

**Comment by dtopuzov** [comment] 2017-06-19 07:39
Hi @3rror404 

Did you managed to re-test the issue with 3.* versions?
https://github.com/NativeScript/NativeScript/issues/4141 is already fixed in `tns-core-modules@3.0.1`.

**Comment by 3rror404** [comment] 2017-06-19 08:32
Hi @dtopuzov,

I haven't updated this specific project to N3 yet, but I haven't experienced it in other N3.x based projects so maybe it was just an issue with 3.0.0?

**Comment by dtopuzov** [comment] 2017-06-19 13:24
We where never able to reproduce it, so I expect it is environment issue.
May be it happens with specific versions of `node` and `npm`.

Closing the issue since it is not longer reproducible.

@3rror404 let us know if you encounter it again.

**Closed by dtopuzov** 2017-06-19 13:24 UTC
Labels: bug, Need More Info
