### ISSUE TITLE
Enable NativeScript local installation

### ISSUE THREAD

**Issue by hshristov** [NativeScript/nativescript-cli#1561] opened 2016-03-02 11:09 UTC
There is a need to have local installation of NativeScript with local version of cli, modules, runtime, plugins and other dependencies. Using --frameworkPath is hard and not clear enough on which commands should It be passed on.

**Comment by rosen-vladimirov** [comment] 2016-03-02 12:23
@hshristov can you describe what exactly do you need and what's the problem you have. 
`--frameworkPath` is described in our help - by default it is expected to be used on `platform add` command: https://github.com/NativeScript/nativescript-cli/blob/master/docs/man_pages/project/configuration/platform-add.md
As CLI has internal logic to call `platform add` when you call any build related commands and the platform is not installed, the option can be passed to `prepare`, `build`, `deploy`, `run`, `emulate`, `test` commands as well and it will be respected.

I'm using CLI from local installation and I do not have any issues, so I'm wondering what's your case. Also what's the user story behind this request, I'm not sure there are many users that need local installation.

**Comment by hshristov** [comment] 2016-03-07 07:46
@rosen-vladimirov I want to install custom CLI, with custom modules and custom runtimes.

**Comment by dtopuzov** [comment] 2016-03-07 09:21
What it the problem with local installations now?

If you want to use local packages you have two options:
- Use something like Sinopia to fake npm
- Use local modules and runtimes from local tgz file (obviously you need some flags to say this is local file, not official npm package)

**Comment by rosen-vladimirov** [comment] 2016-03-09 15:41
@hshristov you can install custom CLI, custom modules and custom runtimes without any issues.
Consider the following workflow:
* You are in a project dir and you want to test the project with old modules, runtimes and CLI
* First of all remove `platforms` dir and preferably, but not mandatory, remove `node_modules`.
* Install custom CLI
```
npm i <path to nativescript-cli.tgz>
```
or install older CLI version:
```
npm i --save-dev nativescript@1.5.1
```
Any of the above statements will install nativescript-cli in your local node_modules directory, so you can just call
```
node_modules/.bin/tns --version
```
* Now install required tns-code-modules version:
```
npm i --save tns-core-modules@1.5.0
```
or custom .tgz:
```
npm i --save <path to tns-core-modules tgz>
```
* The last step is to install custom runtime:
```
node_modules/.bin/tns platform add android --frameworPath <path to android framework>
```
or specific version:
```
node_modules/.bin/tns platform add android@1.5.0
```
* It is time to build your application and run it on device:
```
node_modules/.bin/tns run android
```

And that's it - you have the same application, but it is using "custom" modules, runtime and built with custom CLI.

In case you do not have any other issues, I'm going to close this thread.

**Comment by rosen-vladimirov** [comment] 2016-03-10 07:07
I just want to add some more information here - in some cases you are not able to use project created with one version of NS CLI with other version of CLI, runtimes and modules without manually modifying the project. This is due to the dynamic NativeScript environment and changes we apply in each versions. For example you cannot create project with NS CLI 1.6.x, template 1.6.x and use it with NS CLI 1.5.x and android runtime 1.5.x due to differences in the `app/App_Resources/Android/AndroidManifest.xml` handling in these two versions. However this does not mean that you cannot use custom CLI, it just shows that we have breaking changes.

**Comment by PanayotCankov** [comment] 2016-03-10 07:19
I think if we enable:
```
npm i --save <path to framework path>
```
To make each platform specific command (including platform remove/add, debug etc.) use the local installation of the run-time without passing explicitly the --frameworkPath, would make development with custom runtimes somewhat easier.

Optionally allowing:
```
tns platform add <filepath>
```
would be more consistent with `tns plugin add <filepath>` and IMO better than `tns platform add android --frameworkPath <path to tns-android>`.

Some of the commands like `tns debug` required --frameworkPath to be passed around. Now the tns-ios is separating the WebInspector app, so I do not know how it works at the moment, but it would be better if it could too be `npm i --save-dev`-ed instead of `--debuggerPath`-ed.

We also would be happy if the `tns` command hand over execution to `node_modules/.bin/tns` if present.

It feels like for development it is more convenient if all nativescript packages work as simple npmjs packages that can just be installed locally, skipping the extra effort to memory map between commands, flags and tgz paths.

**Comment by rosen-vladimirov** [comment] 2016-03-10 07:27
Using runtimes as npm packages is on the route, we are currently discussing best way to handle this. ```
We also would be happy if the tns command hand over execution to node_modules/.bin/tns if present.
```
I'm strongly against this idea - it's user's decision to select the executable. In case there are local installation and global installation of CLI, it's up to the user which executable to call. CLI **must** not have logic to change the executable!

As per the debug, I've really not tested it with local installation, but all of the other commands are working at the moment. In case the issue is only with debug commands, I'll rename the issue, as the current title suggests that local installation is not possible at all. Yes, it can be improved, but it's easy enough at the moment to follow the steps and create customized project that will work :)

**Comment by enchev** [comment] 2016-06-03 06:43
Hey @hshristov @PanayotCankov @rosen-vladimirov what's the status of this?

**Closed** 2016-06-08 13:23 UTC
Labels: question
