### ISSUE TITLE
[@next] tns create TestApp --ng (or --tsc) takes too long

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2299] opened 2016-12-02 09:09 UTC
Steps:
```
npm install -g nativescript@next
tns create TestApp --tsc
```
Result: It takes 60+ sec.

Notes: This issue does not exist in {N} 2.4.0 official release

**Comment by tzraikov** [comment] 2016-12-02 13:06
Fixed with https://github.com/NativeScript/template-hello-world-ts/pull/23

**Comment by dtopuzov** [comment] 2016-12-02 20:52
Not sure template is best place to fix it, what if we have another plugin with postinstall script that do npm install?

**Comment by tzraikov** [comment] 2016-12-05 08:54
I am not sure that it is a good practice to call `npm install` within a postinstall script. Is this a common practice in our scripts?

**Comment by rosen-vladimirov** [comment] 2016-12-06 06:49
It's not common practice to have `npm install` in postinstall script. In fact it's a bad practice. However I'm wondering how adding a new dependency fixes this issue. Can you provide more details, @tzraikov ?

**Comment by tzraikov** [comment] 2016-12-06 08:37
CLI calls `npm install` of the template, which now has a reference to nativescript-dev-typescript module, which has a postinstall script that calls `npm install` of the snapshot module. Calling `npm install` during `npm install` seems to slow down the process.

**Comment by rosen-vladimirov** [comment] 2016-12-06 09:40
@tzraikov thanks for the explanation. I agree that our TypeScript template must have TypeScript as devDependency. However there's one thing that concerns me - in version 2.4.0 of NativeScript CLI, the issue is not reproducible, but the template there does not have TypeScript as dependency. So something in CLI's master is causing the slowness and maybe (just maybe) the current fix is hiding some other issue.
Anyway, adding TypeScript as devDependency seems absolutely correct.

**Comment by tzraikov** [comment] 2016-12-06 11:18
@rosen-vladimirov I agree, this could be possible. AFAIK we changed the way how project templates are installed and we removed npm2 dependencies. I would suspect those changes. However, this is not necessary an issue.

**Closed** 2016-12-08 15:03 UTC
Labels: bug, critical
