### ISSUE TITLE
https://www.nativescript.org dosen't open in my browser (chrome & firefox) last versions, although https://docs.nativescript.org opens normally ... what is the problem?

### ISSUE THREAD

**Issue by xxyyzz2050** [NativeScript/nativescript-cli#4687] opened 2019-06-06 13:28 UTC
https://www.nativescript.org dosen't open in my browser (chrome & firefox) last versions, although https://docs.nativescript.org opens normally ... what is the problem?

**Comment by rosen-vladimirov** [comment] 2019-06-20 20:17
Hey @xxyyzz2050 ,
This issue seems related to your machine and is not related to NativeScript CLI. Probably there are some configuration issues with your firewall, but this is just a guess.
I'm closing this thread as the problem is not related to NativeScript CLI.

**Closed by rosen-vladimirov** 2019-06-20 20:17 UTC
