### ISSUE TITLE
IOS error

### ISSUE THREAD

**Issue by naturalfreak** [NativeScript/nativescript-cli#2940] opened 2017-07-01 17:56 UTC
Only on ios device I got this error.

` ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1091:24: ERROR TypeError: undefined is not an object (evaluating 'asElementData(view, nodeIndex).componentView')`

package.json

> "dependencies": {
>     "@angular/animations": "~4.1.3",
>     "@angular/common": "~4.1.3",
>     "@angular/compiler": "~4.1.3",
>     "@angular/core": "~4.1.3",
>     "@angular/forms": "~4.1.3",
>     "@angular/http": "~4.1.3",
>     "@angular/platform-browser": "~4.1.3",
>     "@angular/router": "~4.1.3",
>     "ios-uuid": "./packages/ios-uuid-1.0.0.tgz",
>     "loading-indicator": "./packages/loading-indicator-1.0.0.tgz",
>     "nativescript-angular": "~3.1.1",
>     "nativescript-camera": "~3.0.0",
>     "nativescript-facebook": "./packages/nativescript-facebook-2.0.1.tgz",
>     "nativescript-fresco": "~3.0.2",
>     "nativescript-geolocation": "~3.0.0",
>     "nativescript-google-maps-sdk": "~2.3.0",
>     "nativescript-imagepicker": "~3.0.1",
>     "nativescript-iqkeyboardmanager": "~1.1.0",
>     "nativescript-push-notifications": "~0.1.3",
>     "nativescript-socket.io": "~0.6.0",
>     "nativescript-telerik-ui-pro": "./packages/nativescript-ui-pro.tgz",
>     "nativescript-theme-core": "~1.0.4",
>     "reflect-metadata": "^0.1.8",
>     "rxjs": "~5.4.0",
>     "tns-core-modules": "^3.1.0",
>     "zone.js": "~0.8.11"
>   },
>   "devDependencies": {
>     "@angular/compiler-cli": "~4.1.3",
>     "@ngtools/webpack": "~1.4.2",
>     "babel-traverse": "6.11.4",
>     "babel-types": "6.11.1",
>     "babylon": "6.8.4",
>     "codelyzer": "^3.0.1",
>     "copy-webpack-plugin": "~4.0.1",
>     "extract-text-webpack-plugin": "~2.1.0",
>     "fs-extra": "^0.30.0",
>     "glob": "^7.1.2",
>     "lazy": "1.0.11",
>     "markdown-snippet-injector": "^0.2.0",
>     "nativescript-css-loader": "~0.26.1",
>     "nativescript-dev-typescript": "^0.5.0",
>     "nativescript-dev-webpack": "~0.7.1",
>     "opener": "^1.4.1",
>     "raw-loader": "~0.5.1",
>     "resolve-url-loader": "~2.0.2",
>     "rimraf": "^2.5.3",
>     "tar.gz": "^1.0.5",
>     "tns-platform-declarations": "^3.1.0",
>     "tslint": "^5.4.2",
>     "typescript": "~2.3.4",
>     "webpack": "~2.6.1",
>     "webpack-bundle-analyzer": "^2.8.2",
>     "webpack-sources": "~1.0.1"
>   }

tsconfig.json

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "lib": [
            "es6",
            "dom",
            "es2015.iterable"
        ],
        "baseUrl": ".",
        "paths": {
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms",
        "**/*.aot.ts"
    ]
}

```

**Comment by naturalfreak** [comment] 2017-07-02 22:57
The error was from this code 

```
<RadSideDrawer [drawerTransition]="sideDrawerTransition"
               tkExampleTitle
               tkToggleNavButton
               (loaded)="layoutLoaded($event)">
</RadSideDrawer>
```

When I remove this line (loaded)="layoutLoaded($event)" everything works fine.
But this is very difficult to find because it happens only on IOS devices and error is very strange.

**Comment by dtopuzov** [comment] 2017-07-03 13:14
Hi @naturalfreak 

Does `it happens only on IOS devices` means you can not reproduce on iOS Simulators?

**Comment by naturalfreak** [comment] 2017-07-03 23:23
Yes

**Comment by dtopuzov** [comment] 2017-07-04 07:27
Moving to https://github.com/telerik/nativescript-ui-feedback/ since this looks as issue with `RadSideDrawer` component which is part of [nativescript-telerik-ui](http://www.telerik.com/nativescript-ui)

**Comment by dtopuzov** [comment] 2017-07-04 07:27
This issue was moved to telerik/nativescript-ui-feedback#229

**Closed by dtopuzov** 2017-07-04 07:27 UTC
Labels: iOS, question
