### ISSUE TITLE
Changes in App_Resources during prepare triggers a build

### ISSUE THREAD

**Issue by Pip3r4o** [NativeScript/nativescript-cli#2562] opened 2017-02-22 15:17 UTC
Saving changes in `App_Resources` immediately after triggering a prepare (by changing javascript sources) triggers a rebuild of the iOS project and crashes the CLI process at `Installing...`

**1)**
```
tns create app251
cd app251
tns platform add ios
tns run ios
```
**2)**
~~Modify `main-page.ts` without saving, change `Info.plist` in the resources dir without saving. Save `main-page.ts` and then `Info.plist`.~~ 

Modify `Info.plist` in resources directory and save.

The above will trigger a fast prepare followed by a rebuild, the CLI process dies and the device ends up with a black screen/frozen app, and no installed app.

Related issues: 
- https://github.com/NativeScript/nativescript-cli/issues/2560 - rebuild if changes in App_Resources are detected.
- https://github.com/NativeScript/nativescript-cli/issues/2557 - plugins making changes in App_Resources trigger endless builds.

Notes:
- tested on an Iphone 5 device
- nativescript of versions up to 2.4.2 used to output a message that changes in App_Resources won't be synced and that they require a complete rebuild.
- --log trace reports `Results at '/Users/mac/user/nativescript-cli/scratch/app242/platforms/ios/build/device/app242.ipa' 
Project successfully built.
Installing...
Application org.nativescript.app242 has been uninstalled successfully.
BeforeHookName for command install is before-install
Removing device file 'PublicStaging/app242.ipa', result: 8` before terminating the process.

**Comment by Plamen5kov** [comment] 2017-02-28 12:10
Closing since after [this PR](https://github.com/telerik/mobile-cli-lib/pull/889) is merged, this issue will be a duplicate of: https://github.com/NativeScript/nativescript-cli/issues/2500

**Closed by Plamen5kov** 2017-02-28 12:10 UTC
Labels: bug, ios
