### ISSUE TITLE
latest Nativescript cli - SSL error on iOS release build (works on debug build)

### ISSUE THREAD

**Issue by udugama** [NativeScript/nativescript-cli#5226] opened 2020-01-24 01:53 UTC
using Nativescript v6.3.3 and debug build on this application works flawlessly.
when I do a release build it breaks during the login and throws following error on console.

build with `tns run ios --bundle --release` {`tns run ios --bundle` works without any modification}

projects set to code sig automatically

Using new build system but tried with old system too..

performed `tns platform remove ios` and add the platform back in ..
```
boringssl_context_info_handler(1969) [C3.1:2][0x106347c90] Client handshake started
boringssl_context_message_handler(2257) [C3.1:2][0x106347c90] Writing SSL3_RT_HANDSHAKE 512 bytes
boringssl_context_info_handler(1982) [C3.1:2][0x106347c90] Client handshake state: TLS client enter_early_data
boringssl_context_add_handshake_message_pending(577) [C3.1:2][0x106347c90] Adding message(1)
boringssl_context_info_handler(1982) [C3.1:2][0x106347c90] Client handshake state: TLS client read_server_hello
boringssl_context_add_handshake_message_pending(577) [C3.1:2][0x106347c90] Adding message(2)
boringssl_session_handshake_incomplete(191) [C3.1:2][0x106347c90] Early handshake return caused by SSL_ERROR_WANT_READ [2]
boringssl_session_handshake_incomplete(191) [C3.1:2][0x106347c90] Early handshake return caused by SSL_ERROR_WANT_READ [2]
boringssl_session_handshake_incomplete(191) [C3.1:2][0x106347c90] Early handshake return caused by SSL_ERROR_WANT_READ [2]
boringssl_session_handshake_incomplete(191) [C3.1:2][0x106347c90] Early handshake return caused by SSL_ERROR_WANT_READ [2]
boringssl_session_handshake_incomplete(191) [C3.1:2][0x106347c90] Early handshake return caused by SSL_ERROR_WANT_READ [2]
boringssl_session_handshake_incomplete(191) [C3.1:2][0x106347c90] Early handshake return caused by SSL_ERROR_WANT_READ [2]
boringssl_context_message_handler(2257) [C3.1:2][0x106347c90] Reading SSL3_RT_HANDSHAKE 93 bytes
boringssl_context_info_handler(1982) [C3.1:2][0x106347c90] Client handshake state: TLS client read_server_certificate
boringssl_context_add_handshake_message_pending(577) [C3.1:2][0x106347c90] Adding message(2)
boringssl_session_handshake_incomplete(191) [C3.1:2][0x106347c90] Early handshake return caused by SSL_ERROR_WANT_READ [2]
boringssl_session_handshake_incomplete(191) [C3.1:2][0x106347c90] Early handshake return caused by SSL_ERROR_WANT_READ [2]
boringssl_session_handshake_incomplete(191) [C3.1:2][0x106347c90] Early handshake return caused by SSL_ERROR_WANT_READ [2]
boringssl_context_message_handler(2257) [C3.1:2][0x106347c90] Reading SSL3_RT_HANDSHAKE 6525 bytes
boringssl_context_info_handler(1982) [C3.1:2][0x106347c90] Client handshake state: TLS client read_certificate_status
boringssl_context_info_handler(1982) [C3.1:2][0x106347c90] Client handshake state: TLS client verify_server_certificate
boringssl_context_copy_peer_sct_list(1002) [C3.1:2][0x106347c90] SSL_get0_signed_cert_timestamp_list returned no SCT extension data
boringssl_helper_create_sec_trust_with_certificates(607) [C3.1:2][0x106347c90] SecTrustCreateWithCertificates result: 0
boringssl_helper_create_sec_trust_with_certificates(614) [C3.1:2][0x106347c90] No TLS-provided OCSP response
boringssl_helper_create_sec_trust_with_certificates(621) [C3.1:2][0x106347c90] No TLS-provided SCTs
boringssl_context_certificate_verify_callback(2070) [C3.1:2][0x106347c90] Asyncing for verify block
boringssl_session_handshake_incomplete(191) [C3.1:2][0x106347c90] Early handshake return caused by SSL_ERROR_WANT_CERTIFICATE_VERIFY [16]
Connection 3: asked to evaluate TLS Trust
Task <F76287E4-54D1-448A-9ADB-F099B38EE490>.<3> auth completion disp=1 cred=0x0
Connection 3: TLS Trust result 0
boringssl_context_certificate_verify_callback_block_invoke_3(2079) [C3.1:2][0x106347c90] Returning from verify block
boringssl_context_certificate_verify_callback(2046) [C3.1:2][0x106347c90] Setting trust result to ssl_verify_ok
boringssl_context_info_handler(1982) [C3.1:2][0x106347c90] Client handshake state: TLS client read_server_key_exchange
boringssl_context_message_handler(2257) [C3.1:2][0x106347c90] Reading SSL3_RT_HANDSHAKE 333 bytes
boringssl_context_info_handler(1982) [C3.1:2][0x106347c90] Client handshake state: TLS client read_certificate_request
boringssl_context_message_handler(2257) [C3.1:2][0x106347c90] Reading SSL3_RT_HANDSHAKE 4 bytes
boringssl_context_info_handler(1982) [C3.1:2][0x106347c90] Client handshake state: TLS client read_server_hello_done
boringssl_context_info_handler(1982) [C3.1:2][0x106347c90] Client handshake state: TLS client send_client_certificate
boringssl_context_add_handshake_message_pending(577) [C3.1:2][0x106347c90] Adding message(14)
boringssl_context_info_handler(1982) [C3.1:2][0x106347c90] Client handshake state: TLS client send_client_key_exchange
boringssl_context_message_handler(2257) [C3.1:2][0x106347c90] Writing SSL3_RT_HANDSHAKE 70 bytes
boringssl_context_info_handler(1982) [C3.1:2][0x106347c90] Client handshake state: TLS client send_client_certificate_verify
boringssl_context_info_handler(1982) [C3.1:2][0x106347c90] Client handshake state: TLS client send_client_finished
boringssl_context_message_handler(2257) [C3.1:2][0x106347c90] Writing SSL3_RT_CHANGE_CIPHER_SPEC 1 bytes
boringssl_context_message_handler(2257) [C3.1:2][0x106347c90] Writing SSL3_RT_HANDSHAKE 16 bytes
boringssl_context_info_handler(1982) [C3.1:2][0x106347c90] Client handshake state: TLS client finish_flight
boringssl_context_info_handler(1982) [C3.1:2][0x106347c90] Client handshake state: TLS client read_session_ticket
boringssl_context_info_handler(1982) [C3.1:2][0x106347c90] Client handshake state: TLS client process_change_cipher_spec
boringssl_session_handshake_incomplete(191) [C3.1:2][0x106347c90] Early handshake return caused by SSL_ERROR_WANT_READ [2]
boringssl_session_handshake_incomplete(191) [C3.1:2][0x106347c90] Early handshake return caused by SSL_ERROR_WANT_READ [2]
```

package.json 

```JSON
"nativescript": {
        "id": "xxxxxxxxxxyyyyyyyy",
        "tns-android": {
            "version": "6.0.0"
        },
        "tns-ios": {
            "version": "6.3.0"
        }
    },
    "version": "0.0.0",
    "private": true,
    "dependencies": {
        "@angular/animations": "8.0.0",
        "@angular/cdk": "^7.3.7",
        "@angular/common": "8.0.0",
        "@angular/compiler": "8.0.0",
        "@angular/core": "8.0.0",
        "@angular/forms": "8.0.0",
        "@angular/platform-browser": "8.0.0",
        "@angular/platform-browser-dynamic": "8.0.0",
        "@angular/router": "8.0.0",
        "@fortawesome/angular-fontawesome": "^0.3.0",
        "@fortawesome/fontawesome-svg-core": "^1.2.24",
        "@fortawesome/free-solid-svg-icons": "^5.11.1",
        "@nstudio/nativescript-checkbox": "^1.0.0",
        "classlist.js": "^1.1.20150312",
        "core-js": "^2.6.9",
        "nativescript-accordion": "^6.0.0-beta.2",
        "nativescript-angular": "8.0.2",
        "nativescript-checkbox": "^3.0.3",
        "nativescript-fancyalert": "^3.0.6",
        "nativescript-iqkeyboardmanager": "^1.5.1",
        "nativescript-loading-indicator": "^2.4.0",
        "nativescript-theme-core": "~1.0.4",
        "nativescript-ui-autocomplete": "6.0.0",
        "nativescript-ui-listview": "8.0.1",
        "nativescript-ui-sidedrawer": "8.0.0",
        "nativescript-web-image-cache": "^5.0.0",
        "ngx-loading": "^3.0.1",
        "primeflex": "^1.0.0-rc.1",
        "primeicons": "^1.0.0",
        "primeng": "^7.1.0",
        "reflect-metadata": "~0.1.8",
        "rxjs": "^6.5.3",
        "rxjs-compat": "^6.5.3",
        "tns-core-modules": "6.0.1",
        "web-animations-js": "^2.3.2",
        "zone.js": "0.9.1"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "0.12.4",
        "@angular/cli": "^7.0.0",
        "@angular/compiler-cli": "8.0.0",
        "@nativescript/schematics": "~0.3.0",
        "@types/jasmine": "2.8.11",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "~8.9.4",
        "codelyzer": "~4.2.1",
        "jasmine-core": "~2.99.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~1.7.1",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.0",
        "karma-jasmine": "~1.1.1",
        "karma-jasmine-html-reporter": "^0.2.2",
        "nativescript-dev-webpack": "^1.4.0",
        "node-sass": "4.12.0",
        "protractor": "~5.3.0",
        "ts-node": "~5.0.1",
        "tslint": "~5.9.1",
        "typescript": "3.4.5",
        "webpack": "^4.41.5",
        "webpack-cli": "^3.3.10",
        "webpack-dev-server": "^3.8.1"
    },
    "hooks": [{
        "type": "before-livesync",
        "script": "before-livesync.js"
    }]
}
```

**Comment by rosen-vladimirov** [comment] 2020-01-27 07:38
Hey @udugama ,
Can you clarify when this error happens - is it at runtime of your application, when you try to login?

**Comment by udugama** [comment] 2020-01-28 01:46
happening on a login interface as soon as I enter user credentials and press log in it breaks and keep displaying the loading image .. and above log was the output.

**Comment by rosen-vladimirov** [comment] 2020-01-28 07:22
Hey @udugama,
It looks like there's a problem with one of your certificates, I'm not sure which one.
You can find similar issue reported here: https://stackoverflow.com/questions/58011737/ios-13-tls-issue

It seems the problem is not related to NativeScript CLI, so I'm closing this thread.

**Closed by rosen-vladimirov** 2020-01-28 07:22 UTC
Labels: needs more info
