### ISSUE TITLE
Migrating to NativeScript 6.0 - Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by sputn1k** [NativeScript/nativescript-cli#5059] opened 2019-10-08 11:57 UTC
After I migrate my project to cli 6 `tns migrate` update cocoapods/brew/node/everything.. 

`tns run ios`

```
Webpack build done!
Project successfully prepared (ios)
Cannot read property 'toLowerCase' of undefined
```

The app was compiling and running fine before I upgraded to v6?

**Comment by Fatme** [comment] 2019-10-08 13:06
@sputn1k,

Try the following: 
```
rm -rf node_modules hooks platforms && tns run ios
```

**Comment by sputn1k** [comment] 2019-10-09 09:01
> @sputn1k,
> 
> Try the following:
> 
> ```
> rm -rf node_modules hooks platforms && tns run ios
> ```

Thanks I will try that out now, cheers

**Comment by sputn1k** [comment] 2019-10-09 09:11
@Fatme , Still says the same thing - **Cannot read property 'toLowerCase' of undefined**

```
Generating Pods project
Integrating client project
[!] Please close any current Xcode sessions and use `ProjectName.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 8 dependencies from the Podfile and 11 total pods installed.
Project successfully prepared (ios)
Cannot read property 'toLowerCase' of undefined
```

**Comment by Fatme** [comment] 2019-10-09 11:55
@sputn1k,

Can you execute the command with `--log trace`  (`tns run ios --log trace`) and send us the produced log ?

**Comment by vasudevan24** [comment] 2019-10-17 10:20
Android also having the same issue. i ran with tns run android --log trace

Cannot read property 'toLowerCase' of undefined
Error: Cannot read property 'toLowerCase' of undefined
    at Errors.failWithOptions (C:\Users\<n>\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:147:28)
    at Errors.fail (C:\Users\<n>\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:120:21)
    at DevicesService.<anonymous> (C:\Users\<n>\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\mobile-core\devices-service.js:376:30)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\<n>\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\mobile-core\devices-service.js:11:65)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

**Comment by Oscarato** [comment] 2019-10-18 20:45
I resolved this looking for in ./hooks folder. I found hookArgs.platform.toLowerCase() and I had to change to (hookArgs.platform || '').toLowerCase();

**Comment by rosen-vladimirov** [comment] 2020-02-19 16:42
This issue is probably caused by plugin hooks which are not compatible with NativeScript 6.0.0.  @Oscarato fix is what should be applied in the plugin itself.
As there's nothing to do in the CLI, I'm closing this issue.

**Closed by rosen-vladimirov** 2020-02-19 16:42 UTC
Labels: needs more info
