### ISSUE TITLE
Cannot uninstall CLI

### ISSUE THREAD

**Issue by tonyhogben** [NativeScript/nativescript-cli#5215] opened 2020-01-14 15:58 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.1

**Describe the bug**
I installed Sidekick and received a message saying I needed to update the CLI. I did this but still received the message. 

Running tns info showed I had 5.1.1 even though the installation displayed 6.3.3. I removed nativescript and tns info still shows 5.1.1 as installed. 

`npm list -g` shows no mention of nativescript

How do I find out where nativescript is still installed and how do I remove it so I can re-install?

**Comment by rosen-vladimirov** [comment] 2020-01-14 16:13
Hey @tonyhogben ,
You can try `which tns` in the command line in case you work on Linux or macOS. For windows you can use `where tns`.
These commands will show you where your NativeScript CLI executable is located. After figuring it out, you can remove the instance of the CLI and install the new version.

**Comment by tonyhogben** [comment] 2020-01-15 09:56
Thanks @rosen-vladimirov. I'm working in macOS. 

Can you tell me, do I just delete the executable in Finder or do I need to run a command in Terminal?

**Comment by rosen-vladimirov** [comment] 2020-01-21 10:29
Hey @tonyhogben ,
After deleting the executable, you can run `hash -d tns` to clean the reference in your terminal and try `which tns` again.
Also you probably have the full package installed in `/usr/local/lib/node_modules/nativescript` - you can delete it as well.

**Comment by rosen-vladimirov** [comment] 2020-02-19 06:58
Hey @tonyhogben ,
I'm closing this thread as I assume the problem is resolved now. Feel free to reopen it in case you still have problems with uninstalling CLI.

**Closed by rosen-vladimirov** 2020-02-19 06:58 UTC
