### ISSUE TITLE
tns create stuck at loadDep:tns-core-modules

### ISSUE THREAD

**Issue by kokizzu** [NativeScript/nativescript-cli#4835] opened 2019-07-11 08:55 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4.2
 - Cross-platform modules: ?
 - Android Runtime: 5.4.0
 - iOS Runtime: 5.4.2
 - Plugin(s):
```
  "dependencies": {
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-sidedrawer": "~6.0.0",
    "rxjs": "~6.5.0",
    "tns-core-modules": "~5.4.0"
  },
  "devDependencies": {
    "eslint": "~5.8.0",
    "nativescript-dev-sass": "~1.7.0",
    "nativescript-dev-webpack": "~0.24.0"
  },
  "gitHead": "8c1a4866a66daab09bf5ef8e5a96472687192373",
```

**Describe the bug**
running command `tns create foo` stuck at loadDep:tns-core-modules, the progress bar still cycling but it's been 2 hours now.
running `tns info` also stuck at the same progress bar.
```
$ tns create foo
Do you want to help us improve NativeScript by automatically sending anonymous usage statistics? We will not use this information to identify or contact you. You can read our official Privacy Policy at
? http://www.telerik.com/company/privacy-policy Yes

# Let’s create a NativeScript app!

Answer the following questions to help us build the right app for you. (Note: you
can skip this prompt next time using the --template option, or the --ng, --vue, --ts,
or --js flags.)

? First, which style of NativeScript project would you like to use: Plain JavaScript

? Next, which template would you like to start from: SideDrawer

loadDep:tns-core-modules  ▌ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
```

**To Reproduce**
running command `tns create foo`

**Expected behavior**
not stuck

**Sample project**

**Additional context**
Ubuntu 18.04.2 Linux Amd64

**Comment by kokizzu** [comment] 2019-07-12 16:54
Retrying today, stuck at idk what is this '__')

```
loadDep:parse-asn1 -> netw
```

previously stuck at:

```
loadDep:webpack-sources
```

**Comment by kokizzu** [comment] 2019-07-12 17:08
wait, it's works now '__')
after i change to typescript, then back to javascript

**Comment by rosen-vladimirov** [comment] 2019-07-15 07:29
Hey @kokizzu ,
It looks like there was some problem with downloading dependencies on your side. This could be caused by slow network connection, misconfiguration of a proxy or locked directories. 
As the issue seems resolved now, I'm closing this thread. Feel free to reopen it in case you still face the same problem.

**Closed by rosen-vladimirov** 2019-07-15 07:29 UTC
