### ISSUE TITLE
White screen during LiveSync

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#3125] opened 2017-09-14 14:37 UTC
_From @jogboms on September 11, 2017 10:7_

Since I upgraded to v3.2.0 I get a blank White screen without errors during LiveSync. I think it has something to do with the resumeActivity. Haven't tested if this is reproducible on iOS but the occurs on Android.

`nativescript  3.2.0`
`tns-core-modules  3.2.0`
`tns-android  3.2.0`
`tns-ios  3.2.0`

Dependencies below.

```
  "dependencies": {
    "@angular/animations": "^4.2.6",
    "@angular/common": "^4.2.6",
    "@angular/compiler": "^4.2.6",
    "@angular/core": "^4.2.6",
    "@angular/forms": "^4.2.6",
    "@angular/http": "^4.2.6",
    "@angular/platform-browser": "^4.2.6",
    "@angular/router": "^4.2.6",
    "nativescript-angular": "^4.3.0-2017-8-10-8",
    "nativescript-animate-sass": "0.0.2",
    "nativescript-carousel": "^3.1.0",
    "nativescript-geolocation": "^3.0.0",
    "nativescript-google-maps-sdk": "^2.3.2",
    "nativescript-gradient": "^2.0.1",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-permissions": "^1.2.3",
    "nativescript-phone": "^1.3.1",
    "nativescript-push-notifications": "^0.1.4",
    "nativescript-ripple": "^2.0.0",
    "nativescript-social-login": "^1.7.1",
    "nativescript-telerik-ui": "3.0.4",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toast": "^1.4.6",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^5.4.3",
    "tns-core-modules": "^3.2.0",
    "zone.js": "^0.8.2"
  }
```

_Copied from original issue: NativeScript/NativeScript#4829_

**Comment by NickIliev** [comment] 2017-09-14 14:37
_From @sserdyuk on September 11, 2017 13:12_

I'd like to second that. I've been using 3.2 for a few days already, and livesync is less reliable that it was before. The symptom is the same: white screen upon change of view XML of an internal page view. It happens pretty reliably.

**Comment by NickIliev** [comment] 2017-09-28 10:34
@sserdyuk are you still experiencing this with NativeScript 3.2.1 ?

**Comment by jogboms** [comment] 2017-09-29 04:55
@NickIliev I still do on 3.2.1

**Comment by NickIliev** [comment] 2017-09-29 10:36
@jogboms if possible please provide sample project so I could investigate the issue locally.

**Comment by jogboms** [comment] 2017-10-01 10:09
@NickIliev I just confirmed its one of the plugins causing this. Haven't figured out which but the push-plugin is being suspected. You could close this for now until further investigations.

**Closed** 2017-10-02 08:41 UTC

**Comment by whoozle** [comment] 2018-01-13 12:22
I have clean native script installation (basically following your hello world setup), but seldom see anything both in emulator or device. it's just white screen, sometimes ui flashes with new content before exception dialog. Maybe it's something with UI updates propagation up to the native ui.

**Comment by whoozle** [comment] 2018-01-13 12:32
I figured out what triggers it, when you have top-level AbsoluteLayout, and manually set its width to page.getMeasuredSize() from navigated event

**Comment by abdullahkhalidmahmood** [comment] 2020-10-28 13:10
The issue is with [HMR](https://github.com/NativeScript/nativescript-angular/issues/2243) , for now you can use `ns run ios --no-hmr`
