### ISSUE TITLE
livesync confused by temporary editor files

### ISSUE THREAD

**Issue by brianmay** [NativeScript/nativescript-cli#2488] opened 2017-02-04 02:16 UTC
In Linux:

```
tns livesync android --emulator --watch
```

make changes with vim, emacs, etc, gives the following error in livesync:

```
Unable to sync files. Error is: ENOENT: no such file or directory, stat '/home/brian/tree/sample-Groceries/platforms/android/src/main/assets/app/login/login.component.html.bak'
```

It appears to notice the bak file while the editor is saving, and then gets upset when that file gets deleted after the editor has finished the save process. There is no need to even look at the *.bak files.

**Comment by ludwiktrammer** [comment] 2017-02-06 09:16
The same thing happens with .scss files - here is the relevant bug in the `nativescript-dev-sass` bugtracker:

https://github.com/toddanglin/nativescript-dev-sass/issues/18

**Comment by Plamen5kov** [comment] 2017-02-08 13:20
I'm closing this issue because it's a duplicate of https://github.com/NativeScript/nativescript-cli/issues/2476. Please follot and comment in there.

**Closed by Plamen5kov** 2017-02-08 13:20 UTC
