### ISSUE TITLE
Add analitycs for command options

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/nativescript-cli#2830] opened 2017-05-22 07:59 UTC
We should be able to track not only commands but also options used with them. This can help us define which flags are not used anymore and give us the opportunity to select and develop only the useful ones.

**Comment by rosen-vladimirov** [comment] 2019-05-22 19:35
Duplicate of https://github.com/NativeScript/nativescript-cli/issues/4211

**Closed by rosen-vladimirov** 2019-05-22 19:35 UTC
Labels: feature
