### ISSUE TITLE
'tns run android' does not sync after launch but shows 'Compilation complete'

### ISSUE THREAD

**Issue by pako8x** [NativeScript/nativescript-cli#3124] opened 2017-09-14 11:14 UTC
I was looking for open issues that deal with this problem but did not find anything. So I guess it's my configuration problem and I do not think it's reproducible easly.... anyway:

when I launch `tns run android --watch` the application starts normally, when I edit and save any file the console shows the following messages

> 12:59:33 - File change detected. Starting incremental compilation...
> 
> 12:59:35 - Compilation complete. Watching for file changes.

but nothing happens to the application, and this happens to every change. To apply the changes to the emulator, I must restart the app.

My OS is windows 10 and the the problem occurs with any applications tested (also latest versions of **SampleGroceries** or **lazyNinjas**)

**Comment by pkoleva** [comment] 2017-09-14 12:16
Hi @pako8x,

`--watch` flag is no longer necessary to sync changes, `run` does that by default. We changed that a couple of releases ago. You can check the documentation for more info or just run `tns run android --help` to see what run does and what flags you can use with the latest CLI.

Hope this helps!

**Comment by pako8x** [comment] 2017-09-14 12:28
@pkoleva thanks for the fast reply but no, It is exactly the same....

**Comment by NickIliev** [comment] 2017-09-28 10:29
@pako8x 

Can you try by creating a brand new project and apply some changes while the command `tns run android` is executed. Also do let us know in which file you are making changes (CSS, HTML or TS).

**Comment by pako8x** [comment] 2017-09-28 11:05
@NickIliev 
I understand what you want to do, but as I said it happens with any project, including SampleGroceries and other template projects, modifying everything inside them. By the way, I have a guest VM with MacOS that I use to compile and emulate iOS and it works perfectly with the same projects, previously changed and committed to github by the host machine that has this problem. 

I do not think it's an application-level issue, but more likely at configuration level. Could it be a problem with the setup of Android or TNS?

If so, what would be the best practices for a clean installation of everything (removing old files)?

Thank you

**Comment by NickIliev** [comment] 2017-10-03 13:50
The issue is reproducible on some Windows environment.
Reported via templates team
Steps to reproduce:
```
tns create MDF --template https://github.com/NativeScript/template-master-detail-ng 
tns run android
// make a change in some of the HTML or SCSS files
```

**Comment by pako8x** [comment] 2017-10-03 16:38
@NickIliev It seems to me that this is not my issue.
Here my result: http://www.screencast.com/t/rz8YewaQk8

**Comment by NickIliev** [comment] 2017-10-04 11:58
@pako8x the hard part is that neither your case or the case above (reported by another user) is reproducible on our side - we are currently investigating and trying to find a stable way to reproduce the problem.

**Comment by pako8x** [comment] 2017-10-04 12:58
@NickIliev Sure... Thanks for your support!!

**Comment by solracph** [comment] 2017-11-09 16:06
I'm in the same situation 
OS is windows 10
tns --version 3.3.0 

target device (1+1) android version  6.0.1
and emulator with android version 8

**Comment by Fatme** [comment] 2018-04-12 07:11
Hi @pako8x, @solracph,

Have you managed to resolve the problem?

In case you're not, can you please update to latest NativeScript and try it on your side?
```
npm i -g nativescript@latest
```

**Comment by maik-becker** [comment] 2018-06-15 15:07
I have had the exact same problem the past weeks. For some reason, what seems to be helping - at least for me - is to run `adb logcat` on a seperate console window.

**Comment by kamok** [comment] 2018-09-11 20:48
I just did `tns platform remove android && tns platform add android` and now I can run `tns run android --device <MYDEVICEID>`

**Comment by NickIliev** [comment] 2018-10-12 12:13
Closing as the issue seems not to be reproducible with the `next` and `latest` CLI. Please if anyone has a stable way to reproduce the issue - let me know and I will reopen this one immediately!

**Closed** 2018-10-12 12:12 UTC
Labels: bug, needs more info, os: windows
