### ISSUE TITLE
Require is not defined when running tests

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2765] opened 2017-05-04 12:39 UTC
_From @rowandh on April 27, 2017 12:21_

Follow the tutorial here to set up a project with unit testing: http://developer.telerik.com/products/nativescript/adding-unit-tests-to-your-nativescript-app/

```
tns create MyAwesomeApp 
tns test init --framework qunit
npm install qunitjs
npm test android
```

Results in this message:

```
Successfully synced application org.nativescript.Helloworld on device emulator-5554.

JS: NSUTR: require script /base/app/tests/example.js?5d3f78c074ff4fc0cfc7481eca65c77a40c8a8c8 from ../../tests/example.js
JS: NSUTR: beginning test run
Chrome 57.0.2987 (Windows 10 0.0.0) ERROR
  Uncaught ReferenceError: require is not defined
  at app/app.js:7

```

Example.js

```
// require the view model to expose the functionality inside it
var mainViewModel = require("../main-view-model");

QUnit.test("Hello World Sample Test:", function (assert) {
    //Assert that the counter equals 42.        
    assert.equal( mainViewModel.mainViewModel.counter, 42, "Counter, 42; equal succeeds." );

    //Assert that the message is "42 taps left".
    assert.equal( mainViewModel.mainViewModel.message, "42 taps left", "Message, 42 taps left; equal succeeds." );
});
```

_Copied from original issue: NativeScript/nativescript-unit-test-runner#24_

**Comment by DanielHargesheimer** [comment] 2018-04-26 13:25
What's the status of this issue?

**Comment by miroslavaivanova** [comment] 2019-03-29 15:34
Closing the issue since it is not longer reproducible.

**Closed by miroslavaivanova** 2019-03-29 15:34 UTC
Labels: bug, unit testing

**Comment by colby2** [comment] 2019-05-23 16:21
How is this no longer reproducible? I can reproduce this right now

`23 05 2019 11:21:14.999:INFO [Chrome 74.0.3729 (Windows 10.0.0)]: Connected on socket 3hkVTpM0vAWi3aZ9AAAA with id manual-4681
Chrome 74.0.3729 (Windows 10.0.0) ERROR
  An error was thrown in afterAll
  ReferenceError: require is not defined
      at src/tests/time-capture.component.js:1:15`
