### ISSUE TITLE
Error tns publish ios

### ISSUE THREAD

**Issue by DevZatokio** [NativeScript/nativescript-cli#5562] opened 2021-08-13 17:33 UTC
**Environment**
{
  "nativescript": {
    "id": "XXXX",
    "tns-android": {
      "version": "6.5.0"
    },
    "tns-ios": {
      "version": "6.5.4"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"src/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nstudio/nativescript-camera-plus": "^3.3.0",
    "fi-rut": "^1.3.1",
    "nativescript-angular": "^8.20.3",
    "nativescript-appversion": "^1.4.2",
    "nativescript-background-http": "^4.2.0",
    "nativescript-bitmap-factory": "^1.8.1",
    "nativescript-camera": "^4.5.0",
    "nativescript-contacts": "^1.6.2",
    "nativescript-drop-down": "^5.0.4",
    "nativescript-fresco": "^5.3.0",
    "nativescript-geolocation": "5.1.0",
    "nativescript-google-maps-sdk": "^2.9.1",
    "nativescript-google-maps-utils": "^0.1.3",
    "nativescript-google-places-autocomplete": "^1.0.3",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-localize": "^4.2.0",
    "nativescript-localstorage": "^2.0.1",
    "nativescript-mediafilepicker": "^2.0.17",
    "nativescript-plugin-firebase": "10.6.3",
    "nativescript-share-file": "^1.0.6",
    "nativescript-social-share": "^1.5.2",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-tooltip": "^2.1.2",
    "nativescript-ui-listview": "8.0.1",
    "nativescript-ui-sidedrawer": "~8.0.0",
    "nativescript-videoplayer": "^4.2.1",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "^6.5.27",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "codelyzer": "~4.5.0",
    "nativescript-dev-webpack": "^1.4.0",
    "node-sass": "^4.7.1",
    "tns-android": "6.5.0",
    "tns-ios": "6.5.4",
    "tns-platform-declarations": "^6.1.2",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3"
  },
  "gitHead": "e9af7b54b243e55ef28e4610c4ef8c83837d86c0",
  "readme": "NativeScript Application"
}

At the time of publishing it sends me an error: tns publish ios --ipa

httpRequest: Sending:
{"contentProviderId":123203951,"dsId":"20205677719","ipAddress":null}
httpRequest: Done. code = 404
Request was unsuccessful. Server returned:  
Failed to get error from http request:  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at HttpClient.getErrorMessage (/usr/local/lib/node_modules/nativescript/lib/common/http-client.js:254:34)
    at IncomingMessage.responseStream.on (/usr/local/lib/node_modules/nativescript/lib/common/http-client.js:195:59)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Error: The server returned unexpected response: 
    at IncomingMessage.responseStream.on (/usr/local/lib/node_modules/nativescript/lib/common/http-client.js:196:45)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by rigor789** [comment] 2021-08-13 18:01
Duplicate of #5553

**Closed by rigor789** 2021-08-13 18:01 UTC
