### ISSUE TITLE
Nativescript 1.6.1 - tns livesync exits with an error on both ios and android platforms

### ISSUE THREAD

**Issue by dskaggs** [NativeScript/nativescript-cli#1554] opened 2016-03-01 03:36 UTC
Since upgrading to v1.6.1, I cannot run livesync successfully.  Running either of the commands below causes an exception (see attached error report). The app is loaded onto the specified emulator once then livesync exits and fails to update changes. 

`tns livesync ios --emulator --watch`
`tns livesync android --geny 1 --watch`

I created a completely new project from the typescript template after upgrading to v1.6.1.  

The attached error report was generated with 'tns livesync ios --emulator --watch --log trace'. I replaced the name of the project with '/projectName/' in the directory path. The original name matches the last part of the nativescript.id property in package.json.
[livesync-error-report.txt](https://github.com/NativeScript/nativescript-cli/files/152108/livesync-error-report.txt)

**Comment by rosen-vladimirov** [comment] 2016-03-01 06:25
Hi @dskaggs 

Thanks for the provided log. Based on it, it looks like TypeScript's compiler is failing. Can you try executing the following command in your project:
```
$ <project_dir>/node_modules/.bin/tsc --watch
```

**Comment by dskaggs** [comment] 2016-03-01 10:45
The result of that command gives the same error as was seen in the end of the log I posted.

tsc -v reports version 1.8.2

Thanks,
Dan

**Comment by rosen-vladimirov** [comment] 2016-03-01 12:27
@dskaggs I'm not sure what is causing TypeScript compiler issue. Can you try the following workflow and see if it works:
```
$ tns create app1 --template tsc
$ cd app1
$ tns run android --justlaunch
$ tns livesync android --watch
```
Maybe the issue is in your TypeScript code or the name of the project (for example if it has spaces, special symbols, etc)
Anyway the above steps should work.

**Comment by dskaggs** [comment] 2016-03-01 14:00
Thanks for the reply. My project name (both the directory name and the last section of nativescript.id property in /package.json) is two words, camel-cased (like projectName).

I completed those 4 steps and got the same error as before (livesync log attached). 

I had originally built my project with the following command based on a blog post last week from @tjvantoll (https://www.tjvantoll.com/2016/02/22/creating-nativescript-templates/):

`tns create projectName --template tns-template-hello-world-ts`

I thought maybe that was the issue but after having just created a brand new app, and trying the above steps, maybe that's not the issue after all.

[livesync-error-new-project.txt](https://github.com/NativeScript/nativescript-cli/files/152890/livesync-error-new-project.txt)

**Comment by rosen-vladimirov** [comment] 2016-03-01 15:11
@dskaggs  the syntax:
```
tns create projectName --template tns-template-hello-world-ts
```
is exactly the same as:
```
tns create projectName --tsc
```
We've added a short option when you want to use TypeScript :) 

Anyway it looks like there's a problem with the file watcher that TypeScript is using. One thing that comes to my mind is to check if you are working on a mounted drive and what's the file system that's being used.
You can try executing:
```
 <project_dir>/node_modules/.bin/tsc
```
Just to verify the issue is only with the watcher, not with the compiler. I advise you to open issue in TypeScript repo: https://github.com/Microsoft/TypeScript

**Comment by dskaggs** [comment] 2016-03-01 15:25
Thanks for your help. Running tsc directly produces no errors.

I downgraded to TypeScript v1.7.5 and confirmed that the livesync behavior works correctly with both Genymotion and iOS emulators.

**Comment by rosen-vladimirov** [comment] 2016-03-07 06:45
@dskaggs as we are unable to provide a fix for the TypeScript compiler, I'm closing this issue.

Feel free to contact us in case you have any other problems or concerns.

**Closed by rosen-vladimirov** 2016-03-07 06:45 UTC
Labels: external, livesync, TypeScript
