### ISSUE TITLE
EISDIR when using npm-link approach on Windows

### ISSUE THREAD

**Issue by mkosieradzki** [NativeScript/nativescript-cli#1436] opened 2016-01-30 12:40 UTC
I am using a scoped npm module for my nativescript project. If I use a standard packaged approach everything works as expected.
 If I use npm-link to improve development workflow and execute: "tns run android":
 I get:
 Error: EISDIR: illegal operation on a directory, read
 at Error (native)

Just after processing hooks (typescript/babel) also happens when hooks are disabled.
 tns version 1.5.2

**Comment by dtopuzov** [comment] 2016-06-07 06:35
@mkosieradzki can you please verify if this issue is still valid. If you still experience the problem please provide exact steps to reproduce.

**Comment by enchev** [comment] 2016-06-10 14:47
Hey @mkosieradzki,

I'm closing this issue since we cannot reproduce it locally. If you still have problems please post more info/steps how to reproduce it.

**Closed by enchev** 2016-06-10 14:47 UTC
