### ISSUE TITLE
Help, App runs in Xcode and CLI but not on test flight

### ISSUE THREAD

**Issue by victorhugom** [NativeScript/nativescript-cli#2302] opened 2016-12-02 13:35 UTC
I have an app running in nativescript for a few months, I deployed a free versions to the app store, but since the last xcode update I can't make it run on test flight anymore.

The app runs fine on the emulator and the device when I deploying via CLI or via Xcode, but the TestFlight submitted version it opens and close without any reason. I already remove some key dependencies requests of the app main screen (Facebook and Location) to see if anything changes, but the error continues.

Sorry to ask for help here, but it's been a week since I'm trying to figure out this error and I have no clue what it is.

**Comment by bradmartin** [comment] 2016-12-05 01:47
Oh my. This is happening to me too. I've spent 5 days trying to find out why :( glad I'm not alone anymore.

**Comment by bradmartin** [comment] 2016-12-05 01:50
I have a prod app with 2.3 uploaded on November 14, I updated my mac on the 16th and then last week updated the app to NS 2.4 and made just a few js changes so I can't figure out what's wrong. I've tried going through the crash logs in xcode but  I have no clue how to do that really :) I've published to iTunes with symbols and then tried downloading the dYms (not sure what that abbreviation is right now) but I can't see any actual errors in xcode just threads on the left side and nothing meaningful elsewhere

**Comment by bradmartin** [comment] 2016-12-05 03:02
My situation is exactly the way described in the issue. I can run in xcode and in simulator with the CLI commands. I successfully uploaded an archive to iTunes for TestFlight testing and the app will launch and crash. It doesn't seem to even start the app and enter the uncaughexception event (I have logs for that and not getting any logs). I have uninstalled xcode and reinstalled, made sure I have the latest xcode command line tools installed. I've played around in xcode so much I am depressed :) any help with this would be awesome. I'm glad I'm not the only one encountering this exact issue now. I'll gladly provide the exported app or anything else that can help someone figure it out.

**Comment by bradmartin** [comment] 2016-12-05 04:50
My system is a MacBook pro 2011 running the latest Mac OS (not at comp now but maybe 10.12), whichever gave us Siri :) and latest xcode and latest NS everything. Just for some system details

**Comment by valentinstoychev** [comment] 2016-12-05 07:25
We are using TestFlight for our public apps with 2.4, so there should be something specific here. @bradmartin can you share the app maybe?

**Comment by bradmartin** [comment] 2016-12-05 08:30
When the day starts here Im going to try downgrading xcode and see what happens. If that fails then I'll email you an export of the archive or I can send a zip of the application. Whatever works best to investigate. It's really strange, I thought it was just my app or my mac was screwed up but the original user who reported it has the same issue down to the final detail so something funny is going on for sure.

**Comment by bradmartin** [comment] 2016-12-05 20:19
Downgrading xcode to 7.3.1 has no change. I can run the app on connected device in xcode and via CLI to simulator 😢  I'm going to try and downgrade the NS bits to 2.3 and see if this changes anything so we have an idea where to go next. I'll report back with any news. After this last step I really have no clue what to possibly try so I'll be in touch @valentinstoychev with an exported archive and possibly a .zip of the application for you all to take a look on your side. Just FYI - I've exported the archive and opened it up to few the contents and everything looks okay from what I know (which isn't a whole lot on iOS unfortunately 😄 ) so maybe you all will see something.

**Comment by bradmartin** [comment] 2016-12-05 21:51
@victorhugom downgrade everything to 2.3 and it works fine. So 2.4 has something odd happening and not for everyone unfortunately. I'm going to provide the team with an archive that works and one that doesn't, only difference being the NS modules/runtimes

**Comment by bradmartin** [comment] 2016-12-05 22:22
I have a successful archive, upload and run on testflight with NS 2.3 
![snip20161205_3](https://cloud.githubusercontent.com/assets/6006148/20904821/cef355e8-bb06-11e6-9ef8-ccc80033a7b6.png) and built with xcode Version 7.3.1 (7D1014). I'm about to update xcode and try again with 2.3 to confirm it still works. Then I'm going to compare the archives to see if anything is obvious and then send them over to the team.

**Comment by bradmartin** [comment] 2016-12-05 23:21
@tsonevn I've sent the archives to @valentinstoychev via slack. If you all prefer a different way let me know. The folder labeled *NASTC2-4* is with NS 2.4 and the other 2.3. Building with 2.3 and uploading the archive to itunes and running on testflight works every time. Everything I've tried with 2.4 doesn't work. Here is how I've been trying with 2.4 (a few issues encountered).

First, I delete the `lib`, `node_modules`, and `platforms` folder, then run `tns emulate ios` to get the app built and launched on the simulator. At this point I move to Xcode to try and upload to itunes for testing.

- Build the app via CLI
- Open in Xcode
- Build
 -- *ERROR*  https://github.com/NativeScript/nativescript-cli/issues/2158#issuecomment-264971882
- Fix that by setting `PODS_ROOT` = `{SRCROOT}/Pods` in the Build Settings for the project.
- Now Archive in Xcode
- Upload to Itunes (if you notice here the app icon will be missing in the upload dialog)
- The upload will fail due to missing icons 
- Fix the missing icons with this approach https://github.com/NativeScript/nativescript-cli/issues/2319
- Now with the new archive
- Upload to Itunes
- TestFlight updates
- Update the app
- App launches, you see splash screen, and then crashes.

**Comment by vchimev** [comment] 2016-12-06 07:36
@bradmartin, are there any logs from the crashes?

**Comment by bradmartin** [comment] 2016-12-06 12:25
I've tried with 8.1 and 7.3 xcode with same result. I do have crash logs but I'm not sure how to get any valuable information from them in xcode :( I open the log in xcode and on the left menu I see just threads that can be expanded and I select them and nothing shows anywhere else in xcode to see what caused the crash. I tried downloading the dYMs (whatever that acronym is in the organizer) to see if that helps (been reading and saw to download it) but it doesn't let me download anything. I publish with the symbols option enabled which i read is important for inspecting crashes also.

**Comment by bradmartin** [comment] 2016-12-06 12:26
It's the same result regardless of xcode version for me between the two versions I've tried.

**Comment by bradmartin** [comment] 2016-12-06 12:28
I can make a video of my workflow to show the issue and add someone to my TestFlight users if that helps any. Willing to do anything at this point to get past it. I wish I had some exceptions so I could actually fix myself just not sure where to find them in those crash logs in xcode

**Comment by vchimev** [comment] 2016-12-06 13:09
@bradmartin,

could you please send us the app in order to try to publish it from our side, reproduce and examine this problem? A video of your workflow would help as well as if you add me (Vasil.Chimev@telerik.com) to your TestFlight users.

**Comment by victorhugom** [comment] 2016-12-06 13:37
After reading this forum thread https://forums.developer.apple.com/message/52955 I`ve tried a few solutions described in it, and what worked for me was rename the project root project folder.

I don't know why but it just worked, I used to name my folder with [ProjectName].[SubProject], something like, Project.Api, Project.Admin and Project.App. I think the problem was the .App in the folder name, one of the issues with xcode is that you can't have a '+' sign in your project name, I thought that maybe the same problem was occurring with the '.' in the project name, I remove it and the app started to work.

**Comment by bradmartin** [comment] 2016-12-06 14:52
For me unfortunately, my project is just one word so I don't know if that will help me :(

**Comment by bradmartin** [comment] 2016-12-07 15:44
All good - the process I used with 2.3 wasn't the correct process (still worked but not right). Running the correct command `tns build ios --release` fixes all of the issues with a release build and publishing that I've encountered.

**Comment by bradmartin** [comment] 2016-12-07 15:44
Thanks @vchimev @valentinstoychev

**Comment by vchimev** [comment] 2016-12-07 17:32
The NativeScript CLI has a `tns publish ios` command; it is the suggested (and the easiest) way to publish an iOS application to iTunes Connect. We use it internally in the {N} team: as part of our CI builds, as well as to publish our sample apps. 

 Basically, if the *DEVELOPMENT_TEAM* value is specified in *<app>/App_Resources/iOS/build.xcconfig*, the only think that left is to execute `tns publish ios <username> <password>` at the root of the project. The value of *DEVELOPMENT_TEAM* could also be passed to the `--team-id` option of the command.

A link to its documentation could be found [here](https://github.com/NativeScript/nativescript-cli/blob/release/docs/man_pages/publishing/publish-ios.md).

However, if you want to perform additional manipulations over the native project (not suggested), the best option is to use `tns build ios --release` command before going to Xcode.

The reason that `tns emulate ios` used to produce a "good" project for upload to iTunes with 2.3 is that it prepared the native project for both debug and release no matter which flag has been passed. This has been fixed in 2.4 as part of a major performance refactoring of the `tns prepare` command. Therefore the respective flag `--debug` of `--release` should be passed to the commands `prepare`, `build`, `emulate`, `run`, etc.

**Comment by vchimev** [comment] 2016-12-07 17:35
I'm closing this issue as all mentioned problems were resolved.

**Closed by vchimev** 2016-12-07 17:35 UTC
Labels: critical

**Comment by NathanaelA** [comment] 2016-12-07 18:41
@vchimev - I hope that the CLI is smart enough to assume `--debug` if we don't pass a `--release` flag.  99% of the time when I am building I'm wanting to run the debug version.  I don't want to have to now add another flag for the day to day use of `tns`

**Comment by vchimev** [comment] 2016-12-07 18:44
@NathanaelA, this is correct. If no flag is passed, the CLI assumes `--debug`.
