### ISSUE TITLE
there is wrong logs when save the code without changes

### ISSUE THREAD

**Issue by miroslavaivanova** [NativeScript/nativescript-cli#5109] opened 2019-11-01 15:34 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2.0
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
Without any changes when you use CTRL+S, there is sync on bundle.js in console.log for React NativeScript project. 

**To Reproduce**
1. open https://play.nativescript.org and create `ReactNativeScript` app
2. download it and run with `tns preview`
3. open project and save without changes. You will see: `Successfully synced bundle.js for platform ios.`

**Expected behavior**
this logs should miss

**Comment by rosen-vladimirov** [comment] 2019-11-20 08:36
Closing as duplicate of https://github.com/NativeScript/nativescript-dev-webpack/issues/1096

**Closed by rosen-vladimirov** 2019-11-20 08:36 UTC
Labels: bug
