### ISSUE TITLE
Support for Node.js 12.4.0 is not verified. NativeScript CLI might not install or run properly

### ISSUE THREAD

**Issue by Allavudeen** [NativeScript/nativescript-cli#4696] opened 2019-06-09 07:08 UTC
Microsoft Windows [Version 10.0.17134.765]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>node -v
v12.4.0

C:\WINDOWS\system32>npm -version
6.9.0

C:\WINDOWS\system32>tns --version

Support for Node.js 12.4.0 is not verified. NativeScript CLI might not install or run properly.

5.4.0

C:\WINDOWS\system32>

**Comment by rosen-vladimirov** [comment] 2019-06-14 11:24
Hey @Allavudeen ,
The Support for Node.js 12.x.x will be added in our next official release. I'm closing this thread as it is duplicate of https://github.com/NativeScript/nativescript-cli/issues/4650

**Closed by rosen-vladimirov** 2019-06-14 11:24 UTC
