### ISSUE TITLE
TNS 2.5 Installtion of Android 2.5 runtimes

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#2475] opened 2017-02-02 07:21 UTC
I had a very simple 2.4 app that I upgraded to 2.5 and when I did this:
`tns platform remove android` then `tns platform add android@latest` I got the following error:

```
Error: cp: no such file or directory: D:\projects\nativescript\repos\nativescript-print-zebra\demo\node_modules\tns-android\framework\gradle.properties
It's possible, the final .apk file will contain all architectures instead of the ones described in the abiFilters!
You can fix this by using the latest android platform.
```

It doesn't seem to have affected anything; I was able to build the app and run it on my phone, but the error is still a concerning error message.

My package json looks like this:
```
{
  "nativescript": {
    "id": "org.nativescript.demo",
    "tns-android": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "nativescript-dom": "^1.0.8",
    "nativescript-print-zebra": "file:..",
    "tns-core-modules": "^2.5.0"
  },
  "devDependencies": {
    "babel-traverse": "6.22.1",
    "babel-types": "6.22.0",
    "babylon": "6.15.0",
    "lazy": "1.0.11"
  }
}
```

**Comment by Plamen5kov** [comment] 2017-02-07 09:53
Hi @NathanaelA,
In 2.4 template we introduced a `gradle.properties` file which has a single line in it `android.useDeprecatedNdk = true`. This allows splitting and filtering the correct architectures. It's strange that there's no such file on your side, because the 2.4.0 and 2.5.0 templates do have that file.
What I recommend is making sure you have the latest published `tns-android` package containing the native project template.

**Comment by NathanaelA** [comment] 2017-02-07 19:57
I'm seeing this in several projects.   When I do a 
`tns platform add android@2.4.1` and `tns platform add android@2.5.0` -- so if this file is in those platforms shouldn't it be in my project after I do that `tns platform add` of one of those two versions.   Or is this file in the hello world template?

**Comment by Plamen5kov** [comment] 2017-02-09 12:17
@NathanaelA are you using CLI 2.5?

**Comment by NathanaelA** [comment] 2017-02-09 17:35
Yes.  I am using 2.5 cli

**Comment by Plamen5kov** [comment] 2017-02-10 07:43
@NathanaelA the gradle.properties file is in the tns-android @2.4.x and 2.5.x versions, so when you do a ths paltform add android @2.4/5.x you should get the file in platforms/android/gradle.properties.

**Comment by Plamen5kov** [comment] 2017-02-10 12:33
I'll try to reproduce on windows, and keep you posted. Meanwhile, can you do an `npm install tns-android` and check if there is a gradle.properties file in the `<project_name>/node_modules/tns-android/framework/` folder.

**Comment by NathanaelA** [comment] 2017-02-10 18:31
Nope no such file: 
![image](https://cloud.githubusercontent.com/assets/850871/22838913/db676610-ef8c-11e6-84d1-d108bb21a54f.png)

**Comment by NathanaelA** [comment] 2017-02-10 19:28
Ok, I have some very disturbing news and I'm not sure why it happened.   This issue as it is can be closed and a new one needs to be made.     I discovered the reason why this issue occurred, but I don't know the how's.  

As a check I went and checked my npm cache and I had 5 or 6 2.5.0@next versions.  However I noticed the dates were all last year (which made sense) however what surprised me was the date for the 2.5.0 folder was also in the same date range; so I examined the directory and it didn't have the file; nor did a couple of the @next version.      

So just as a test I purged all 2.5.* versions and did another install.   This is where it gets very concerning; the 2.5.0 that it downloaded was DIFFERENT than the 2.5.0 that I had before.     Since I no longer have the old 2.5.0 folders; I went to one of the remaining projects that I installed 2.5 into and it appears that I somehow got a EARLY beta version of 2.5.0 as my official 2.5.0 which then has been used since.       

Unfortunately before I actually figured this out I deleted all the 2.5.x to see if installing again would give me a fresh copy.   The only data I have to work from is a project that I have installed the 2.5.0 runtimes into earlier the week, I hex edited the runtimes and it doesn't have my "-MT" version added to it (so it isn't from my builds).   I honestly have no idea how my `2.5.0` cache came to hold a early beta `2.5.0`

Do you know of any bugs in the TNS / NPM that could have installed 2.5.0@next as "2.5.0"?

**Comment by Plamen5kov** [comment] 2017-02-11 13:54
>Do you know of any bugs in the TNS / NPM that could have installed 2.5.0@next as "2.5.0"?

Not as far as I've seen. The only way for this to happen should be if the package.json file has `next` instead of a version. And the other way is passing `@next` to a command like `tns platform add`.

**Comment by Plamen5kov** [comment] 2017-02-11 13:55
I'm closing this but, if we find reproduce the problem, this issue will be reopened.

**Closed by Plamen5kov** 2017-02-11 13:55 UTC

**Comment by NathanaelA** [comment] 2017-02-11 18:44
@Plamen5kov - Yeah, no reason to leave it open, as the issue was caused by a different thing.
