### ISSUE TITLE
Failed Installation iOS - cp: dest is not a directory (too many sources)

### ISSUE THREAD

**Issue by jwall132** [NativeScript/nativescript-cli#3517] opened 2018-04-04 00:42 UTC
**Tell us about the problem**
Since updating to the latest version of macOS/xcode I have not been able to install and run on iOS. Android works as expected. Below a snippet of the error. 

Successfully installed on device with identifier '9B71C377-5274-4B96-93D0-B51E687E64B1'.
Unable to apply changes on device: 9B71C377-5274-4B96-93D0-B51E687E64B1. Error is: cp: dest is not a directory (too many sources).

**Which platform(s) does your issue occur on?**
iOS

**Please provide the following version numbers that your issue occurs with:**
- CLI: 4.0.0-2018-04-03-11347
- Cross-platform modules: "^4.0.0-2018-04-02-03"
- Runtime(s): 4.0.1-2018-03-26-01

**Comment by dtopuzov** [comment] 2018-04-04 05:35
Hi @jwall132 

Can you please execute `tns run ios --log trace` and provide logs?

**Comment by Fatme** [comment] 2018-04-04 06:32
Hi @jwall132,

Thank you for providing the log file. As I can see you're using iOS simulator 11.3. Can you tell us the exact type of your device (iphone, iPad)? Also can you please try to manually uninstall your app from device and try to execute `tns run ios` again? Is the error still reproduced?

**Comment by jwall132** [comment] 2018-04-04 06:46
Hi @Fatme 

Originally the device was a iPhone X. I have just attempted  a clean install on an iPhone 6 and the some error is produced... I am currently downloading a iOS11.2 emulator and will attempt again :) 

Thank you

**Comment by jwall132** [comment] 2018-04-04 15:26
I have just attempted an install on iOS 11.2 and received the same error. Do you recommend downgrading my macOS?

**Comment by Fatme** [comment] 2018-04-05 05:53
Hi @jwall132,

I've investigated your problem and was not able to reproduce it on my side. Can you please provide us your `package.json` file?

**Comment by Fatme** [comment] 2018-04-05 06:03
Also can you please provide us your `build.xcconfig` and `app.entitlements` files from `app\App_Resources` in case you have such?

**Comment by jwall132** [comment] 2018-04-05 07:17
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.session",
    "tns-android": {
      "version": "4.0.0-2018.3.22.2"
    },
    "tns-ios": {
      "version": "4.0.1-2018-04-03-02"
    }
  },
  "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "base-64": "^0.1.0",
    "moment": "^2.20.1",
    "nativescript-angular": "~5.2.0",
    "nativescript-bitmap-factory": "^1.7.1",
    "nativescript-cardview": "^2.0.5",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-dev-android-snapshot": "0.0.11",
    "nativescript-imagepicker": "^4.0.0",
    "nativescript-modal-datetimepicker": "^1.1.0",
    "nativescript-oauth": "^2.1.2",
    "nativescript-orientation": "^2.2.0",
    "nativescript-platform-css": "^1.6.5",
    "nativescript-pro-ui": "^3.4.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-web-image-cache": "^4.2.4",
    "nativescript-webview-utils": "^2.0.3",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~5.5.5",
    "tns-core-modules": "^4.0.0-2018-04-02-03",
    "tns-platform-declarations": "^3.4.1",
    "utf8": "^3.0.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.2.0",
    "@ngtools/webpack": "~1.9.1",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.3.5",
    "nativescript-dev-typescript": "^0.6.0",
    "nativescript-dev-webpack": "~0.9.1",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "typescript": "~2.6.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }
}

**Comment by jwall132** [comment] 2018-04-05 07:17
// You can add custom settings here
// for example you can uncomment the following line to force distribution code signing
// CODE_SIGN_IDENTITY = iPhone Distribution 
// To build for device with XCode 8 you need to specify your development team. More info: https://developer.apple.com/library/prerelease/content/releasenotes/DeveloperTools/RN-Xcode/Introduction.html
// DEVELOPMENT_TEAM = YOUR_TEAM_ID;
ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME = LaunchImage;

**Comment by Fatme** [comment] 2018-04-05 10:29
Hi @jwall132,

Thank you for providing the files. Actually my first suspicion was the amount of files. I've tested it with all your dependencies from package.json file and it worked on my side.

After some discussions we thing the problem might be that this path `/Users/jackwaller/Code/Session/NativeScript/session/platforms/ios/session/app to /Users/jackwaller/Library/Developer/CoreSimulator/Devices/9B71C377-5274-4B96-93D0-B51E687E64B1/data/Containers/Bundle/Application/4E8B3ACD-4430-44D0-BD6A-877DDABBB39A/Session.app/` actually does not exist.
**Can you please verify this path exists on your mac?**
NOTE: These guids can be different 9B71C377-5274-4B96-93D0-B51E687E64B1, 4E8B3ACD-4430-44D0-BD6A-877DDABBB39A.

When the problem occurs can you please execute `xcrun simctl list devices | grep Booted` and `xcrun simctl get_app_container <device_GUID> org.nativescript.session` commands and send us the output.
NOTE: device_GUID should be the device id returned from `xcrun simctl list devices | grep Booted`.

**Comment by Fatme** [comment] 2018-04-05 12:36
Hi @jwall132,

Based on you output it seems that your application is not installed on simulator with id `9B71C377-5274-4B96-93D0-B51E687E64B1`. Is it possible to have more than one running simulators?

Can you please provide us the output of `xcrun simctl list devices` command?

**Comment by jwall132** [comment] 2018-04-05 12:42
I only have the one simulator running. iPhone X 11.2

== Devices ==
-- iOS 11.2 --
    iPhone 5s (BC73BDB4-2496-4DFE-BD42-DCB9DB990806) (Shutdown)
    iPhone 6 (4D8B1ED5-23FC-488A-AC8E-BF6EC9D3EED5) (Shutdown)
    iPhone 6 Plus (942FB4B3-250D-48AD-ABFF-1B286817B82F) (Shutdown)
    iPhone 6s (115D31DC-6F35-4BBA-A9C2-2999F1EF5325) (Shutdown)
    iPhone 6s Plus (8C039D3E-5BEE-431A-BCE8-E3EF67A6A7AE) (Shutdown)
    iPhone 7 (B6E35CC8-0B8F-438B-9BCB-5633D46C89D4) (Shutdown)
    iPhone 7 Plus (4769DEB4-CD19-485A-BF1F-F56C2F590AE7) (Shutdown)
    iPhone 8 (FE3D0E24-CFC0-4A75-A478-6378CF130FD2) (Shutdown)
    iPhone 8 Plus (89C08087-C448-49CB-BF84-AA75FA9C566C) (Shutdown)
    iPhone SE (72B2D49F-4C1E-4E42-8AB3-460972465276) (Shutdown)
    iPhone X (E21F06DE-D39E-4A09-A285-F510DBCD71A3) (Booted)
    iPad Air (BADAB0CD-E255-42F9-8C2E-AC8AD3F4CB17) (Shutdown)
    iPad Air 2 (171526E5-262E-4690-A830-BC84263902CA) (Shutdown)
    iPad (5th generation) (BDF96608-705D-48E5-B671-66FBDDAE2FC5) (Shutdown)
    iPad Pro (9.7-inch) (562CDFCC-FC7F-4E77-9A18-0F28C5E150DA) (Shutdown)
    iPad Pro (12.9-inch) (EA3147C6-86BC-43DB-BB04-3ED099E5151C) (Shutdown)
    iPad Pro (12.9-inch) (2nd generation) (5A501086-72D5-40A4-B8B3-4068B7F635A2) (Shutdown)
    iPad Pro (10.5-inch) (65304F5E-3E3A-4D0A-A55B-22411343DBC7) (Shutdown)
-- iOS 11.3 --
    iPhone 5s (66CC368C-5F0B-4734-A8E4-8F9B98B22434) (Shutdown)
    iPhone 6 (79112740-3794-480E-BC8F-601359E2BFCF) (Shutdown)
    iPhone 6 Plus (63784AA2-1FC3-4682-9C61-37DB043BD00D) (Shutdown)
    iPhone 6s (9F76A776-556F-44A9-8546-C257F777E943) (Shutdown)
    iPhone 6s Plus (5358611B-D182-41A4-BFBC-284FB4F68689) (Shutdown)
    iPhone 7 (9ED24ED1-213D-486D-801A-7645481627A2) (Shutdown)
    iPhone 7 Plus (5C9DF493-E1AA-4C51-BF3F-B2F25729B62F) (Shutdown)
    iPhone 8 (2021DF86-EFFF-473F-BC01-11190FF11568) (Shutdown)
    iPhone 8 Plus (B6536E54-2521-47C1-81D7-66271C0BA1AA) (Shutdown)
    iPhone SE (95F7E188-171E-40F2-9967-08A23A233B97) (Shutdown)
    iPhone X (9B71C377-5274-4B96-93D0-B51E687E64B1) (Shutdown)
    iPad Air (1ED321EA-32BD-486A-ACA1-23E92DFC96F9) (Shutdown)
    iPad Air 2 (AAED714C-2A56-43DC-A953-871D45A881FA) (Shutdown)
    iPad (5th generation) (A67EE0AC-A699-4EE9-AF4F-C4FBF39E8577) (Shutdown)
    iPad Pro (9.7-inch) (23F8B540-92CE-41FA-B449-FAD08FEF9FFF) (Shutdown)
    iPad Pro (12.9-inch) (A72DD252-AA16-4023-BFDF-7685410C34B5) (Shutdown)
    iPad Pro (12.9-inch) (2nd generation) (CF6843B9-5816-4AEA-833D-69D90F7035F3) (Shutdown)
    iPad Pro (10.5-inch) (3E6C76E3-86DA-469F-8CC3-DF4CCBCE42B9) (Shutdown)
-- tvOS 11.3 --
    Apple TV (41C97115-2FF0-4032-ADE4-EEEE9C33A8FE) (Shutdown)
    Apple TV 4K (2DAD4A2B-C78F-49C6-A236-C2B5DD212FB6) (Shutdown)
    Apple TV 4K (at 1080p) (F54BD887-CCDE-4711-86AC-17F08767DD86) (Shutdown)
-- watchOS 4.3 --
    Apple Watch - 38mm (ADA3915A-4A09-435C-A52C-DA6500F8182F) (Shutdown)
    Apple Watch - 42mm (228AED77-904A-486C-B2F0-08297062BFE9) (Shutdown)
    Apple Watch Series 2 - 38mm (135D934D-482C-43A8-9D47-964A31A21E57) (Shutdown)
    Apple Watch Series 2 - 42mm (F427F0B1-7295-40AB-A828-5F28480C6A45) (Shutdown)
    Apple Watch Series 3 - 38mm (8691C3E1-7459-4D3D-B774-152E9DB98C84) (Shutdown)
    Apple Watch Series 3 - 42mm (9B19B939-5CA7-4887-A098-74B21A7260CD) (Shutdown)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-10-3 --
    iPhone 5 (39F45BD4-6917-4168-9FC7-FFA5C4400D3E) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (5DDEDBCF-DC9A-4B4F-9756-84DDDF72BF6C) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (40F59BEC-0C88-4E07-9547-CBA4CA2107C1) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (CF38FF56-95B3-4F2B-AD34-CAA2B7C9AE9D) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s (F4C45B45-1147-4FC1-9A93-971FED2B0F2C) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s Plus (5D4CB313-9823-4A45-AA8D-D02F29B14D95) (Shutdown) (unavailable, runtime profile not found)
    iPhone 7 (BBE189CE-C478-4F76-9E5B-DB64EE7322A4) (Shutdown) (unavailable, runtime profile not found)
    iPhone 7 Plus (FD9262AA-6C6F-4727-A6A3-77301EF0D78D) (Shutdown) (unavailable, runtime profile not found)
    iPhone SE (BC99E4CE-E6BA-4292-9741-82E664650BCE) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (9D0F5C92-9F87-4512-9D59-F13CC29F406A) (Shutdown) (unavailable, runtime profile not found)
    iPad Air 2 (4B91A3F7-19E8-4CD9-B509-F8F72B5ABCE0) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (9.7 inch) (919C6E9B-6ED6-4697-A7B3-30649C0B3990) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (12.9 inch) (0A799B08-1281-4009-A18C-093A3C0395E3) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.tvOS-10-2 --
    Apple TV 1080p (E14DC423-ABAF-4AAC-A1BC-819010492EDE) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.tvOS-11-2 --
    Apple TV (5454F659-349A-4636-8455-8BAC06124BCC) (Shutdown) (unavailable, runtime profile not found)
    Apple TV 4K (DF06BE06-A856-489A-B022-165EBD83B473) (Shutdown) (unavailable, runtime profile not found)
    Apple TV 4K (at 1080p) (42985E1C-CBB4-4E2F-B385-621CD8EE0580) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-3-2 --
    Apple Watch - 38mm (AEC02610-A049-4B7C-B66C-949D26C8296C) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 42mm (B39920B8-6368-4772-9F4D-F4C2C893A8E4) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 2 - 38mm (A26E8ECC-DD95-4219-B8F0-A7F55DCD895A) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 2 - 42mm (488B1089-A04E-4CD2-B9C2-A858D33499C1) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-4-2 --
    Apple Watch - 38mm (C3E22891-08B6-4DD9-B5EF-980902701740) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 42mm (1404233C-2B23-4B4E-9A4D-FDDC851DDCF3) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 2 - 38mm (6E361732-3F23-490A-8308-FDD86D9F4BE0) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 2 - 42mm (96896FEA-62DF-480E-86C7-4FF8723AF6D1) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 3 - 38mm (BBB90C32-3D44-4BB6-BD22-125C2A0EBB24) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 3 - 42mm (DA0F8DBC-BA54-46F3-A0B8-CF4211F4C893) (Shutdown) (unavailable, runtime profile not found)

**Comment by jwall132** [comment] 2018-04-05 12:46
Sorry I think the initial log trace was run on the 11.2 emulator. I have just run the command again to the ensure the log is correct to the emulator. 

**Output**

Transferring from /Users/jackwaller/Code/Session/NativeScript/session/platforms/ios/session/app to /Users/jackwaller/Library/Developer/CoreSimulator/Devices/E21F06DE-D39E-4A09-A285-F510DBCD71A3/data/Containers/Bundle/Application/13D0FC37-CB90-42B6-A100-ED28DCA9F0BB/Session.app/app
Unable to apply changes on device: E21F06DE-D39E-4A09-A285-F510DBCD71A3. Error is: cp: dest is not a directory (too many sources).

**Comment by jwall132** [comment] 2018-04-05 13:30
Hi @Fatme 

I can confirm OS is case-insensitive

**Output**

jackwaller$ touch abc.js
jackwaller$ ls -la abc.js
-rw-r--r--  1 jackwaller  staff  0  5 Apr 23:26 abc.js
Jacks-MacBook-Pro:Code jackwaller$ ls -la aBc.js
-rw-r--r--  1 jackwaller  staff  0  5 Apr 23:26 aBc.js

**Comment by Fatme** [comment] 2018-04-05 13:45
Hi @jwall132,

Thank you for your fast answers and cooperation. We're still trying to reproduce your issue on our side but without success.

Can you please execute the followings:
1. Go to your project directory and delete your platforms directory.
2. Clean your simulator . Go Hardware -> Erase all Content and Settings

After that try to run the application again.

**Comment by jwall132** [comment] 2018-04-06 01:26
Hi @Fatme 

Still receiving the same error.

Cheers

**Comment by Fatme** [comment] 2018-04-10 07:04
Hi @jwall132,

Sorry to hear that. I've noticed something strange:
> Transferring from /Users/jackwaller/Code/Session/NativeScript/session/platforms/ios/session/app to /Users/jackwaller/Library/Developer/CoreSimulator/Devices/E21F06DE-D39E-4A09-A285-F510DBCD71A3/data/Containers/Bundle/Application/13D0FC37-CB90-42B6-A100-ED28DCA9F0BB/Session.app/app

Here the name of the application is `Session.app` (note: **with first upper case letter**).
I've tried to hardcode this name (with first upper case) and was able to reproduce the problem. It's  
a strange how this can happen at all.

Can you please execute the following commands and send us the output:
1. `xcrun simctl get_app_container booted org.nativescript.session`
2. `xcrun simctl get_app_container booted org.nativescript.Session`

**Comment by Fatme** [comment] 2018-04-10 11:33
@jwall132,

Thank you for providing the output. Do you have 'Info.plist' file under `app\App_Resources\iOS` folder? In case you have can you please send us?

**Comment by jwall132** [comment] 2018-04-10 11:43
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>Session</string>
	<key>CFBundleExecutable</key>
	<string>Session</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Session</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1.0</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIRequiresFullScreen</key>
	<true/>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>NSAppTransportSecurity</key>
	<dict>
		
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>UIStatusBarStyle</key>
	<string>UIStatusBarStyleLightContent</string>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

**Comment by jwall132** [comment] 2018-04-10 11:47
[Untitled.pdf](https://github.com/NativeScript/nativescript-cli/files/1894425/Untitled.pdf)

**Comment by jwall132** [comment] 2018-04-11 04:25
Hi @Fatme 

I can confirm that I have now got the app to install correctly. I must have changed the info.plist... 

I thank you so much for the effort you have gone through to help me work this out! You are the best!!! 

Jack

**Comment by Fatme** [comment] 2018-04-11 07:10
Hi @jwall132,

I'm so happy your issue is resolved. I would like to thank you again for your fast response and cooperation.

I'm closing this issue but feel free to write here or open an another in case you have some problems.

**Closed by Fatme** 2018-04-11 07:10 UTC
