### ISSUE TITLE
Build failure on tutorial app for android : no parameters passed at GetInterfaceNames

### ISSUE THREAD

**Issue by Sebadst** [NativeScript/nativescript-cli#3226] opened 2017-11-21 19:37 UTC
### Tell us about the problem
As per title, I am trying to build and deploy the tutorial app on android emulator. However, I am getting following issue:
```
Searching for devices...
Starting Android emulator with image Nexus_5X_API_25_x86
Waiting for emulator device initialization.......
Executing before-liveSync hook from C:\Users\xxx\NativeScriptsProjects\HelloWorld\hooks\before-liveSync\nativescript-angular-sync.js
Skipping prepare.
Building project...
Gradle build...
         + applying user-defined configuration from C:\Users\xxx\NativeScriptsProjects\HelloWorld\app\App_Resources\Android\app.gradle
         + creating include.gradle for plugin C:\Users\xxx\NativeScriptsProjects\HelloWorld\node_modules\tns-core-modules-widgets
         + applying plugin configuration from C:\Users\xxx\NativeScriptsProjects\HelloWorld\platforms\android\build\configurations\tns-core-modules-widgets\include.gradle
         + adding nativescript runtime package dependency: nativescript-optimized
         + adding aar plugin dependency: C:\Users\xxx\NativeScriptsProjects\HelloWorld\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
Exception in thread "main" java.lang.IllegalArgumentException: There are no parameters passed!
        at com.ig.GetInterfaceNames.main(GetInterfaceNames.java:27)

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\xxx\NativeScriptsProjects\HelloWorld\platforms\android\build-tools\android-static-binding-generator\build.gradle' line: 67

* What went wrong:
Execution failed for task ':asbg:generateInterfaceNamesList'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_121\bin\java.exe'' finished with non-zero exit value 1 
```
### Which platform(s) does your issue occur on?
Android . iOS not tested

### Please provide the following version numbers that your issue occurs with:
nativescript : 3.3.0
tns-core-modules: 3.1.1
tns-android: 3.3.1
node: 8.9.1

### Please tell us how to recreate the issue in as much detail as possible.
tns create HelloWorld --template nativescript-template-ng-tutorial
tns run android

Thanks for your support

**Comment by Sebadst** [comment] 2017-11-28 21:27
this issue is a duplicate of #3144

**Comment by Plamen5kov** [comment] 2017-11-29 14:49
I'll close this issue in favor of #3144, please comment there. FYI I couldn't reproduce the issue.

**Closed by Plamen5kov** 2017-11-29 14:49 UTC
Labels: Windows
