### ISSUE TITLE
TNS 2.5.0 Building 2.4 app issue

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-cli#2474] opened 2017-02-02 07:17 UTC
All I did was upgrade my "nativescript" command to 2.5 to do some testing;  and when I was built\ a app with 2.4.2 of modules and a 2.4.1 runtime on android when it went to show the ErrorReportActivity screen (caused by a error I had in my code) it actually crashed out (no error screen) with this error:

```
E/AndroidRuntime(27611): FATAL EXCEPTION: main
E/AndroidRuntime(27611): Process: org.nativescript.demo, PID: 27611
E/AndroidRuntime(27611): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nati
vescript.demo/com.tns.ErrorReportActivity}: android.content.res.Resources$NotFoundException: File res/color/abc_primary_text_material_dark.xml from drawable resource ID #0x7f0c0056
E/AndroidRuntime(27611):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395)
E/AndroidRuntime(27611):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2453)
```

**Comment by rosen-vladimirov** [comment] 2017-02-08 21:10
Hey @NathanaelA ,
Do you have steps to reproduce for this issue? It looks like some of the resources are missing:
`abc_primary_text_material_dark.xml` - do you have such file?
Also have you tried removing `node_modules` and `platforms` directory, uninstalling the app from device and executing `tns run android`?

**Comment by NathanaelA** [comment] 2017-02-08 21:40
@rosen-vladimirov - This app started out as a 1.7.x app.  I upgraded it to 2.4.x a couple days before 2.5 was released; (meaning I deleted the platforms).    I don't recall if I had ever built it using 2.4 before the 2.5 test as I work with a lot of different projects each day and this new plugin functionality wasn't completed until after 2.5 was released.    
So my believe it is:
1. Fresh 2.4.1 Runtimes, newly installed tns-core-modules@2.4.2
2. TNS 2.5 command line
3. Phone did NOT have an existing app on it.
4. TNS run android (going to a real phone).

A typo had tried to cause the error screen to appear; and then instead it crashed out with the application has stopped dialog; and the `adb logcat` showed that error stack.     I have NOT tried to reproduce it; as I just decided to update the app to 2.5 modules & runtime, and that fixed the issue and I was able to get the exception screen with the mistake I had made.

**Comment by rosen-vladimirov** [comment] 2017-02-08 21:47
@NathanaelA thanks for the detailed steps. We'll take a look and we'll try to figure it out. 
I'm glad your app is working now. It's recommended to use CLI `x.y.z` with runtimes `x.y.<smth>` as at the moment everything is coupled. For example we strongly recommend using CLI 2.5.x with runtimes 2.5.x.
In case you target 2.4.x android runtime, it will be better to use 2.4.x CLI. Note that this is just recommendation, not a must. Anyway, I'll mark this issue as a minor bug. Again, thanks for the detailed report.

**Comment by Pip3r4o** [comment] 2017-04-28 11:46
I have recently tested upgrading an application 2.5 -> 3.0-rc bits. I did not encounter the problem you described in detail above.

If you are faced with the same issue please follow @rosen-vladimirov's suggestion of sticking with versions of the same major version and minor versions (X.Y.Z - X and Y should match between components). 

We try to not cause incompatibilities between the different components, but sometimes they are inevitable to make, in that case we try to be as transparent as possible.

Closing this issue. Feel free to reopen if it shows up again.

**Closed by Pip3r4o** 2017-04-28 11:46 UTC
Labels: bug, minor
