### ISSUE TITLE
Got stuck after upgrading to 6.3.*

### ISSUE THREAD

**Issue by jannomeister** [NativeScript/nativescript-cli#5195] opened 2020-01-03 11:28 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.3.0
 - Cross-platform modules:6.3.2
 - Android Runtime: 6.3.1
 - iOS Runtime: 6.3.0
 - Plugin(s):

**Describe the bug**
after upgrading, I got stuck in `Installing MaterialComponents (94.5.0)`

**To Reproduce**
upgrade to the latest version and run `tsn run ios --device "iPhone 11"

**Expected behavior**
should install the plugins and continue to run

**Comment by rosen-vladimirov** [comment] 2020-01-06 10:42
Hey @jannomeister ,
It seems there's a problem with your cocoapods installation. Can you try running `pod repo update` and try running your application after that? Please note cocoapods update may take a while.

**Comment by hbg34** [comment] 2020-01-13 04:43
I have the same problem. I also updated with pod repo update. Then i re-installed NativeScript. However iOS build stuck on "Installing MaterialComponents (94.5.0)". Is there any advise for this issue. Android build works fine.

**Comment by rosen-vladimirov** [comment] 2020-01-13 06:49
Hey @hbg34 ,
It seems for some reason the `pod install` command is stuck. Can you try navigating to your `<project dir>/platfoms/ios` directory in a terminal and run `pod install --verbose` - this could give some more information what is causing the command hang.

**Comment by hbg34** [comment] 2020-01-13 07:09
We can not fix the problem. We started a new project with Angular, "tns create Name --ng", android has no problem however iOS stuck at these lines:
...
Installing MDFInternationalization (2.0.0)
Installing MaterialComponents (94.5.0)

We can not fix it with any of the recommended solutions.
Please advise.

**Comment by rosen-vladimirov** [comment] 2020-01-13 07:12
Hey @hbg34 ,
Can you try the following:
```
tns create app1 --ng
cd app1
tns prepare ios
```
If the last command is stuck, stop it (with Ctrl +C ) and after that do the following:
```
cd platforms/ios
pod install --verbose
```

The last command should print a lot of output and it should give more information what's causing the issue. NOTE it might take a lot of time the first time when `pod install` is executed.

**Comment by hbg34** [comment] 2020-01-13 07:48
Thanks for the feedback Rosen. I did what you recommended. And the result is as follows:
...
Downloading dependencies
Installing MDFInternationalization (2.0.0)
Installing MaterialComponents (94.5.0)
^C[!] Cancelled

hsn-mbp:ios hsngnr$ cd platforms/ios
hsn-mbp:ios hsngnr$ pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-app1`:
  (`$(ARCHS_STANDARD)`)

Resolving dependencies of `Podfile`
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because
  checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_0_1_9.txt exists! Returning local
  because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/0/1/9/MaterialComponents/101.0.1/MaterialComponents.podspec.json exists!
  Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/0/1/9/MaterialComponents/94.5.0/MaterialComponents.podspec.json exists!
  Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_7_1_d.txt exists! Returning local
  because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/7/1/d/MDFInternationalization/2.0.0/MDFInternationalization.podspec.json
  exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/0/1/9/MaterialComponents/94.5.0/MaterialComponents.podspec.json exists!
  Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/0/1/9/MaterialComponents/94.5.0/MaterialComponents.podspec.json exists!
  Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/0/1/9/MaterialComponents/94.5.0/MaterialComponents.podspec.json exists!
  Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/0/1/9/MaterialComponents/94.5.0/MaterialComponents.podspec.json exists!
  Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/0/1/9/MaterialComponents/94.5.0/MaterialComponents.podspec.json exists!
  Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/0/1/9/MaterialComponents/94.5.0/MaterialComponents.podspec.json exists!
  Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/0/1/9/MaterialComponents/94.5.0/MaterialComponents.podspec.json exists!
  Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/0/1/9/MaterialComponents/94.5.0/MaterialComponents.podspec.json exists!
  Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/0/1/9/MaterialComponents/94.5.0/MaterialComponents.podspec.json exists!
  Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/0/1/9/MaterialComponents/94.5.0/MaterialComponents.podspec.json exists!
  Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/0/1/9/MaterialComponents/94.5.0/MaterialComponents.podspec.json exists!
  Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/7/1/d/MDFInternationalization/2.0.0/MDFInternationalization.podspec.json
  exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/7/1/d/MDFInternationalization/1.1.1/MDFInternationalization.podspec.json
  exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/7/1/d/MDFInternationalization/1.1.0/MDFInternationalization.podspec.json
  exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/7/1/d/MDFInternationalization/1.0.4/MDFInternationalization.podspec.json
  exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/7/1/d/MDFInternationalization/1.0.3/MDFInternationalization.podspec.json
  exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/7/1/d/MDFInternationalization/1.0.2/MDFInternationalization.podspec.json
  exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/7/1/d/MDFInternationalization/1.0.1/MDFInternationalization.podspec.json
  exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/7/1/d/MDFInternationalization/1.0.0/MDFInternationalization.podspec.json
  exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/7/1/d/MDFInternationalization/0.3.1/MDFInternationalization.podspec.json
  exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/7/1/d/MDFInternationalization/0.2.0/MDFInternationalization.podspec.json
  exists! Returning local because checking is only perfomed in repo update

Comparing resolved specification to the sandbox manifest
  A MDFInternationalization
  A MaterialComponents

Downloading dependencies

-> Installing MDFInternationalization (2.0.0)
  > Copying MDFInternationalization from
  `/Users/hasanguner/Library/Caches/CocoaPods/Pods/Release/MDFInternationalization/2.0.0-01009`
  to `Pods/MDFInternationalization`

-> Installing MaterialComponents (94.5.0)
 > Git download
 > Git download
     $ /usr/local/bin/git clone
     https://github.com/material-components/material-components-ios.git
     /var/folders/k5/d28njvc51rs8dkdy0jn8m7cw0000gn/T/d20200113-4977-4ihym8
     --template= --single-branch --depth 1 --branch v94.5.0
     Cloning into '/var/folders/k5/d28njvc51rs8dkdy0jn8m7cw0000gn/T/d20200113-4977-4ihym8'...
     fatal: unable to access 'https://github.com/material-components/material-components-ios.git/': LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

[!] Error installing MaterialComponents
[!] /usr/local/bin/git clone https://github.com/material-components/material-components-ios.git /var/folders/k5/d28njvc51rs8dkdy0jn8m7cw0000gn/T/d20200113-4977-4ihym8 --template= --single-branch --depth 1 --branch v94.5.0

Cloning into '/var/folders/k5/d28njvc51rs8dkdy0jn8m7cw0000gn/T/d20200113-4977-4ihym8'...
fatal: unable to access 'https://github.com/material-components/material-components-ios.git/': LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54


/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader.rb:142:in `rescue in execute_command'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader.rb:139:in `execute_command'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downloader/base.rb:154:in `block in executable'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downloader/git.rb:79:in `block in clone'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader.rb:173:in `block in ui_sub_action'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader.rb:172:in `ui_sub_action'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downloader/git.rb:77:in `clone'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downloader/git.rb:45:in `download!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downloader/base.rb:82:in `block in download'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader.rb:157:in `block in ui_action'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader.rb:156:in `ui_action'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downloader/base.rb:80:in `download'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader.rb:108:in `download_source'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader.rb:75:in `download_request'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader/cache.rb:171:in `download'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader/cache.rb:154:in `block in uncached_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader.rb:42:in `download'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:117:in `download_source'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:557:in `install_source_of_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:508:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:507:in `block in install_pod_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:490:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:490:in `install_pod_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:248:in `block in download_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:247:in `download_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:157:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
hsn-mbp:ios hsngnr$

**Comment by rosen-vladimirov** [comment] 2020-01-13 07:56
Hey @hbg34 ,
`pod install` command internally executes `git clone ...`, which fails in your case:
```
Error installing MaterialComponents
[!] /usr/local/bin/git clone https://github.com/material-components/material-components-ios.git /var/folders/k5/d28njvc51rs8dkdy0jn8m7cw0000gn/T/d20200113-4977-4ihym8 --template= --single-branch --depth 1 --branch v94.5.0

Cloning into '/var/folders/k5/d28njvc51rs8dkdy0jn8m7cw0000gn/T/d20200113-4977-4ihym8'...
fatal: unable to access 'https://github.com/material-components/material-components-ios.git/': LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
```

This is usually caused by your git, libssl or local proxy. You can try updating your local `git` or see how to set a proxy.

As the issue is not caused by NativeScript CLI, I'm closing this thread.

**Closed by rosen-vladimirov** 2020-01-13 07:56 UTC
Labels: CocoaPods, needs more info, os: ios

**Comment by hbg34** [comment] 2020-01-13 08:12
Thanks Rosen. I will try with your advise couple more time.
