### ISSUE TITLE
Inconsistent naming of output files (apk, app, ipa)

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2575] opened 2017-02-26 06:31 UTC
Let's imagine you have {N} app in folder `nativescript-toast` and your app id in package.json is `org.nativescript.nativescripttoastexample`.

APK will be named: `nativescripttoastexample-release.apk` (id in package.json is respected)
IPA will be named: `nativescripttoast.ipa` (folder name is respected)

Can we make them consistent (both respect id in package.json)?

**Comment by rosen-vladimirov** [comment] 2017-02-26 17:25
The name is produced by the build tools - gradle and Xcode. What's the case here and why do you need the same name? If it's for automation purposes, you can use the `--copy-to` parameter and set the same name for the `.apk` and `.ipa` files. For example:
```
$ tns build ios --copy-to ./nativescript-toast.ipa
$ tns build android --copy-to ./nativescript-toast.apk
```
I'm closing this issue as it's not a bug in NativeScript CLI - the name is created by external tools that we are using. Feel free to reopen it in case there something that I'm missing here.

**Closed by rosen-vladimirov** 2017-02-26 17:25 UTC
Labels: bug
