### ISSUE TITLE
`tns prepare ios --provision` starts simulator

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/nativescript-cli#2889] opened 2017-06-14 08:41 UTC
If you execute `tns build ios --for-device` the CLI searches for a running device and if none is found it starts the default simulator image:
```
➜  demo git:(nativescript) ✗ tns build ios --for-device
Executing before-prepare hook from /Users/peter/Documents/NativeScriptProjects/demo/hooks/before-prepare/nativescrip
t-dev-android-snapshot.js
Executing before-prepare hook from /Users/peter/Documents/NativeScriptProjects/demo/hooks/before-prepare/nativescrip
t-dev-sass.js
Found peer node-sass
Executing before-prepare hook from /Users/peter/Documents/NativeScriptProjects/demo/hooks/before-prepare/nativescrip
t-dev-typescript.js
Found peer TypeScript 2.2.2
Executing before-prepare hook from /Users/peter/Documents/NativeScriptProjects/demo/hooks/before-prepare/nativescrip
t-push-notifications.js
Preparing project...
Project successfully prepared (ios)
Executing after-prepare hook from /Users/peter/Documents/NativeScriptProjects/demo/hooks/after-prepare/nativescript-
dev-android-snapshot.js
Executing after-prepare hook from /Users/peter/Documents/NativeScriptProjects/demo/hooks/after-prepare/nativescript-
dev-sass.js
All SASS source files removed from app package
Building project...
Searching for devices...
Build settings from command line:
```
 Is there any requirement that requires a running simulator or attached device when building with the `--for-device` flag?

**Comment by PanayotCankov** [comment] 2017-06-14 10:17
Side note: Requesting the list of connected devices starts an emulator. I've seen the same problem in commands such as `tns prepare ios --provision` that are supposed to list provisioning profiles but also filters provisioning profiles for the connected devices.

**Comment by dtopuzov** [comment] 2017-06-14 12:59
Looks to be duplicate of https://github.com/NativeScript/nativescript-cli/issues/2757

@PeterStaev Can you please try with `nativescript@next`, it should be fixed.

**Comment by PeterStaev** [comment] 2017-06-14 14:23
@dtopuzov , I can confirm that this is fixed in `nativescript@next` 👍

**Comment by briandilley** [comment] 2017-07-11 01:40
This is not fixed:
```
briandilley@Brians-MacBook-Pro:~$ tns --version
3.2.0-2017-07-10-9398
```

`tns prepare ios --provision XXXXX` still launches a simulator

**Comment by rosen-vladimirov** [comment] 2017-07-18 07:04
Hey @briandilley ,
Can you try with latest `@next` version - we've applied a fix for this in our master branch.

**Closed** 2017-07-26 07:29 UTC
Labels: bug
