### ISSUE TITLE
"Expected "\"", "\\\"", "\\n", or [^\\"] but "\\" found." error on tns run

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#2424] opened 2017-01-13 13:15 UTC
An error on `tns run ios`: *Expected "\"", "\\\"", "\\n", or [^\\"] but "\\" found.*

Prerequisite:
{N} CLI 2.5.0 release candidate.

Note:
I have an iOS device connected and iOS Simulator booted.

Steps:
```
git clone https://github.com/NativeScript/sample-Groceries
cd sample-Groceries
tns update
tns run ios
```

Output:
```
mcsofvchimev:sample-Groceries vchimev$ tns run ios
Executing before-prepare hook from /Users/vchimev/Work/git/sample-Groceries/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.0.10
Preparing project...
Project successfully prepared (ios)
Executing after-prepare hook from /Users/vchimev/Work/git/sample-Groceries/hooks/after-prepare/nativescript-unit-test-runner.js
Searching for devices...
Building project...
Skipping package build. No changes detected on the native side. This will be fast!
Installing...
Successfully installed on device with identifier '6CBB0388-1AD2-42F8-9992-8D8E7F55F04A'.
Expected "\"", "\\\"", "\\n", or [^\\"] but "\\" found.
```

Log Trace:
```
stderr: 
Skipping package build. No changes detected on the native side. This will be fast!
Skipping install.
SyntaxError: Expected "\"", "\\\"", "\\n", or [^\\"] but "\\" found.
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:566:15)
    at ex (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:120:33)
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:80:104
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/yok.js:191:124
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    - - - - -
    at peg$buildStructuredError (/usr/local/lib/node_modules/nativescript/node_modules/pbxproj-dom/parser.js:316:12)
    at Object.peg$parse [as parse] (/usr/local/lib/node_modules/nativescript/node_modules/pbxproj-dom/parser.js:901:11)
    at Function.Xcode.open (/usr/local/lib/node_modules/nativescript/node_modules/pbxproj-dom/xcode.js:15:43)
    at /usr/local/lib/node_modules/nativescript/lib/services/ios-project-service.js:316:41
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/services/ios-project-service.js:254:70
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/services/ios-project-service.js:212:74
Analytics statuses: 
```

**Comment by PanayotCankov** [comment] 2017-01-16 12:43
There is a parsing error in pbxproj-dom that has been fixed now in the release branch.

**Closed** 2017-01-16 15:04 UTC
Labels: 3 - Done

**Comment by ullalaaron** [comment] 2017-04-11 12:42
This keeps on happening :(
{N} v 2.5.4 
Plugin v 3.10.10
Only way to solve is to remove & add ios platform

**Comment by vchimev** [comment] 2017-04-11 13:33
Hey @ullalaaron,

Could you please elaborate more on your steps to reproduce? Also, it'd be great if you open a new issue and provide the information needed.

Many thanks,
@vchimev

**Comment by PanayotCankov** [comment] 2017-04-12 06:00
@ullalaaron Could you please attach the `platforms/ios/<yourapp>.xcodeproj/project.pbxproj` from the project while it is in broken state? The problem is because errors in the grammar used for the parser in pbxproj-dom: https://github.com/NativeScript/pbxproj-dom Probably some of the plugins introduce string literals that have special characters. We've already expanded the grammar quite a lot though.

**Comment by ullalaaron** [comment] 2017-04-12 07:02
Hi @PanayotCankov ! Here it is!
[Haloose.xcodeproj.zip](https://github.com/NativeScript/nativescript-cli/files/915574/Haloose.xcodeproj.zip)

**Comment by PanayotCankov** [comment] 2017-04-12 08:04
Hi @ullalaaron,
Your pbxproj is in XML format. I think we've tried to avoid converting the xcodeproj files to the xml plist format in the past. If I am not mistaken cocoapods may be doing this with the pbxproj. I will need your package.json in that case to figure out what is converting the project to XML format.

**Comment by PanayotCankov** [comment] 2017-04-12 08:22
Reading this discussion: http://stackoverflow.com/questions/37083467/why-my-project-pbxproj-file-changes-its-format
It may be something with missing xcproj:
```
brew install xcproj
```

**Comment by ullalaaron** [comment] 2017-04-12 11:41
@PanayotCankov thank you for your time!
pod -v output 
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /usr/local in PATH, mode 040777
1.0.0
```

package.json
```
  "nativescript": {
    "id": "com.haloose.app",
    "tns-ios": {
      "version": "2.5.0"
    },
    "tns-android": {
      "version": "3.0.0-next-2017-04-11-1736"
    }
  },
  "dependencies": {
    "nativescript-camera": "0.0.8",
    "nativescript-i18n": "^0.1.6",
    "nativescript-image-cache-media": "^1.0.6",
    "nativescript-imagepicker": "^2.5.1",
    "nativescript-loading-indicator": "^2.2.2",
    "nativescript-local-notifications": "^1.2.1",
    "nativescript-plugin-firebase": "^3.11.3",
    "nativescript-slides": "^2.2.8",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toast": "^1.4.5",
    "tns-core-modules": "^2.5.2",
    "underscore": "^1.8.3"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.16.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "typescript": "~2.1.0"
  }
```

**Comment by robtoll** [comment] 2018-12-18 01:44
I have had the same error "Expected """, "\"", "\n", or [^\"] but "\" found."

The corruption of the project file seemed to be related to the DEVELOPMENT_TEAM value in the build.xconfig file, so make sure your build config DEVELOPMENT_TEAM is commented out.

Then remove ios with "tns platform remove ios" and add again with ""tns platform add ios".

I have used the NaviteScript SideKick app to configure the IOS Provisioning and Certificates. It needs to be configured one way or another.

Now try running "tns run ios" again, and it should let you choose the development team

It may be that your problem is not specifically related to the DEVELOPMENT_TEAM value, but the file in your project folder - /App_Resources/iOS/build.xconfig is worth investigating.

Try commenting out some of the lines, and see what it says in the build.

Good luck!

**Comment by mikegurbani** [comment] 2025-03-21 14:57
There is a fix here that worked for me, if you have any single quotes in your distribution certifcate, it could cause this error...

https://github.com/NativeScript/nativescript-cli/issues/5320

**Comment by mikegurbani** [comment] 2025-03-28 17:42
> [@mikegurbani](https://github.com/mikegurbani) can you run `security find-identity -p codesigning` with the quotes in and send the result?
> 
> You change the personal info there (change the identities to `AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA` and the team to `AAAAAAAAAA`)
> 
> We can probably fix this parser, I just need a good test scenario

Unfortunately, we have already issued a new certificate without the single quote.
