### ISSUE TITLE
Initial LiveSync is extremly slow if the project has thousands of files

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#921] opened 2015-09-15 14:25 UTC
`tns livesync --watch` always syncs all files on first execution.

We've considered some ideas for optimizations:
* Create and upload archive instead to execute `adb push` for each file.
* Compute file hashes and upload only the changed files.

Here is the repo project  https://github.com/NativeScript/sample-ng-todomvc

**Comment by Fatme** [comment] 2015-09-16 10:46
related to this https://github.com/NativeScript/nativescript-cli/issues/913

**Comment by atanasovg** [comment] 2016-01-05 14:42
Let's see whether the problem is present when files are bundled with WebPack

**Comment by rosen-vladimirov** [comment] 2016-02-05 15:41
okay, we've found the way to speed the process for Android. In case your project is huge, every time you use `tns livesync android` (or the initial part of `tns livesync android --watch`, the full project will be transferred to device).
Persist all file hashes of project's files and next time when command is executed transfer only the changed ones.
The json which contains hashes information should be on device, so when the device is attached to another PC, where the same project is developed, we'll still transfer only the changed files.

**Comment by rosen-vladimirov** [comment] 2016-02-05 15:44
In order to test this - create project with thousands of files, execute `tns livesync android --justlaunch`.
Now change 1 file and execute it again - compare the times, second time should be really fast.

**Closed** 2016-02-26 12:50 UTC
Labels: 2 - Ready For Test, changelog, feature, livesync
