### ISSUE TITLE
Errors with upgrading to 1.5 and platform/doctor commands

### ISSUE THREAD

**Issue by gverschuur** [NativeScript/nativescript-cli#1266] opened 2015-11-27 10:54 UTC
I updated the global NPM package to 1.5, following the upgrade guide. During the install, I get the following error:

```
Cannot read property 'match' of null
Error: Unknown command 'dev-post-install'. Try '$ tns help' for a full list of supported commands.
```

After removing the Android platform, when I run ```tns platform add android``` I get an error  ```Cannot read property 'match' of null```.

When i run ```tns doctor``` I also get the ```Cannot read property 'match' of null``` error.

This is with the latest Android SDK installed (I think, I'm not much of an Android developer so I basically install what seems necessary). The iOS platform installs without any errors.

This happens on OSX 10.0.5 (Yosemite) using either node **v4.2.1** or node **5.1.0**, with node having been installed using Brew.

**Comment by rosen-vladimirov** [comment] 2015-11-27 10:57
Hi @gverschuur ,
The problem is that you do not have cocoapods installed. You can find more information in [this thread](https://github.com/NativeScript/nativescript-cli/issues/1245).
I'm closing this one as it is duplicate of the mentioned one. Please note that the fix for this issue will be included in our next release. For the moment I suggest you to install cocoapods on your machine.

**Closed by rosen-vladimirov** 2015-11-27 10:57 UTC

**Comment by gverschuur** [comment] 2015-11-27 11:01
Thanks for the very quick reply, and for the duplicate issue. The fix there worked for me.

**Comment by rosen-vladimirov** [comment] 2015-11-27 11:02
I'm glad it helped. :smile_cat:
