### ISSUE TITLE
tns build android takes 15-20 mins on every small change

### ISSUE THREAD

**Issue by ishandutta2007** [NativeScript/nativescript-cli#2851] opened 2017-05-28 06:55 UTC
```tns build android ```
is very slow It takes 15-20 mins every time I run it , it basically get stuck at generateF0F1F2DebugAssets and packageF0F1F2Debug for ever.
What are workarounds to speed it up.
This make it unusable to deploy and test while building the app.
On top of that when I am not skipping prepare it takes additional 4-5 mins for that as well.

```

MacBook-Pro:bb-ns-ng-dr ishandutta2007$ tns build android --clean  | while IFS= read -r line; do printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$line"; done 
[2017-05-28 11:24:20] Executing before-prepare hook from /Users/ishandutta2007/Documents/Projects/bb-ns-ng-dr/hooks/before-prepare/nativescript-dev-typescript.js
[2017-05-28 11:24:23] Found peer TypeScript 2.2.2
[2017-05-28 11:24:34] Preparing project...
[2017-05-28 11:25:35] Project successfully prepared (android)
[2017-05-28 11:25:35] Building project...
[2017-05-28 11:25:53] 
[2017-05-28 11:25:53] :config phase:  createDefaultIncludeFiles
[2017-05-28 11:25:53] 	+found plugins: nativescript-exoplayer
[2017-05-28 11:25:53] 	+found plugins: nativescript-telerik-ui
[2017-05-28 11:25:54] 	+found plugins: tns-core-modules-widgets
[2017-05-28 11:25:54] 
[2017-05-28 11:25:54] :config phase:  createPluginsConfigFile
[2017-05-28 11:25:54] 	 Creating product flavors include.gradle file in /Users/ishandutta2007/Documents/Projects/bb-ns-ng-dr/platforms/android/configurations folder...
[2017-05-28 11:25:54] 
[2017-05-28 11:25:54] :config phase:  pluginExtend
[2017-05-28 11:25:54] 	+applying configuration from: /Users/ishandutta2007/Documents/Projects/bb-ns-ng-dr/platforms/android/configurations/include.gradle
[2017-05-28 11:25:54] 	+applying configuration from: /Users/ishandutta2007/Documents/Projects/bb-ns-ng-dr/platforms/android/configurations/nativescript-exoplayer/include.gradle
[2017-05-28 11:25:54] 	+applying configuration from: /Users/ishandutta2007/Documents/Projects/bb-ns-ng-dr/platforms/android/configurations/nativescript-telerik-ui/include.gradle
[2017-05-28 11:25:54] 	+applying configuration from: /Users/ishandutta2007/Documents/Projects/bb-ns-ng-dr/platforms/android/configurations/tns-core-modules-widgets/include.gradle
[2017-05-28 11:25:57] 
[2017-05-28 11:25:57] :config phase:  addAarDependencies
[2017-05-28 11:25:57] 	+adding dependency: /Users/ishandutta2007/Documents/Projects/bb-ns-ng-dr/platforms/android/libs/aar/Common-2017.1.504-dev-release.aar
[2017-05-28 11:25:57] 	+adding dependency: /Users/ishandutta2007/Documents/Projects/bb-ns-ng-dr/platforms/android/libs/aar/Data-2017.1.504-dev-release.aar
[2017-05-28 11:25:57] 	+adding dependency: /Users/ishandutta2007/Documents/Projects/bb-ns-ng-dr/platforms/android/libs/aar/List-2017.1.504-dev-release.aar
[2017-05-28 11:25:57] 	+adding dependency: /Users/ishandutta2007/Documents/Projects/bb-ns-ng-dr/platforms/android/libs/aar/Primitives-2017.1.504-dev-release.aar
[2017-05-28 11:25:57] 	+adding dependency: /Users/ishandutta2007/Documents/Projects/bb-ns-ng-dr/platforms/android/libs/aar/widgets-release.aar
[2017-05-28 11:26:01] The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
[2017-05-28 11:26:01] The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
[2017-05-28 11:26:01] Incremental java compilation is an incubating feature.
[2017-05-28 11:26:01] The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
[2017-05-28 11:26:01] 	at build_10eukjozje3krzsrnzmfs3ac2.run(/Users/ishandutta2007/Documents/Projects/bb-ns-ng-dr/platforms/android/build-tools/android-static-binding-generator/build.gradle:126)
[2017-05-28 11:26:01] :preBuild UP-TO-DATE
[2017-05-28 11:26:01] :preF0F1F2DebugBuild UP-TO-DATE
[2017-05-28 11:26:01] :checkF0F1F2DebugManifest
[2017-05-28 11:26:01] :preF0F1F2ReleaseBuild UP-TO-DATE
[2017-05-28 11:26:02] :prepareBbnsngdrRuntimeUnspecifiedLibrary UP-TO-DATE
[2017-05-28 11:26:02] :prepareComAndroidSupportAnimatedVectorDrawable2531Library UP-TO-DATE
[2017-05-28 11:26:02] :prepareComAndroidSupportAppcompatV72531Library UP-TO-DATE
[2017-05-28 11:26:02] :prepareComAndroidSupportDesign2531Library UP-TO-DATE
[2017-05-28 11:26:02] :prepareComAndroidSupportRecyclerviewV72531Library UP-TO-DATE
[2017-05-28 11:26:02] :prepareComAndroidSupportSupportCompat2531Library UP-TO-DATE
[2017-05-28 11:26:02] :prepareComAndroidSupportSupportCoreUi2531Library UP-TO-DATE
[2017-05-28 11:26:02] :prepareComAndroidSupportSupportCoreUtils2531Library UP-TO-DATE
[2017-05-28 11:26:02] :prepareComAndroidSupportSupportFragment2531Library UP-TO-DATE
[2017-05-28 11:26:02] :prepareComAndroidSupportSupportMediaCompat2531Library UP-TO-DATE
[2017-05-28 11:26:02] :prepareComAndroidSupportSupportV42531Library UP-TO-DATE
[2017-05-28 11:26:02] :prepareComAndroidSupportSupportVectorDrawable2531Library UP-TO-DATE
[2017-05-28 11:26:02] :prepareComAndroidSupportTransition2531Library UP-TO-DATE
[2017-05-28 11:26:02] :prepareComGoogleAndroidExoplayerExoplayerR231Library UP-TO-DATE
[2017-05-28 11:26:02] :prepareCommon20171504DevReleaseLibrary UP-TO-DATE
[2017-05-28 11:26:02] :prepareData20171504DevReleaseLibrary UP-TO-DATE
[2017-05-28 11:26:02] :prepareList20171504DevReleaseLibrary UP-TO-DATE
[2017-05-28 11:26:02] :preparePrimitives20171504DevReleaseLibrary UP-TO-DATE
[2017-05-28 11:26:02] :prepareWidgetsReleaseLibrary UP-TO-DATE
[2017-05-28 11:26:02] :prepareF0F1F2DebugDependencies
[2017-05-28 11:26:02] :compileF0F1F2DebugAidl UP-TO-DATE
[2017-05-28 11:26:02] :compileF0F1F2DebugRenderscript UP-TO-DATE
[2017-05-28 11:26:02] :generateF0F1F2DebugBuildConfig UP-TO-DATE
[2017-05-28 11:26:02] :cleanLocalAarFiles
[2017-05-28 11:26:02] :ensureMetadataOutDir
[2017-05-28 11:26:03] :collectAllJars
[2017-05-28 11:26:03] :setProperties
[2017-05-28 11:26:03] :generateTypescriptDefinitions SKIPPED
[2017-05-28 11:26:03] :copyTypings SKIPPED
[2017-05-28 11:26:03] :asbg:generateInterfaceNamesList
[2017-05-28 11:26:05] :asbg:traverseJsFiles
[2017-05-28 11:26:05] :asbg:runAstParser UP-TO-DATE
[2017-05-28 11:26:05] :asbg:generateBindings UP-TO-DATE
[2017-05-28 11:26:05] :generateF0F1F2DebugResValues UP-TO-DATE
[2017-05-28 11:26:05] :generateF0F1F2DebugResources UP-TO-DATE
[2017-05-28 11:26:06] :mergeF0F1F2DebugResources UP-TO-DATE
[2017-05-28 11:26:06] :processF0F1F2DebugManifest UP-TO-DATE
[2017-05-28 11:26:06] :processF0F1F2DebugResources UP-TO-DATE
[2017-05-28 11:26:06] :generateF0F1F2DebugSources UP-TO-DATE
[2017-05-28 11:26:06] :incrementalF0F1F2DebugJavaCompilationSafeguard UP-TO-DATE
[2017-05-28 11:26:06] :compileF0F1F2DebugJavaWithJavac UP-TO-DATE
[2017-05-28 11:26:06] :compileF0F1F2DebugNdk UP-TO-DATE
[2017-05-28 11:26:06] :compileF0F1F2DebugSources UP-TO-DATE
[2017-05-28 11:26:06] :buildMetadata UP-TO-DATE
[2017-05-28 11:26:06] :mergeF0F1F2DebugShaders UP-TO-DATE
[2017-05-28 11:26:06] :compileF0F1F2DebugShaders UP-TO-DATE
[2017-05-28 11:26:06] :generateF0F1F2DebugAssets UP-TO-DATE
[2017-05-28 11:31:16] :mergeF0F1F2DebugAssets
[2017-05-28 11:33:42] :transformClassesWithDexForF0F1F2Debug
[2017-05-28 11:33:48] :mergeF0F1F2DebugJniLibFolders
[2017-05-28 11:34:14] :transformNative_libsWithMergeJniLibsForF0F1F2Debug
[2017-05-28 11:34:14] :processF0F1F2DebugJavaRes UP-TO-DATE
[2017-05-28 11:34:17] :transformResourcesWithMergeJavaResForF0F1F2Debug
[2017-05-28 11:34:17] :validateSigningF0F1F2Debug
[2017-05-28 11:42:06] :packageF0F1F2Debug
[2017-05-28 11:42:06] :assembleF0F1F2Debug
[2017-05-28 11:42:07] :assembleDebug
[2017-05-28 11:42:07] :buildapk
[2017-05-28 11:42:07] 
[2017-05-28 11:42:07] BUILD SUCCESSFUL
[2017-05-28 11:42:07] 
[2017-05-28 11:42:07] Total time: 16 mins 28.718 secs
```

**Comment by Pip3r4o** [comment] 2017-05-28 10:16
Duplicate of https://github.com/NativeScript/NativeScript/issues/4281

**Closed by Pip3r4o** 2017-05-28 10:16 UTC

**Comment by ishandutta2007** [comment] 2017-05-28 10:18
this one needs to remain open, let thatone be closed

**Comment by ishandutta2007** [comment] 2017-05-28 10:20
ok either is fine
