### ISSUE TITLE
Main entry is missing. App cannot be started. Verify app bootstrap.

### ISSUE THREAD

**Issue by job111** [NativeScript/nativescript-cli#4942] opened 2019-08-10 23:16 UTC
started facing this problem after migrating to Cli 6.6.0

**Comment by DimitarTachev** [comment] 2019-08-12 05:57
@job111. please follow the issue template and provide the required versions and logs in order to allow us to investigate it further. Most probably the issue is caused by some Webpack compilation errors.

**Comment by ace-zhang18** [comment] 2019-09-07 18:04
I'm having the same issue. Here's the stacktrace when loading to emulator:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{org.nativescript.ngsample/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.ngsample/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
System.err:     at android.app.Activity.performCreate(Activity.java:7136)
System.err:     at android.app.Activity.performCreate(Activity.java:7127)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
System.err:     ... 11 more
```
Here's my package.json

```
{
  "name": "arenamaster",
  "version": "0.0.0",
  "scripts": {
    "android": "tns run android --bundle",
    "ios": "tns run ios --bundle",
    "mobile": "tns run --bundle",
    "preview": "tns preview --bundle",
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "nativescript-angular": "8.2.1",
    "nativescript-theme-core": "~2.0.17",
    "reflect-metadata": "~0.1.13",
    "tns-core-modules": "~6.1.0",
    "@angular/animations": "8.2.5",
    "@angular/common": "8.2.5",
    "@angular/compiler": "~8.2.5",
    "@angular/core": "8.2.5",
    "@angular/forms": "8.2.5",
    "@angular/platform-browser": "8.2.5",
    "@angular/platform-browser-dynamic": "8.2.5",
    "@angular/router": "8.2.5",
    "@nativescript/schematics": "^0.6.0",
    "angular-in-memory-web-api": "^0.9.0",
    "core-js": "^3.2.1",
    "ngx-ez": "^0.2.6",
    "rxjs": "~6.5.3",
    "tslib": "^1.10.0",
    "zone.js": "0.10.2",
    "@angular/http": "8.0.0-beta.10"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.3",
    "@angular/cli": "~8.3.3",
    "@angular/compiler-cli": "8.2.5",
    "@angular/language-service": "~8.2.5",
    "@nativescript/schematics": "~0.7.1",
    "@types/jasmine": "~3.4.0",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "~12.7.4",
    "codelyzer": "~5.1.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "nativescript-dev-webpack": "^1.2.0",
    "protractor": "~5.4.2",
    "ts-node": "~8.3.0",
    "tslint": "~5.19.0",
    "typescript": "3.5.3",
    "webpack-cli": "^3.3.8"
  },
  "nativescript": {
    "id": "org.nativescript.ngsample",
    "tns-android": {
      "version": "6.0.0"
    }
  }
}

```

**Comment by Fatme** [comment] 2019-09-09 06:05
Hey @ace-zhang18,

The problem is the way the files are imported. The following import is not correct:
```
import { PlayersComponent } from '..\players\players.component';
```

It should be:
```
import { PlayersComponent } from '../players/players.component';
```

Currently NativeScript CLI has an issue when webpack's compilation is not successful - for example when there is a syntax error in the code. In a such situation CLI goes ahead and tries to deploy the application on device. More info can be found [here](https://github.com/NativeScript/nativescript-cli/issues/3785).

I'm closing this issue as a duplicate to https://github.com/NativeScript/nativescript-cli/issues/3785.

**Closed by Fatme** 2019-09-09 06:05 UTC
Labels: needs more info
