### ISSUE TITLE
Documentation for plugins hooks

### ISSUE THREAD

**Issue by abhayastudios** [NativeScript/nativescript-cli#3825] opened 2018-08-17 14:51 UTC
Would it be possible to add some documentation/spec on the hooks that we can use for plugins? Like at least a list of the hooks that exist, in what order they are called, and their API? I couldn't find any so far in the docs or the [wiki](https://github.com/NativeScript/nativescript-cli/wiki).

Thanks!

**Comment by rosen-vladimirov** [comment] 2019-05-22 21:00
Closing as duplicate of https://github.com/NativeScript/nativescript-cli/issues/3341

**Closed by rosen-vladimirov** 2019-05-22 21:00 UTC
Labels: docs
