### ISSUE TITLE
`tns run android` does not start the app sometimes after file changes

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2576] opened 2017-02-27 08:39 UTC
Scenario:

1. Open MyApp in some editor (in my case VSCode)
2. `tns run android --path MyApp`
3. Start editing some JS, XML, CSS
4. After livesync sometimes app does not start automatically (it works if I manual start it)

Will write again when I have more logs or repro steps.

This bug makes CLI tests flaky and we can not rely on them. 
This is critical!

**Comment by mostafa-raafat** [comment] 2017-02-27 10:19
yes same problem here tns run android doesn't start emulator after upgrade to 2.5.2 , it was working in 2.5.1 but now not open the app automatically

**Comment by Plamen5kov** [comment] 2017-02-28 15:32
>After livesync sometimes app does not start automatically 

@dtopuzov, does this happen when you run `tns run android` command again, or just by changing and saving a file from the source code?

**Comment by nicoabie** [comment] 2017-02-28 17:46
@Plamen5kov I'm changing files and I have to remove the platform and add it again for the changes to get to the device.
And I have to start the app manually on the emulator

**Comment by Plamen5kov** [comment] 2017-03-01 08:19
@nicoabie the PR I've linked should fix your problem.

**Comment by Plamen5kov** [comment] 2017-03-01 12:44
Closing as duplicate of: https://github.com/NativeScript/nativescript-cli/issues/2486

**Closed by Plamen5kov** 2017-03-01 12:44 UTC
Labels: bug, critical

**Comment by eksahin** [comment] 2017-03-09 16:08
Have you ever tried to run with `emulator -avd`. Because i realized i did not set the ANDROID_SDK_ROOT enviroment
