### ISSUE TITLE
Setup Script Fails With Wrong Password

### ISSUE THREAD

**Issue by burkeholland** [NativeScript/nativescript-cli#2237] opened 2016-11-17 17:54 UTC
Trying to run the setup script fails after stating that it requires sudo permission and then asks for password. Each time I enter my password, it says, "Sorry, try again". This happens three times before the script fails. I verified that my password is being entered correctly.

### Environment

macOS 10.12.1
NativeScript 2.4
Node 4.4.7
npm 3.10.9

![burkeholland_ _burkeholland_hollandmac_ _-zsh_ _118x47_and_setup_script_fails_with_wrong_password_ _issue__2237_ _nativescript_nativescript-cli](https://cloud.githubusercontent.com/assets/686963/20401068/f972f1c8-acbc-11e6-8ddc-0c2dd8b43c2e.png)

**Comment by rosen-vladimirov** [comment] 2016-11-18 20:44
Hey @burkeholland ,
Did you execute `sudo npm install -g nativescript` or `npm install -g nativescript` when the prompt for password failed?

**Comment by PolCPP** [comment] 2016-11-25 20:14
It's happening to me too. But if i download the setup script and run it using ruby it seems to work fine (was using sudo the first time). 

Some of the times it was asking for password even before i told it to run the Setup script.

**Comment by giangdhwhtbr** [comment] 2016-12-02 05:09
Hi, do anyone has fixed this problem?

**Comment by Plamen5kov** [comment] 2016-12-08 13:08
Can anyone give steps to reproduce, because I can't seem to reproduce the faulty behavior?

**Comment by giangdhwhtbr** [comment] 2016-12-12 01:42
@Plamen5kov I 've solve this problem. I don't know why but you could run the failed command by yourself. Just copy the red line then run it with sudo.

**Comment by Plamen5kov** [comment] 2016-12-20 09:09
@giangdhwhtbr I believe this is more of a workaround, and until we have the steps to reproduce we can't fix the underlying problem.

**Comment by burkeholland** [comment] 2017-01-09 20:54
This happens even if I run `sudo npm install -g nativescript`. I there a log file or something else that I could attach here that might provide more information?

**Comment by demetrio812** [comment] 2017-02-06 22:01
Hello, this is still happening, not a great start for ppl evaluating NativeScript...

**Comment by KingAndroid** [comment] 2017-02-08 15:53
10.12.3, same error!
I was a patient with slow network speed for a hr, but met same error!
My head is spinning now!
Any solution for this?

**Comment by Plamen5kov** [comment] 2017-02-09 11:59
@KingAndroid still need steps to reproduce.

**Comment by etabakov** [comment] 2017-04-27 11:33
We are closing the issues as we still don't have steps to reproduce. Feel free to reopen if the issue arises again.

**Closed by etabakov** 2017-04-27 11:33 UTC
Labels: bug
