### ISSUE TITLE
Exceptions in Android app entry point are sporadically not shown in the terminal

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#4431] opened 2019-03-12 14:41 UTC
_From @vhristov5555 on August 10, 2018 8:54_

### Did you verify this is a real problem by searching the [NativeScript Forum]
yes

### Tell us about the problem
When an exception is thrown in the app entry points (e.g. app.js), the error is shown in the app error activity but sometimes it's not shown in the terminal.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: RC
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
1) Create new hello world js app.
2) Throw an exception in app.js.
3) Run the app (`tns run android`).
4) (Sometimes) The exception will be shown in the error activity, but not shown in the terminal.

_Copied from original issue: NativeScript/android-runtime#1150_

**Comment by NickIliev** [comment] 2019-03-12 14:41
_From @mbektchiev on March 12, 2019 14:23_

The issue is in {N} CLI. 

I've checked with the latest version from RC (5.2.3-2019-03-12-13015) and it still happens sporadically. The exception log always appears in `logcat`, but from time to time it's missing from CLI's output. 

It seems that pressing the home button to put the test app in the background before invoking `tns run android` increases the chance of reproducing the build but I'm not sure whether it matters at all.

**Comment by rosen-vladimirov** [comment] 2019-03-12 14:46
Duplicate of https://github.com/NativeScript/nativescript-cli/issues/3812

**Closed by rosen-vladimirov** 2019-03-12 14:46 UTC
Labels: bug, severity: low
