### ISSUE TITLE
Possible to pause device results

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli#2775] opened 2017-05-04 12:41 UTC
_From @sitefinitysteve on January 3, 2016 20:34_

On the device is there a way to maybe pause the results window to see the final pass\fail counts?  It closes pretty fast once it's done, and I don't love hunting through the terminal output :)

_Copied from original issue: NativeScript/nativescript-unit-test-runner#1_

**Comment by dtopuzov** [comment] 2017-05-04 12:42
_From @sitefinitysteve on January 3, 2016 21:17_

Is it also possible to hide the unit-test-runner stack stuff from the output as well?  I just kinda want to see the AssertionError itself, maybe the line it failed in my test script, nothing to do with "/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js"

NativeScript / 19 (4.4.4; Samsung Galaxy S5 - 4.4.4 - API 19 - 1080x1920) Outbreak Services returns webinars FAILED
    AssertionError: method not yet implemented
        at Context.<anonymous> (data/data/ca.leaplearning.OutbreakHelp/files/app/tests/services.js:50:15)
        at callFnAsync (eval at <anonymous> (data/data/ca.leaplearning.OutbreakHelp/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:209:21), <anonymous>:4222:8)
        at Test.Runnable.run (eval at <anonymous> (data/data/ca.leaplearning.OutbreakHelp/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:209:21), <anonymous>:4177:7)
        at Runner.runTest (eval at <anonymous> (data/data/ca.leaplearning.OutbreakHelp/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:209:21), <anonymous>:4661:10)
        at eval (eval at <anonymous> (data/data/ca.leaplearning.OutbreakHelp/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:209:21), <anonymous>:4768:12)
        at next (eval at <anonymous> (data/data/ca.leaplearning.OutbreakHelp/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:209:21), <anonymous>:4581:14)
        at eval (eval at <anonymous> (data/data/ca.leaplearning.OutbreakHelp/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:209:21), <anonymous>:4591:7)
        at next (eval at <anonymous> (data/data/ca.leaplearning.OutbreakHelp/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:209:21), <anonymous>:4523:14)
        at eval (eval at <anonymous> (data/data/ca.leaplearning.OutbreakHelp/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:209:21), <anonymous>:4559:5)
        at timeslice (eval at <anonymous> (data/data/ca.leaplearning.OutbreakHelp/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:209:21), <anonymous>:12326:27)
NativeScript / 19 (4.4.4; Samsung Galaxy S5 - 4.4.4 - API 19 - 1080x1920): Executed 5 of 5 (1 FAILED) (1.049 secs / 0.942 secs)

**Comment by dtopuzov** [comment] 2017-05-04 12:42
_From @BenElliottBV on March 9, 2016 13:40_

+1 from me on this, keeping the app open would be great

**Comment by dtopuzov** [comment] 2017-05-04 12:42
Same as: https://github.com/NativeScript/nativescript-unit-test-runner/issues/10
A lot of users prefer the opposite (including me). Pause is bad for CI.
Even if we change the default, we should have an option not to pause.

**Comment by rosen-vladimirov** [comment] 2020-01-14 07:08
Closing as duplicate of https://github.com/NativeScript/nativescript-cli/issues/1125

**Closed by rosen-vladimirov** 2020-01-14 07:08 UTC
Labels: feature, hacktoberfest, help wanted, severity: low, unit testing
