### ISSUE TITLE
Failed to verify bitcode error

### ISSUE THREAD

**Issue by tgpetrov** [NativeScript/nativescript-cli#3620] opened 2018-05-25 14:21 UTC
### Tell us about the problem
I get an error `Failed to verify bitcode in TNSCore.framework/TNSCore` every time I try to run the demo of a Pro UI plugin (for example `nativescript-ui-listview`) on a device. 

It seems to be related to the way the plugin is referenced. If I reference it from npm, demo’s `node_modules` include both `nativescript-ui-listview` and (its dependency) `nativescript-ui-core`, then the demo runs successfully. 

However if I reference it from its source directory, demo’s `node_modules` include only `nativescript-ui-listview`, but (its dependency) `nativescript-ui-code` is inside listview’s own `node_modules`, then I get the above error.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.2
- Cross-platform modules: 4.0.1
- Runtime(s): 4.0.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Clone this repo: https://github.com/NativeScript/nativescript-ui-listview
2. Go to `src`
3. Run `npm run demo.ios`

**Comment by DimitarTachev** [comment] 2018-07-11 10:47
Hi @tgpetrov,

Thanks for reporting this one. The issue is already fixed and the fix is available in the `@next` version of the NativeScript CLI which will be released with NativeScript `v4.2.0`. Please, reopen the issue if you experience the same problem with the above-mentioned CLI versions.

**Closed by DimitarTachev** 2018-07-11 10:47 UTC
Labels: bug, in progress
