### ISSUE TITLE
Command failed due to space in file path

### ISSUE THREAD

**Issue by Lukosenka** [NativeScript/nativescript-cli#470] opened 2015-05-07 18:04 UTC
The error occurs with most of the commands.
```
Command failed: C:\Windows\system32\cmd.exe /s /c "c:\Users\Lukas Rakauskas\AppD
ata\Roaming\npm\node_modules\nativescript\lib\common\resources\platform-tools\an
droid\win32\adb start-server"
'c:\Users\Lukas' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by RangerMauve** [comment] 2015-05-07 18:32
It's happening because you have a space in your name username. Not sure how it'd be fixed though :open_mouth:

**Comment by teobugslayer** [comment] 2015-05-08 08:44
Hi @Lukosenka,

we have reproduced the issue on our side and will fix it in one of our next public releases.

**Comment by Lukosenka** [comment] 2015-05-09 08:11
Thank you very much, can't wait to start app developing. :+1:

**Comment by rosen-vladimirov** [comment] 2015-05-11 09:03
Hi @Lukosenka,
As a workaround you may install Android SDK and add it to your PATH environment variable. This way we'll not call adb from nativescript-cli resources and everything should work fine.
I'm reopening this issue and I'll take care to close it once we have permanent fix for it in our code.
Hope this helps.

**Comment by saadeez** [comment] 2015-06-13 19:06
This issue is still exist. As I'm learning the Nativescript's Hello World but in 2nd step I stucked in "tns platform add android" it gives me the same error even I have set environmental variable for Android SDk but still getting this error dont know why?

**Comment by teobugslayer** [comment] 2015-07-14 13:14
Hello @saadeez, please run ```tns platform add --log trace > log.txt``` and send us the log.txt file (you can create a Gist, for example)

**Comment by rosen-vladimirov** [comment] 2015-07-27 11:33
The steps to reproduce this issue are:
1) Remove path to android-sdk from your PATH environment variable.
2) Install CLI locally in directory which has spaces in its name.
3) Try executing `tns device android` command (make sure that when you write `adb` in your terminal, you get output like: "command not found")

**Closed** 2015-07-30 12:18 UTC
Labels: 4 - Ready For Test, bug
