### ISSUE TITLE
Templates support

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#254] opened 2015-02-27 12:34 UTC
Currently only hello-world-template is supported. But actually we have 4 templates - Blank, Hello World, Master Detail, Tabbed App. It should be nice if we support all of them.

**Comment by shrimpywu** [comment] 2015-03-06 00:40
will be nice to have a typescript project template as well.

**Comment by ch-weiss** [comment] 2015-03-09 10:23
I  would appreciate TypeScript templates as well.

**Comment by rosen-vladimirov** [comment] 2015-12-16 21:56
Closing this one as duplicate of https://github.com/NativeScript/nativescript-cli/issues/374
Check the other thread for more details.

**Closed by rosen-vladimirov** 2015-12-16 21:56 UTC
Labels: 0 - Open, feature
