### ISSUE TITLE
Cannot destructure property 'version' of 'this.$projectDataService.getRuntimePackage(...)' as it is undefined.

### ISSUE THREAD

**Issue by karauda** [NativeScript/nativescript-cli#5391] opened 2020-09-20 18:49 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.8
 - Cross-platform modules: "@nativescript/angular": "10.0.0"
 - Android Runtime: -
 - iOS Runtime: "@nativescript/ios": "7.0.0"
 - Plugin(s): nativescript-ui-listview, nativescript-ui-sidedrawer

xCode12 / NS7 / Angular10

**Describe the bug**

App after upgrade NativeScript to v7 and Angular to v10, works perfect when building in debug mode - on emulator and on real iOS device. But when pushing app to TestFlight it is Crashing just after run. So I tried to run on emulator in release mode:

**tns run ios --release --clean --emulator**

And just after searching for devices I see an error:

**Cannot destructure property 'version' of 'this.$projectDataService.getRuntimePackage(...)' as it is undefined.**

**tns run ios** (without release parameter) works, app builded and working well on emulator.

**To Reproduce**

tns run ios --release --clean --emulator

**Expected behavior**

expected to work in release mode and on test flight

**Comment by karauda** [comment] 2020-09-20 19:04
Still the same:

` ✗ tns run ios --release --emulator                             
Searching for devices...
Cannot destructure property 'version' of 'this.$projectDataService.getRuntimePackage(...)' as it is undefined.
`

My nativescript.config.ts:

`import { NativeScriptConfig } from '@nativescript/core'

export default {
  id: 'com.xxxx',
  appResourcesPath: 'App_Resources',
  android: {
    v8Flags: '--expose_gc',
    markingMode: 'none',
  },
  appPath: 'src',
  ios: {
    id: 'com.xxxx',
    markingMode: 'none',
  },
} as NativeScriptConfig
`

**Comment by karauda** [comment] 2020-09-20 19:05
One more important comment - when I have multiple devices/emulators connected, I see the same error - but multiple times.

**Comment by rigor789** [comment] 2020-09-20 21:33
What's in your `package.json`?

**Comment by karauda** [comment] 2020-09-20 21:42
```
 "dependencies": {
    "@angular/animations": "~10.1.0",
    "@angular/common": "~10.1.0",
    "@angular/compiler": "~10.1.0",
    "@angular/core": "~10.1.0",
    "@angular/forms": "~10.1.0",
    "@angular/platform-browser": "~10.1.0",
    "@angular/platform-browser-dynamic": "~10.1.0",
    "@angular/router": "~10.1.0",
    "@nativescript/angular": "10.0.0",
    "@nativescript/core": "~7.0.0",
    "@nativescript/theme": "~2.5.0",
    "apollo-angular": "^1.10.0",
    "apollo-angular-link-http": "^1.11.0",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.10",
    "apollo-link": "^1.2.14",
    "core-js": "^3.6.0",
    "graphql": "^15.1.0",
    "graphql-tag": "^2.10.4",
    "nativescript-ui-listview": "^9.0.2",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.6.0",
    "tslib": "1.10.0",
    "zone.js": "^0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1001.0",
    "@angular/cli": "~10.1.0",
    "@angular/compiler-cli": "~10.1.0",
    "@nativescript/android": "7.0.0",
    "@nativescript/ios": "7.0.0",
    "@nativescript/tslint-rules": "~0.0.5",
    "@nativescript/webpack": "~3.0.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "node-sass": "^4.7.1",
    "protractor": "^7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "^5.20.1",
    "typescript": "~3.9.0"
  },
```

**Comment by karauda** [comment] 2020-09-20 21:43
Also, app builded without --release is working ultra fine, builded with --release is always crashing after splash.

**Comment by jwrascoe** [comment] 2020-09-22 15:50
@rigor789 I am also having the same issue, is there any work-around other than to build without --release?

**Comment by BlueHunter99** [comment] 2020-09-23 13:36
@rigor789 I seem to have a similar issue, but my error is `Cannot destructure property 'version' of 'undefined' or 'null'.`. It shows upon running `tns run` with the previous line being `Platform android/ios succesfully added. v7.0.0`

I can confirm this happens _only_ when the `--release` tag is present.
It is a problem on both Android and iOS in my case.

**Comment by farfromrefug** [comment] 2020-09-24 09:17
just got the same issue here. Here is the full error stack
```
Executing before-prepare hook at location /Volumes/dev/nativescript/ns-forecastie/hooks/before-prepare/nativescript-community-ui-material-core.js in-process
Validating before-prepare arguments.
Could not find an installed runtime, falling back to default runtimes
Error while executing action on device 3300f8ed286f148f. The error is TypeError: Cannot destructure property `version` of 'undefined' or 'null'.
    at PrepareController.<anonymous> (/usr/local/pnpm-global/4/node_modules/.pnpm/nativescript@7.0.8/node_modules/nativescript/lib/controllers/prepare-controller.js:283:19)
    at Generator.next (<anonymous>)
    at /usr/local/pnpm-global/4/node_modules/.pnpm/nativescript@7.0.8/node_modules/nativescript/lib/controllers/prepare-controller.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/pnpm-global/4/node_modules/.pnpm/nativescript@7.0.8/node_modules/nativescript/lib/controllers/prepare-controller.js:10:12)
    at PrepareController.trackRuntimeVersion (/usr/local/pnpm-global/4/node_modules/.pnpm/nativescript@7.0.8/node_modules/nativescript/lib/controllers/prepare-controller.js:282:16)
    at PrepareController.descriptor.<computed> (/usr/local/pnpm-global/4/node_modules/.pnpm/nativescript@7.0.8/node_modules/nativescript/lib/common/decorators.js:24:40)
    at PrepareController.<anonymous> (/usr/local/pnpm-global/4/node_modules/.pnpm/nativescript@7.0.8/node_modules/nativescript/lib/controllers/prepare-controller.js:86:24)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/pnpm-global/4/node_modules/.pnpm/nativescript@7.0.8/node_modules/nativescript/lib/controllers/prepare-controller.js:11:58) {
  deviceIdentifier: '3300f8ed286f148f'
}
```

**Comment by BlueHunter99** [comment] 2020-09-25 07:53
Did anyone find a workaround for this? Perhaps a different version or something like that. I have updated our entire app to NS7 and Angular 10, because NS6 wasn't playing nicely with iOS14 anymore for me. This seems like a pretty serious issue thats affecting multiple people but it doesn't seem to have much priority.

**Comment by NathanaelA** [comment] 2020-09-25 08:10
@BlueHunter99 - For NS 6.x, you can use the iOS 6.5.2 engine for IOS 14, we fixed that about a month ago...  

 As for the NS 7 cli, this is not the only issue that has occurred, iOS 14, and XCode 12 actually broke several more items when they were released...

**Comment by farfromrefug** [comment] 2020-09-25 08:12
@BlueHunter99 right now you can edit `nativescript/cliservices/project-data-service.js` . You need to find where it is installed on your computer.
Open it then look for `getInstalledRuntimePackage` function.
add this line at the begining of the method:
```
platform = platform.toLowerCase();
```
It should work now

**Comment by BlueHunter99** [comment] 2020-09-25 08:24
@NathanaelA Sorry for my passive agressiveness, tough morning.
I did use the 6.5.2 engine, which stopped the app from crashing on startup. I ran into other issues after that, which would freeze the app and half-crash the iOS keyboard UI. I spent a solid day debugging it but would get no errors whatsoever.
Decided to try to fix it by updating to NS7, and it is just very frustrating when the app works perfectly now but I'm unable to release it to my users.

@farfromrefug thanks, I'll try it out!

**Comment by NathanaelA** [comment] 2020-09-25 08:30
@BlueHunter99 - I have had many days like that.   No worries...   :grinning:     As an aside I use `iDeviceSysLog` to get sometimes the logs that sometimes NativeScript doesn't show you properly.    If the app crashes during startup; I have seen frequently where NS doesn't log the error; which is very annoying (imho) so idevcesyslog is invaluable for those cases.   

I also just wanted to let you know you could use NS 6 w/ 6.5.2 and it should work the same.   To our knowledge their weren't any other breaking changes in iOS 14 that breaks the 6.5.2 engine.  We do want people to be able to use both NS 6 until they feel comfortable moving to 7.    However, your report is the second mention I have seen of freezes on iOS --- so their might be something, I certain hope not....  :grinning:

**Comment by jwrascoe** [comment] 2020-09-25 12:24
@BlueHunter99 we too have been trying to go production with NS7 & Angular 10, working thur the issues... mainly syntax changes and package issues... but the --release was a deal breaker for us... so we backed back down to NS6 & Angular 8.   

I totally get your frustration as we have been switching back and fourth for the last 10 days...  

We are going to try the patch from @farfromrefug later to day and will let you know if we have any of the freezing issues when we build the --release code....  running it just as ns run ios/android was fine but need to test hard on the --release

**Comment by farfromrefug** [comment] 2020-09-25 13:57
@jwrascoe i did production releases for iOS and Android using the changes above plus the ones here https://github.com/NativeScript/NativeScript/issues/8875#issuecomment-698308608 for snapshot android builds.
I am using svelte and Vue but i dont think angular should make a difference.

**Comment by BlueHunter99** [comment] 2020-10-01 12:40
> We do want people to be able to use both NS 6 until they feel comfortable moving to 7. However, your report is the second mention I have seen of freezes on iOS --- so their might be something, I certain hope not.... 😀

@NathanaelA turns out the freezes were most likely caused by the AutoFitText plugin, because they still very rarely occurred in my NS7 version. Replacing all `AutoFitText` elements with normal `Label` elements has solved the crashing for me. I guess it's a nice thing that our app is now updated for the NS7 future already.

Will be reporting the bug of AutoFitText when I find some time. So far the only logs I've gotten out of it are from XCode:
```
HandleScope::HandleScope
Entering the V8 API without proper locking in place
```

**Comment by jwrascoe** [comment] 2020-10-01 12:59
@BlueHunter99 I finally had the time last night to switch our app back over...  All built fine however I used nativescript@7.0.9-rc.2 for the CLI and @nativescript/core@7.0.9 (just released last night) 

The patch from @farfromrefug for the CLI is still required to build --release 

All appears to be working, however I dont use the AutoFitText (but will try) 

I will publish later today into each app store and see if there is any drama

**Comment by BlueHunter99** [comment] 2020-10-01 13:04
@jwrascoe our app is waiting for review as we speak. Using the latest versions of the CLI and core with the manual patch from @farfromrefug.

**Comment by mreall** [comment] 2020-10-02 21:11
> @BlueHunter99 right now you can edit `nativescript/cliservices/project-data-service.js` . You need to find where it is installed on your computer.

@farfromrefug thanks for the tip. Where did you find `nativescript/cliservices/project-data-service.js`? I can't find it on my mac.

**Comment by mreall** [comment] 2020-10-02 21:35
I finally found it and was able to build my project. It was located here:
`/usr/local/lib/node_modules/nativescript/lib/services/project-data-service.js`

**Comment by jwrascoe** [comment] 2020-10-02 22:02
@BlueHunter99 we released to production today for both Android & iOS... no crashes.. all seems normal.

**Comment by jwrascoe** [comment] 2020-10-02 22:16
@mreall use find on the command line... 
`sudo find / -name project-data-service.js`

**Closed** 2020-10-02 23:13 UTC
Labels: bug
