### ISSUE TITLE
Devices.NotFoundDeviceByIndexErrorMessage / Couldn't attach debugger with modified options

### ISSUE THREAD

**Issue by WouterFlorijn** [NativeScript/nativescript-cli#3891] opened 2018-09-13 11:45 UTC
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

Yes, I have checked all similar issues like #976, #3679, and #3832, but none of the advice provided there works for me.

### Tell us about the problem

Whenever I try to USB debug my project on my OnePlus 6, it only compiles and opens the app once. Afterwards, the command line process stops with the following error:

```
Unable to apply changes on device: 16089e09. Error is: Devices.NotFoundDeviceByIndexErrorMessage 16088 tns.
```

With `--log trace`, I get the following output right above the error:

```
Couldn't attach debugger with modified options. { Error: Cannot read property 'kill' of null
    at DevicesService.<anonymous> (C:\Users\Wouter\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\mobile-core\devices-service.js:330:38)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Wouter\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\mobile-core\devices-service.js:11:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  allErrors:
   [ { TypeError: Cannot read property 'kill' of null
    at LogcatHelper.stop (C:\Users\Wouter\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\android\logcat-helper.js:75:73)
    at AndroidApplicationManager.stopApplication (C:\Users\Wouter\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\android\android-application-manager.js:106:28)
    at AndroidDebugService.<anonymous> (C:\Users\Wouter\AppData\Roaming\npm\node_modules\nativescript\lib\services\android-debug-service.js:153:50)
    at Generator.next (<anonymous>)
    at C:\Users\Wouter\AppData\Roaming\npm\node_modules\nativescript\lib\services\android-debug-service.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Wouter\AppData\Roaming\npm\node_modules\nativescript\lib\services\android-debug-service.js:3:12)
    at AndroidDebugService.debugStartCore (C:\Users\Wouter\AppData\Roaming\npm\node_modules\nativescript\lib\services\android-debug-service.js:152:16)
    at AndroidDebugService.<anonymous> (C:\Users\Wouter\AppData\Roaming\npm\node_modules\nativescript\lib\services\android-debug-service.js:131:28)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Wouter\AppData\Roaming\npm\node_modules\nativescript\lib\services\android-debug-service.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) deviceIdentifier: '16089e09' } ] }
```

I've tried downgrading my CLI, and Android runtimes to one or two minor releases earlier, but got the same issue. Note that this issue doesn't occur with an emulator.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.3
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0
- Plugin(s):
  - "nativescript-dev-webpack": "^0.15.0",
  - "nativescript-vue-template-compiler": "^1.3.1",
  - "nativescript-worker-loader": "~0.9.0",
- I'm using the `next` branch of the [vue-cli-template](https://github.com/nativescript-vue/vue-cli-template)

### Please tell us how to recreate the issue in as much detail as possible.

Create a new project using

```
vue init nativescript-vue/vue-cli-template#next <project-name>
```

Run using

```
tns debug android --bundle
```

**Comment by rosen-vladimirov** [comment] 2018-09-16 09:51
EDIT: It seems using lodash's `_.isNumber` breaks other functionality in CLI, so I had to apply some other changes in the `helpers.isNumber` method, you can check them [here](https://github.com/telerik/mobile-cli-lib/pull/1138).

**Comment by rosen-vladimirov** [comment] 2018-09-16 09:55
Hey @WouterFlorijn , I'm closing this thread as a duplicate of https://github.com/NativeScript/nativescript-cli/issues/3832, we can continue the discussion there.

**Closed by rosen-vladimirov** 2018-09-16 09:55 UTC
Labels: bug, debug, in progress
