### ISSUE TITLE
Android 1.5.0 doesn't build after adding Google Play Services & push notifications

### ISSUE THREAD

**Issue by AntonioCuevaUrraco** [NativeScript/nativescript-cli#1316] opened 2015-12-07 11:21 UTC
tns create myApp
tns platform add android@1.5.0
tns library add android /usr/local/Cellar/android-sdk/24.3.3/extras/google/google_play_services/libproject/google-play-services_lib/libs
tns plugin add nativescript-push-notifications
tns build android

:buildMetadata
Skip com.google.android.gms.cast.CastRemoteDisplayLocalService
	Error: android/support/v7/media/MediaRouter$Callback
Skip com.google.android.gms.cast.CastRemoteDisplayLocalService$1
	Error: android/support/v7/media/MediaRouter$Callback
Skip com.google.android.gms.internal.zzac
	Error: org/apache/http/client/HttpClient
Skip com.google.android.gms.internal.zzt
	Error: [Lorg/apache/http/Header;
Skip com.google.android.gms.internal.zzw
	Error: org/apache/http/HttpEntity
...
...
...
Skip com.google.android.gms.wearable.internal.zzx$zzc
	Error: com.google.android.gms.wearable.internal.zzx and com.google.android.gms.wearable.internal.zzx$zzc disagree on InnerClasses attribute
:copyMetadata
:generateNativescript-plugin-google-play-servicesNativescript-push-notificationsDebugAssets UP-TO-DATE
:mergeNativescript-plugin-google-play-servicesNativescript-push-notificationsDebugAssets
:generateNativescript-plugin-google-play-servicesNativescript-push-notificationsDebugResValues
:generateNativescript-plugin-google-play-servicesNativescript-push-notificationsDebugResources
:mergeNativescript-plugin-google-play-servicesNativescript-push-notificationsDebugResources
:processNativescript-plugin-google-play-servicesNativescript-push-notificationsDebugManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processNativescript-plugin-google-play-servicesNativescript-push-notificationsDebugManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 68; The prefix "android" for attribute "android:name" associated with an element type "uses-permission" is not bound.

**Comment by AntonDobrev** [comment] 2015-12-08 08:37
Hello @AntonioCuevaUrraco,

Perhaps the build error is produced by the clash of the Google Play Services SDK added as a separate module and the one that is being already added by the push plugin (since it is a dependency of the plugin). 

Could you please try with only adding the push plugin?

**Comment by AntonioCuevaUrraco** [comment] 2015-12-08 08:52
@AntonDobrev still not building 
tns create myApp
cd myApp
tns plugin add nativescript-push-notifications
tns build android

:buildMetadata
Skip com.google.android.gms.cast.CastRemoteDisplayLocalService
	Error: android/support/v7/media/MediaRouter$Callback
Skip com.google.android.gms.cast.CastRemoteDisplayLocalService$1
	Error: android/support/v7/media/MediaRouter$Callback
Skip com.google.android.gms.internal.zzac
	Error: org/apache/http/client/HttpClient
Skip com.google.android.gms.internal.zzt
	Error: [Lorg/apache/http/Header;
Skip com.google.android.gms.internal.zzw
	Error: org/apache/http/HttpEntity
Skip com.google.android.gms.internal.zzw$zza
	Error: org/apache/http/client/methods/HttpEntityEnclosingRequestBase
Skip com.google.android.gms.internal.zzx
	Error: org/apache/http/impl/cookie/DateParseException
Skip com.google.android.gms.internal.zzy
	Error: org/apache/http/HttpResponse
Skip com.google.android.gms.internal.zzz


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processNativescript-plugin-google-play-servicesNativescript-push-notificationsDebugManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 68; The prefix "android" for attribute "android:name" associated with an element type "uses-permission" is not bound.

**Comment by AntonioCuevaUrraco** [comment] 2015-12-08 09:05
Also there is some other people having problems with the same scenario.   
Without push working I can't update to 1.5 and there is some bugs that fix crash on the runtime that I have been waiting for...
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/nativescript/TJtjBo8hPC8/GxwHNyroCwAJ

**Comment by rosen-vladimirov** [comment] 2015-12-08 13:25
Hi @AntonioCuevaUrraco 
The problem is with the push-notifications plugin - we have just released a new version, so can you try 
```
tns plugin remove nativescript-push-notifications
tns plugin add nativescript-push-notifications
tns build android
```

**Comment by teobugslayer** [comment] 2015-12-10 13:12
As the new plugin should resolve the problem, I am closing this issue. Feel free to reopen it if you need further assistance.

**Closed by teobugslayer** 2015-12-10 13:12 UTC
Labels: bug, external

**Comment by AntonioCuevaUrraco** [comment] 2015-12-10 16:54
Sorry for the delay, yes the update in the plugin solve the building problem :-D Thank you guys for the fast reaction. We just finished the update to 1.5 and now starting the testing.

**Comment by fritzvd** [comment] 2016-03-18 07:31
Thanks for solving this!
@rosen-vladimirov
