### ISSUE TITLE
Offline trying to build error 

### ISSUE THREAD

**Issue by adriantether** [NativeScript/nativescript-cli#5125] opened 2019-11-11 10:13 UTC
**Environment**
trying to build in visual code ,

**Describe the bug**
building my code while connected to the internet is fine , when i disconnect and then try to rebuild the code i get the error below, is this correct do i always need to be online to build nativescript. ???

--- tns debug android
Command failed: npm view tns-core-modules  versions --json
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by KristianDD** [comment] 2019-11-12 16:26
Hi @adriantether ,
We had similar issue in NativeScript CLI v6.1.0, which is fixed in version 6.2.0. You can read more about the issue [here](https://github.com/NativeScript/nativescript-cli/issues/5026). After the first successful run, the following ones should succeed. Offline support for building NativeScript applications is not an official feature and might behave differently in future releases.

If the issue is still reproducible in Visual Studio Code after updating CLI to v6.2.0, please log a separate issue in https://github.com/NativeScript/nativescript-vscode-extension/issues.

**Closed** 2019-11-18 08:25 UTC
