### ISSUE TITLE
Support for Node.js 14.0.0 is not verified

### ISSUE THREAD

**Issue by asajuenitan** [NativeScript/nativescript-cli#5306] opened 2020-05-14 21:06 UTC
**Environment**
Manjaro Linux 20.0.1 Lysia
Node 14.0.0
npm 6.14.5

**Describe the bug**
`Support for Node.js 14.0.0 is not verified. NativeScript CLI might not install or run properly.

The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null
Error while reporting exception: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null
`

**To Reproduce**
`npm install -g nativescript`
or
`npm install -g nativescript@latest

**Comment by darylteo** [comment] 2020-05-19 05:59
On releases page 6.4.1 is the latest, but `tns --version` gives me 6.5.0.

Reverting to 6.4.1 does not resolve the issue.

Force installing Node v12 resolves issue but may not be the ideal solution for some.

**Comment by ThViana94** [comment] 2020-05-22 16:36
Having the same issue.
In my terminal, when I type tns --version, this is my result :
@arch ~]$ tsn --version
bash: tsn: command not found
[thiago@arch ~]$ tns --version
(node:7844) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7844) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:7844) Warning: Accessing non-existent property 'which' of module exports inside circular dependency

Support for Node.js 14.2.0 is not verified. NativeScript CLI might not install or run properly.

6.5.0

**Comment by asajuenitan** [comment] 2020-05-23 10:09
I was able to use this workaround
Using [nvm]("https://github.com/creationix/nvm")
Uninstall the latest version of your node if you are using Windows, not necessary for Unix Users 
Then, install the latest version of nvm using the instructions on the page.

## Steps
Install the specific version Nativescript requires `nvm install 12.16.3`
Doing this will make `node 12.16.3` default.
To use the latest version of node `nvm install node`
It'll install the two versions, you can check by using `nvm ls`
To use a specific installed version of node(for example v12) `nvm use 12.16.3`
What I did was create aliases so I can easily switch
`nvm alias n12 12.16.3` for v12
`nvm alias n14 14.3.0` for v14

switch to v12 `nvm use n12` and `npm install -g nativescript`
then create your Nativescript app `tns create AppName`

When you are done you switch back to latest version `nvm use n14`.
Hope this is fixed soon

**Comment by NathanWalker** [comment] 2020-05-30 06:10
Support for node 14 is now available in `v6.7.0` release 👍

**Comment by NathanWalker** [comment] 2020-05-30 07:29
I'm going to reopen this for few more days - the cli supports node 14 now but the underlying issue `The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null` as originally reported by @asajuenitan is related to another dep in the project stack and will close this once the other dependencies are totally clear of that 👍

**Comment by gravataLonga** [comment] 2020-05-30 07:53
I'm still have this problem, today. My node version is `14.3.0` on OSX, 
![Screenshot 2020-05-30 at 08 50 55](https://user-images.githubusercontent.com/1126525/83322862-d99a2f80-a252-11ea-9b9c-eac02fb2e45b.png). I'm starting today my first app on NativeScript! Oh yeah!! Let's go to build some fun :D

**Comment by NathanWalker** [comment] 2020-05-30 08:02
@gravataLonga please try `6.7.2` published now.
you can just `npm uninstall nativescript -g` to ensure prior version is totally removed and then install latest published just mins ago:
```
npm install nativescript -g
``

**Comment by NathanWalker** [comment] 2020-05-30 08:08
Closing as verified fix here - if you find further issue just let us know. Good luck on your first app @gravataLonga 🎉

**Closed by NathanWalker** 2020-05-30 08:08 UTC

**Comment by gravataLonga** [comment] 2020-05-30 08:14
@NathanWalker it's work! Thank you so much!! 

![Screenshot 2020-05-30 at 09 11 52](https://user-images.githubusercontent.com/1126525/83323286-9ee5c680-a255-11ea-89f0-2286139eeed9.png)

I have another issue non-related which is i don't have `tns` command in my system, i think is because of my `$PATH` isn't updated for years :D But rather than that this issue is resolved, i can confirm.
