### ISSUE TITLE
stack trace source map column resolving problem

### ISSUE THREAD

**Issue by vtrifonov** [NativeScript/nativescript-cli#4937] opened 2019-08-09 08:54 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.3
 - Cross-platform modules: 6.0.3
 - Android Runtime: 6.0.1
 - iOS Runtime: 6.0.2

**Describe the bug**
When the stack trace is output in the console and CLI tries to resolve the source file from bundle/vendor files the column is always resolved to 0

**To Reproduce**
1. Create empty app using `tns create test --js`
2. Add `console.trace("test");` in the `viewModel.onTap` method
3. Start the app and press the button

Output:
* Android
  * from `adb logcat`:
    ```
    08-09 11:44:55.971  3963  3963 E JS      : Trace: test
    08-09 11:44:55.971  3963  3963 E JS      : at viewModel.onTap (file:///data/data/org.nativescript.test/files/app/bundle.js:275:17)
    08-09 11:44:55.971  3963  3963 E JS      : at push.../node_modules/tns-core-modules/data/observable/observable.js.Observable.notify (file:///data/data/org.nativescript.test/files/app/vendor.js:3697:32)
    08-09 11:44:55.971  3963  3963 E JS      : at push.../node_modules/tns-core-modules/data/observable/observable.js.Observable._emit (file:///data/data/org.nativescript.test/files/app/vendor.js:3717:18)
    08-09 11:44:55.971  3963  3963 E JS      : at ClickListenerImpl.onClick (file:///data/data/org.nativescript.test/files/app/vendor.js:14601:23)
    ```

  * from CLI:
    ```
    JS: Trace: test
    JS: at viewModel.onTap file:///app/main-view-model.js:17:0
    JS: at push.../node_modules/tns-core-modules/data/observable/observable.js.Observable.notify file:///node_modules/tns-core-modules/data/observable/observable.js:107:0
    JS: at push.../node_modules/tns-core-modules/data/observable/observable.js.Observable._emit file:///node_modules/tns-core-modules/data/observable/observable.js:127:0
    JS: at ClickListenerImpl.onClick file:///node_modules/tns-core-modules/ui/button/button.js:29:0
    ```
* iOS
  * from Console app:
    ```
	CONSOLE TRACE file:///app/bundle.js:267:22: test
	1   onTap@file:///app/bundle.js:267:22
	2   notify@file:///app/vendor.js:3749:37
	3   _emit@file:///app/vendor.js:3769:24
	4   tap@file:///app/vendor.js:15424:24
	5   UIApplicationMain@[native code]
	6   _start@file:///app/vendor.js:782:26
	7   run@file:///app/vendor.js:810:11
	8   @file:///app/bundle.js:155:16
	9   ./app.js@file:///app/bundle.js:172:34
	10  __webpack_require__@file:///app/runtime.js:751:34
	11  checkDeferredModules@file:///app/runtime.js:44:42
	12  webpackJsonpCallback@file:///app/runtime.js:31:39
	13  anonymous@file:///app/bundle.js:2:61
	14  evaluate@[native code]
	15  moduleEvaluation@:1:11
	16  promiseReactionJob@:1:11
    ```
  * from CLI:
    ```
	CONSOLE TRACE file:///app/main-view-model.js:17:0 test
	1   onTap@file:///app/main-view-model.js:17:0
	2   notify@file:///node_modules/tns-core-modules/data/observable/observable.js:107:0
	3   _emit@file:///node_modules/tns-core-modules/data/observable/observable.js:127:0
	4   tap@file:///node_modules/tns-core-modules/ui/button/button.js:216:0
	5   UIApplicationMain@[native code]
	6   _start@file:///node_modules/tns-core-modules/application/application.js:277:0
	7   run@file:///node_modules/tns-core-modules/application/application.js:305:0
	8   @file:///app/app.js:46:0
	9   ./app.js@file:///app/bundle.js:172:34
	10  __webpack_require__@file:///app/webpack/bootstrap:750:0
	11  checkDeferredModules@file:///app/webpack/bootstrap:43:0
	12  webpackJsonpCallback@file:///app/webpack/bootstrap:30:0
	13  anonymous@file:///app/bundle.js:2:61
	14  evaluate@[native code]
	15  moduleEvaluation@:1:11
	16  promiseReactionJob@:1:11
    ```

**Expected behavior**
The column to be resolved correctly

**Additional context**
Seems like the resolving in **.js** files is not working as the location in **.ts** is correctly resolved.  Here's the log from TypeScript app with the same functionality:
```
JS: Trace: test
JS: at module.exports.push../main-view-model.ts.HelloWorldModel.onTap file:///app/main-view-model.ts:28:16
JS: at push.../node_modules/tns-core-modules/data/observable/observable.js.Observable.notify file:///node_modules/tns-core-modules/data/observable/observable.js:107:0
JS: at push.../node_modules/tns-core-modules/data/observable/observable.js.Observable._emit file:///node_modules/tns-core-modules/data/observable/observable.js:127:0
JS: at ClickListenerImpl.onClick file:///node_modules/tns-core-modules/ui/button/button.js:29:0
```

**Comment by rosen-vladimirov** [comment] 2019-09-09 05:42
We've investigated this case and the behavior is caused by webpack itself - when generating the source maps, the first statement on each row is marked as starting from column 0. In case there are multiple statements on the same line, the source maps for the next one are correct.
There's nothing we can do here, so I'm closing this issue. Feel free to reopen it in case you have further concerns.

**Closed by rosen-vladimirov** 2019-09-09 05:42 UTC
Labels: bug, device logs
