### ISSUE TITLE
nativescript installation overwrites .bash_profile if activating bash autocompletion.

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#2124] opened 2016-10-13 06:22 UTC
_From @adlh on October 13, 2016 6:6_

I noticed this because after installing nativescript my aliases stopped working on tmux. 

After a bit of looking around, I noticed, that the 3 lines here:

```
###-tns-completion-start-###
if [ -f /home/andrea/.tnsrc ]; then 
    source /home/andrea/.tnsrc  
fi 
###-tns-completion-end-###
```

... were correctly appended to .bashrc at the end of the file, But on my .bash_profile (which only had a line sourcing my .bashrc) the old content was gone, and having only the tns-completion block now.
Because tmux uses .bash_profile, then that was the reason my .bashrc wasn't being sourced anymore on tmux windows.  

So I'm almost sure, the problem was caused by the installation script from nativescript, even though I didn't found on the github source where the install process lives. So I couldn't verify this.

_Copied from original issue: NativeScript/NativeScript#2890_

**Comment by NickIliev** [comment] 2016-10-13 08:46
Hey @adlh,

We need some additional information about the OS you are using - are you using tmux on Windows 10?
We are currently working on some fixes for the installation and will keep you updated on that matter.

**Comment by adlh** [comment] 2016-10-13 10:26
Hi @NickIliev,

Of course. Sorry. I'm using Ubuntu 16.04. And, just for the record, I have no issues with tmux anymore after re-adding the line to my .bash_profile: `source ~/.bashrc` ... It's just, I guess if the installation script is just doing something like:

`echo '....' > ~/.bash_profile` 

instead of:
  
`echo '....' >> ~/.bash_profile`

Then it should be fixed ASAP before someone looses more than just a line (like in my case) :-)

**Comment by tzraikov** [comment] 2016-10-13 12:01
Hey @adlh, I just checked and indeed in some of our older versions we write directly in .bash_profile and .bashrc. That is not the case with our latest release 2.3.0 where this issue is addressed. Can you confirm that you are using this version?

**Comment by adlh** [comment] 2016-10-13 13:31
This is the output from the directory I installed the project:

```
andrea@bobo:~/angular-days/nativescript/WorkshopOne$ npm ls | grep native
├─┬ nativescript-angular@1.0.1
│ ├── nativescript-intl@0.0.4
├─┬ nativescript-dev-typescript@0.3.2
│ └─┬ nativescript-hook@0.2.1
```

**Comment by tzraikov** [comment] 2016-10-13 13:48
You should have also the latest version of NativeScript CLI. You can check the version by executing: `tns --version`

**Comment by adlh** [comment] 2016-10-13 14:39
Yes. That's right:

```
$ tns --version
2.3.0
```

**Comment by tzraikov** [comment] 2016-10-24 10:36
@adlh We were not able to reproduce the issue locally. Could you, please try executing the following CLI commands:
`tns autocomplete enable --log trace`
`tns autocomplete disable --log trace`

Send us the log trace if the issue can be reproduced consistently.

**Comment by adlh** [comment] 2016-11-28 13:26
@tzraikov ok, I finally did the tests for adding/removing auto completion, but I couldn't reproduce the problem either, so I guess you can close the issue.
Thanks!

**Closed** 2016-11-29 16:01 UTC
Labels: question
