### ISSUE TITLE
cli v 7.1.2 fresh projects broken ns create 

### ISSUE THREAD

**Issue by aquinn637** [NativeScript/nativescript-cli#5475] opened 2021-01-18 14:47 UTC
Environment

macOS Big Sur v 11.1

node -v
v12.18.4

ns -v
7.1.2

ns create new-app-2

cd new-app-2

I opened my Android emulator from Android Studio.

ns run android
```

System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
System.err: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:107)
System.err: 	at android.os.Looper.loop(Looper.java:214)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
System.err: Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err: 	at com.tns.Module.bootstrapApp(Module.java:316)
System.err: 	at com.tns.Runtime.run(Runtime.java:680)
System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
System.err: 	... 8 more
System.err: Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
System.err: 	at com.tns.Module.resolvePathHelper(Module.java:151)
System.err: 	at com.tns.Module.bootstrapApp(Module.java:314)
System.err: 	... 12 more

```

This is a fresh project created by the cli.

**Comment by rigor789** [comment] 2021-01-18 15:50
Fixed by https://github.com/NativeScript/nativescript-cli/pull/5466 - will be merged&released very soon.

**Closed** 2021-01-26 18:20 UTC

**Comment by erodriguezh** [comment] 2021-03-23 07:58
Unfortunately I just came across this issue on cli version 7.2.1

**Env**
OS: macOS Catalina 10.15.7
Node: 12.13.1
NS: 7.2.1

**Steps**
1. ns create ns-ng-base --ng
2. cd ns-ng-base
3. ns run android

Run it on an Android 10 device

`System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
System.err: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:107)
System.err: 	at android.os.Looper.loop(Looper.java:214)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
System.err: Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err: 	at com.tns.Module.bootstrapApp(Module.java:316)
System.err: 	at com.tns.Runtime.run(Runtime.java:680)
System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
System.err: 	... 8 more
System.err: Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
System.err: 	at com.tns.Module.resolvePathHelper(Module.java:151)
System.err: 	at com.tns.Module.bootstrapApp(Module.java:314)
System.err: 	... 12 more
Successfully synced application org.nativescript.xoloapp on device 5083f661.`
