### ISSUE TITLE
-bash: tns: command not found (Mac OS X 10.11.5)

### ISSUE THREAD

**Issue by brendalynharper34** [NativeScript/nativescript-cli#1814] opened 2016-06-08 06:27 UTC
I've seen people posting this same exact issue and I've followed the installation documents to the very last period. For some strange reason, I still cannot run any tns commands after the nativescript CLI installation. 

These are the version of node.js and npm installed
$ node -v
v4.4.5
$ npm -v
2.15.5

Any suggestions??

**Comment by enchev** [comment] 2016-06-08 07:23
Hey @brendalynharper34,

Do you get any errors when you call `npm install nativescript -g`?

**Comment by brendalynharper34** [comment] 2016-06-08 19:19
@enchev I didn't get any errors when I ran the command but after installation, I was still unable to use the "tns doctor" command

**Comment by dtopuzov** [comment] 2016-06-08 20:36
@brendalynharper34 how did you run the installation, please attach logs

**Comment by rosen-vladimirov** [comment] 2016-06-08 20:38
@brendalynharper34 also during installation you'll see where the CLI is installed (usually the path is written just above the dependency tree printed at the end of the installation). Can you verify that the directory where tns executable is created is in your PATH environment variable?

**Comment by brendalynharper34** [comment] 2016-06-09 02:18
@rosen-vladimirov I got it to work! So yeah, I had to change my PATH environment variable for the tns executable.. Thank you so much!!

**Comment by rosen-vladimirov** [comment] 2016-06-09 06:18
@brendalynharper34 I'm glad the issue is resolved. I'm closing it now, but feel free to reopen it in case you have any problems or concerns.

**Closed by rosen-vladimirov** 2016-06-09 06:18 UTC

**Comment by har1s1m** [comment] 2016-07-18 17:41
Hey, I got the same problem. Tns commands don't work. 
How to change PATH variable? What to insert?
