### ISSUE TITLE
CLI@next fails to install with npm@3.10.8

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#2980] opened 2017-07-17 07:25 UTC
Caused by: https://github.com/NativeScript/nativescript-cli/pull/2979 (https://github.com/NativeScript/nativescript-cli/commit/82d6abcfcf07d915ab0e798909aa0ebafb700055)

Steps:
```
npm i nativescript@next
```

Details:
```
npm --version
> 3.10.8
```

Output:
```
15:37:51 ##### OUTPUT BEGIN #####
15:37:51 
15:37:51 C:\Jenkins\workspace\CLI-stable-tests-smoke-windows
15:37:51 `-- (empty)
15:37:51 
15:37:51 npm WARN enoent ENOENT: no such file or directory, open 'C:\Jenkins\workspace\CLI-stable-tests-smoke-windows\package.json'
15:37:51 npm WARN CLI-stable-tests-smoke-windows No description
15:37:51 npm WARN CLI-stable-tests-smoke-windows No repository field.
15:37:51 npm WARN CLI-stable-tests-smoke-windows No README data
15:37:51 npm WARN CLI-stable-tests-smoke-windows No license field.
15:37:51 npm ERR! Windows_NT 10.0.10586
15:37:51 npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "C:\\Jenkins\\workspace\\CLI-stable-tests-smoke-windows\\sut\\nativescript.tgz"
15:37:51 npm ERR! node v6.9.1
15:37:51 npm ERR! npm  v3.10.8
15:37:51 npm ERR! code EBADPLATFORM
15:37:51 
15:37:51 npm ERR! notsup Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
15:37:51 npm ERR! notsup Valid OS:    darwin
15:37:51 npm ERR! notsup Valid Arch:  any
15:37:51 npm ERR! notsup Actual OS:   win32
15:37:51 npm ERR! notsup Actual Arch: x64
15:37:51 
15:37:51 npm ERR! Please include the following file with any support request:
15:37:51 npm ERR!     C:\Jenkins\workspace\CLI-stable-tests-smoke-windows\npm-debug.log
15:37:51 npm ERR! code 1
15:37:51 
15:37:51 ##### OUTPUT END #####
```

**Comment by rosen-vladimirov** [comment] 2017-07-17 19:25
The problem is with npm itself and some specific versions. The problem is reproducible with npm 3.10.8, but not with 3.10.10. Some npm versions do not handle optional dependencies correctly (it looks like 3.10.8) is one of the problematic.

I'm marking this as known issue. The solution is - update your npm version.

**Comment by dtopuzov** [comment] 2017-08-02 08:26
Closing as known issue.

**Closed by dtopuzov** 2017-08-02 08:26 UTC
Labels: bug
