### ISSUE TITLE
Internal error: TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by MiroValchev** [NativeScript/nativescript-cli#435] opened 2015-04-23 14:11 UTC
When I try to debug app on a connected Android device using CLI: tns debug android --debug-brk
I keep getting "Internal error: TypeError: Cannot convert a Symbol value to a string" when trying to navigate to a page for instance. If I use tns run android the app is running just fine. I can't figure out what's the problem but it's impossible to debug. Any ideas what might be the cause?

**Comment by benchik** [comment] 2015-04-29 18:02
Happens to me as well

**Comment by teobugslayer** [comment] 2015-05-04 10:36
Hello @MiroValchev , @benchik ,

It looks like this was [fixed in the Android runtime](https://github.com/NativeScript/android-runtime/commit/f93c8b6296848d2fcc39ecaa43b29f0ddec5cab7) in time for the [1.0 release](https://github.com/NativeScript/android-runtime/commits/release). Can you update to 1.0 and verify that debugging works?

**Comment by benchik** [comment] 2015-05-04 10:38
Works! Thanks!

**Comment by teobugslayer** [comment] 2015-05-15 15:26
> But project files must be copied manually to a new project.

@benchik, we should be able to silently update every released version of {N}. Please open an issue describing the exact problem and steps to reproduce. If possible, give us a small sample project reproducing the case. I am closing this issue for now.

**Closed by teobugslayer** 2015-05-15 15:26 UTC
