### ISSUE TITLE
Android package name mismatch issues

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/nativescript-cli#2187] opened 2016-11-01 19:31 UTC
This is kind of difficult to explain, but here is what I did and couldn't figure it out for a couple hours until it dawned on me what I did couple days ago.

I was running livesync, all was going well and then I started to prep for releasing the app so I changed the package name in the package.json, and I forgot to change it in the `app.gradle` located in *app_resources/android*. I had forgotten all about app.gradle that I set the package name there weeks ago when I started the app. So it's value didn't match what the package.json value for the app was. So I did my build, started to livesync and the CLI synced everything but the app was not launching (obvious now) but it threw me off for a while. 

You all will know better than I on maybe some informational message to the user about this when the CLI is running, most people won't remember to track that down cause they probably rarely touch app.gradle. Curious to hear what you all think, if you need more info let me know.

**Comment by dtopuzov** [comment] 2017-08-02 08:42
Looks to be duplicate of https://github.com/NativeScript/nativescript-cli/issues/2825.
Warning message will be added with https://github.com/NativeScript/android-runtime/pull/810

**Closed by dtopuzov** 2017-08-02 08:42 UTC
Labels: Android, livesync
