### ISSUE TITLE
tns doctor shows warning about ant

### ISSUE THREAD

**Issue by unlight** [NativeScript/nativescript-cli#960] opened 2015-09-24 11:52 UTC
Windows 8.1, tns 1.3.0

>WARNING: Apache Ant is not installed or is not configured properly.
>You will not be able to build your projects for Android.
>To be able to build for Android, download and install Apache Ant and
>its dependencies as described in http://ant.apache.org/manual/index.html

https://github.com/NativeScript/nativescript-cli#windows
But instruction tells install gradle.

**Comment by gabbered** [comment] 2015-09-24 17:28
having same issue

**Comment by ligaz** [comment] 2015-09-24 21:24
Thanks for the report. Since 1.3 Ant is not a dependency for Android builds. 

Actually the fix for this warning is trivial. You just have to [delete those lines](https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/doctor-service.ts#L28-L36). If any of you wants to submit a Pull Request we will be more than glad to merge it.

**Comment by rosen-vladimirov** [comment] 2015-09-25 11:24
Hi, in fact this issue is duplicate of https://github.com/NativeScript/nativescript-cli/issues/941 
I've already created pull request for this change - https://github.com/NativeScript/nativescript-cli/pull/965

**Comment by rosen-vladimirov** [comment] 2015-09-28 11:08
Ok, this is fixed in master, so I'm closing the issue. Thanks for reporting it :)

**Closed by rosen-vladimirov** 2015-09-28 11:08 UTC

**Comment by gabbered** [comment] 2015-09-29 16:13
:+1:
