### ISSUE TITLE
Livesync starts the app twice on iOS devices

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/nativescript-cli#1956] opened 2016-07-27 12:44 UTC
1. Create an app and add ios platform and navigate to the app's folder
2. Deploy the app on the device and make sure it is not opened
3. Run `tns livesync`

Expected result: App is started and synced with current state
Actual result: Splash screen is opened, closed and opened once again

**Comment by dtopuzov** [comment] 2016-08-23 09:55
Works for me with {N} 2.1.1

**Comment by slavchev** [comment] 2016-11-15 11:41
ping @pkoleva @dtopuzov 

Can we close this issue?

**Comment by pkoleva** [comment] 2017-01-03 07:21
Hey guys, would you please stop moving this issue as Ready for Test and have a look at it. It is still reproduced in 2.5 master. The issue reproduces when the app is already installed on the device.

**Comment by Plamen5kov** [comment] 2017-02-09 16:01
fixed by: https://github.com/NativeScript/nativescript-cli/pull/2484

**Comment by pkoleva** [comment] 2017-03-23 11:33
Issue still reproducible (3.0) with run command as well

**Comment by rosen-vladimirov** [comment] 2017-04-24 08:04
As @Plamen5kov  described - the problem is with the GDB server on device - if the application is not runnning, calling `stopApplication` starts it and stops it after that. That causes the blink effect (double restart). As we cannot detect if application is currently running (and skip `stopApplication` in case it is not), we always call `stopApplication`. So I'm closing this issue as we cannot fix it.

**Closed by rosen-vladimirov** 2017-04-24 08:04 UTC
Labels: bug, livesync
