### ISSUE TITLE
--watch not working

### ISSUE THREAD

**Issue by IvRRimum** [NativeScript/nativescript-cli#1933] opened 2016-07-18 15:50 UTC
Hello,

So a few days i started this app and --watch was working just fine until today.

This is what i call: tns run android --emulator --device=ANDROID --watch

but when i change code, nothing happens, my changes are not present.
When i run tns doctor, it shows that everything is up to date except ios emulator( witch i am not using at this time ).

**Comment by IvRRimum** [comment] 2016-07-18 17:35
Nobody ? Ideas ?

**Comment by IvRRimum** [comment] 2016-07-18 21:00
Just tried to reinstall the app( from git ) and re-created the avd. still --watch not working.

**Comment by NickIliev** [comment] 2016-07-19 06:22
Hello @IvRRimum 

You are using **_run_** instead of **_livesync_** The command to execute your app and watch for changes is the following

```
tns livesync android --watch
```

If you want to pass a specific device you can do it with the --device key and an ID of the device
For example
woth 
```
tns device

│ # │ Device Name │ Platform │ Device Identifier    │ Type     │ Status    │
│ 1 │ vbox86p     │ Android  │ 192.168.206.102:5555 │ Emulator │ Connected │
│ 2 │ vbox86p     │ Android  │ 192.168.206.101:5555 │ Emulator │ Connected │

```
Now you pass as id 1 to run your app on this specific device 
For example:
```
tns livesync android --watch --device 1
```

**Comment by IvRRimum** [comment] 2016-07-19 08:20
@NickIliev THANKS! However, everytime it syncs the changes, after it reverts all my code changes..

**Comment by IvRRimum** [comment] 2016-07-19 08:30
@NickIliev Update: It only undoes my code changes, when i stop the tns livesync.. and start it again. How does one fix that ?

**Comment by NickIliev** [comment] 2016-07-19 08:39
@IvRRimum are you truuing to sunc changes made to XML or CSS files - if so I suspect you have reproduced the issue discussed at [https://github.com/NativeScript/nativescript-cli/issues/1907](https://github.com/NativeScript/nativescript-cli/issues/1907)

This bug with livesync not syncing XML and CSS files is now fixed and the fix will be released with our next release.

**Comment by IvRRimum** [comment] 2016-07-19 09:13
@NickIliev Okey, what i am suposed to do now ? I need this working today or i am getting an ass kicking from my boos ;[

**Comment by NickIliev** [comment] 2016-07-19 09:57
@IvRRimum you can install our next **nativescript-cli** where the bug-fix is applied.
Here are the steps to achive taht (notice taht this will install tns v.2.2.0 which is not official release yet)

```
mkdir latest-cli
cd latest-cli
git clone https://github.com/NativeScript/nativescript-cli
cd nativescript-cli
git submodule update --init
npm install
grunt
```

Now let's assume your folder **_latest-cli_** is located in your **D:** partition
In order to run your project with the latest cli you should give your full path to the **tns** executable
For example:
```
D:\latest-cli\nativescript-cli\bin\tns livesync --watch android
```

Now your project will be livesynced with tns v2.2.0 where the fix for livesync is implemented.

**Comment by IvRRimum** [comment] 2016-07-19 10:06
@NickIliev Thanks, will try that. P.S I am using linux

**Comment by IvRRimum** [comment] 2016-07-19 10:08
karlis@karlis-SATELLITE-L750 ~/Projects/my-instagram/latest-cli/nativescript-cli $ git submodule update --init
Cloning into 'lib/common'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:telerik/mobile-cli-lib.git' into submodule path 'lib/common' failed

**Comment by NickIliev** [comment] 2016-07-19 10:15
Hey @IvRRimum 

This error is caused more likely because you do not have SSH key set to your github.
Check this discussion where the solution is described : [https://github.com/NativeScript/nativescript-cli/issues/1916#issuecomment-232360061](https://github.com/NativeScript/nativescript-cli/issues/1916#issuecomment-232360061)

Basically, you need to set an SSH key in [https://github.com/settings/keys](https://github.com/settings/keys)
Here is a github how-to add new SSH key : [https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/)

**Comment by IvRRimum** [comment] 2016-07-19 10:20
but this step is optional. Also why do i need grunt ? when i run without grunt i get:

karlis@karlis-SATELLITE-L750 ~/Projects/my-instagram/latest-cli/nativescript-cli $ ~/Projects/my-instagram/latest-cli/nativescript-cli/bin/tns livesync android --watch --device=emulator-5554
module.js:440
    throw err;
    ^

Error: Cannot find module '../lib/nativescript-cli.js'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/karlis/Projects/my-instagram/latest-cli/nativescript-cli/bin/nativescript.js:4:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

**Comment by IvRRimum** [comment] 2016-07-19 10:22
Also, grunt fails


Note:  You may wish to enable the suppressImplicitAnyIndexErrors grunt-ts option to allow dynamic property access by index.  This will suppress TypeScript error TS7017.
>> 1995 non-emit-preventing type warnings  
>> Error: tsc return code: 2
Warning: Task "ts:devlib" failed. Use --force to continue.

**Comment by IvRRimum** [comment] 2016-07-19 10:34
Great, this broke all of my previous tns installations.

Now when i run tns:

karlis@karlis-SATELLITE-L750 ~/Projects/my-instagram/latest-cli/nativescript-cli $ tns
module.js:440
    throw err;
    ^

Error: Cannot find module './common/verify-node-version'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js:4:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

**Comment by NickIliev** [comment] 2016-07-19 10:38
Grunt is automation tool which runs a set of tasks which otherwise should be run manually by the user.
Without running **grunt** command your CLI won't be installed properly as those tasks won't be executed.

As for your grunt error - this error log is discussed here [https://github.com/NativeScript/nativescript-cli/issues/250](https://github.com/NativeScript/nativescript-cli/issues/250) you can check if the solution is working out for your environment.

If you want to revert to tns 2.1.0 run
```
npm uninstall -g nativescript
npm install -g nativescript
```

**Comment by IvRRimum** [comment] 2016-07-19 11:13
I followed your instructions( including grunt ). Now when i run ~/Projects/my-instagram/latest-cli/nativescript-cli/bin/tns livesync android --watch --device=emulator-5554

My changes is still reverted... Is nativescript-cli still in beta or something ?

**Comment by NickIliev** [comment] 2016-07-19 11:23
@IvRRimum 

Can you give us more detailed information about your issue:
1.)  is it CSS, XML or js/ts file that you are changing?
2.) What do you mean by reverting!? There is no logic in the CLI to revert changes made by the user in their files. Can you explain step by step what is happening in your project?  As far as I understand 
 - you are making a change to your code
 - you are running **tns livesync --watch android**
 - your changes are not applied to your project (!?)
 - your code is reverted back to the state before changes (!?)

Is that what's happening?

**Comment by IvRRimum** [comment] 2016-07-19 11:26
1) Yes, i have an nativescript( with angular2 ), i change .js files( and maybe and .html file sometimes ).
2) For example, when the command tns livesync... is running i change something - it ussualy syncs. But when i stop the command and run command again. All my changes are lost( witch i made while i was in sync ).

**Comment by IvRRimum** [comment] 2016-07-19 11:30
Like everytime i run the livesync command, it takes the old changes. It's probably that i am being moronic, not doing something correctly ?

**Comment by NickIliev** [comment] 2016-07-19 11:44
@IvRRimum 
We will investigate further the issue you are having.(we were able to reproduce it locally on one machine) and I will follow up when we have a solution/fix. 
In our case the changes made to the code are NOT lost - they are not applied but still present in the places they are made.

As a temp workaround, you can rebuild your app after stopping **livesync**.
To do that remove the **platform** folder and then execute your new livesync/run command.
This will force your app to be built with your last changes.

Can you also give us more details about the environment you are working on 
(like OS, Node.js version, npm version)

**Comment by IvRRimum** [comment] 2016-07-19 11:50
P.S My current monkey-pached workflow: I run livesync, code my stuff, but if i need to restart livesync command i commit eveything. Then i run livesync, wait till it reverts all my changes, then git reset --hard after it syncs i can work again.


DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
cat: /etc/upstream-release: Is a directory

node - v6.0.0

npm - 3.10.5


Thanks, ping me, if you have some news.

Thanks for help! I still can work further and that's what matter right now.

**Comment by IvRRimum** [comment] 2016-07-19 11:53
P.S I was wrong, it is still not working... ;//

**Comment by IvRRimum** [comment] 2016-07-19 12:08
As i see it now, it looks like its some kind of cache, do you have cache somewhere in there ? How can i clear it ?

**Comment by NickIliev** [comment] 2016-07-19 12:26
Hey @IvRRimum 
Try the following flow:
- run **tns livesync --watch android**
- make some changes in your code and **save** (you should see the changes in your emulator/device)
- **stop** your livesync (ctrl + c)

at this moment your changes should be present in your IDE (VSCode or what you are using). There is no code in our CLI that can revert changes made in your files. If at this point you do not have your changes saved in your files then you should probably check your local permission settings for writing/reading files.
- remove the **platforms** folder ( `rm -rf platforms` )
- rebuild your app **tns run android**

At this point, all changes should be applied and your attached device/emulator should present them.

Please do not hesitate to report back on how your environment is responding to this workflow.

**Comment by harlankoehn** [comment] 2016-07-19 12:46
@IvRRimum I noticed you said you're using Angular2 but made changes to .js files. I don't know what .js files you're talking about for sure. Angular2 usually uses TypeScript (.ts) files and those compile/transpile to .js. If you make a change to one of those .js files, then when the transpiler runs on the .ts file, you'll lose those changes you made in your .js. I'm assuming you know this already, but just in case you don't, I thought I would mention it.

There has been a bug reported (not sure the number or if its open anymore) that sometimes the NativeScript "compile" process doesn't pick up changes to certain files, usually .xml/.html files and it ends up putting old versions in the .apk (android). I've seen this myself and did eventually resolve the issue though I never figured out what I did that resolved it (I tried a lot of different things). It could be this is the issue you're having and I think it's the issue that @NickIliev is eluding to in his replies.

**Comment by IvRRimum** [comment] 2016-07-19 12:54
@burkeholland Didn't know that... Will try, right now the app just woun't. Will try to fix.

**Comment by IvRRimum** [comment] 2016-07-19 13:43
Yes, that was it. But ofcourse i have 1 more last problem...

Now when i start application up, it shows error:

Failed to find module 'nativescript-angular/application', relative to 'app/tns_modules'

I tryed to add code references.d.ts file: /// <reference path="./node_modules/nativescript-angular/application.d.ts" /> Needed for autocompletion and compilation.

No luck.. Any ideas ? Last problem.

**Comment by NickIliev** [comment] 2016-07-19 13:54
@IvRRimum glad to hear that you have resolved your main issue! Kudos to @harlankoehn !

As for your current problem - You should reset your **platforms** folder
```
tns platform remove android
tns platform add android
```
or
```
rm -rf platforms
tns platform add android
```
and then rebuild your app to install all dependencies including nativescript-angular/application'
```
tns run android
```
The situation is explained [here](nativescript-angular/application')

**Comment by IvRRimum** [comment] 2016-07-19 14:00
Did what you sayd, still the same problem ;///

**Comment by IvRRimum** [comment] 2016-07-19 14:02
Also the link is dead ;/

**Comment by IvRRimum** [comment] 2016-07-19 16:26
Problem is still there.. ://

**Comment by NickIliev** [comment] 2016-07-20 06:30
@IvRRimum can you paste the content of your package.json
You can try to remove your node_modules (as the nativescript-angular/application is not present in your project) and then rebuild your project. If this does not solve your problem you can send us your sample project (Github link or here with archive) to test it locally (again no need to upload **platforms** and **node_modules** folders)

**Comment by NickIliev** [comment] 2016-07-21 08:44
Hey @IvRRimum I have noticed you have posted a question about working with nativescript-firebase plugin - are your problems discussed here resolved?

**Comment by IvRRimum** [comment] 2016-07-21 09:12
Hey, yeah. I just followed the tutorial video. I still have 1 error in console, but it doesn't effect the app's functionality. So thats wierd. Thanks!

**Closed** 2016-07-21 11:16 UTC
Labels: question

**Comment by francisrod01** [comment] 2018-06-02 23:34
I think a tsc watch compilation is necessary to me.
