### ISSUE TITLE
Is it necessary to copy all modules from node_modules directory, including devDependencies?

### ISSUE THREAD

**Issue by unlight** [NativeScript/nativescript-cli#1143] opened 2015-11-04 18:22 UTC
I have this `package.json`
```js
{
	"nativescript": {
		"id": "org.nativescript.test1",
		"tns-android": {
			"version": "1.4.0"
		}
	},
	"dependencies": {
		"tns-core-modules": "1.4.0"
	},
  "devDependencies": {
    "babel": "^5.8.29",
    "gulp-debug": "^2.1.2"
  }
}
```
I have some `devDependencies` modules, and of course, after install, they are placed `to node_modules`. After build, all of them are copied to `platforms\android\src\main\assets\app\tns_modules\`. (app-debug.apk contains it too)
I'm using `devDependencies` modules for building and testing only.

Is it really necessary to copy them all?

**Comment by rosen-vladimirov** [comment] 2015-11-04 18:25
Hi @unlight ,

May I ask you for your version of nativescript-cli? By default CLI does not copy devDependencies to CLI modules. 
Can you try removing node_modules dir and executing `tns build android` and see if the devDependencies will be placed under `platforms\android\src\main\assets\app\tns_modules` (CLI will create node_modules for you)?

**Comment by rosen-vladimirov** [comment] 2015-11-04 18:31
Also you can remove `platforms` dir alongside with `node_modules` so you'll have clean project :)

**Comment by unlight** [comment] 2015-11-04 18:53
My tns version is 1.4.3.
> Can you try removing node_modules dir and executing tns build android and see if the 
> devDependencies will be placed under platforms\android\src\main\assets\app\tns_modules
After I done this, `tns build android` command hangs.
I done some more experiments, and it looks like
1. items from `/node_modules` are copying to `platforms\android\src\main\assets\app\tns_modules\.
2. items from `app/node_modules` are copying to `platforms\android\src\main\assets\app\node_modules\`
And it seems that in both case, tns ignores settings in `package.json`

**Comment by NathanaelA** [comment] 2015-11-06 21:47
I'm not with Telerik, but The app/node_modules is no longer used.  This was depreciated in v1.30, I believe.  Any node_modules you are using should be moved out to the main node_modules.   the app/node_modules folder is now treated as any other normal folder in the app/ folder and everything will be copied...

**Comment by rosen-vladimirov** [comment] 2015-11-09 22:37
Hi @unlight ,
@NathanaelA  is absolutely right. Anything inside app directory is included in the application itself. Defining anything in root's package.json as devDependency means that it will not be included in `platforms\android\src\main\assets\app\tns_modules`
In case you find different behavior, can you send us a sample reproducing the unexpected behavior?

**Comment by unlight** [comment] 2015-11-10 06:27
Seems that it is weird if it happens for me. I'll try to dig this.

**Comment by unlight** [comment] 2015-11-11 19:22
I tried to reproduced it using clean project. Is not reproduced.

**Comment by unlight** [comment] 2016-01-04 17:13
Reopening.
Looks like `tns build` work as follow:
It copies all node_modules except those which are defined in `devDependencies`.

But npm3 comes with flatten dependencies.
Event if I install by npm3 as devDependency one module, node_modules can contain dozen of other directories (all of them will be copied to `platforms\android\src\main\assets\app\tns_modules`)

I think it is an issue, npm3 released a long time ago.

*How to repeat:*
1. Create project `tns create demo1143`
2. `cd demo1143 & mkdir node_modules\dummy & cd node_modules\dummy`
3. Create any js file with package.json (touch 1.js & npm init)
4. `tns build android`
5. Check `platforms\android\src\main\assets\app\tns_modules\`. Directory `dummy` is here. Why? It is not defined as any dependency anywhere.

**Comment by rosen-vladimirov** [comment] 2016-01-05 06:37
Hi @unlight ,

Thanks for sharing the steps to reproduce. In fact there are two different "issues" here. The first one is related to npm3 as you have noticed. It really flattens the dependencies and when we process them, we do not know if they are from dependencies or devDependencies section of any module. The issue occurs whenever you install npm package with `npm i` (when you are using npm 3). The workaround is to remove `node_modules` directory and execute your `tns` command, for example `tns build android`. One of the first steps that we execute during preparing the project is to ensure all dependencies are installed. In case you do not have `node_modules` directory, we'll install the dependencies with the npm version that we have in our nativescript-cli (2.14.12 - https://github.com/NativeScript/nativescript-cli/blob/master/package.json#L57). This way all packages will be installed correctly (as we are using npm 2)  and we'll prepare them correctly in the native project.
The other issue is one implementation detail in our logic - when we process `node_modules` we get all directories (and subdirectories and subsubdirectories, etc.) and we filter only the ones that are devDependency of any package. When a package in node_modules is not defined anywhere in any package.json, we do not filter it as it is not defined as devDependency.

Hope this makes sense for you :)

**Comment by rosen-vladimirov** [comment] 2016-01-26 16:35
As the question had been answered and currently this is the expected workflow, I'm closing this issue.

**Closed by rosen-vladimirov** 2016-01-26 16:35 UTC

**Comment by irwansyahwii** [comment] 2018-11-17 07:18
I think this issue must be open again since I found out if we install npm module as a dev dependency then it won't get copied to the tns_modules folder hence it will run error at run time. So the fix is to remove the platform and re-add it again and install the module as a runtime dependency.
