### ISSUE TITLE
Livesync - Unable to livesync on device XYZ

### ISSUE THREAD

**Issue by cime** [NativeScript/nativescript-cli#738] opened 2015-08-03 16:43 UTC
On Samsung Galaxy S6 with Android 5.1.1 and Samsung Galaxy Tab S (SM-T805) with Android 5.0.2 I get this message:

    Unable to livesync on device XYZ. Consider upgrading your device OS.

The problem is in this line:
https://github.com/NativeScript/nativescript-cli/blob/9276b515231ecf0965e78b8721bc959f294e41c0/lib/services/usb-livesync-service.ts#L42

Some info:
https://code.google.com/p/android/issues/detail?id=58373
http://visualgdb.com/KB/?ProblemID=nopkg

Temp fix - remove this line https://github.com/NativeScript/nativescript-cli/blob/9276b515231ecf0965e78b8721bc959f294e41c0/lib/services/usb-livesync-service.ts#L45

**Comment by teobugslayer** [comment] 2015-08-06 15:25
Hello @cime,

We are aware of the problem and prepared a fix. You can track he changes [here](https://github.com/NativeScript/nativescript-cli/issues/742).

The fix will be included in our next release, which we plan to release tomorrow. Of course, if we find a critical bug, we may postpone the release.

**Comment by vchimev** [comment] 2015-08-19 08:27
Hi @cime,

the problem is resolved in {N} CLI version 1.2.2 or later. Closing this issue, may be reopened if needed.

**Closed by vchimev** 2015-08-19 08:27 UTC
Labels: 3 - Done, bug
