### ISSUE TITLE
'iTunes is not installed...' on Windows when using the '--device' flag

### ISSUE THREAD

**Issue by Pip3r4o** [NativeScript/nativescript-cli#2361] opened 2016-12-19 13:03 UTC
The following message is output when starting up a NativeScript application using the NS CLI, or when polling for the connected devices using `tns devices` on Windows OS:

"`iTunes is not installed. Install it on your system and run this command again.`" - the message is obviously harmless, but can be very misleading, and is absolutely irrelevant to application development on Windows machines.

**Comment by dtopuzov** [comment] 2017-05-05 08:18
No such message with {N} 3.0.0

**Comment by NathanaelA** [comment] 2017-06-29 20:37
This also occurs  by default with just a `tns run android` (v3.1) on windows also.

**Comment by dtopuzov** [comment] 2017-07-24 10:56
Hi @NathanaelA this issue should be fixed in `nativescript@next`

**Comment by dtopuzov** [comment] 2017-07-24 11:12
Hi @NathanaelA 

The issue is fixed in `nativescript@next`.

CLI will not show `iTunes is not installed` when you run:
- `tns device android`
- `tns run android`

CLI will still show it when you run:
- `tns device`

**Closed** 2017-07-26 06:49 UTC
Labels: bug

**Comment by cfguimaraes** [comment] 2018-10-23 09:16
Ok, alright.
Thanks for the reply.
