### ISSUE TITLE
calling `tns deploy android` twice runs webpack and gradle builds again

### ISSUE THREAD

**Issue by vtrifonov** [NativeScript/nativescript-cli#4985] opened 2019-08-28 09:48 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.3

**Describe the bug**
If you deploy an app to an android device using `tns deploy android` and then without making any changes run the same command (for the same device) again webpack and gradle build are run again.

**To Reproduce**
```bash
tns deploy android
tns deploy android
```

**Expected behavior**
When you run deploy command once and then run it again for the same device, the apk built with the first run should be reused without running any new builds if there are no changes

**Comment by KristianDD** [comment] 2019-10-25 15:38
Hi @vtrifonov ,
This behavior is expected and by design. A Webpack compilation is executed, without checking if there are changes or not. In order to integrate the newly generated assets(js, css and other) files inside the apk that will be installed we need to start a new build.

The `run` command will skip the build operation as the newly produced assets files will be synced by the LiveSync operation.

**Closed by KristianDD** 2019-10-25 15:38 UTC
