### ISSUE TITLE
Error occurs when i run command "tns run android --emulator" in Ubuntu

### ISSUE THREAD

**Issue by dowinning** [NativeScript/nativescript-cli#328] opened 2015-03-16 12:14 UTC
Main error info was here:
-----------------------------------------------------------------
 
BUILD FAILED
/usr/local/android/android-sdk-linux/tools/ant/build.xml:653: The following error occurred while executing this line:
/usr/local/android/android-sdk-linux/tools/ant/build.xml:698: null returned: 1

Total time: 1 second
Command ant failed with exit code 1
 
-----------------------------------------------------------------

Will you tell me what happened and how to correct this.
Thanks a lot.

**Comment by rosen-vladimirov** [comment] 2015-03-16 12:22
Hi @dowinning ,
This is a known issue, that had been discussed here: https://github.com/NativeScript/nativescript-cli/issues/299 The problem is with values-v21 directory when you are targeting android sdk below 21. We've already prepared a fix for this issue and it will be included in our next release. Meanwhile you can use the workaround that's been discussed in https://github.com/NativeScript/nativescript-cli/issues/299

**Comment by rosen-vladimirov** [comment] 2015-03-16 12:22
I'm closing this thread now, you can write your comments regarding this problem in https://github.com/NativeScript/nativescript-cli/issues/299 or in case you think this one is another issue, you can reopen it.

**Closed by rosen-vladimirov** 2015-03-16 12:22 UTC
