### ISSUE TITLE
Problem installing pod on El Capitan. 

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-cli#1045] opened 2015-10-12 08:39 UTC
_From @charalamposc on October 9, 2015 12:23_

I followed the steps described here https://www.nativescript.org/blog/using-cocoapods-is-a-piece-of-cake-with-nativescript-1.3.0 but I encounter the error:
```
Creating project scheme...
Installing pods...
Processing node_modules failed. Error:Error: Command failed: /bin/sh -c pod install
dyld: warning, LC_RPATH @executable_path/../../../../../../../SharedFrameworks in /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
```

_Copied from original issue: NativeScript/NativeScript#910_

**Comment by Fatme** [comment] 2015-10-13 15:38
Hi @charalamposc,

It seems that this is issue with CocoaPods on El Capitan  https://github.com/CocoaPods/CocoaPods/issues/4121

**Comment by charalamposc** [comment] 2015-10-14 05:34
Yes, I am using El Capitan. I never tried it out with yosemite.

**Comment by teobugslayer** [comment] 2016-01-05 12:29
The issue is considered [resolved](https://github.com/CocoaPods/CocoaPods/issues/4121#issuecomment-142202448) in CocoaPods and I am closing this one.

**Closed by teobugslayer** 2016-01-05 12:29 UTC

**Comment by borislemke** [comment] 2017-06-19 05:40
Even though this thread is almost 2 years old, I ran into this issue with Cocoapod -v 1.2.0, upgrading to 1.3.0 resolved it for me.
Running macOS Sierra
