### ISSUE TITLE
Export fails for Xcode 9

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/nativescript-cli#3061] opened 2017-08-14 12:44 UTC
The export options plist has additional fields:
```
    provisioningProfiles : Dictionary

        For manual signing only. Specify the provisioning profile to use for each executable in your app. Keys in this dictionary are the bundle identifiers of executables; values are the provisioning profile name or UUID to use.
```

When performing a build with `--provision` option, or if provision is specified in the .xcconfig, the signing mode is switched from auto to manual. The CLI commands for `tns build|run ios` do an Xcode build and then Xcode export.

The solution would be to add provisioningProfiles dictionary with the app id key and provision UUID or identifier here:
https://github.com/NativeScript/nativescript-cli/blob/381b35ebd276c7e1eb412f95e268626902efca58/lib/services/ios-project-service.ts#L256-L264

**Comment by dtopuzov** [comment] 2017-08-14 14:50
Close as duplicate of https://github.com/NativeScript/nativescript-cli/issues/3046

**Closed by dtopuzov** 2017-08-14 14:50 UTC
