### ISSUE TITLE
Chrome-devtools crashes when click on Global Listeners

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#2453] opened 2017-01-26 11:40 UTC
### Prerequisites:
- installed {N} CLI 2.5.0

### Workflow:
```shell
tns create appJS
cd appJS
tns debug android/ios
```
- open chrome-devtools URL in Chrome
- click on Global Listeners in the right pane

### Error:
```
Framework Event Listeners API Errors:
	devtoolsFrameworkEventListeners call produced error: ReferenceError: Can't find variable: self
	fetcher call produced error: ReferenceError: Can't find variable: Nod
```

### ADB logcat:
https://gist.github.com/vchimev/c39e715fbb11450227caa52ed3e19569

**Comment by Pip3r4o** [comment] 2017-01-26 13:34
@vchimev these should probably be posted in the respective runtime repos.

**Comment by KristinaKoeva** [comment] 2017-02-02 07:31
I am not able to reproduce this for iOS. Would you also share the iOS log ?

**Comment by Pip3r4o** [comment] 2017-02-02 08:03
The android devtools no longer crash with a fix available in the `master` branch, but `self` still isn't evaluated. I'll see what we can do about that.

**Comment by Pip3r4o** [comment] 2017-02-27 15:48
Addressed in the android-runtime with https://github.com/NativeScript/android-runtime/pull/698

**Closed** 2017-02-27 15:49 UTC
Labels: bug
