### ISSUE TITLE
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/nativescript-cli#4115] opened 2018-11-08 18:47 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0
 - Cross-platform modules: 4.0
 - Android Runtime: 4.0
 - iOS Runtime: 4.0
 - Plugin(s): GridView

**Describe the bug**
So after the upgrade to NS CLI 5.0 the GridView plugin started failing CI builds: 
https://travis-ci.org/PeterStaev/NativeScript-Grid-View/jobs/452440840#L1936
For all other plugins I had to upgrade android runtime to 28, and after that all is working fine, but here seems a different problem. 

**To Reproduce**

**Expected behavior**

**Sample project**
You can use the demo apps in the GridView repo. 

**Additional context**

**Comment by KristianDD** [comment] 2018-11-09 17:48
Hi @PeterStaev ,
I investigated the issue and found that it is related to the code inside the `include.gradle` file of the plugin. There is a breaking change in `NativeScript CLI` version `5.0.0`, which is described in detail in the [release changelog](https://github.com/NativeScript/nativescript-cli/blob/master/CHANGELOG.md#breaking). Older version of CLI(<5.0.0) always provided Android support library version to the `Gradle build`, but since 5.0.0 CLI no longer passes this argument to the build.

This causes [this line](https://github.com/PeterStaev/NativeScript-Grid-View/blob/8573b95dbd7472fe1d116a5fe75a441e2a61a512/platforms/android/include.gradle#L2) in the `include.gradle` to set `supportVer` to `+`, which later resolves to Android support library `28.0.0`, because of [this dependency](https://github.com/PeterStaev/NativeScript-Grid-View/blob/8573b95dbd7472fe1d116a5fe75a441e2a61a512/platforms/android/include.gradle#L3). The error is caused because `tns-core-modules` version `4.x.x` are not compatible with Android support library `28.0.0`.

We are still investigating which is the best approach to fix such issues.  One option for fixing the issue is to change  [this line](https://github.com/PeterStaev/NativeScript-Grid-View/blob/8573b95dbd7472fe1d116a5fe75a441e2a61a512/platforms/android/include.gradle#L2) to:
```Groovy
def supportVer = project.hasProperty("supportVersion") ? supportVersion : "26.0.0-alpha1";
```
This should work with `tns-core-modules` version `4.x.x` and `5.x.x`(Gradle will fallback to  Android support library `28.0.0` for the latter), but we are not sure this is the optimal solution and will post more information once we try and evaluate all options.

**Comment by PeterStaev** [comment] 2018-11-09 18:50
Thanks for the info @KristianDD ! I will wait further info before I decide to make the change. At the end it is not a problem to bump a major version for the plugin to make it work under both NS version 😃

**Comment by KristianDD** [comment] 2018-11-16 14:03
Hi @PeterStaev,
After further research this seems like the best approach that takes advantage of the built-in dependency resolution of `Gradle`, i.e.
```Gradle
def supportVer = project.hasProperty("supportVersion") ? supportVersion : "26.0.0-alpha1";
``` 
Will close the issue with the provided solution. If you experience any further issues don't hesitate to reopen the issue and write back to us.

**Closed by KristianDD** 2018-11-16 14:03 UTC
