### ISSUE TITLE
tns livesync ios --emulator --watch doesn't sync changes

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#776] opened 2015-08-12 12:26 UTC
Hey all,

After 1.2.2 `tns livesync ios --emulator` works great, but if I add the `--watch` flag the iOS simulator no longer reflects my changes. The watcher works, and the simulator reloads, but my changes are not present.

`tns livesync android --emulator --watch` works as expected.

Thanks.

**Comment by Fatme** [comment] 2015-08-12 13:47
Hi @tjvantoll ,

Can you give us more information about your iOS simulator - device type, sdk version? I've just tested `tns livesync ios --emulator --watch` command with `iPhone-4s/ iOS 7.1` and `iPhone 6 Plus/ iOS 8.4` and it works as expected.

**Comment by tjvantoll** [comment] 2015-08-12 14:01
I'm using the default on my machine, which is an iPhone-4s running iOS 8.4. It's odd because `tns livesync ios --emulator` works, but with the `--watch` flag those changes don't make it to the app. I'm going to try playing with some other device combinations.

**Comment by tjvantoll** [comment] 2015-08-12 14:18
I made a short video to show this in action: https://www.dropbox.com/s/odfkf9rvrj26dqp/livesync-issue.mov?dl=0

**Comment by Fatme** [comment] 2015-08-12 14:20
I've tested `iPhone-4s/ iOS 8.4` and it works as expected. Can you execute `tns livesync ios --emulator --watch --log trace` and send us the output?

**Comment by tjvantoll** [comment] 2015-08-12 14:24
Looking at the logs myself it seems I'm actually running the iOS 8.1 simulator, which I'm not sure how that happened. Let me get an iOS 8.4 simulator running and get back with you.

Thanks for the quick help.

**Comment by tjvantoll** [comment] 2015-08-12 14:31
Hmmmm... I made sure to run an iOS 8.4 simulator and I had the same issue. Here's a log of me making a single change: https://gist.github.com/tjvantoll/6a29fb6d77eb22050b97.

**Comment by tjvantoll** [comment] 2015-08-12 14:51
Just tried on a new project and this command works as expected, which is odd. I had updated the previous project to use the 1.2.1 iOS runtime. I'm still playing with this to try to see what's up.

**Comment by Fatme** [comment] 2015-08-12 15:04
We've reproduced the problem using `Groceries sample`. The problem is with nested folders. We've moved `login.js` file from `views/login/login.js` file to `app/login.js` which is wrong location. I'm preparing a fix that will be released ASAP.

**Closed** 2015-08-17 08:08 UTC
Labels: 3 - Done, bug

**Comment by xuezier** [comment] 2016-02-23 15:39
tns --version:1.6.1
tns livesync ios --emulator --watch, js file has changed,but not sync

**Comment by vchimev** [comment] 2016-02-24 10:06
Hi @xuezier,

I am not aware and not able to reproduce such a problem with NativeScript 1.6.1 . Could you please open a new issue if you are still experiencing it?

Thank you.

**Comment by xuezier** [comment] 2016-02-24 11:07
yes,I tried many time but still experiencing this problem.
now, I open a new issue at https://github.com/NativeScript/nativescript-cli/issues/1532

**Comment by ecabrera1** [comment] 2016-09-22 16:11
I have run tns livesync ios --emulator --watch and it launches the emulator and the groceries app launches but then immediately closes. Any suggestions?

**Comment by asterizk** [comment] 2016-09-22 18:18
@ecabrera1 Maybe you're running into this? https://github.com/NathanWalker/angular2-seed-advanced/issues/230
