### ISSUE TITLE
Following Xcode linker error, cli throws irrelevant usage suggestion 

### ISSUE THREAD

**Issue by stephenfeather** [NativeScript/nativescript-cli#1000] opened 2015-10-03 15:09 UTC
### Background
While working on a plugin, using 1.4.0 (pulled 2015-oct-2), I'm working through some framework dependencies.  If the xcode linker throws an error, I'm presented with nativescript-cli help suggestions that don't match the actual problem. 

### Command run
```
tns emulate ios --device iPhone-5
```

### Log output
```
Command xcodebuild failed with exit code 65
Analytics statuses:
{ TrackFeatureUsage: 1, TrackExceptions: 0 }
Trying to track feature 'CLI' with value 'help'.
List of registered commands: /?, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, create, debug, debug|android, debug|ios, deploy, device, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, emulate, emulate|android, emulate|ios, error-reporting, help, init, install, library, library|add, livesync, platform, platform|add, platform|remove, platform|update, plugin, plugin|add, plugin|remove, prepare, run, run|android, run|ios, usage-reporting
Reading help for command 'emulate|ios'. FileName is 'emulate-ios.md'.
# emulate ios
┌─────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Usage   │ Synopsis                                                                                                      │
│ General │ $ tns emulate ios [--path <Directory>] [--device <Device Name>] [--available-devices] [--release] [--timeout] │
└─────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

Builds the specified project and runs it in the native iOS Simulator.

### Options

    * --available-devices - Lists all available device type identifiers for the current Xcode.
    * --release - If set, produces a release build. Otherwise, produces a debug build.
    * --path - Specifies the directory that contains the project. If not specified, the project is searched for in the current directory and all directories above it.
    * --device - Specifies the name of the iOS Simulator device on which you want to run your app. To list the available iOS Simulator devices, run $ tns emulate ios --available-devices
    * --timeout - Sets the number of seconds that the NativeScript CLI will wait for the iOS Simulator to start before quitting the operation and releasing the console. The value must be a positive integer. If not set, the default timeout is 90 seconds.

### Attributes

    * <Device Name> is the name of the iOS Simulator device on which you want to run your app as listed by $ tns emulate ios --available-devices
```

### System Information
```
Exec uname -a
 stdout: Darwin Stephens-iMac.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64

 stderr:
Exec npm -v
 stdout: 2.13.2

 stderr:
spawn: java -version
Exec node-gyp -v
 stdout:
 stderr: /bin/sh: node-gyp: command not found

Exec xcodebuild -version
 stdout: Xcode 7.0.1
Build version 7A1001

 stderr:
Exec pod --version
 stdout: 0.38.2

 stderr:
Exec adb version
 stdout: Android Debug Bridge version 1.0.32
Revision eac51f2bb6a8-android

 stderr:
Exec android -h
 stdout:
       Usage:
       android [global options] action [action options]
       Global options:
  -s --silent     : Silent mode, shows errors only.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -h --help       : Help on a specific command.

                                                                    Valid
                                                                    actions
                                                                    are
                                                                    composed
                                                                    of a verb
                                                                    and an
                                                                    optional
                                                                    direct
                                                                    object:
-    sdk              : Displays the SDK Manager window.
-    avd              : Displays the AVD Manager window.
-   list              : Lists existing targets or virtual devices.
-   list avd          : Lists existing Android Virtual Devices.
-   list target       : Lists existing targets.
-   list device       : Lists existing devices.
-   list sdk          : Lists remote SDK repository.
- create avd          : Creates a new Android Virtual Device.
-   move avd          : Moves or renames an Android Virtual Device.
- delete avd          : Deletes an Android Virtual Device.
- update avd          : Updates an Android Virtual Device to match the folders
                        of a new SDK.
- create project      : Creates a new Android project.
- update project      : Updates an Android project (must already have an
                        AndroidManifest.xml).
- create test-project : Creates a new Android project for a test package.
- update test-project : Updates the Android project for a test package (must
                        already have an AndroidManifest.xml).
- create lib-project  : Creates a new Android library project.
- update lib-project  : Updates an Android library project (must already have
                        an AndroidManifest.xml).
- create uitest-project: Creates a new UI test project.
- update adb          : Updates adb to support the USB devices declared in the
                        SDK add-ons.
- update sdk          : Updates the SDK by suggesting new platforms to install
                        if available.

 stderr:
Exec mono --version
 stdout: Mono JIT compiler version 4.2.0 (Stable 4.2.0.179/a224653 Sun Sep 13 20:00:34 PDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen

 stderr:
Exec git --version
 stdout: git version 2.6.0

 stderr:
Exec gradle -v
 stdout:
------------------------------------------------------------
Gradle 2.7
------------------------------------------------------------

Build time:   2015-09-14 07:26:16 UTC
Build number: none
Revision:     c41505168da69fb0650f4e31c9e01b50ffc97893

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_51 (Oracle Corporation 25.51-b03)
OS:           Mac OS X 10.11 x86_64


 stderr:
Exec javac -version
 stdout:
 stderr: javac 1.8.0_51

System information:
{ procInfo: 'nativescript/1.4.0-non-ci',
  platform: 'darwin',
  os: 'Darwin Stephens-iMac.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64\n',
  shell: '/bin/bash',
  dotNetVer: null,
  procArch: 'x64',
  nodeVer: 'v0.12.6',
  npmVer: '2.13.2',
  javaVer: '1.8.0',
  nodeGypVer: null,
  xcodeVer: 'Xcode 7.0.1\nBuild version 7A1001\n',
  itunesInstalled: true,
  cocoapodVer: '0.38.2\n',
  adbVer: 'Android Debug Bridge version 1.0.32',
  androidInstalled: true,
  monoVer: '4.2.0',
  gitVer: '2.6.0',
  gradleVer: '2.7',
  javacVersion: '1.8.0_51' }
```

**Comment by Fatme** [comment] 2015-10-05 08:51
Hi @sfeather,

I've noticed this message `Command xcodebuild failed with exit code 65`  in your log output. Actually the real error should be above this message. Can you send us the full log ?

**Comment by sfeather** [comment] 2015-10-07 10:41
Fatme, the 'real error' is a linker error due to build.xcconfig not being merged from a plugin properly. I'll open an issue regarding that when I can confirm and reproduce. This issue remains, that the cli is making command line param suggestions that would in no way resolve the linker issue.

CLI should be grabbing the error from the link process, know that it occurred in xcode, and not assume that there was an error in the nativescript cli command formatting.

**Comment by dtopuzov** [comment] 2016-06-06 13:44
@stephenfeather can you confirm this is still valid and if so please provide exact steps to reproduce.

**Closed** 2016-06-13 07:31 UTC
Labels: Plugins, xcode

**Comment by inuwas** [comment] 2016-06-24 14:53
The developers of Nativescript need to improve their documentation. TNS emulate deletes files permanently. I had a project almost completed in Xcode and decided to use the command line and without a warning tns emulate deleted all my work. The installation is a nightmare, there are no instructions on how to use to use virtualbox or what that useless genymotion does. Genymotion won't start, only God knows what gradle does or why it needs to be installed for the android emulator to work. Your tutorials online have zero troubleshooting tips and the lessons are definitely not for beginners. 
Are you guys telling me that with all your skills, you don't have a one size fits all installer and a simple Hello World tutorial, which does not torment and make mental cases out ordinary enthusiasts?
