### ISSUE TITLE
Java error with more recent NativeScript versions on Ubuntu.

### ISSUE THREAD

**Issue by ztkavc** [NativeScript/nativescript-cli#909] opened 2015-09-12 15:09 UTC
When I upgrade to the latest version of NativeScript i get warning:
WARNING: The Java Development Kit (JDK) is not installed or is not configured properly.
If I then add platform to my project I get error:
Error executing command 'java'. Make sure you have java installed and added to your PATH.
Affected are only more recent versions (1.2.2, 1.2.3 and 1.2.4).
Java is properly installed and previous versions of NativeScript (1.2.0, 1.2.1) are working fine.

Tested on system with:
- Ubuntu 14.04, 64bit
- node: 0.10.40

**Comment by khagesh** [comment] 2015-09-13 05:11
Installed latest version on Ubuntu 15.04 and facing the same issue, any workaround?

**Comment by rosen-vladimirov** [comment] 2015-09-13 15:17
Hi, 
Can you check if you can execute the following command in your terminal:
```java -h```
Also can you check if your JAVA_HOME environment variable is set correctly (```echo $JAVA_HOME```).
You have to add the path to your Java bin directory to your PATH environment variable in order to get it work.

Hope this helps.

**Comment by ztkavc** [comment] 2015-09-13 21:31
Hello rosen-vladimirov,
as I wrote I can use {N} only up to 1.2.1 version and I also wrote that I do have Java properly installed as I can develop in older {N} versions and in Java.

Thank you for your help.

**Comment by Fatme** [comment] 2015-09-14 07:51
Hi guys,

You can try to use this https://github.com/telerik/mobile-cli-lib/commit/834e65ddd67435981cc0717a9e85eff9ae6d3a78 as workaround.

**Comment by fritzvd** [comment] 2015-09-14 13:23
Thank you @Fatme. and @ztkavc .. I just went back to 1.2.1. At least stuff's running now. I've been running around in circles editing my ~/.bashrc like a madmen, before stumbling upon this.

**Comment by nthrnth** [comment] 2015-09-18 06:33
Same error here on Ubuntu 15.04 and node 0.12.7 tns 1.3.0
JAVA_HOME is set correctly (points to jdk folder), also PATH=...:...:$JAVA_HOME/bin.
tns platform add android produces: Error executing command 'java'. Make sure you have java installed and added to your PATH.
I'm giving up

**Comment by nthrnth** [comment] 2015-09-18 09:38
Finally, I solved this problem by uninstalling jayatana (or you can just run sudo rm /usr/share/upstart/sessions/jayatana.conf). Now when I run `java -version` that annoying `Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar ` disappeared and tns platform add android works like a charm.
Answer can be found here: https://askubuntu.com/questions/650548/remove-annoying-environment-variable-java-tool-options/650597#650597

**Comment by fritzvd** [comment] 2015-09-21 07:28
YESSHHH! Thank you. That kicked that bug right in the face. 

Also after rm-ing the conf or the package. It's advisable to restart some services or just the OS. For me it kept looking for jayatana, after removal.

**Comment by teobugslayer** [comment] 2015-10-23 07:18
Thanks for finding out the root cause of the problem and sharing the information with is! I am closing this issue, as it seems resolved.

**Closed by teobugslayer** 2015-10-23 07:18 UTC
