### ISSUE TITLE
{N}3 tns debug android not launching app

### ISSUE THREAD

**Issue by jeffswitzer** [NativeScript/nativescript-cli#2763] opened 2017-05-03 21:30 UTC
### Tell us about the problem
tns debug android --device 1 --debug-port=40000 doesn't launch a newly created app on android device.

### Which platform(s) does your issue occur on?
only checked Android on windows 10

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.0
- Cross-platform modules: 3.0.0
- Runtime(s): 3.0.0

### Please tell us how to recreate the issue in as much detail as possible.
tns create MyApp --ng
tns run android (works correctly)

However when I run tns debug android --device 1 --debug-port=40000 The app doesn't launch on my android device. The console shows:

```
Searching for devices...
iTunes is not installed. Install it on your system and run this command again.
Your application will be deployed only on the device specified by the provided index or identifier.
Executing before-prepare hook from C:\Users\Jeff\MyApp\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
Preparing project...
Project successfully prepared (Android)
Skipping package build. No changes detected on the native side. This will be fast!
Skipping install.
Executing before-livesync hook from C:\Users\Jeff\MyApp\hooks\before-livesync\nativescript-angular-sync.js
Transferring project files...
Successfully transferred all files.
Successfully synced application org.nativescript.MyApp on device ZY222W4LPP.

Using  C:\Users\Jeff\MyApp\platforms\android\build\outputs\apk\MyApp-debug.apk
Executing before-watch hook from C:\Users\Jeff\MyApp\hooks\before-watch\nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
2:24:46 PM - Compilation complete. Watching for file changes.
```

And then just sits there... will responds to file changes, but the app never launches on the phone.

**Comment by pkoleva** [comment] 2017-05-04 08:01
Hi, @jeffswitzer,

Can you try the same thing using the device name: `tns debug android --device <device identifier>`. You can see the device identifier by executing `tns devices android`.

**Comment by jeffswitzer** [comment] 2017-05-04 16:34
@pkoleva thanks! When I use the device identifier it does indeed launch on my phone. I get a message in the console about debugging not being enabled which I'm guessing is some flag I need to set:

```
Jeff@JEFF-WORK C:\Users\Jeff\MyApp
> tns debug android --device ZY222W4LPP
Searching for devices...
iTunes is not installed. Install it on your system and run this command again.
Your application will be deployed only on the device specified by the provided index or identifier.
Executing before-prepare hook from C:\Users\Jeff\MyApp\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
Preparing project...
Project successfully prepared (Android)
Skipping package build. No changes detected on the native side. This will be fast!
Skipping install.
Executing before-livesync hook from C:\Users\Jeff\MyApp\hooks\before-livesync\nativescript-angular-sync.js
Transferring project files...
Successfully transferred all files.
Successfully synced application org.nativescript.MyApp on device ZY222W4LPP.

Using  C:\Users\Jeff\MyApp\platforms\android\build\outputs\apk\MyApp-debug.apk
device: ZY222W4LPP debug port: 40000

# NativeScript Debugger started #
The application org.nativescript.MyApp does not appear to be running on ZY222W4LPP or is not built with debugging enabled.
```

**Comment by jeffswitzer** [comment] 2017-05-04 16:40
Interesting, I then ran just tns debug android and didn't get the last error message

```
Jeff@JEFF-WORK C:\Users\Jeff\MyApp
> tns debug android
Searching for devices...
Executing before-prepare hook from C:\Users\Jeff\MyApp\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
Preparing project...
Project successfully prepared (Android)
Skipping package build. No changes detected on the native side. This will be fast!
Skipping install.
Executing before-livesync hook from C:\Users\Jeff\MyApp\hooks\before-livesync\nativescript-angular-sync.js
Transferring project files...
Successfully transferred all files.
Successfully synced application org.nativescript.MyApp on device ZY222W4LPP.

Using  C:\Users\Jeff\MyApp\platforms\android\build\outputs\apk\MyApp-debug.apk
device: ZY222W4LPP debug port: 40000

# NativeScript Debugger started #
To start debugging, open the following URL in Chrome:
chrome-devtools://devtools/bundled/inspector.html?experiments=true&ws=localhost:40000

Executing before-watch hook from C:\Users\Jeff\MyApp\hooks\before-watch\nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
9:38:38 AM - Compilation complete. Watching for file changes.



JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
```

**Comment by pkoleva** [comment] 2017-05-12 08:04
Hey, @jeffswitzer, 
I am glad it worked. About the message you get -> looks like the first time you used debug with --start option. If so, the message says you didn't have the app started on the device, so the debugger cannot attach. Basically the --start option can be used only if you have the application started on beforehand on your device and then you can execute the debug command `tns debug android --start`. Hope this clears it out a bit. :)

**Comment by woozie** [comment] 2017-05-18 00:27
Same problem

`tns debug android --log trace  --device 73QDU16828004860` didn't help

**Comment by jeffswitzer** [comment] 2017-05-18 02:38
@woozie I've had good results with this method:
`tns run android --device 73QDU168280048` to run the app and then once it's running try
`tns debug android --start` to attach the debugger to the already running app
Give it a shot?

**Comment by pkoleva** [comment] 2017-05-18 06:24
Hey, @woozie,

Would you send us the output of the command with --log trace and the version of the CLI you're using.

Thanks!

**Comment by woozie** [comment] 2017-05-18 21:47
@pkoleva http://jo.ee/bug.txt

tns --version
3.0.1-2017-05-15-8921
tsc --version
Version 2.3.2

**Comment by sitefinitysteve** [comment] 2017-06-03 02:07
Im hitting this now as well on device

**Comment by Cayan** [comment] 2017-06-16 00:04
I'm having the same error

**Comment by vtjon** [comment] 2017-06-23 18:31
I am hitting this same issue on both an emulator (genymotion) and a real android device. At the moment, it's only happening with Eddy's mapbox plugin demo.  It does install the app in both places and "tns run android" will stay running and watch for changes. The app does not automatically get restarted despite the changes getting pushed.

Environment:
MacOS (I think I'm having the same problem on Windows but haven't been able to confirm yet)
tns --version = 3.0.3

Duplicate:
git clone https://github.com/EddyVerbruggen/nativescript-mapbox.git mapbox-test
cd mapbox-test/src
npm install
npm run preparedemo
cd ../demo
tns debug android --emulator

I realize that it could be something related to the Mapbox SDK however since the app will run in the emulator, it seems like the debugger should at least work. I've attached a trace log from the debug command.

[trace.txt](https://github.com/NativeScript/nativescript-cli/files/1098690/trace.txt)

**Comment by marco-gagliardi** [comment] 2017-07-26 16:10
Same here. It looks like the cli can't start the application on the emulator (maybe too slow?) in time before connecting to it for debugging

**Comment by miroslavaivanova** [comment] 2018-10-25 14:02
Closing the issue seems not to be reproducible with the next CLI.

**Closed by miroslavaivanova** 2018-10-25 14:02 UTC
Labels: debug, os: android
