### ISSUE TITLE
The lib folder is getting cached, or something

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#1399] opened 2016-01-15 14:23 UTC
Ok I have a weird one. When I updated versions of UI for {N} I kept having this issue where my `TelerikUI.framework` was out of sync. I tried everything—deleting `platforms/ios`, rebuilding `node_modules`, praying to the iOS gods, etc—and nothing worked. UNTIL I tried deleting the `lib` folder, and then building everything again from scratch. That totally worked.

Soooooo, I’m not sure about this, but it _seems_ like the CLI’s `prepare` step is caching `lib`, or it doesn’t update it when plugins get updated, or something. Here’s how you can recreate the problem:

```
git clone https://github.com/NativeScript/sample-Groceries.git
cd sample-Groceries
git checkout c0e9e42b3b68b35a1552dfbff70d79c2d2973d1e
```

Open the project’s `package.json` and update the `"nativescript-telerik-ui"` dependency to `"0.2.3"`. Then:

```
tns install
tns run ios --emulator
```

A couple of people [reported this issue on our Google Group](https://groups.google.com/forum/#!topic/nativescript/ovDzPNlXQ9I), so it’s not just me that hit this problem. Also, shout out to @karaahmed for helping me track down this one.

**Comment by NathanaelA** [comment] 2016-01-15 17:05
@tjvantoll - Yeah I've seen this happen before and it is reported at https://github.com/NativeScript/android-runtime/issues/284 ...  

 It is a pain because it really leaves you wondering what is going on.  So if I get any weird issues my second step is to kill the lib folder.

**Comment by MiroValchev** [comment] 2016-01-31 12:12
+1 Lost a day wondering what's going on. Removing and adding again a local plugin did not refresh the lib folder.

**Comment by MiroValchev** [comment] 2016-02-04 14:08
OK, so it's not just about lib folder and iOS. This happens on Android too. If you have a local plugin and change the .aar file, the only way for the change to propagate is to remove android from platforms and add it again.

**Comment by enchev** [comment] 2016-06-02 12:55
Hey folks,

Do you still have such problems?

**Comment by NathanaelA** [comment] 2016-06-02 20:27
@enchev last time I looked, the lib folder is still being used by iOS -- so this issue might still be valid on iOS.   Not sure about Android anymore; seems like everything on android is now kept in the platforms folder.    I would guess that the android team could confirm if lib is no longer used by the android runtimes.

**Comment by enchev** [comment] 2016-06-03 06:18
Hey @jasssonpet @slavchev can you check this and confirm if still valid?

**Comment by slavchev** [comment] 2016-06-03 06:36
On Android everything is kept in `platforms`.

>I would guess that the android team could confirm if lib is no longer used by the android runtimes.

We don't use `lib` folder anymore.

**Comment by jasssonpet** [comment] 2016-06-09 07:55
Following the issue guidelines it does seem that the problem is still reproducible for iOS.

**Comment by NathanaelA** [comment] 2016-07-13 20:00
I can confirm that iOS still uses the lib folder; it just bit me again.   
**tns platform remove ios** and **tns platform clean ios** should both delete that folder.

**Comment by enchev** [comment] 2016-08-01 14:01
Merged with https://github.com/NativeScript/nativescript-cli/issues/1003

**Closed by enchev** 2016-08-01 14:01 UTC
Labels: bug
