### ISSUE TITLE
After building plugin folder `tempPlugin/`  remains in `platforms/` 

### ISSUE THREAD

**Issue by Natalia-Hristova** [NativeScript/nativescript-cli#3763] opened 2018-07-20 15:38 UTC
### Tell us about the problem
After adding plugin in your app by pointing to its src folder, and build the app (which build the plugin too) - folder `tempPlugin/` remains in `platforms/` 

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.3

### Please tell us how to recreate the issue in as much detail as possible.
1. download [some plugin](https://github.com/NativeScript/nativescript-camera) source
2. `tns create SomeApp`
3. `tns plugin add ../nativescript-camera/src/`
4. `tns build android`

check `SomeApp/platforms/` for folder `tempPlugin/`

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Consider using the [playground](https://play.nativescript.org) to provide the code you have issues with.

**Comment by rosen-vladimirov** [comment] 2018-07-20 16:31
This is currently by design - the idea is that CLI adds additional files in order to build the plugin. Users may want to check the exact files used for building the plugin. These files can be used to build the plugin again or fix failing build.

I'm closing this issue, but in case you think these directories are not needed, feel free to reopen it.

**Closed by rosen-vladimirov** 2018-07-20 16:31 UTC
