### ISSUE TITLE
Could not create service of type DefaultUserHomeScopedCompileCaches using UserHomeScopeServices.createCompileCaches().

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#4485] opened 2019-04-01 06:45 UTC
@JohnGalt1717 commented on [Fri Mar 29 2019](https://github.com/NativeScript/NativeScript/issues/7088)

**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

√ Component nativescript has 5.3.0 version and is up to date.
√ Component tns-core-modules has 5.3.1 version and is up to date.
√ Component tns-android has 5.3.0 version and is up to date.
√ Component tns-ios has 5.3.0 version and is up to date.

**Describe the bug**
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not create service of type DefaultUserHomeScopedCompileCaches using UserHomeScopeServices.createCompileCaches().

**To Reproduce**
Setup Nativescript and got a clean bill of health from tns doctor.

I created a new nativescript project per the documentation like this: tns create HelloWorld --template tns-template-blank-ng and then ran tns run android. It worked perfectly fine.

Then used the nsconfig.json useLegacyWorkflow: false to make sure hot reload was on all of the time per the docs for 5.3 and ran tns run android.

Switching back by removing the command from nsconfig.json doesn't fix this issue.

**Expected behavior**
Should just build and work right.

**Additional context**
I have Android studio and flutter installed and had to fix the android sdk stuff to point to the Android Studio version.  Not sure that this matters but would be pretty common.

**Comment by rosen-vladimirov** [comment] 2019-04-01 08:19
Hey @JohnGalt1717 ,

It looks like your problem is related to Gradle itself, not particularly with NativeScript. It seems Gradle has some permission issues on your machine, but I'm not entirely sure without checking the full log. What I can suggest you is to try `tns run android --log trace > out.txt ` and investigate the generated `out.txt` file - it should contain much more information what exactly is breaking the process.

Hope this helps.

**Comment by JohnGalt1717** [comment] 2019-04-01 12:07
Turns out that it's the cache directory under the /users/<username>/cache folder.  There is no error but clearing that folder solves the problem,  Given that graddle creates this folder no matter where you put the sdk, seems like a bug to me. Whether it's eith graddle or nativescript not invalidating something properly I'll leave to you to decide.

**Comment by rosen-vladimirov** [comment] 2019-04-01 20:16
Hey @JohnGalt1717 ,
Thanks for sharing the solution. This way, anyone who uses NativeScript and receives this error, will find this issue and will have a solution. I'm wondering what is the specific in your case that causes the manifestation of the issue on your side as I was unable to reproduce it on my side. I suspect gradle has been running with another user on your machine and it tries to share the same cache between users, but I was unable to verify this idea.

As I've mentioned, the problem is specific to gradle and I don't think it is applicable to handle this is NativeScript CLI's code, so I'm closing this thread. Feel free to share any other information that might be helpful for reproducing the error or even reopen the issue in case NativeScript CLI causes the actual error on your side.

Thanks again for your investigation and sharing the solution to this issue.

**Closed by rosen-vladimirov** 2019-04-01 20:16 UTC
Labels: question

**Comment by JohnGalt1717** [comment] 2019-04-01 20:17
Ok, I can confirm that there are no other users even registered on the machine.

**Comment by BharathBunty** [comment] 2019-04-17 05:12
Hi i m getting same issue while running project.. can you help me how to solve this..

**Comment by JohnGalt1717** [comment] 2019-04-17 12:20
Just delete the cache directory per above and it starts working again.

**Comment by MrMus1000** [comment] 2021-01-30 17:42
If this error occur while you are trying to run an app in your mobile device, just uninstall the app in your phone and run the app again. if the error persist then go-to C:\Users\name\.gradle\caches\5.6.4\javaCompile and delete the javaCompile.lock  file.
