### ISSUE TITLE
"Error: EPERM: operation not permitted, lstat" on device watch with NativeScript version 2.5.3

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/nativescript-cli#2680] opened 2017-03-31 14:59 UTC
_From @briosheje on March 28, 2017 15:5_

I had no issue with version 2.5.2, after updating I get an lstat error everytime I perform a change in any file, I need to delete the platforms/android/src/main directory to make it work again (and, after the first change, the same error pops up again):

Stack:
```
Error: EPERM: operation not permitted, lstat 'c:\Users\briosheje\Documents\vierinc_handler\NativeScript\TestApp\platforms\android\src\main\assets\app\item\item-detail.component.ts'
    at Error (native)
    at Object.fs.lstatSync (fs.js:982:18)
    at rmdirSyncRecursive (C:\Users\briosheje\AppData\Roaming\npm\node_modules\nativescript\node_modules\shelljs\src\rm.js:28:23)
    at C:\Users\briosheje\AppData\Roaming\npm\node_modules\nativescript\node_modules\shelljs\src\rm.js:136:9
    at Array.forEach (native)
    at Object._rm (C:\Users\briosheje\AppData\Roaming\npm\node_modules\nativescript\node_modules\shelljs\src\rm.js:113:9)
    at Object.rm (C:\Users\briosheje\AppData\Roaming\npm\node_modules\nativescript\node_modules\shelljs\src\common.js:365:25)
    at FileSystem.deleteDirectory (C:\Users\briosheje\AppData\Roaming\npm\node_modules\nativescript\lib\common\file-system.js:101:17)
    at AppFilesUpdater.deleteDestinationItem (C:\Users\briosheje\AppData\Roaming\npm\node_modules\nativescript\lib\services\app-files-updater.js:38:17)
    at _.each (C:\Users\briosheje\AppData\Roaming\npm\node_modules\nativescript\lib\services\app-files-updater.js:26:18)
```

Permissions on folders are ok already, so not sure what the issue is really, but since this last update I'm having troubles with the extension.

_Copied from original issue: NativeScript/nativescript-vscode-extension#122_

**Comment by dtopuzov** [comment] 2017-03-31 19:50
Hi @briosheje,

Can you reproduce the problem with hello-world app and provide exact steps to reproduce the issue.

**Comment by briosheje** [comment] 2017-04-03 09:50
@dtopuzov I wish I could, but right now if I try to create a new HelloWorld project I get another error in the create phase.

TNS Doctor says that everything is okay, but whenever I try to create a new project using:
`tns create HelloWorldApp --template nativescript-template-ng-tutorial`

It gives me this:

```
Installing  nativescript-template-ng-tutorial
C:\Users\briosheje\Documents\vierinc_handler\NativeScript\HelloWorldApp
+-- @angular/common@4.0.0  extraneous
+-- @angular/compiler@4.0.0  extraneous
+-- @angular/core@4.0.0  extraneous
+-- @angular/forms@4.0.0  extraneous
+-- @angular/http@4.0.0  extraneous
+-- @angular/platform-browser@4.0.0  extraneous
+-- @angular/platform-browser-dynamic@4.0.0  extraneous
+-- @angular/router@4.0.0  extraneous
+-- nativescript-theme-core@1.0.3  extraneous
+-- reflect-metadata@0.1.10  extraneous
+-- tns-core-modules@2.5.2  extraneous
`-- zone.js@0.8.5  extraneous

Error: Command npm.cmd failed with exit code 4294963248
```
I guess the cleverest I can do right now is to reinstall nativescript and try once again the whole process.

**Comment by dtopuzov** [comment] 2017-04-03 09:56
@briosheje `nativescript-template-ng-tutorial` is not official template.
If you want to create new {N} angular application you can use: `tns create MyApp --ng`

**Comment by briosheje** [comment] 2017-04-06 16:59
@dtopuzov Oh. I'm sorry, I was trying the "official" (....?) getting started guide to be absolutely sure that I was doing everything correctly, but the guide actually suggests to use `tns create HelloWorld --template nativescript-template-ng-tutorial`:

![image](https://cloud.githubusercontent.com/assets/1898880/24766283/08f50bd4-1afb-11e7-9e80-a4e99405939f.png)

Anyway, I can confirm that using the regular command (tns create Something --ng) everything is working properly, I've tried to edit the code a couple of times using the VSCode extension and everything now is working properly so I guess the issue is rather related to the nativescript-template-ng-tutorial.

Thanks again!

**Comment by dtopuzov** [comment] 2017-05-09 14:11
Hi @briosheje,

Can you try with {N} 3.0.0.
Do you experience the same issue if you run `tns create MyApp` without any templates?

**Comment by briosheje** [comment] 2017-05-10 16:41
@dtopuzov 

I have created a brand new project, ran `tns create MyApp`, ran `tns --version` which was 2.5.3, ran `tns platform add android`, update the visual studio extension to version 0.7.0, run attach on android and everything is working properly.

However, my original issue was with an Angular project, so tomorrow I will try an angular 2 project to be sure that the issue doesn't exist in an angular project.

Thanks.

**Comment by dtopuzov** [comment] 2017-05-17 08:09
@briosheje Any update on this? Is it still valid?

**Comment by briosheje** [comment] 2017-05-17 16:30
@dtopuzov Sorry for the late answer, I did a fast test (I didn't have much time, I'm sorry), but everything seems to work pretty well (just like the regular project). I didn't try many edits, just some styles changed, but it didn't give me the error any further. I will post there if I still find the issue and I will try to be as precise as possible if that happens.

**Comment by pkoleva** [comment] 2017-05-18 06:26
Hi @briosheje, 
That's great news. I'm closing the issue now, but do not hesitate to reopen it or comment below if it reappears!

**Closed by pkoleva** 2017-05-18 06:26 UTC
Labels: bug, Need More Info
