### ISSUE TITLE
Multi arch support for Android

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/nativescript-cli#1392] opened 2016-01-13 17:00 UTC
# Multi arch support for Android
## Overview

Users of NativeScript face conflicting goals when using architecture-dependant native code (*.so files).
During development they want to build their program very quickly to iterate very fast. They usually develop for x86 emulator (like Genymotion or Visual Studio) and arm-based testing devices.

When publishing to Google Play Store, they may need to split the archive to avoid the 100 MB file size limit currently imposed.

Additional obstacle is that 64-bit Android does not allow mixing 64-bit and 32-bit architecture-dependent native code. When a single dependency introduces a 64-bit .so file, **all** dependencies **must** be 64-bit as well. This can easily slip during development, when people usually use 32-bit devices and emulators.
## Proposed work flow

We need to solve these problems in couple of places: The CLI, the Docs and the Gradle scripts

I propose this behavior:
- Android runtime introduces aarch64 build [Android runtime]
- introduce options to control the architectures included in the apk during build:
  - --arch all (default), armeabi-v7a, arm64-v8a, x86, x86_64. Multiple architectures are allowed. The names are the IDs taken from [Android docs](http://developer.android.com/ndk/guides/application_mk.html) [CLI]
- this option must be passed to the gradle build script [CLI, Android runtime]
- Gradle build script builds the correct apk [Android runtime]
- If a pluging is missing requested architecture, stop the build. This does not apply when only jars are used [Android runtime]
- The option is mandatory for the future `publish` [command](https://github.com/NativeScript/nativescript-cli/issues/1172). It is also mandatory for `build --release` (but see bellow for comments). When building _without_ `--release`, it is not mandatory. [CLI]
- document the proper structure of NativeScript plugin to allow including of .so files. See http://docs.nativescript.org/runtimes/android/getting-started/project-structure and http://docs.nativescript.org/plugins/plugins [@ErjanGavalji]
## iOS

Apple has different requirements for publishing to App Store. I believe that build and publish commands can differ in this case. iOS specific functionality should be addressed in a dedicated issue.

Comments:
- If we make `--arch` mandatory for building in release mode, AppBuilder team will need to revise the BpcTooling to introduce it. Also, this may not be the optimal behavior for the user.

**Comment by NathanaelA** [comment] 2016-01-13 17:29
Awesome, thanks for putting this into its own subject.  

One item that you do need to make sure that is correct is the versioncode.  See: https://androidbycode.wordpress.com/2015/06/30/android-ndk-version-code-scheme-for-publishing-apks-per-architecture/  covers the requirements on the versioncode much better than the official docs: http://developer.android.com/google/play/publishing/multiple-apks.html    Basically each apk platform needs a apk prefix.   Xyyy where X is the platform code; and yyy is my code.  

Example:
If I set my version code to 105, then build a Arm-v8 then the version code ends up being:
3105.    So this requires that the VersionCode .

**Comment by Plamen5kov** [comment] 2016-01-14 07:37
In the third case:

"If a pluging is missing requested architecture, stop the build. **This does not apply when** only jars **or aars are used** [Android runtime]"

`.aar` files can contain `.so` files so we should take care of that too.

**Comment by teobugslayer** [comment] 2016-01-14 08:06
@Plamen5kov - updated the text, thank you!

**Comment by slavchev** [comment] 2016-01-14 08:34
:+1:

**Comment by blagoev** [comment] 2016-01-14 08:44
@teobugslayer  some notes
The apk limit is 100MB currently.

We need to think support for all scenarios in http://developer.android.com/google/play/publishing/multiple-apks.html

Also if there is no 64bit  libs in my app why the option is mandatory. A 32bit app will run fine on 64 bit devices.

I think we should package a single apk by default (and as per the guidance) and introduce complexity only when user wants it.

**Comment by teobugslayer** [comment] 2016-02-03 15:46
@blagoev, when we switch to using combined 32 and 64 bit {N} runtime, there always will be 64 bit code in the APK. We can either make the option mandatory (again, only for the "publish" command"), or default to something which we consider "safe", like, 32-bit only build, all build, or something else. Opinions?

**Comment by blagoev** [comment] 2016-02-08 14:07
@teobugslayer for the publish command only it is ok to have this to be mandatory.  If there are no other 64bit libs in the project we can build against a 32bit only runtime. We just need to make sure the build fails if there is one plugin which does not have a 64bit library on 64 builds.

**Comment by NathanaelA** [comment] 2016-02-22 20:35
Please note the 64 bit version of the library seems to be coming along for the ride anyway; so now the APK files are 10 megs JUST for the runtimes.   Can this be moved up in priority.   This does make NS look horrible compared to other solutions.  And the issue is WAY more import than silly things like than #1420 which has a critical rating .

**Comment by calebeaires** [comment] 2016-03-04 17:03
:+1:

**Comment by dfg-nota** [comment] 2016-06-08 09:14
Hello. I was wondering if there is still no way to make tns build for a specific android architecture?

In an app we're currently working on we want to use libVLC through a plugin. But it really slows down our development process that we arent able to build for one architecture at a time. If anyone knows of a manual fix to the build.gradle file it would be very much appreciated.

**Comment by enchev** [comment] 2016-06-13 13:22
Hey @Plamen5kov,

Do you know such manual fix?

**Comment by dfg-nota** [comment] 2016-06-13 14:53
@enchev 
I used to be able to do this in my plugin include.gradle file:
```
android {
    productFlavors {
        'nativescript-plugin-name' {
            dimension 'nativescript-plugin-name'

            // Setting below requires 'android.useDeprecatedNdk=true'
            // in platforms/android/gradle.properties file.
            ndk {
                abiFilters 'armeabi-v7a'
            }
        }
    }
}
```
But it doesn't seem like it's possible anymore in the latest version of Nativescript CLI.

**Comment by Plamen5kov** [comment] 2016-06-13 15:01
Hi @dfg-nota 
I don't believe the new version of cli can change the way `include.gradle` works. What you're doing should be working. Let me check it out and i'll get back to you.
Could you give me the version of CLI you're using?

**Comment by dfg-nota** [comment] 2016-06-13 16:03
@Plamen5kov I just checked my `platforms/android/configurations` folder after a build and it seems my plugin include.gradle file from above is turned into this:
```
android {
    productFlavors {
              "F0" {
                dimension "nativescriptpluginname"
              }
            }
}
dependencies {
    compile 'de.mrmaffen:vlc-android-sdk:1.9.8'
}
```
ndk abiFilters was removed.

**Comment by Plamen5kov** [comment] 2016-06-14 05:56
Hi @dfg-nota,
I tested it out and you're right, you can open an issue in the [android-runtime](https://github.com/NativeScript/android-runtime).

**Comment by ansarizafar** [comment] 2016-09-18 13:02
I am facing the same issue. Is there any work around available?

**Comment by Plamen5kov** [comment] 2016-09-19 06:56
Hi @ansarizafar,
You can reduce the apk size for android. You can look at the documentation [here](https://docs.nativescript.org/publishing/publishing-android-apps) under the `APKs with ABI splits` section. Additionally you can look at [this](https://github.com/NativeScript/android-runtime/issues/518) issue.

**Comment by vbresults** [comment] 2017-03-31 13:18
@Plamen5kov Any chance this will get in?  It's a bit of a pain having to double my build time compiling arm and x86 separately, especially at scale

**Comment by Plamen5kov** [comment] 2017-03-31 14:07
Hi @vbresults you can use [this PR](https://github.com/NativeScript/android-runtime/pull/738), where abi split configuration is respected and once `tns build android` is ran there are two resulting apk files:
```
testapp-debug-x86.apk
testapp-debug-armeabi-v7a.apk
```

**Comment by Pip3r4o** [comment] 2017-04-28 12:22
Starting with android runtime v3.0.0 when abi split configuration is provided in the `app/App_Resources/Android/app.gradle` script, apks for all distinct architectures will be output, allowing the developer to publish smaller packages in the Google Play Store.

Please refer to the [Publishing for Android](https://docs.nativescript.org/publishing/publishing-android-apps#builds) article if you want to learn how to setup ABI splits.

Closing this as resolved.

**Closed by Pip3r4o** 2017-04-28 12:22 UTC
Labels: feature

**Comment by vbresults** [comment] 2017-07-30 13:24
@Plamen5kov @Pip3r4o The splits code sample/doc doesn't set a different `versionCode` for each ABI and therefore can't be used to publish to the app stores.

Please update the docs, this is what I use (`armv7` adds `2` to the base version code, `x86` adds `4`):

```
ext.abiCodes = ['armeabi-v7a': 2, x86: 4]

android.applicationVariants.all { variant ->
	variant.outputs.each { output ->
		def baseAbiVersionCode = project.ext.abiCodes.get(output.getFilter("ABI"))

		if (baseAbiVersionCode != null) {
			output.versionCodeOverride = baseAbiVersionCode + variant.versionCode
		}
	}
}
```

**Comment by Pip3r4o** [comment] 2017-07-30 19:23
@vbresults Thanks for reporting that behavior. What you point out is indeed the case with the APKs, they don't have a distinct version code themselves. The respective code configuring the apks can be found here - https://github.com/NativeScript/android-runtime/blob/master/build-artifacts/project-template-gradle/build.gradle#L162 . Do you have a suggestion on general naming of apks configured with separate ABIs?  The `abiCodes` list with the `2` and `4` versions appears non-standard. 

Would you be willing to submit a PR?

**Comment by vbresults** [comment] 2017-07-31 02:59
@Pip3r4o The [official guide](https://developer.android.com/studio/build/configure-apk-splits.html#configure-APK-versions) shows a convention but I personally don't want to be locked into their `versionCode * 1000` formula.  What to do here?
