### ISSUE TITLE
cli 7.1.2 fresh project unit tests don't work

### ISSUE THREAD

**Issue by aquinn637** [NativeScript/nativescript-cli#5476] opened 2021-01-18 15:59 UTC
Environment

macOS Big Sur v 11.1

node -v
v12.18.4

ns -v
7.1.2

ns create new-app-2

cd new-app-2

Fresh Project: https://github.com/aquinn637/new-app-v2

I opened my Android emulator from Android Studio.

ns run android

First time issue:
Second attempt OK.

Ns test init karma & jasmine

Ns test android

aubrey@Softworkss-MacBook-Pro new-app-2 % ns test android   
Searching for devices...
```
18 01 2021 14:49:20.015:ERROR [preprocess]: Can not load "webpack"!
  Error: No provider for "customFileHandlers"! (Resolving: preprocess -> preprocessor:webpack -> webpackPlugin -> customFileHandlers)
    at error (/Users/aubrey/Documents/Repos/new-app-2/node_modules/di/lib/injector.js:22:12)
    at Object.get (/Users/aubrey/Documents/Repos/new-app-2/node_modules/di/lib/injector.js:9:13)
    at get (/Users/aubrey/Documents/Repos/new-app-2/node_modules/di/lib/injector.js:54:19)
    at /Users/aubrey/Documents/Repos/new-app-2/node_modules/di/lib/injector.js:71:14
    at Array.map (<anonymous>)
    at invoke (/Users/aubrey/Documents/Repos/new-app-2/node_modules/di/lib/injector.js:70:31)
    at Array.instantiate (/Users/aubrey/Documents/Repos/new-app-2/node_modules/di/lib/injector.js:59:20)
    at get (/Users/aubrey/Documents/Repos/new-app-2/node_modules/di/lib/injector.js:48:43)
    at /Users/aubrey/Documents/Repos/new-app-2/node_modules/di/lib/injector.js:71:14
    at Array.map (<anonymous>)
    at Array.invoke (/Users/aubrey/Documents/Repos/new-app-2/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/Users/aubrey/Documents/Repos/new-app-2/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/Users/aubrey/Documents/Repos/new-app-2/node_modules/karma/lib/preprocessor.js:84:20)
    at Array.forEach (<anonymous>)
    at createPriorityPreprocessor (/Users/aubrey/Documents/Repos/new-app-2/node_modules/karma/lib/preprocessor.js:101:43)
    at Array.invoke (/Users/aubrey/Documents/Repos/new-app-2/node_modules/di/lib/injector.js:75:15)
18 01 2021 14:49:20.060:ERROR [karma-server]: Error during file loading or preprocessing
TypeError: process is not a function
    at executeProcessor (/Users/aubrey/Documents/Repos/new-app-2/node_modules/karma/lib/preprocessor.js:47:11)
    at runProcessors (/Users/aubrey/Documents/Repos/new-app-2/node_modules/karma/lib/preprocessor.js:60:23)
    at FileList.preprocess [as _preprocess] (/Users/aubrey/Documents/Repos/new-app-2/node_modules/karma/lib/preprocessor.js:134:11)
    at async Promise.all (index 0)
    at /Users/aubrey/Documents/Repos/new-app-2/node_modules/karma/lib/file-list.js:90:11
    at async Promise.all (index 3)
18 01 2021 14:49:20.127:INFO [karma-server]: Karma v6.0.0 server started at http://localhost:9876/
18 01 2021 14:49:20.127:INFO [launcher]: Launching browsers android with concurrency unlimited
18 01 2021 14:49:20.128:ERROR [karma-server]: Error: Found 1 load error
    at Server.<anonymous> (/Users/aubrey/Documents/Repos/new-app-2/node_modules/karma/lib/server.js:205:26)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:327:22)
    at emitListeningNT (net.js:1347:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
Test run failed.
```

**Comment by clintmod** [comment] 2021-01-20 03:18
duplicate of #5472

**Comment by janoshrubos** [comment] 2021-04-13 07:50
Closing as a duplicate of #5472

**Closed by janoshrubos** 2021-04-13 07:50 UTC
