### ISSUE TITLE
Install fails under io.js

### ISSUE THREAD

**Issue by codechimera** [NativeScript/nativescript-cli#286] opened 2015-03-07 00:06 UTC
When using io.js 1.5.0, running `npm i -g nativescript` fails due to compile errors on `fibers.js`.

**Comment by tjwudi** [comment] 2015-03-07 02:05
+1 for this error

**Comment by rosen-vladimirov** [comment] 2015-03-09 22:03
Hi @codechimera , @tjwudi 
Currently nativescript-cli does not support io.js. The problem is that io.js is using version of V8 that is different from the one used on Nodejs 0.10.x and 0.12.x 
Several of our dependencies are using native calls to V8 and at the moment most of them do not support io.js. We are notifying the developers of the dependencies for these issues and we are working closely with them in order to add support for io.js in the near future. Unfortunately you will have to use nodejs 0.10.x or nodejs 0.12.x for the moment.

**Comment by codechimera** [comment] 2015-03-09 23:14
Ok, makes sense. Thanks for the response! 
Do you want me to close the issue, since it seems the team was already aware of it?

**Comment by rosen-vladimirov** [comment] 2015-03-09 23:15
@codechimera , I prefer to keep it open, so we'll all track it here and write comments in case we have new information. So I'll assign it to myself and I'll keep it updated with the current progress.

**Comment by codechimera** [comment] 2015-03-10 01:15
Gotcha. Sounds great!

**Comment by rosen-vladimirov** [comment] 2015-09-29 07:02
Hi, support for io.js is not deprecated now, please follow the new issue for working with Node 4.x.x [here](https://github.com/NativeScript/nativescript-cli/issues/958).

**Closed by rosen-vladimirov** 2015-09-29 07:02 UTC
Labels: bug
