### ISSUE TITLE
Not able to install NativeScript on OS X

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#835] opened 2015-08-31 13:28 UTC
_From @5HT2A on August 31, 2015 13:22_

I can't install NativeScript on this new Macbook Pro. I try

sudo npm install nativescript -g --unsafe-perm

and here's what it says:

http://pastebin.com/dJ9ng4jY

What am I doing wrong?

_Copied from original issue: NativeScript/NativeScript#645_

**Comment by teobugslayer** [comment] 2015-08-31 13:43
Hi @5HT2A,
I've never seen such error before. Quick googling led me to believe that this issue is related Xcode 7 beta. Do you have Xcode 7 Beta installed? If so, you may need to download and set as default the 6.4 command line tools for Xcode.

**Comment by 5HT2A** [comment] 2015-08-31 20:31
I really want to install NativeScriptf, fellas, what's wrong with it?

**Comment by teobugslayer** [comment] 2015-09-01 10:21
Hello @5HT2A,

It appears that there is an issue with your Xcode installation. I recommend that you try reinstalling Xcode 6.4 and verify that its matching command line tools are set as default.

If anything else, this change may do the trick:
```
$ cd /usr/local/lib
$ sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib
```

This will create the missing dependency gcc_s.10.5.

Let me know if this worked for you.

**Comment by e2l3n** [comment] 2015-09-01 10:52
Hello @5HT2A,

What version of Mac OS do you use?
Can you also verify that the missing library exists in 
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/lib`.

**Comment by 5HT2A** [comment] 2015-09-01 11:17
Holy crow! I tried removing and then reinstalling Xcode, which didn't seem to do it. But then I entered Todor's magic lines and it seems to work now! Thanks a lot! Can you explain what happened here and why?

Toma, I use OS X 10.10.5. What missing library? libgcc_s.10.5.dylib? That one's there. :O

**Comment by teobugslayer** [comment] 2015-09-01 12:27
Your machine is missing the required libgcc_s.10.5.dylib where node-gyp is searching for. We created a symlink to the existing one so it is happy now.

As it seems that the problem is resolved, I am closing this issue.

**Closed by teobugslayer** 2015-09-01 12:27 UTC
