### ISSUE TITLE
increased app size when building for ios with --bundle --env.uglify

### ISSUE THREAD

**Issue by endarova** [NativeScript/nativescript-cli#4425] opened 2019-03-11 09:45 UTC
- CLI: next (5.3.0)
 - tns-ios@next
 -nativescript-dev-webpack@next

The app size of angular project built with bundle and env. aot and  env. uglify flag has increased lately. 'Actual app size:16167835. Expected size:  15386993'

Steps:
1. tns create TestApp --ng
2. Install tns-ios@ next and nativescript-dev-webpack@next
3. tns build ios --bundle --release --for-device
4. tns build ios --bundle  --release  --for-device  --env.aot  --env.uglify

**Comment by rosen-vladimirov** [comment] 2019-04-02 13:58
Closing as the regression is not caused by CLI. Seems it is caused by Angular release.

**Closed by rosen-vladimirov** 2019-04-02 13:58 UTC
Labels: in progress, no-changelog
