### ISSUE TITLE
npm install windows 7 error 

### ISSUE THREAD

**Issue by joaomello** [NativeScript/nativescript-cli#228] opened 2015-02-18 02:05 UTC
Hi! I`m getting this error at my installation, I only have visual studio 2013...

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The bu
ild tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools,
 please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools
 by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Users\me
llo\AppData\Roaming\npm\node_modules\nativescript\node_modules\ffi\build\deps\dlfcn-win32\dlfcn.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The bu
ild tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools,
 please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools
 by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Users\me
llo\AppData\Roaming\npm\node_modules\nativescript\node_modules\ffi\build\deps\libffi\ffi.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The bu
ild tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools,
 please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools
 by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Users\me
llo\AppData\Roaming\npm\node_modules\nativescript\node_modules\ffi\build\deps\pthreads-win32\pthread.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build
.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "r
ebuild"
gyp ERR! cwd C:\Users\mello\AppData\Roaming\npm\node_modules\nativescript\node_modules\ffi
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.j
s" "install" "nativescript" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! ref@0.1.3 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@0.1.3 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ref
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mello\npm-debug.log

**Comment by rosen-vladimirov** [comment] 2015-02-18 09:27
Hi @joaomello, 
It looks like you are trying to use Nodejs 0.12.0. Currently this version is not supported as some of our dependencies are not buildable with it. We are working on this issue and hopefully we'll be able to support Node 0.12.0 very soon.

You can follow this issue for more information on the progress (I'm closing this issue as it is duplicate of the mention one): https://github.com/NativeScript/nativescript-cli/issues/224

**Comment by mikehamil10** [comment] 2015-02-26 17:32
Mmmm...I'm not so sure about that. I'm getting the same error and am on Node 0.10.26

I can build node-gyp just fine on its own, but when it gets rebuilt as part of the nativescript installation I get the error above (googling the error landed me here).

I think there's something else wrong here...

**Comment by rosen-vladimirov** [comment] 2015-02-27 07:13
Hi @mikehamil10,
We've found a problem with one of our dependencies which was preventing the installation from npm. We've already fixed it, so could you try executing 
```$ npm install nativescript```
one more time and inform us if it works for you.

**Comment by mikehamil10** [comment] 2015-03-04 22:56
Hey, it works now! Thanks!

P.S. To be sure the problem was that my node version wasn't TOO old, I also updated to Node 0.10.36 (being sure to keep off the 12.x releases for now).

**Closed** 2015-03-18 10:34 UTC
Labels: 2 - Ready For Test, bug
