### ISSUE TITLE
The `tns create` command fails on node v12.0.0

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-cli#4569] opened 2019-04-26 07:44 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.3.4

**Describe the bug**

The `tns create` command fails on node v12.0.0.

**To Reproduce**

Install node v12.0.0 from https://nodejs.org/en/.
Install latest {N} CLI via `npm i -g nativescript@latest`.
Try to create a new project via the interactive `tns create` command.

**Output**

https://gist.github.com/vchimev/c42a95f9cb1986832a8c132c2f9bef5e

**Comment by Fatme** [comment] 2019-04-29 06:04
@vchimev,

It seems the problem is in this request:

> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node":

> HTTP error 404 Not Found

The above request is to wrong node version - `v4.11.0`. As in that moment there wasn't yet prebuilt versions of `node_sass` for node `v12.0.0`, it fallbacks to latest available release. As there isn't `darwin-x64-72_binding.node` for `v4.11.0`, it returns 404.

`node-sass` have already released prebuilt versions for `node v12.0.0`, so if you create a new project now, it should work.

```
npm view node-sass time
    '4.12.0': '2019-04-27T02:37:54.201Z'
```

I'm closing this issue as it should be working now.

**Closed by Fatme** 2019-04-29 06:04 UTC
