### ISSUE TITLE
Android AAR library package gets replaced with 2KB file

### ISSUE THREAD

**Issue by backraw** [NativeScript/nativescript-cli#3531] opened 2018-04-17 14:10 UTC
Hi,
I'm having a weird problem creating a NS plugin using the Plugin Seed repo and an Android AAR library.

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes - couldn't find anything close to my problem.

### Tell us about the problem
I cloned the NativeScript Plugin Seed repo, followed the Getting Started guide and replaced the `src/platforms/android/<plugin-name>.aar` with my own AAR (Android native library acting as an interface between a C library and an Android app).

**Edit**: The AAR is around 2.5MB in size.

When I run `npm run demo.andoird` my AAR gets replaced with a 2KB AAR file of the same name. I even tried to create a plugin without the help of the Plugin Seed repo, but that resulted in the same behavior, so I think the problem lies somewhere in NS's core or CLI.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.0
- Cross-platform modules: 3.4.1
- Runtime(s): 4.0.0
- Plugin(s): *where do I look exactly?*

### Please tell us how to recreate the issue in as much detail as possible.
1. `git clone https://github.com/NativeScript/nativescript-plugin-seed.git ns-sample`
2. `cd ns-sample/src`
3. `npm run postclone` -- enter details
4. Replace `src/platforms/android/ns-sample.aar` with an AAR you have lying around (my AAR contains proprietary code and libraries, so I can't share it here)
5. `npm run demo.android`

**Edit**: If I name my plugin `ns_sample.aar` it will get replaced with the 2KB AAR. However, if I name it `ns-sample.aar` (like the project itself), it will stay and NS creates a 2KB `ns_sample.aar` alongside the 2.5MB `ns-sample.aar` one. Why is it doing that?

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
None other than my AAR library.

### Thank you for your help!

**Comment by KristianDD** [comment] 2018-04-20 11:42
Hi @backraw,

Thank you for the detailed description and steps to reproduce. 

The `.aar` with the name of you project is generated, because of the `AndroidManifest.xml` file inside `src/platforms/android`. If you want only your `.aar` file to be included just remove the `src/platforms/android/AndroidManifest.xml` file.

The NativeScript CLI decides that there are permissions or other configurations inside the manifest file and builds an `.aar` file with the name of the plugin by convention (with `-` replaced by `_`). This way when the `.aar` files of all plugins are applied during the build of the application, the manifest files of all plugins and the one of the application itself are properly merged by the native android build infrastructure. This behavior was introduced with NativeScript 4.0.0 and you can read more about it in this [issue](https://github.com/NativeScript/nativescript-plugin-seed/issues/65).

Please let me know if this solution works out for you.

**Comment by backraw** [comment] 2018-04-23 08:13
Hi @KristianDD,

Thank you! Your explanation really helped me out big time!
I got all my dependencies bundled into the AAR and NS uses mine instead of building a new one.

I'm closing this issue.

**Comment by backraw** [comment] 2018-04-23 08:35
I'll have to reopen the issue, sorry.

Everything gets bundled with the APK, however, shouldn't my AAR appear in my app's `platforms/android/app/libs/runtime-libs` directory like `nativescript-optimized` and `nativescript-regular`?
Since it doesn't and my app crashes with the message:
`ActivityManager: Process <package-name> (pid 9924)(adj 1) has died(98,470)`. Is this due to the AAR missing from that `runtime-libs` folder?

**Comment by KristianDD** [comment] 2018-04-24 08:10
Hi @backraw,
I am glad that I could help. Thank you for updating us on your progress. I will close this issue as the loading of the `.aar` file seems resolved.

**Closed by KristianDD** 2018-04-24 08:10 UTC
