### ISSUE TITLE
Livesync crashes app every OTHER time on iOS with 3.0.0-rc.2

### ISSUE THREAD

**Issue by alexziskind1** [NativeScript/nativescript-cli#2732] opened 2017-04-22 17:45 UTC
### Description
When using the new 3.0.0-rc.2 branch with iOS simulator, the livesynced app crashed every other time (literally every other time). 
I make one change, the change breaks the app. I make another app, the app livesyncs successfully, after a third change the app crashed, etc.

### Which platform(s) does your issue occur on?
iOS only

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.0-rc.2
- Cross-platform modules: rc
- Runtime: "3.0.0-rc.1-2017-3-28-2"
- iOS 10.3

### Please tell us how to recreate the issue in as much detail as possible.
I created a new app:
`tns create rctest`
Ran the app
`tns run ios`
Made changes to the javascript code. 
Received the following error on the console (the app itself crashed)

```
Transferring project files...
Successfully transferred app.js.
Refreshing application...
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=3):
The request to open "org.nativescript.rctest" failed.
The process did launch, but has since exited or crashed.
Unable to sync files. Error is: Multiple errors were thrown:
Error Command failed: xcrun simctl launch 316B5D74-F5CF-4706-ABD7-1EA6F287AAF0 org.nativescript.rctest
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=3):
The request to open "org.nativescript.rctest" failed.
The process did launch, but has since exited or crashed.
 while executing xcrun simctl launch 316B5D74-F5CF-4706-ABD7-1EA6F287AAF0 org.nativescript.rctest.
Apr 22 13:41:32 Alexander-Mac CoreSimulatorBridge[4627]: Pasteboard change listener callback port <NSMachPort: 0x7fdf31e14470> registered
Apr 22 13:41:32 Alexander-Mac SpringBoard[4621]: [KeyboardArbiter] HW kbd: Failed to set (null) as keyboard focus
Apr 22 13:41:32 Alexander-Mac com.apple.CoreSimulator.SimDevice.316B5D74-F5CF-4706-ABD7-1EA6F287AAF0.launchd_sim[4604] (UIKitApplication:org.nativescript.rctest[0x9d6e][4626][5736]): Service exited due to Terminated: 15
Apr 22 13:41:32 Alexander-Mac backboardd[4622]: [Common] Unable to get short BSD proc info for 5736: No such process
Apr 22 13:41:32 Alexander-Mac backboardd[4622]: [Common] Unable to get proc info for 5736: Undefined error: 0
Apr 22 13:41:32 Alexander-Mac CoreSimulatorBridge[4627]: Pasteboard change listener callback port <NSMachPort: 0x7fdf31d04e10> registered
Apr 22 13:41:32 Alexander-Mac CoreSimulatorBridge[4627]: Requesting launch of org.nativescript.rctest with options: {
	    environment =     {
	    };
	}
Apr 22 13:41:32 Alexander-Mac CoreSimulatorBridge[4627]: Beginning launch sequence for bundle 'org.nativescript.rctest'
		retryTimeout: 120.000000 (default write com.apple.CoreSimulatorBridge LaunchRetryTimeout <value>)
		bootTimeout: 300.000000 (default write com.apple.CoreSimulatorBridge BootRetryTimeout <value>)
		bootLeeway: 120.000000 (default write com.apple.CoreSimulatorBridge BootLeeway <value>)
		Note: Use 'xcrun simctl spawn booted defaults write <domain> <key> <value>' to modify defaults in the booted Simulator device.
	Simulator booted at: 2017-04-22 16:31:12 +0000
	Current time: 2017-04-22 17:41:32 +0000
	Within boot leeway: NO
Apr 22 13:41:32 Alexander-Mac CoreSimulatorBridge[4627]: Launch attempt #0 for bundle 'org.nativescript.rctest', have been trying to launch for 0 seconds. Modern launch services = YES
Apr 22 13:41:32 Alexander-Mac CoreSimulatorBridge[4627]: Got LSBundleProxy for 'org.nativescript.rctest', sequenceNumber 260, cacheGUID 444AF7D9-F80F-4F19-A597-4EF1EF9128BC
Apr 22 13:41:32 Alexander-Mac CoreSimulatorBridge[4627]: [Common] [FBSSystemService][0x1094] Sending request to open "org.nativescript.rctest"
Apr 22 13:41:32 Alexander-Mac CoreSimulatorBridge[4627]: [Common] [FBSSystemService][0x1094] Error handling open request for org.nativescript.rctest: <NSError: 0x7fdf31e18340; domain: FBSOpenApplicationServiceErrorDomain; code: 3 (ProcessExited); reason: "The process did launch, but has since exited or crashed."> {
	    description = "The request to open "org.nativescript.rctest" failed.";
	    failureReason = "The process did launch, but has since exited or crashed.";
	}
Apr 22 13:41:32 Alexander-Mac CoreSimulatorBridge[4627]: Error Launching: Error Domain=FBSOpenApplicationServiceErrorDomain Code=3 "The request to open "org.nativescript.rctest" failed." UserInfo={NSLocalizedFailureReason=The process did launch, but has since exited or crashed., BSErrorCodeDescription=ProcessExited, NSLocalizedDescription=The request to open "org.nativescript.rctest" failed.}
Apr 22 13:41:32 Alexander-Mac CoreSimulatorBridge[4627]: Non-FBS error launching 'org.nativescript.rctest', will NOT retry. Error was: Error Domain=FBSOpenApplicationServiceErrorDomain Code=3 "The request to open "org.nativescript.rctest" failed." UserInfo={NSLocalizedFailureReason=The process did launch, but has since exited or crashed., BSErrorCodeDescription=ProcessExited, NSLocalizedDescription=The request to open "org.nativescript.rctest" failed.}
Apr 22 13:41:32 Alexander-Mac assertiond[4626]: Ignoring assertion request named "Deliver Message" from <BSProcessHandle: 0x7f8360605da0; SpringBoard:4621; valid: YES> because process { pid 5736; bundleID (null) } is unknown.
Apr 22 13:41:32 Alexander-Mac assertiond[4626]: Ignoring assertion request named "FBSceneSnapshotAction:org.nativescript.rctest" from <BSProcessHandle: 0x7f8360605da0; SpringBoard:4621; valid: YES> because process { pid 5736; bundleID (null) } is unknown.
```

**Comment by dtopuzov** [comment] 2017-04-23 20:37
Can you please try:
```
tns create rctest --template tns-template-hello-world@rc
tns platform add ios@rc --path rctest
tns run ios --path tctest
```
{N} 3,0,0 include breaking changes and template is also changed (and released with @rc tag).

**Comment by alexziskind1** [comment] 2017-04-24 11:51
Hi @dtopuzov 
I tried your suggestion, but received the same error when I made a change in the running app.

**Comment by dtopuzov** [comment] 2017-04-26 13:52
I still can not reproduce the issue.
Can you please post exact `package.json` of your app.

**Comment by alexziskind1** [comment] 2017-04-26 15:19
Sure. This happens with any app I try on my machine. I've tried your template. Now I'm able to reproduce the problem with the nativescript groceries app too. Here's the package.json from the groceries app based on the groceries template.

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.Groceries",
    "tns-ios": {
      "version": "3.0.0-rc.1-2017-3-28-2"
    },
    "tns-android": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "nativescript-angular": "1.4.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.0.1",
    "tns-core-modules": "2.5.0"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.3.5",
    "typescript": "~2.1.0",
    "zone.js": "~0.7.2"
  }
}
```

**Comment by alexziskind1** [comment] 2017-05-07 20:02
Confirmed this is still a problem with the 3.0.0 release. But, you probably are already way ahead of me on this one. :)

**Comment by dtopuzov** [comment] 2017-05-08 15:17
Hi @alexziskind1 we are working on the problem and we will provide fix soon (in first hot fix release after 3.0.0).

**Comment by dtopuzov** [comment] 2017-05-10 10:29
Hi @alexziskind1 fix for is already available in master, can you please try:
```
npm un -g nativescript
npm cache clean
npm i -g nativescript@next
```

I'm reopening the issue now, if you still experience problems when save only once, please post more details:
- Can you reproduce it with hello-world app?
- What plugins you use in your app (preferably post our package.json)?
- What is the IDE you use for development?

**Comment by b4rtt** [comment] 2017-05-10 10:43
@dtopuzov It seems to be working now

**Comment by alexziskind1** [comment] 2017-05-10 14:49
Thanks @dtopuzov . I've tested and it seems to be working with iOS. However, Android doesn't even start up now. Now I'm getting an error saying the app keeps stopping (see screenshot).
<img width="422" alt="screen shot 2017-05-10 at 10 47 48 am" src="https://cloud.githubusercontent.com/assets/1638579/25904761/2fa4f70c-356e-11e7-9aa6-28fc69346448.png">

**Closed** 2017-05-11 07:02 UTC
Labels: bug, iOS, livesync
