### ISSUE TITLE
[ios] Could not install application with code: -402620394

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-cli#3325] opened 2018-01-18 12:39 UTC
_From @surdu on January 18, 2018 12:22_

When I try to to install any NativeScript application on an iPad Air running iOS 11.2.2, I get the following error:

```
$ tns run ios --log trace
[...]
Installing...
Will send the following information to Google Analytics: { googleAnalyticsDataType: 'event',
  action: 'Deploy',
  label: 'iOS_Device_11.2.2',
  customDimensions: { cd2: 'Pure JavaScript' } }
Getting applications information for devices with identifiers: 5784c839f6bde322f71ed053979b3459900e92d5
Received multiple results:
{ '5784c839f6bde322f71ed053979b3459900e92d5': 
   [ { deviceId: '5784c839f6bde322f71ed053979b3459900e92d5',
       response: [] } ] }
Result when getting applications for which LiveSync is enabled:  []
Project dir from hooksArgs is: undefined.
Hooks directories: [ '/Users/nicolae.surdu/.npm-global/lib/node_modules/nativescript/lib/hooks',
  '/Users/nicolae.surdu/.npm-global/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/nicolae.surdu/work/<my-app>/hooks' ]
BeforeHookName for command install is before-install
Installing /Users/nicolae.surdu/work/<my-app>/platforms/ios/build/device/myApp.ipa on devices with identifiers: 5784c839f6bde322f71ed053979b3459900e92d5.
Error while executing ios device operation: Could not install application with code: -402620394
Failed to install /Users/nicolae.surdu/work/<my-app>/platforms/ios/build/device/myApp.ipa on device with identifier 5784c839f6bde322f71ed053979b3459900e92d5. Error is: Could not install application
Unable to apply changes on device: 5784c839f6bde322f71ed053979b3459900e92d5. Error is: Failed to install /Users/nicolae.surdu/work/<my-app>/platforms/ios/build/device/myApp.ipa on device with identifier 5784c839f6bde322f71ed053979b3459900e92d5. Error is: Could not install application.
Project dir from hooksArgs is: /Users/nicolae.surdu/work/<my-app>.
Hooks directories: [ '/Users/nicolae.surdu/.npm-global/lib/node_modules/nativescript/lib/hooks',
  '/Users/nicolae.surdu/.npm-global/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/nicolae.surdu/work/<my-app>/hooks' ]
AfterHookName for command watch is after-watch
Project dir from hooksArgs is: /Users/nicolae.surdu/work/<my-app>.
Hooks directories: [ '/Users/nicolae.surdu/.npm-global/lib/node_modules/nativescript/lib/hooks',
  '/Users/nicolae.surdu/.npm-global/lib/node_modules/nativescript/lib/common/hooks',
  '/Users/nicolae.surdu/work/<my-app>/hooks' ]
AfterHookName for command liveSync is after-liveSync
```

Versions:
```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.4.1           │ 3.4.1          │ Up to date  │
│ tns-core-modules │ 3.4.0           │ 3.4.0          │ Up to date  │
│ tns-android      │ 3.4.1           │ 3.4.1          │ Up to date  │
│ tns-ios          │ 3.4.1           │ 3.4.1          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘

$ npm --version
4.6.1

$ node --version
v7.7.2
```

_Copied from original issue: NativeScript/NativeScript#5293_

**Comment by NickIliev** [comment] 2018-01-18 12:59
@surdu tested with the template applications and with[ this app](https://github.com/NickIliev/nativescript-ng-cosmos) and all applications are successfully deployed and started on iPad Air using iOS 11.2.
If testing on a real device make sure you have [development certificate](https://docs.nativescript.org/publishing/publishing-ios-apps#certificates-identifiers--profiles) for the specific device.

**Comment by surdu** [comment] 2018-01-18 13:03
@NickIliev Works also on iOS 11.2**.2** ? It works on my ios 11.2 devices as well.

As far as I can tell, it sees one valid provisioning profile for this device:

```
$ tns run ios --provision
Searching for devices...
┌───────────────────────────────────────────────────────────┬───────────────────────┬──────────────┬─────────────┐
│ Provision Name / Provision UUID / App Id                  │ Team                  │ Type / Due   │ Devices     │
│                                                           │                       │              │             │
│ 'NS WorkTrak Development'                                 │ South49 Solutions LLC │ Development  │ 24 total    │
│ 40988c33-b25d-470d-9ff5-75342dde4cf8                      │ (92VNFH5XDR)          │ 4 Jan 2019   │ 1/1 targets │
│ 92VNFH5XDR.*                                              │                       │              │             │
│                                                           │                       │              │             │
│ 'iOS Team Provisioning Profile: *'                        │ South49 Solutions LLC │ Development  │ 23 total    │
│ 8e6686c1-7f68-45d9-866c-ad0da1f78ae7                      │ (92VNFH5XDR)          │ 5 Dec 2018   │ 0/1 targets │
│ 92VNFH5XDR.*                                              │                       │              │             │
│                                                           │                       │              │             │
└───────────────────────────────────────────────────────────┴───────────────────────┴──────────────┴─────────────┘

There are also 2 non-eligable provisioning profiles.
```

**Comment by surdu** [comment] 2018-01-18 14:15
Hmm... Managed to make it work by running the prepared project from XCode. Once I did this for every project, now they work on this device, even after deleting `/platform` `/hooks` and `/node_modules` 😕

**Comment by Fatme** [comment] 2018-04-05 08:11
Hi @surdu,

Can you try to run `tns run ios --provision 'NS WorkTrak Development'`?

**Comment by surdu** [comment] 2018-04-05 08:17
I didn't manage to reproduce this lately.

Either it was an environment problem that was fixed, or the problem was fixed in NS.

**Comment by Fatme** [comment] 2018-04-05 12:38
Hi @surdu,

I'm glad that your issue is resolved. I'm closing this thread but feel free to open an another in case you have some problems.

**Closed by Fatme** 2018-04-05 12:38 UTC
Labels: os: ios
