### ISSUE TITLE
nativescript-apiclient module not found

### ISSUE THREAD

**Issue by nitishsainani** [NativeScript/nativescript-cli#4729] opened 2019-06-17 12:43 UTC
Plugin(s): nativescript-apiclient

I am new to nativescript want to use apiclient in my application.
What steps I took:
 - installed plugin
```
npm i nativescript-apiclient --save-dev
npm i nativescript-apiclient --save
```
 - verified the plugin is there in node-modules
 - just imported the plugin.
`const { ApiClient } = require("nativescript-apiclient")`

```
ERROR in ./home/home-page.js
Module not found: Error: Can't resolve 'nativescript-apiclient' in '/home/nitish/nativeproj/direct/app/home'
 @ ./home/home-page.js 5:22-55
 @ . sync (root|page)\.(xml|css|js|ts|scss)$
 @ ./app.js
```
I am working in pure JS.

Is there anything to do with the plugin file in .ts.

**Comment by rosen-vladimirov** [comment] 2019-06-17 19:56
Hey @nitishsainani ,
It seems this is an issue with the plugin itself - it looks like plugin author had published only `.ts` files of the plugin and had added postinstall script to transpile them to `.js`. However, it seems the postinstall fails in some cases, which leads to the error you've noticed. You can check [this issue](https://github.com/mkloubert/nativescript-apiclient/issues/5) for further details and idea how to resolve the issue.

I'm closing this thread as the issue is not related to NativeScript CLI.

**Closed by rosen-vladimirov** 2019-06-17 19:56 UTC
Labels: question
