### ISSUE TITLE
Cannot change android package id via package.json

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-cli#2089] opened 2016-10-03 17:19 UTC
From https://github.com/NativeScript/docs/pull/496.

1) Create a NativeScript app.
2) Run it on Android.
3) Change the `nativescript.id` in your `package.json` file.
4) `rm -rf platforms`
5) `tns install`
6) `tns run android --emulator`

Expected: The `package` in the Android app’s manifest will be updated to the new value.
Actual: No update occurs.

It seems that once an `App_Resources/Android/app.gradle` file exists, you must change your application id there rather than in `package.json`. But that goes against [what our documentation says](https://docs.nativescript.org/publishing/publishing-android-apps#application-id-and-package-name).

Where is the right place to change this value? We either need to update the CLI or the docs, and I’m not sure which.

Thanks.

**Comment by tjvantoll** [comment] 2016-10-03 17:24
I’ll note that my vote is for `nativescript.id` to go away in the `package.json` file. I’d rather just update that value in `App_Resources/Android/app.gradle` and `App_Resources/iOS/Info.plist` personally.

Having both is confusing though.

**Comment by rosen-vladimirov** [comment] 2016-10-03 20:18
I vote for keep using one value (in package.json) and populate it in the native project. I've not tried the steps provided by @tjvantoll , but updating the file in app/App_Resources/Android/app.gradle seems incorrect for me. All placeholders should be replaced in the native project, not in the app directory. [Here](https://github.com/NativeScript/nativescript-cli/blob/c751d92137835a9d32b631f5bb140ab381bb9393/lib/services/android-project-service.ts#L208)'s the code that modifies the app.gradle. 
However the user may not notice the app.gradle and modify the package.json (as @tjvantoll tried to do) and the appid will not be respected. This will make the `run`, `livesync` and all other commands working with device useless as they are unable to determine application state on device (the commands read the appid from package.json). Also we may end-up with three different application identifiers:
 - one in package.json
 - another one in `app/App_Resources/Android/app.gradle`
 - another one in `app/App_Resources/Android/AndroidManifest.xml`

For beginner users this will be really difficult to understand, so I vote to keep the id in package.json and make sure CLI works correctly with the id in different files.

**Comment by Plamen5kov** [comment] 2016-12-06 14:53
We can introduce logic that replaces the app_id from the `package.json` to `app.gradle` and `AndroidManifest.xml`, but for android that might introduce some unexpected behavior since these values can be different in a native project, and the one in the `AndroidManifest.xml` is the one responsible for what is the application name on the device, and the one in `app.gradle` is responsible for the publishing in app store. If we force these two values to be the same, we loose functionality that is otherwise present on the native platform.
IMO since this is a native configuration, it should be separated from the common part. This is the point of the `app.gradle` file - to present the user with a way to configure the native project.

**Comment by dtopuzov** [comment] 2016-12-12 14:18
Not sure if users (specially web developer we target) will be happy to manually edit `app.gradle`

**Comment by PanayotCankov** [comment] 2016-12-12 15:25
Can't we read the id from the Info.plist for iOS and the AndroidManifest.xml for android, instead of reading the package.json?

**Comment by Plamen5kov** [comment] 2016-12-12 15:46
Currently CLI reads the id from `package.json` and interpolates the name into the `AndroidManifest.xml` and `Info.plist`. And as I understand the question, the problem is changing the package id, not reading it.

**Comment by EricRobertBrewer** [comment] 2016-12-12 23:57
I [tested this functionality](https://github.com/EricRobertBrewer/nativescript-package-test), but I can't seem to get the iOS app to read its `CFBundleIdentifier` in `Info.plist`. It currently gets clobbered by `nativescript.id` in `package.json`.

![device-2016-12-12-153402 androidstudio2-2-3](https://cloud.githubusercontent.com/assets/1558524/21121567/17c45cc4-c082-11e6-86b0-d98d744019bd.png)
![screen shot 2016-12-12 at 3 29 12 pm xcode8-1](https://cloud.githubusercontent.com/assets/1558524/21121568/17c4b296-c082-11e6-80f4-cd974f1b593b.png)

(I'm expecting to see `com.company.ios` above).

I [added `CFBundleIdentifier` here](https://github.com/EricRobertBrewer/nativescript-package-test/blob/master/app/App_Resources/iOS/Info.plist#L11-L12) according to [TJ VanToll's SO answer](http://stackoverflow.com/a/39960055/1559071).

*When I [try to remove `nativescript.id`](https://github.com/EricRobertBrewer/nativescript-package-test/commit/7f6fcfdc492aeac23d6cac9f31e8d17797670ca9)*, the project doesn't run:

iOS:

    Project successfully built
    Segmentation fault: 11

Android:

    Project successfully built
    No .apk found in /Users/ericbrewer/Documents/Personal/NativeScript/package-test/platforms/android/build/outputs/apk directory

Am I missing some setting?

**Comment by Plamen5kov** [comment] 2016-12-20 08:19
We need an iOS expert here: ping @PanayotCankov

**Comment by rosen-vladimirov** [comment] 2016-12-20 08:21
These are two different issues here:
1) During project creation CLI sets app id directly in app/App_Resources/app.gradle, so any additional changes in package.json will not be respected.
2) During every prepare of iOS platform, CLI replaces the bundle identifier in `platforms/ios/<project_name>/*.plist` with the id in package.json and disregards value in `app/App_Resources/ios/Info.plist`.

**Comment by Plamen5kov** [comment] 2016-12-20 09:06
I vote for removing the `app_id` from the `package.json`, because it's error prone, plus we already have a native configuration specific for each platform.
Given we provide a good default behavior and it's documented well, I don't see the novice users making unwilling mistakes, and for the advanced users we have documentation describing how the native configuration is augmented or changed.
IMO in our current state, we neither have one decent abstraction, nor do we guide the users to properly using the native configuration we've exposed.

**Comment by Plamen5kov** [comment] 2016-12-20 13:35
closing in favor of: https://github.com/NativeScript/nativescript-cli/issues/2367

**Closed by Plamen5kov** 2016-12-20 13:35 UTC
Labels: Android

**Comment by iamabs2001** [comment] 2020-09-09 09:50
> I vote for keep using one value (in package.json) and populate it in the native project. I've not tried the steps provided by @tjvantoll , but updating the file in app/App_Resources/Android/app.gradle seems incorrect for me. All placeholders should be replaced in the native project, not in the app directory. [Here](https://github.com/NativeScript/nativescript-cli/blob/c751d92137835a9d32b631f5bb140ab381bb9393/lib/services/android-project-service.ts#L208)'s the code that modifies the app.gradle.
> However the user may not notice the app.gradle and modify the package.json (as @tjvantoll tried to do) and the appid will not be respected. This will make the `run`, `livesync` and all other commands working with device useless as they are unable to determine application state on device (the commands read the appid from package.json). Also we may end-up with three different application identifiers:
> 
> * one in package.json
> * another one in `app/App_Resources/Android/app.gradle`
> * another one in `app/App_Resources/Android/AndroidManifest.xml`
> 
> For beginner users this will be really difficult to understand, so I vote to keep the id in package.json and make sure CLI works correctly with the id in different files.

safe doing manually ?
